unpackaged/main/default/objects/CV_Mapping__mdt/CV_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>Used to populate CalendarView records when activating Users to provide colour-coded calendars</description>
    <label>Calender View Mapping</label>
    <pluralLabel>Calender View Mappings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/CV_Mapping__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Is this CV Mapping active?</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/CV_Mapping__mdt/fields/Colour__c.field-meta.xml
<CustomField>
    <fullName>Colour__c</fullName>
    <inlineHelpText>Represents the color used in the background for records displayed in a user’s calendar view within the user interface.</inlineHelpText>
    <label>Colour</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CV_Mapping__mdt/fields/Display_Field__c.field-meta.xml
<CustomField>
    <fullName>Display_Field__c</fullName>
    <inlineHelpText>Represents the SobjectType field used as the subject for records displayed in a user’s calendar view within the user interface.</inlineHelpText>
    <label>Display Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CV_Mapping__mdt/fields/Field_for_Start__c.field-meta.xml
<CustomField>
    <fullName>Field_for_Start__c</fullName>
    <inlineHelpText>Represents the SobjectType field used as the start time for records displayed in a user’s calendar view within the user interface. Must be a date or dateTime field type.</inlineHelpText>
    <label>Field for Start</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CV_Mapping__mdt/fields/Fill_Pattern__c.field-meta.xml
<CustomField>
    <fullName>Fill_Pattern__c</fullName>
    <label>Fill Pattern</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>verticalStripes</fullName>
                <default>true</default>
                <label>verticalStripes</label>
            </value>
            <value>
                <fullName>ascDiagonalStripes</fullName>
            </value>
            <value>
                <fullName>descDiagonalStripes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CV_Mapping__mdt/fields/List_View__c.field-meta.xml
<CustomField>
    <fullName>List_View__c</fullName>
    <inlineHelpText>References the ListView used to filter records represented by the CalendarView. ListView must have the same sObjectType. If no List View is defined, the calendar displays only records with the same owner as the CalendarView.</inlineHelpText>
    <label>List View</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CV_Mapping__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <inlineHelpText>The type of standard or custom Salesforce object that is used to create records for the CalendarView. Use the API name of the desired SobjectType.</inlineHelpText>
    <label>Object</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Task</fullName>
                <default>true</default>
                <label>Task</label>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CV_Mapping__mdt/fields/User_Profiles__c.field-meta.xml
<CustomField>
    <fullName>User_Profiles__c</fullName>
    <inlineHelpText>Comma separated User Profile names for which user activation should trigger creation of this CalendarView</inlineHelpText>
    <label>User Profiles</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/DM_CVMapping.cls
/*******************************************************************************************************
* Class Name      	: DM_CVMapping
* Description		: Data Layer - Selector for custom metadata CV_Mapping__mdt
* Author          	: Simplus - Philip Clark
* Created On      	: 29/06/2020
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Philip Clark			29/06/2020		1000				Initial version
******************************************************************************************************/
public with sharing class DM_CVMapping {
    /**
    * @description 
    * @author Philip Clark | 29/06/2020 
    * @return List<CV_Mapping__mdt> 
    **/
    public static List<CV_Mapping__mdt> getCVMappings() {
        return [
            SELECT Id, Object__c, MasterLabel, Field_for_Start__c, List_View__c, Display_Field__c, Colour__c, Fill_Pattern__c, User_Profiles__c
            FROM CV_Mapping__mdt
            WHERE Active__c = TRUE
        ];
    }
}