unpackaged/main/default/objects/ServiceAppointment/fields/DaysInTheFuture__c.field-meta.xml
<CustomField>
    <fullName>DaysInTheFuture__c</fullName>
    <description>Computes the number of days between today and the SchedStartTime</description>
    <formula>DATEVALUE(SchedStartTime) - TODAY()</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DaysInTheFuture</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>Account.PersonContact.Email</formula>
    <label>Email</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <formula>Account.FirstName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FirstName</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <formula>Account.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>LastName</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <description>Customer order number against which the service appointment is scheduled.</description>
    <inlineHelpText>Customer order number against which the service appointment is scheduled.</inlineHelpText>
    <label>Order Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/Store_Timezone__c.field-meta.xml
<CustomField>
    <fullName>Store_Timezone__c</fullName>
    <formula>ServiceTerritory.TimeZone__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Store Timezone</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/StoreId__c.field-meta.xml
<CustomField>
    <fullName>StoreId__c</fullName>
    <formula>ServiceTerritory.Store_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>StoreId</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/DriveAndCollectService.cls
/*******************************************************************************************************
* Apex Name       	: DriveAndCollectService
* Description    	: REST API for Data Pull
* Author            : Simplus - John Dayondon
* Created On        : 02/02/2022
* Modification Log  :
* -----------------------------------------------------------------------------------------------------
* Developer        Date      Modification ID    Description
* -----------------------------------------------------------------------------------------------------
* John Dayondon   02/02/2022    1000        Initial version
******************************************************************************************************/
@RestResource(urlMapping='/schedulermanagement/v1/')
global with sharing class DriveAndCollectService 
{
	@HttpGet
    global static void doGet()
    {
        RestRequest req = RestContext.request;
        RestResponse res = Restcontext.response;
        
        try
        {
            Integer numberOfFutureDays = RestContext.request.params.get('NumberOfFutureDays') == null ? 2 : integer.valueOf(RestContext.request.params.get('NumberOfFutureDays'));
            String lastUpdated = RestContext.request.params.get('LastUpdated');
            
            //actually build the payload here
            List<DriveAndCollectServiceAppointment> listOfAppointments = new List<DriveAndCollectServiceAppointment>();  
            
            //get the matching records
            String query = 'select Id, SchedStartTime, DaysInTheFuture__c, FirstName__c,LastName__c,Email__c,StoreId__c,Status,Order_Number__c from ServiceAppointment where ParentRecordType=\'Account\' AND ((DaysInTheFuture__c <=' + numberOfFutureDays + ' AND DaysInTheFuture__c >= 0)';
            query = string.isNotBlank(lastUpdated) ? query + ' OR LastModifiedDate > ' + lastUpdated + ')' : query + ')';
            List<ServiceAppointment> listOfMatchingServiceAppointment = Database.query(query);
            for(ServiceAppointment serviceAppointment: listOfMatchingServiceAppointment)
            {
                DriveAndCollectServiceAppointment appointment = new DriveAndCollectServiceAppointment();
                appointment.Id = serviceAppointment.Id;
                appointment.appointmentDateTime = serviceAppointment.SchedStartTime != null ? string.valueOf(serviceAppointment.SchedStartTime.formatGmt('yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\'')) : '';
                appointment.firstName = serviceAppointment.FirstName__c;
                appointment.lastName = serviceAppointment.LastName__c;
                appointment.email = serviceAppointment.Email__c;
                appointment.status = serviceAppointment.Status;
                appointment.orderNumber = serviceAppointment.Order_Number__c;
                //appointment.timeZone = serviceAppointment.Store_Timezone__c;
                appointment.Locationid = string.isNotBlank(serviceAppointment.StoreId__c) ? integer.valueOf(serviceAppointment.StoreId__c) : 0;
                listOfAppointments.add(appointment);
            }      
            
            res.responseBody = Blob.valueOf(JSON.serialize(listOfAppointments));
            res.statusCode = 200;
        }
        catch(Exception ex)
        {
            system.debug(ex.getMessage());
            res.responseBody = Blob.valueOf(JSON.serialize('{"message":"' + ex.getMessage() + '""}'));
            res.statusCode = 500;
        }
    }
    
    @HttpPost
    global static void doPost()
    {
        RestRequest req = RestContext.request;
        RestResponse res = Restcontext.response;
        
        try
        {
            //check if they passed the params in the body
            system.debug(req.requestBody.toString());
            DriveAndCollectRequestBody readRequest = DriveAndCollectRequestBody.parse(req.requestBody.toString());
            
            //actually build the payload here
            List<DriveAndCollectServiceAppointment> listOfAppointments = new List<DriveAndCollectServiceAppointment>();
            
            //get the matching records
            String query = 'select Id, SchedStartTime, DaysInTheFuture__c, FirstName__c,LastName__c,Email__c,StoreId__c,Status,Order_Number__c from ServiceAppointment where ParentRecordType=\'Account\' AND ((DaysInTheFuture__c <=' + readRequest.NumberOfFutureDays + ' AND DaysInTheFuture__c >= 0)';
            query = string.isNotBlank(readRequest.LastUpdated) ? query + ' OR LastModifiedDate > ' + readRequest.LastUpdated + ')' : query + ')';
            system.debug(query);
            List<ServiceAppointment> listOfMatchingServiceAppointment = Database.query(query);
            for(ServiceAppointment serviceAppointment: listOfMatchingServiceAppointment)
            {
                DriveAndCollectServiceAppointment appointment = new DriveAndCollectServiceAppointment();
                appointment.Id = serviceAppointment.Id;
                appointment.appointmentDateTime = serviceAppointment.SchedStartTime != null ? string.valueOf(serviceAppointment.SchedStartTime.formatGmt('yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\'')) : '';
                appointment.firstName = serviceAppointment.FirstName__c;
                appointment.lastName = serviceAppointment.LastName__c;
                appointment.email = serviceAppointment.Email__c;
                appointment.status = serviceAppointment.Status;
                appointment.orderNumber = serviceAppointment.Order_Number__c;
                //appointment.timeZone = serviceAppointment.Store_Timezone__c;
                appointment.Locationid = string.isNotBlank(serviceAppointment.StoreId__c) ? integer.valueOf(serviceAppointment.StoreId__c) : 0;
                listOfAppointments.add(appointment);
            }        
            res.responseBody = Blob.valueOf(JSON.serialize(listOfAppointments));
            res.statusCode = 200;
        }
        catch(Exception ex)
        {
            system.debug(ex.getMessage());
            res.responseBody = Blob.valueOf(JSON.serialize('{"message":"' + ex.getMessage() + '""}'));
            res.statusCode = 500;
        }
    }
}