unpackaged/main/default/objects/Individual/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>The Country of where the individual is situated</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Individual/fields/SourceCustomerId__c.field-meta.xml
<CustomField>
    <fullName>SourceCustomerId__c</fullName>
    <description>From Consent Event API the Customer ID</description>
    <label>Source Customer ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Individual/fields/SourceSystem__c.field-meta.xml
<CustomField>
    <fullName>SourceSystem__c</fullName>
    <description>The Source System from which the individual was created from.</description>
    <label>Created By Source System</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Individual/fields/SourceSystemModule__c.field-meta.xml
<CustomField>
    <fullName>SourceSystemModule__c</fullName>
    <description>From the Consnt Event API, Indicates the system in which the record originated</description>
    <inlineHelpText>Indicates the system in which this record originated</inlineHelpText>
    <label>Created by Source System Module</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Individual/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>The state from the country that the Individual is situated</description>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NSW</fullName>
            </value>
            <value>
                <fullName>VIC</fullName>
            </value>
            <value>
                <fullName>QLD</fullName>
            </value>
            <value>
                <fullName>NT</fullName>
            </value>
            <value>
                <fullName>SA</fullName>
            </value>
            <value>
                <fullName>WA</fullName>
            </value>
            <value>
                <fullName>TAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/SM_Individual_Test.cls
/*******************************************************************************************************
* Class Name      	: SM_Individual_Test
* @description		: Test class for SM_Individual
* @author          	: Deloitte - Juan Cutrera
* Created On      	: 08/04/2025
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Juan Cutrera          08/04/2025		1000				Initial Version
******************************************************************************************************/
@isTest
private class SM_Individual_Test {

    /**
     * @description testBuildNewIndividual
     * @author 
     */
    @IsTest
    static void testBuildNewIndividual(){
        Consent_ConsentManagerPayload.Entity entity = new Consent_ConsentManagerPayload.Entity();
        entity.countryCode = 'AU';
        entity.person = new Consent_ConsentManagerPayload.Person();
        entity.person.firstName = 'John';
        entity.person.lastName = 'Doe';
        entity.person.contactPoints = new List<Consent_ConsentManagerPayload.ContactPoint>();
        Consent_ConsentManagerPayload.ContactPoint contactPoint = new Consent_ConsentManagerPayload.ContactPoint();
        contactPoint.address = new Consent_ConsentManagerPayload.Address();
        contactPoint.type = 'Address';
        contactPoint.address.stateCode = 'NSW';
        entity.person.contactPoints.add(contactPoint);
        entity.capture = new Consent_ConsentManagerPayload.Capture();
        entity.capture.source = 'TestSource';
        entity.capture.sourceModule = 'TestModule';
        entity.capture.sourceReference = 'TestSystemId';
        
        Individual result = SM_Individual.buildNewIndividual(entity);
        Assert.areNotEqual(null, result, 'Result should not be null');
    }

    /**
     * @description testUpsertIndividual 
     * @author Juan M. Cutrera
     */
    @IsTest
    static void testUpsertIndividual(){
        Individual result = new Individual(
            FirstName = 'John',
            LastName = 'Doe',
            Country__c = 'AU',
            State__c = 'NSW',
            SourceSystem__c = 'TestSource',
            SourceSystemModule__c = 'TestModule',
            SourceCustomerId__c = 'TestSystemId'
        );
        test.startTest();
        SM_Individual.upsertIndividual(result);
        test.stopTest();
        Assert.areNotEqual(null, result.Id, 'Result should not be null');
    }

    @IsTest
    static void testUpsertIndividual_Exception(){
        //No lastName will throw an exception
        Individual result = new Individual(
            FirstName = 'John',
            Country__c = 'AU',
            State__c = 'NSW',
            SourceSystem__c = 'TestSource',
            SourceSystemModule__c = 'TestModule',
            SourceCustomerId__c = 'TestSystemId'
        );
        test.startTest();
        try {
            SM_Individual.upsertIndividual(result);
            Assert.fail('Expected exception to be thrown');
        } catch (Exception e) {
            Assert.isTrue(true);
        }
        test.stopTest();
    }
}