unpackaged/main/default/objects/Individual/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>The Country of where the individual is situated</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Individual/fields/SourceCustomerId__c.field-meta.xml
<CustomField>
    <fullName>SourceCustomerId__c</fullName>
    <description>From Consent Event API the Customer ID</description>
    <label>Source Customer ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Individual/fields/SourceSystem__c.field-meta.xml
<CustomField>
    <fullName>SourceSystem__c</fullName>
    <description>The Source System from which the individual was created from.</description>
    <label>Created By Source System</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Individual/fields/SourceSystemModule__c.field-meta.xml
<CustomField>
    <fullName>SourceSystemModule__c</fullName>
    <description>From the Consnt Event API, Indicates the system in which the record originated</description>
    <inlineHelpText>Indicates the system in which this record originated</inlineHelpText>
    <label>Created by Source System Module</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Individual/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>The state from the country that the Individual is situated</description>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NSW</fullName>
            </value>
            <value>
                <fullName>VIC</fullName>
            </value>
            <value>
                <fullName>QLD</fullName>
            </value>
            <value>
                <fullName>NT</fullName>
            </value>
            <value>
                <fullName>SA</fullName>
            </value>
            <value>
                <fullName>WA</fullName>
            </value>
            <value>
                <fullName>TAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/SM_IndividualBuilder_Test.cls
/*******************************************************************************************************
* Class Name      	: SM_IndividualBuilder_Test
* @description		: Test class for SM_IndividualBuilder
* @author          	: Deloitte - Juan Cutrera
* Created On      	: 08/04/2025
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Juan Cutrera          08/04/2025		1000				Initial Version
******************************************************************************************************/
@isTest
private class SM_IndividualBuilder_Test {

    /**
    * @description  Test method for setFirstName
    * @author Juan Cutrera | 08/04/2025
    **/
    @isTest
    static void testSetFirstName() {
        SM_IndividualBuilder builder = new SM_IndividualBuilder();
        builder.setFirstName('John');
        Individual individual = builder.build();
        System.assertEquals('John', individual.FirstName, 'FirstName should be set correctly.');
    }

    /**
    * @description  Test method for setLastName
    * @author Juan Cutrera | 08/04/2025
    **/
    @isTest
    static void testSetLastName() {
        SM_IndividualBuilder builder = new SM_IndividualBuilder();
        builder.setLastName('Doe');
        Individual individual = builder.build();
        System.assertEquals('Doe', individual.LastName, 'LastName should be set correctly.');
    }

    /**
    * @description  Test method for setAccountOwner
    * @author Juan Cutrera | 08/04/2025
    **/
    @isTest
    static void testSetAccountOwner() {
        SM_IndividualBuilder builder = new SM_IndividualBuilder();
        builder.setAccountOwner('0059200000LUtz8AAD');
        Individual individual = builder.build();
        System.assertEquals('0059200000LUtz8AAD', individual.OwnerId, 'OwnerId should be set correctly.');
    }

    /**
    * @description  Test method for setCountry
    * @author Juan Cutrera | 08/04/2025
    **/
    @isTest
    static void testSetCountry() {
        SM_IndividualBuilder builder = new SM_IndividualBuilder();
        builder.setCountry('AU');
        Individual individual = builder.build();
        System.assertEquals('AU', individual.Country__c, 'Country should be set correctly.');
    }

    /**
    * @description  Test method for setState
    * @author Juan Cutrera | 08/04/2025
    **/
    @isTest
    static void testSetState() {
        SM_IndividualBuilder builder = new SM_IndividualBuilder();
        builder.setState('VIC');
        Individual individual = builder.build();
        System.assertEquals('VIC', individual.State__c, 'State should be set correctly.');
    }

    /**
    * @description  Test method for setSourceSystem
    * @author Juan Cutrera | 08/04/2025
    **/
    @isTest
    static void testSetSourceSystem() {
        SM_IndividualBuilder builder = new SM_IndividualBuilder();
        builder.setSourceSystem('COS');
        Individual individual = builder.build();
        System.assertEquals('COS', individual.SourceSystem__c, 'SourceSystem should be set correctly.');
    }

    /**
    * @description  Test method for setSourceSystemModule
    * @author Juan Cutrera | 08/04/2025
    **/
    @isTest
    static void testSetSourceSystemModule() {
        SM_IndividualBuilder builder = new SM_IndividualBuilder();
        builder.setSourceSystemModule('HireShop');
        Individual individual = builder.build();
        System.assertEquals('HireShop', individual.SourceSystemModule__c, 'SourceSystemModule should be set correctly.');
    }

    /**
    * @description  Test method for setSourceCustomerId
    * @author Juan Cutrera | 08/04/2025
    **/
    @isTest
    static void testSetSourceCustomerId() {
        SM_IndividualBuilder builder = new SM_IndividualBuilder();
        builder.setSourceCustomerId('CUST12345');
        Individual individual = builder.build();
        System.assertEquals('CUST12345', individual.SourceCustomerId__c, 'SourceCustomerId should be set correctly.');
    }
}