unpackaged/main/default/objects/User/fields/Bunnings_Job_Role__c.field-meta.xml
<CustomField>
    <fullName>Bunnings_Job_Role__c</fullName>
    <description>Bunnings Job Role from the source system, used to determine what Sales Rep ID field on Store object to assign to the trade specialist user.</description>
    <label>Bunnings Job Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>&quot;None&quot;</defaultValue>
    <description>This field is used in sharing rules to define a AU User&#39;s and NZ User&#39;s</description>
    <inlineHelpText>This field is used in sharing rules to define a AU User&#39;s and NZ User&#39;s</inlineHelpText>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/User/fields/Is_TS__c.field-meta.xml
<CustomField>
    <fullName>Is_TS__c</fullName>
    <formula>CONTAINS(Profile.Name, &#39;Trade Specialist&#39;)</formula>
    <label>Is TS</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/User/fields/Location_Code__c.field-meta.xml
<CustomField>
    <fullName>Location_Code__c</fullName>
    <description>Location code that maps to the external ID on the store object</description>
    <label>Location Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/Sales_Rep_ID__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep_ID__c</fullName>
    <description>Unique sales rep number assigned to the user either from legacy system sequence or newly generated in Salesforce</description>
    <label>Sales Rep ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/DM_User.cls
/*******************************************************************************************************
* Class Name      	: DM_User
* Description		: Data Layer - Selector for Sobject User
* Author          	: Simplus - Yi Zhang
* Created On      	: 14/05/2020
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Yi Zhang              14/05/2020		1000				Initial version
* Philip Clark			01/07/2020		1001				getActiveUsers
* Simplus MS            11/06/2021      1002                added isActive field query on getUsers
* Bunnnings Dev         28/08/2024      1003                added getUserStatus
******************************************************************************************************/
public with sharing class DM_User {
    /**
    * @description 
    * @author Yi Zhang | 15/05/2020 
    * @param userId 
    * @return User 
    **/
    public static User getUser(String userId) {
        if(userId == null) {
            return null;
        }
        List<User> users = [
            SELECT Id, Name, Profile.Name, Is_TS__c, ManagerId, Country__c, LocaleSidKey
            FROM User
            WHERE Id = :userId];
        return (users.isEmpty()) ? null : users[0];
    }

    /**
    * @description 
    * @author Yi Zhang | 15/05/2020 
    * @param userIds 
    * @return Map<Id, User> 
    **/
    public static Map<Id, User> getUsers(List<String> userIds) {
        return new Map<Id, User>([
            SELECT Id, Profile.Name, Is_TS__c, ManagerId, isActive,Sales_Rep_ID__c
            FROM User
            WHERE Id IN :userIds
        ]);
    }

    /**
    * @description 
    * @author Philip Clark | 01/07/2020 
    * @param userIds 
    * @return Map<Id, User> 
    **/
    public static Map<Id, User> getActiveUsers() {
        return new Map<Id, User>([
            SELECT Id, Profile.Name, Is_TS__c, ManagerId, DelegatedApproverId
            FROM User
            WHERE isActive = TRUE
        ]);
    }

    /**
    * @description 
    * @author Yi Zhang | 23/06/2020 
    * @param managerId 
    * @param profileNames 
    * @return List<User> 
    **/
    public static List<User> getActiveUsersManagedBy(String managerId, List<String> profileNames) {
        return new List<User>([
            SELECT Id, Name
            FROM User
            WHERE ManagerId = :managerId
            AND Profile.Name IN :profileNames
            AND IsActive = true
            ORDER BY Name ASC
        ]);
    }

    /**
    * @description 
    * @author Yi Zhang | 23/06/2020 
    * @param profileNames 
    * @return List<User> 
    **/
    public static List<User> getActiveUsersOfProfiles(List<String> profileNames) {
        return new List<User>([
            SELECT Id, Name
            FROM User
            WHERE Profile.Name IN :profileNames
            AND IsActive = true
            ORDER BY Name ASC
        ]);
    }

    /**
    * @description  Only Trade Specialists
    * @author Yi Zhang | 24/08/2020 
    * @param locationCodes 
    * @return List<User> 
    **/
    public static List<User> getTSUsersByLocationCode(List<String> locationCodes) {
        return new List<User>([
            SELECT Id, Location_Code__c, Bunnings_Job_Role__c
            FROM User
            WHERE Location_Code__c IN :locationCodes
            AND Is_TS__c = true
        ]);
    }

    /**
    * @description 
    * @author Yi Zhang | 28/10/2020 
    * @param names 
    * @return List<User> 
    **/
    public static List<User> getUsersByName(List<String> names) {
        return new List<User>([
            SELECT Id, Name 
            FROM User 
            WHERE Name IN :names
        ]);
    }


     /**
    * @description : getUserStatus
    * @author Sowjanya 
    * @param userId 
    * @return Boolean 
    **/
    public static Boolean getUserStatus(String userId) {
        if(userId == null) {
            return null;
        }
        List<User> users = [
            SELECT id, isActive 
            FROM User 
            WHERE Id = :userId];
        return (users.isEmpty()) ? null : users[0].isActive;
    }
}