unpackaged/main/default/objects/CZ_Mapping__mdt/CZ_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>Used to determine applicable cost zones based on contract country, state and cost zone</description>
    <label>Cost Zone Mapping</label>
    <pluralLabel>Cost Zone Mapping</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/CZ_Mapping__mdt/fields/Applicable_Cost_Zones__c.field-meta.xml
<CustomField>
    <fullName>Applicable_Cost_Zones__c</fullName>
    <description>Applicable Cost Zones based on country, state &amp; cost zone</description>
    <label>Applicable Cost Zones</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CZ_Mapping__mdt/fields/Cost_Zone__c.field-meta.xml
<CustomField>
    <fullName>Cost_Zone__c</fullName>
    <label>Cost Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ALL</fullName>
                <default>true</default>
                <label>ALL</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CZ_Mapping__mdt/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>&quot;Australia&quot;</defaultValue>
    <description>Contract Country</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Australia</fullName>
                <default>true</default>
                <label>Australia</label>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CZ_Mapping__mdt/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Contract State</description>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NATIONAL</fullName>
                <default>true</default>
                <label>NATIONAL</label>
            </value>
            <value>
                <fullName>ACT</fullName>
            </value>
            <value>
                <fullName>NQ</fullName>
            </value>
            <value>
                <fullName>NSW</fullName>
            </value>
            <value>
                <fullName>NT</fullName>
            </value>
            <value>
                <fullName>QLD</fullName>
            </value>
            <value>
                <fullName>SA</fullName>
            </value>
            <value>
                <fullName>TAS</fullName>
            </value>
            <value>
                <fullName>VIC</fullName>
            </value>
            <value>
                <fullName>WA</fullName>
            </value>
            <value>
                <fullName>NI</fullName>
            </value>
            <value>
                <fullName>SI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/DM_CZMapping.cls
/*******************************************************************************************************
* Class Name      	: DM_CZMapping
* Description		: Data Layer - Selector for Custom Metadata Type CZ Mapping
* Author          	: Simplus - Yi Zhang
* Created On      	: 22/05/2020
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Yi Zhang              22/05/2020		1000				Initial version
* Yi Zhang              28/07/2020		2000				Added static variable
******************************************************************************************************/
public with sharing class DM_CZMapping {
    /**
    * @description 
    * @author Yi Zhang | 22/05/2020 
    * @param country 
    * @param state 
    * @param costZone 
    * @return String 
    **/
    public static String getApplicableCZs(String country, String state, String costZone) {
        List<CZ_Mapping__mdt> mappings = [
            SELECT Applicable_Cost_Zones__c
            FROM CZ_Mapping__mdt
            WHERE Country__c = :country
            AND State__c = :state
            AND Cost_Zone__c = :costZone
        ];
        if(mappings.isEmpty() == true) {
            return null;
        }
        
        return mappings[0].Applicable_Cost_Zones__c;
    }

    /**
    * @description 
    * @author Yi Zhang | 28/07/2020 
    * @return Map<String, String> 
    **/
    public static Map<String, String> costZoneMap {
        get {
            if(costZoneMap == null) {
                costZoneMap = new Map<String, String>();
                for(CZ_Mapping__mdt czm : [SELECT Country__c, State__c, Cost_Zone__c, Applicable_Cost_Zones__c FROM CZ_Mapping__mdt]) {
                    costZoneMap.put(czm.Country__c + czm.State__c + czm.Cost_Zone__c, czm.Applicable_Cost_Zones__c);
                }
            }
            return costZoneMap;
        } set;
    }
}