unpackaged/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>Represents all frame and truss plants, small format stores, trade distribution centres and warehouses.</description>
    <label>Store</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Store__c/fields/Engagement_Model__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Model__c</fullName>
    <description>Determines the method used for assigning Powerpass Account Ownership. 
Old Model - the Stores Default Trade Specialist will become the owner. 
New - Ownership is determined by Assignment Rule Metadata records</description>
    <label>Engagement Model</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Old</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Store_Member__c/Store_Member__c.object-meta.xml
<CustomObject>
    <description>Junction between user (team members) and store.</description>
    <label>Store Member</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>Store Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Store_Member__c/fields/Batch_Update__c.field-meta.xml
<CustomField>
    <fullName>Batch_Update__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Batch Update</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Store_Member__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ASM</fullName>
            </value>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Area BDM</fullName>
            </value>
            <value>
                <fullName>CCS Manager</fullName>
            </value>
            <value>
                <fullName>RCM</fullName>
            </value>
            <value>
                <fullName>Trade Specialist</fullName>
            </value>
            <value>
                <fullName>SSM</fullName>
            </value>
            <value>
                <fullName>CCS</fullName>
                <isActive>false</isActive>
                <label>CCS</label>
            </value>
            <value>
                <fullName>Team Member</fullName>
                <isActive>false</isActive>
                <label>Team Member</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Store_Member__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Store_Member__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipName>User_Stores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Store_Member__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Stores</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/User/fields/Is_TS__c.field-meta.xml
<CustomField>
    <fullName>Is_TS__c</fullName>
    <formula>CONTAINS(Profile.Name, &#39;Trade Specialist&#39;)</formula>
    <label>Is TS</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/SM_SyncCallVolumesBatch.cls
/*******************************************************************************************************
* Class Name      	: SM_SyncCallVolumesBatch
* Description		: Batch class to update Call Volumes of store members when needed 
* Author          	: Simplus - MS
* Created On      	: 15/12/2021
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Simplus MS            15/12/2021		1000				Initial version [CCRM15-487]
******************************************************************************************************/
public class SM_SyncCallVolumesBatch implements Database.Batchable<sObject> {
    
    String query;
    
    public SM_SyncCallVolumesBatch() {
        
        query = 'SELECT Id, Batch_Update__c ' +
            ' FROM Store_Member__c ' + 
            ' WHERE Status__c = \'' + Constants.STOREMEMBER_ACTIVE_STATUS + '\' ' + 
            ' AND Role__c = \'' + Constants.STOREMEMBER_TS_ROLENAME + '\' ' + 
            ' AND Team_Member__r.IsActive = true ' + 
            ' AND Team_Member__r.Is_TS__c = true ' + 
            ' AND Store__r.Engagement_Model__c != null ' +
            ' ORDER BY Id ASC';
    }
    
    public Database.QueryLocator start(Database.BatchableContext BC) {
        System.debug('query: '+query);
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext BC, List<Store_Member__c> scope) {
        // execute code
        System.debug('scope: '+scope);

        List<Store_Member__c> lStoreMembersToUpdate = new List<Store_Member__c>();
        Boolean isToggle = FALSE;

        for(Store_Member__c member : scope) {
            System.debug('member: '+member);
            //just toggling the Batch_Update__c for the sake of running 
            //the isUpdate context of trigger for SM_StoreMember.calculateCallVolume logic
            member.Batch_Update__c = member.Batch_Update__c == isToggle ? TRUE : FALSE;
            lStoreMembersToUpdate.add(member);
        }
        
        try {
            if (!lStoreMembersToUpdate.isEmpty()){
                update lStoreMembersToUpdate;
            }
        } catch(Exception e) {
            ApplicationLogger.log('SM_SyncCallVolumesBatch', 'Store Member', 'Batch', e);
        }
    }
    
    public void finish(Database.BatchableContext BC) {
        // finish code
    }
}