unpackaged/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <description>Status of the Account</description>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Referred</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Last_3_Month_Sales__c.field-meta.xml
<CustomField>
    <fullName>Last_3_Month_Sales__c</fullName>
    <label>Last 3 Month Sales</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Power_Pass_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Power_Pass_Account_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Power Pass Account Number</label>
    <length>32</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/R12_Sales__c.field-meta.xml
<CustomField>
    <fullName>R12_Sales__c</fullName>
    <label>R12 Sales</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Reason_for_Share__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Share__c</fullName>
    <description>Reason for share as identified by the account manager</description>
    <label>Reason for Share</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Share_of_Wallet__c.field-meta.xml
<CustomField>
    <fullName>Share_of_Wallet__c</fullName>
    <description>Share of wallet as identified by the account manager</description>
    <inlineHelpText>This is the R12 Share of Wallet</inlineHelpText>
    <label>Share of Wallet</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/AU_Customer.recordType-meta.xml
<RecordType>
    <fullName>AU_Customer</fullName>
    <active>true</active>
    <description>Australian customer accounts</description>
    <label>AU Customer</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/AU_Prospect.recordType-meta.xml
<RecordType>
    <fullName>AU_Prospect</fullName>
    <active>true</active>
    <description>Australian prospect accounts</description>
    <label>AU Prospect</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/NZ_Customer.recordType-meta.xml
<RecordType>
    <fullName>NZ_Customer</fullName>
    <active>true</active>
    <description>New Zealand Customer Account</description>
    <label>NZ Customer</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/NZ_Prospect.recordType-meta.xml
<RecordType>
    <fullName>NZ_Prospect</fullName>
    <active>true</active>
    <description>New Zealand prospect accounts</description>
    <label>NZ Prospect</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Call_Days__c.field-meta.xml
<CustomField>
    <fullName>Call_Days__c</fullName>
    <description>Call days, applicable to frequencies such as Twice Weekly, 3 x Week</description>
    <label>Call Days</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mon</fullName>
            </value>
            <value>
                <fullName>Tue</fullName>
            </value>
            <value>
                <fullName>Wed</fullName>
            </value>
            <value>
                <fullName>Thu</fullName>
            </value>
            <value>
                <fullName>Fri</fullName>
            </value>
            <value>
                <fullName>Sat</fullName>
            </value>
            <value>
                <fullName>Sun</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/First_Day__c.field-meta.xml
<CustomField>
    <fullName>First_Day__c</fullName>
    <description>First day of planned calls</description>
    <label>First Day</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Recurrence__c.field-meta.xml
<CustomField>
    <fullName>Recurrence__c</fullName>
    <description>Until date of planned calls</description>
    <label>Recurrence</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Tactic__c.field-meta.xml
<CustomField>
    <fullName>Tactic__c</fullName>
    <description>Tactic used by the account manager</description>
    <label>Tactic</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Target_Call_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Target_Call_Frequency__c</fullName>
    <description>Call frequency</description>
    <label>Target Call Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>3 x Week</fullName>
            </value>
            <value>
                <fullName>Twice Weekly</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Bi-Weekly</fullName>
            </value>
            <value>
                <fullName>Every 4 weeks</fullName>
            </value>
            <value>
                <fullName>Every 8 weeks</fullName>
            </value>
            <value>
                <fullName>Every 3 weeks</fullName>
            </value>
            <value>
                <fullName>Every quarter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/DM_Contact.cls
/*******************************************************************************************************
* Class Name        : DM_Contact
* Description       : Data Layer - Selector for Sobject Contact
* Author            : Simplus - Yi Zhang
* Created On        : 2020-05-15
* Modification Log  :
* -----------------------------------------------------------------------------------------------------
* Developer             Date            Modification ID     Description
* -----------------------------------------------------------------------------------------------------
* Yi Zhang              2020-05-15      1000                Initial version
* Jasper R. Galapon     2024-04-04      1001                BUNDIG-23006 - Inactive Contact Is Listed in Call Planner
******************************************************************************************************/
public with sharing class DM_Contact {
    /**
    * @description 
    * @author Yi Zhang | 15/05/2020 
    * @param accountId 
    * @param ownerId 
    * @return Map<Id, Contact> 
    **/
    public static Map<Id, Contact> getContacts(String accountId, String ownerId) {
        return new Map<Id, Contact>([
            SELECT Id
            FROM Contact
            WHERE AccountId = :accountId
            AND OwnerId = :ownerId
        ]);
    }

    /**
    * @description 
    * @author Yi Zhang | 18/05/2020 
    * @param accountIds 
    * @param ownerIds 
    * @return Map<Id, Contact> 
    **/
    public static Map<Id, Contact> getContacts(Set<Id> accountIds, Set<Id> ownerIds) {
        return new Map<Id, Contact>([
            SELECT Id, AccountId, OwnerId
            FROM Contact
            WHERE AccountId IN :accountIds
            AND OwnerId IN :ownerIds
        ]);
    }

    /**
    * @description 
    * @author Yi Zhang | 22/06/2020 
    * @param accountOwnerId 
    * @return Map<Id, Contact> 
    **/
    public static Map<Id, Contact> getContactsBasedOnAcctOwner(Id accountOwnerId) {
        return new Map<Id, Contact>([
            SELECT Id, AccountId, 
            Account.Id, 
            Account.Power_Pass_Account_Number__c,
            Account.Name,
            Account.R12_Sales__c, 
            Account.Last_3_Month_Sales__c, 
            Account.Share_of_Wallet__c, 
            Account.Reason_for_Share__c, 
            Tactic__c, //Modified for CCRM-8162 // Aldrin Rasdas 13.Nov.2020
            Name, Target_Call_Frequency__c, First_Day__c, Recurrence__c, Call_Days__c
            FROM Contact
            WHERE Account.OwnerId = :accountOwnerId
            AND Account.RecordType.DeveloperName IN ('AU_Customer', 'NZ_Customer', 'AU_Prospect', 'NZ_Prospect')
            AND Account.Account_Status__c IN ('Active', 'Referred')
            AND Status__c = 'Active' //BUNDIG-23006
            ORDER BY Account.Name ASC, Name ASC
        ]);
    }
}