unpackaged/main/default/objects/Account/fields/Account_Transferrable__c.field-meta.xml
<CustomField>
    <fullName>Account_Transferrable__c</fullName>
    <formula>IF( ISPICKVAL(Transfer_approval_status__c , &#39;Submitted for approval&#39;) || ISPICKVAL(Pricing_Assignment_Status__c , &#39;Pending Approval&#39;) , &#39;No&#39;, &#39;Yes&#39;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>There are accounts under approval.</inlineHelpText>
    <label>Account Transferrable</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Contract_Group__c.field-meta.xml
<CustomField>
    <fullName>Contract_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent Account for the contract group</description>
    <label>Contract Group</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contract Group Associations</relationshipLabel>
    <relationshipName>Contract_Group_Association</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Various contracts associated to customers, projects and umbrellas. Use of custom object in place of standard considering future implementation of CPQ with contract and its line items.</description>
    <label>Contract</label>
    <nameField>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Contract__c/fields/Original_Reviewer__c.field-meta.xml
<CustomField>
    <fullName>Original_Reviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Original reviwer of the contract. This will help determine who to return the review to after delegation is completed.</description>
    <label>Original Reviewer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>OriginalReviewer</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Associated Project</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the contract</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contract_Group__c/Contract_Group__c.object-meta.xml
<CustomObject>
    <description>A logical contract grouping that defines customer accounts it is applied to.</description>
    <label>Contract Group</label>
    <nameField>
        <label>Contract Group</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Group</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Contract__c/Customer_Contract__c.object-meta.xml
<CustomObject>
    <label>Customer Contract</label>
    <nameField>
        <displayFormat>CC-{00000000}</displayFormat>
        <label>Customer Contract</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Contract__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <description>Contract for customer contract</description>
    <inlineHelpText>Contract for customer contract</inlineHelpText>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Customer Contracts</relationshipLabel>
    <relationshipName>Customer_Contracts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Customer_Contract__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <description>Customer this customer contract is related to. Ref #CCRM-145</description>
    <inlineHelpText>Customer this customer contract is related to</inlineHelpText>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Contracts</relationshipLabel>
    <relationshipName>Customer_Contracts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>This object is used for grouping Opportunities related to a single construction project.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The Status of the Project eg. Quotation</description>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Documentation</fullName>
            </value>
            <value>
                <fullName>Tender</fullName>
            </value>
            <value>
                <fullName>Post Tender</fullName>
            </value>
            <value>
                <fullName>Builder Appointed</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Closed - Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/DM_CustomerContract.cls
/*******************************************************************************************************
* Class Name      	: DM_CustomerContract
* Description		: Data Layer - Selector for Sobject Customer Contract
* Author          	: Simplus - Yi Zhang
* Created On      	: 2020-05-14
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Yi Zhang              2020-05-14		1000				Initial version
* Simplus MS            2021-01-04      1001                CCRM-170 - New method added to fetch non-expired contracts based on AcctIds,OwnerIds & where Contract Group is null
* Simplus MS            2021-02-04      1002                CCRM-170 - Account_Under_Approval__c field replace with Account_Transferrable__c
******************************************************************************************************/
public with sharing class DM_CustomerContract {

    /**
    * @description   
    * @author       Yi Zhang | 14/07/2020 
    * @param        accountId 
    * @return       List<Customer_Contract__c> 
    **/
    public static List<Customer_Contract__c> getCustomerContracts(String accountId) {
        return new List<Customer_Contract__c>([
            SELECT Id, Contract__c, Customer__c, 
            Contract__r.Id,
            Contract__r.Status__c,
            Contract__r.Original_Reviewer__c,
            Contract__r.OwnerId
            FROM Customer_Contract__c
            WHERE Customer__c = :accountId
        ]);
    }

    /**
    * @description 
    * @author John Paul Peñaflor | 08-18-2020 
    * @param Set<String> contractIds 
    * @return List<Customer_Contract__c> 
    **/
    public static List<Customer_Contract__c> getCustomerContracts(Set<String> contractIds) {
        return new List<Customer_Contract__c>([
            SELECT Id, Contract__c, Customer__c, 
            Contract__r.Project__c
            FROM Customer_Contract__c
            WHERE Contract__c IN: contractIds
        ]);
        
    }

    /**
    * @description   
    * @author       Yi Zhang | 15/05/2020 
    * @param        accountId 
    * @return       List<Customer_Contract__c> 
    **/
    public static List<Customer_Contract__c> getNonExpiredCustomerContracts(String accountId) {
        List<Customer_Contract__c> ccs = [
            SELECT Id, Contract__c, Customer__c, 
            Contract__r.Id,
            Contract__r.OwnerId
            FROM Customer_Contract__c
            WHERE Customer__c = :accountId
            AND Contract__r.Status__c != 'Expired'
        ];
        return ccs;
    }

    /**
    * @description 
    * @author Yi Zhang | 18/05/2020 
    * @param accountIds 
    * @param ownerIds 
    * @return List<Customer_Contract__c> 
    **/
    public static List<Customer_Contract__c> getNonExpiredCustomerContracts(Set<Id> accountIds, Set<Id> ownerIds) {
        return new List<Customer_Contract__c>([
            SELECT Id, Contract__c, Customer__c, 
            Contract__r.Id,
            Contract__r.OwnerId
            FROM Customer_Contract__c
            WHERE Customer__c IN :accountIds
            AND Contract__r.OwnerId IN :ownerIds
            AND Contract__r.Status__c != 'Expired'
        ]);
    }

    /**
    * @description  Get list of customer contracts based on Set of Account Ids, OwnerId & where Contract Group is null
    * @author       Simplus MS | 04/01/2021 
    * @param        AccountIds, OwnerIds
    * @return       List<Customer_Contract__c> 
    **/
    public static List<Customer_Contract__c> getNonExpiredCustContracts(Set<Id> accountIds, Set<Id> ownerIds) {
        return new List<Customer_Contract__c>([
            SELECT Id, Contract__c, Customer__c, 
            Contract__r.Id,
            Contract__r.Status__c,
            Contract__r.Original_Reviewer__c,
            Contract__r.OwnerId,
            Customer__r.Contract_Group__c,
            Customer__r.Account_Transferrable__c
            FROM Customer_Contract__c
            WHERE Customer__c IN :accountIds
            AND Contract__r.Status__c != 'Expired'
            AND Contract__r.OwnerId IN :ownerIds
            AND Customer__r.Contract_Group__c = null
        ]);
    }
}