unpackaged/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <description>Status of the Account</description>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Referred</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Digital_Managed__c.field-meta.xml
<CustomField>
    <fullName>Digital_Managed__c</fullName>
    <description>Use in pilot of Predictive Model</description>
    <inlineHelpText>Use in pilot of Predictive Model</inlineHelpText>
    <label>Digital Managed</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FALSE</fullName>
            </value>
            <value>
                <fullName>TRUE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Digitally_Managed__c.field-meta.xml
<CustomField>
    <fullName>Digitally_Managed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Digitally Managed</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Do_Not_Call__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Call__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This flag indicates users who should not be called e.g. for call cycles</description>
    <label>Do Not Call</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Home_Store__c.field-meta.xml
<CustomField>
    <fullName>Home_Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Home Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Onboarding_Status__c.field-meta.xml
<CustomField>
    <fullName>Onboarding_Status__c</fullName>
    <label>Onboarding Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Onboarding Task Created</fullName>
            </value>
            <value>
                <fullName>Onboarding Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Power_Pass_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Power_Pass_Account_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Power Pass Account Number</label>
    <length>32</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/PowerPass_Account_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>PowerPass_Account_Created_Date__c</fullName>
    <description>This field is populated when a PowerPass account is created</description>
    <label>PowerPass Account Created Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Secondary_Segment__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Segment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The secondary segment of the account</description>
    <label>Secondary Segment</label>
    <referenceTo>Segment__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OnBoardingCallDueDates__mdt/OnBoardingCallDueDates__mdt.object-meta.xml
<CustomObject>
    <description>Used in task trigger handler</description>
    <label>OnBoardingCallDueDates</label>
    <pluralLabel>OnBoardingCallDueDates</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/OnBoardingCallDueDates__mdt/fields/Add_Days__c.field-meta.xml
<CustomField>
    <fullName>Add_Days__c</fullName>
    <label>Add Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Powerpass_Assignment_Rule__mdt/Powerpass_Assignment_Rule__mdt.object-meta.xml
<CustomObject>
    <description>Account assignment rules on powerpass submission</description>
    <label>Powerpass Assignment Rule</label>
    <pluralLabel>Powerpass Assignment Rules</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Powerpass_Assignment_Rule__mdt/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Australia</fullName>
                <default>true</default>
                <label>Australia</label>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Powerpass_Assignment_Rule__mdt/fields/Create_Onboarding_Task__c.field-meta.xml
<CustomField>
    <fullName>Create_Onboarding_Task__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Create Onboarding Task</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Powerpass_Assignment_Rule__mdt/fields/Credit_Limit_Floor__c.field-meta.xml
<CustomField>
    <fullName>Credit_Limit_Floor__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Credit Limit - Floor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Predictive_Model__mdt/Predictive_Model__mdt.object-meta.xml
<CustomObject>
    <description>Used to switch the predictive model</description>
    <label>Predictive Model</label>
    <pluralLabel>Predictive Models</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Predictive_Model__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Predictive model switch</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Predictive_Model__mdt/fields/No_of_Days__c.field-meta.xml
<CustomField>
    <fullName>No_of_Days__c</fullName>
    <description>Number of days to process. Indicated as negative in the criteria (-1 for yesterday)</description>
    <label>No of Days</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Segment__c/Segment__c.object-meta.xml
<CustomObject>
    <description>The segment of the account/lead. Contains the secondary and primary segment names.</description>
    <label>Segment</label>
    <nameField>
        <label>Secondary</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Segment__c/fields/Segment_Group__c.field-meta.xml
<CustomField>
    <fullName>Segment_Group__c</fullName>
    <description>The group the segment belongs to</description>
    <label>Segment Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>Represents all frame and truss plants, small format stores, trade distribution centres and warehouses.</description>
    <label>Store</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Store__c/fields/Engagement_Model__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Model__c</fullName>
    <description>Determines the method used for assigning Powerpass Account Ownership. 
Old Model - the Stores Default Trade Specialist will become the owner. 
New - Ownership is determined by Assignment Rule Metadata records</description>
    <label>Engagement Model</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Old</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/SM_OnboardingCallBatch.cls
/*******************************************************************************************************
* Class Name      	: SM_OnboardingCallBatch
* Description		: Batch Class to create onboarding tasks
* Author          	: Simplus - Simplus MS
* Created On      	: 23/08/2021
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Simplus MS			23/08/2021		1000				Initial version for SPRINT1_CCRM15-56 Changes to onboarding creation and due dates
* Simplus MS			03/09/2021		2000				Additional logic for CCRM15-149 Onboarding tasks at end of month
* Bunnings Dev          26/04/2022      3000                SFSUP-477 - Pilot of Predictive Model
* Bunnings Dev          01/09/2022      4000                SFSUP-678 - Reference the new digitally managed flag in account extension
******************************************************************************************************/
public class SM_OnboardingCallBatch implements Database.Batchable<sObject>, Schedulable
{
    Date powerPassAccountCreatedDate;
    String dateStr;
    public SM_OnboardingCallBatch(){
    //    this.powerPassAccountCreatedDate = null;
    }
    
    public SM_OnboardingCallBatch(string powerPassAccountCreatedDate) {
        
        this.powerPassAccountCreatedDate =  date.parse(powerPassAccountCreatedDate) != null ? date.parse(powerPassAccountCreatedDate) : null;
        dateStr = DateTime.newInstance(this.powerPassAccountCreatedDate.year(),this.powerPassAccountCreatedDate.month(),this.powerPassAccountCreatedDate.day()).format('yyyy-MM-dd');
    }
    public Database.QueryLocator start(Database.BatchableContext BC) {
        
        // SFSUP-477 - Get predictive model config
        Predictive_Model__mdt pmModel;
        List<Predictive_Model__mdt> pm = [SELECT MasterLabel, QualifiedAPIName, Active__c, No_of_Days__c FROM Predictive_Model__mdt
                                     WHERE QualifiedAPIName = 'Digitally_Managed'];
        pmModel = pm[0];
        
        String accountQuery = 'SELECT Id, Account_Status__c, Home_Store__c, Country__c, Power_Pass_Account_Number__c, Do_Not_Call__c, ';
        accountQuery += 'Onboarding_Status__c, ParentId, OwnerId, Phone, CreatedDate, Type, Secondary_Segment__c, Credit_Limit__c, ';
        accountQuery += 'Secondary_Segment__r.Segment_Group__c, PowerPass_Account_Created_Date__c, Account_Extension__r.Digitally_Managed__c ';
        accountQuery += 'FROM Account ';
        accountQuery += 'WHERE Account_Status__c != \'' + 'Inactive' +'\' ';
        accountQuery += 'AND Account_Status__c != \'' + 'Terminated' +'\' ';
        accountQuery += 'AND RecordType.Name != \'' + 'Person Account' +'\'';
        accountQuery += 'AND Country__c != null AND Power_Pass_Account_Number__c != null ';
        accountQuery += 'AND Onboarding_Status__c = null AND Do_Not_Call__c = false AND ParentId = null';
        
        
        if(this.powerPassAccountCreatedDate != null) {
            accountQuery += ' AND Home_Store__c != null AND PowerPass_Account_Created_Date__c = '+dateStr;
        }
        else {
            // SFSUP-477 - Predictive Model
            System.debug('***Model Active: '+pmModel.Active__c);
            
            if (pmModel.Active__c) {
                Date dateToProcess = Date.today().addDays(-Integer.valueOf(pmModel.No_of_Days__c));
                
                System.debug('***Predictive Model On: '+pmModel.No_of_Days__c + ' / ' + dateToProcess);                
                
                // Commented for SFSUP-678
                //accountQuery += ' AND Digital_Managed__c = \'FALSE\' AND Home_Store__c != null AND PowerPass_Account_Created_Date__c <=: dateToProcess AND PowerPass_Account_Created_Date__c != null';
                // Added for SFSUP-678
                accountQuery += ' AND Account_Extension__r.Digitally_Managed__c = \'FALSE\' AND Home_Store__c != null AND PowerPass_Account_Created_Date__c <=: dateToProcess AND PowerPass_Account_Created_Date__c != null';
            } else {
                System.debug('***Predictive Model Off');
            	accountQuery += ' AND Home_Store__c != null AND PowerPass_Account_Created_Date__c = YESTERDAY AND PowerPass_Account_Created_Date__c != null';
            }
        }
        System.debug('accountQuery>> '+accountQuery);
        return Database.getQueryLocator(accountQuery);
    }
    
    public void execute(Database.BatchableContext BC, List<Account> accList) {
        Map<Id, Task> onboardingTasks = new Map<Id, Task>(); 
        Map<Id, Account> accountsToUpdate = new Map<Id, Account>();
        Map<Id, Powerpass_Assignment_Rule__mdt> ruleMap = new Map<Id, Powerpass_Assignment_Rule__mdt>();
        Map<Id, Account> accountMap = new Map<Id, Account>(DM_Account.getAccountsWithSecondarySegment(accList));
        List<Id> storeIds = new List<String>();
        List<Integer> taskAdditionalDaysList = new List<Integer>();
        
        //Fetch Metadata which is use to add additional days to task due date
        List<OnBoardingCallDueDates__mdt> forDueDatesList = [SELECT DeveloperName,Add_Days__c from OnBoardingCallDueDates__mdt where DeveloperName = 'Task_Additional_Days'];
        for(OnBoardingCallDueDates__mdt days : forDueDatesList) {
            taskAdditionalDaysList.add(Integer.valueof(days.Add_Days__c));//convert string to integer
        }
        //Get All the Home Stores related to Account
        for(Account acct : accList) {
            storeIds.add(acct.Home_Store__c);
        }

        Map<Id, Store__c> storeMap = new Map<Id, Store__c>(DM_Store.getStoresWithActiveSMs(storeIds));
        System.debug('storeMap>> '+storeMap);
        for(Account acct : accList) {
            
            String storeModel = storeMap.get(acct.Home_Store__c).Engagement_Model__c;
            String accountType = storeModel == Constants.STORE_MODEL_OLD ? null : acct.Type;
            String segment = null;
            if(storeModel != Constants.STORE_MODEL_OLD && String.isNotBlank(acct.Secondary_Segment__c)) {
                segment = accountMap.get(acct.Id).Secondary_Segment__r.Segment_Group__c;
            }
            if(segment != null){
                segment = segment.toLowerCase();
            }
            String key = accountType + storeModel + segment + acct.Country__c;
            system.debug('key>> '+key);
            Double creditLimit = (acct.Credit_Limit__c == null) ? 0 : acct.Credit_Limit__c;
            if(DM_PowerpassAssignmentRule.ruleMap.containsKey(key)) {
                Powerpass_Assignment_Rule__mdt rule;
                for(Powerpass_Assignment_Rule__mdt par : DM_PowerpassAssignmentRule.ruleMap.get(key)) {
                    if(creditLimit >= par.Credit_Limit_Floor__c) {
                        system.debug('par>> '+par);
                        rule = par;
                        ruleMap.put(acct.Id, par);//ruleMap --> Test
                        break;
                    }
                }
            }
            
            if(ruleMap.containsKey(acct.Id) && ruleMap.get(acct.Id).Create_Onboarding_Task__c == true) {
                   Date powerPassAcctDate = date.newinstance(acct.PowerPass_Account_Created_Date__c.year(), acct.PowerPass_Account_Created_Date__c.month(), acct.PowerPass_Account_Created_Date__c.day());
                   Date powerPassAccountDate;
                   if(this.powerPassAccountCreatedDate != null) {
                       powerPassAccountDate = this.powerPassAccountCreatedDate;
                   }
                   else {
                       powerPassAccountDate = powerPassAcctDate;
                   }
                   onboardingTasks.put(acct.Id, new Task(
                       RecordTypeId = DM_RecordType.rtId_Task_OnboardingCall,
                       ActivityDate = powerPassAccountDate.addDays(taskAdditionalDaysList[0]),
                       IsRecurrence = false,
                       IsReminderSet = false,
                       OwnerId = acct.OwnerId,
                       Phone__c = acct.Phone,
                       Subject = 'Onboarding Call',
                       Type = 'Phone',
                       WhatId = acct.Id,
                       Sub_type__c = 'Onboarding'
                   ));
                   acct.Onboarding_Status__c = 'Onboarding Task Created';
               }
            accountsToUpdate.put(acct.Id, acct);
        }
        System.debug('Accounts Status Updating>> '+accountsToUpdate);
        System.debug('On Boarding Task Inserted>> '+onboardingTasks);
        System.debug('Rule Map>> '+ruleMap);
        
        if(accountsToUpdate.size() > 0 && onboardingTasks.size() > 0) {
            try {
                update accountsToUpdate.values();
            } catch(Exception e) {
				ApplicationLogger.log('SM_OnboardingCallBatch.Execute', 'Update Account', 'BatchClass', e);
            }
        }
        if(onboardingTasks.size() > 0) {
            try {
                insert onboardingTasks.values();
            } catch(Exception e) {
               ApplicationLogger.log('SM_OnboardingCallBatch.Execute', 'Insert Task', 'BatchClass', e);
            }
        }
    }
    public void finish(Database.BatchableContext BC) {
    }
  public void execute(SchedulableContext SC) {
      SM_OnboardingCallBatch myBatchObject = new SM_OnboardingCallBatch(); 
      Id batchId = Database.executeBatch(myBatchObject, 10);
      System.debug('batchId '+batchId);
  }
}