unpackaged/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <description>Status of the Account</description>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Referred</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/AU_Customer.recordType-meta.xml
<RecordType>
    <fullName>AU_Customer</fullName>
    <active>true</active>
    <description>Australian customer accounts</description>
    <label>AU Customer</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/AU_Prospect.recordType-meta.xml
<RecordType>
    <fullName>AU_Prospect</fullName>
    <active>true</active>
    <description>Australian prospect accounts</description>
    <label>AU Prospect</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/NZ_Customer.recordType-meta.xml
<RecordType>
    <fullName>NZ_Customer</fullName>
    <active>true</active>
    <description>New Zealand Customer Account</description>
    <label>NZ Customer</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/NZ_Prospect.recordType-meta.xml
<RecordType>
    <fullName>NZ_Prospect</fullName>
    <active>true</active>
    <description>New Zealand prospect accounts</description>
    <label>NZ Prospect</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Call_Days__c.field-meta.xml
<CustomField>
    <fullName>Call_Days__c</fullName>
    <description>Call days, applicable to frequencies such as Twice Weekly, 3 x Week</description>
    <label>Call Days</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mon</fullName>
            </value>
            <value>
                <fullName>Tue</fullName>
            </value>
            <value>
                <fullName>Wed</fullName>
            </value>
            <value>
                <fullName>Thu</fullName>
            </value>
            <value>
                <fullName>Fri</fullName>
            </value>
            <value>
                <fullName>Sat</fullName>
            </value>
            <value>
                <fullName>Sun</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/First_Day__c.field-meta.xml
<CustomField>
    <fullName>First_Day__c</fullName>
    <description>First day of planned calls</description>
    <label>First Day</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Recurrence__c.field-meta.xml
<CustomField>
    <fullName>Recurrence__c</fullName>
    <description>Until date of planned calls</description>
    <label>Recurrence</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Target_Call_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Target_Call_Frequency__c</fullName>
    <description>Call frequency</description>
    <label>Target Call Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>3 x Week</fullName>
            </value>
            <value>
                <fullName>Twice Weekly</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Bi-Weekly</fullName>
            </value>
            <value>
                <fullName>Every 4 weeks</fullName>
            </value>
            <value>
                <fullName>Every 8 weeks</fullName>
            </value>
            <value>
                <fullName>Every 3 weeks</fullName>
            </value>
            <value>
                <fullName>Every quarter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/CallPlanner_ManualCreateBatch.cls
/**
 * @author            : Simplus MS
 * @last modified on  : 25/11/2021
 * @last modified by  : Simplus MS
**/
public with sharing class CallPlanner_ManualCreateBatch implements Database.Batchable<sObject> {
    
    List<String> PROFILES = new List<String>{'Account Manager', 'NZ Account Manager', 'Organisations Sales', 'Sales Person BDM', 'Sales Person BDM - Insurance', 'Sales Person Contact Centre'};

    String query;
    
    public CallPlanner_ManualCreateBatch() {
        query = 
        'SELECT Id, Name, Target_Call_Frequency__c, First_Day__c, Recurrence__c, Call_Days__c, AccountId ' +
        'FROM Contact ' +
        'WHERE Target_Call_Frequency__c != NULL AND Recurrence__c != NULL AND First_Day__c != NULL ' +
        'AND Account.Owner.isActive = TRUE ' +
        'AND Account.Owner.Name != \'Default User\' ' +
        'AND Account.Owner.Profile.Name IN :PROFILES ' +
        'AND Account.RecordType.DeveloperName IN (\'AU_Customer\', \'NZ_Customer\', \'AU_Prospect\', \'NZ_Prospect\')' +
        'AND Account.Account_Status__c IN (\'Active\', \'Referred\')' +
        'ORDER BY Account.Name ASC, Name ASC';
    }

    public Database.QueryLocator start(Database.BatchableContext BC) {
        System.debug('query: '+query);
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, List<Contact> scope) {
        try{
            TEMP_SM_CallPlanner.executePlans(null, null, scope);
        } catch(Exception e) {
            System.debug(e);
        }
    }

    public void finish(Database.BatchableContext BC) { 

    }

}