unpackaged/main/default/objects/Account/fields/Account_State__c.field-meta.xml
<CustomField>
    <fullName>Account_State__c</fullName>
    <description>Seperate to Address, this field shows the Account State.</description>
    <label>Account State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACT</fullName>
            </value>
            <value>
                <fullName>NQ</fullName>
            </value>
            <value>
                <fullName>NATIONAL</fullName>
            </value>
            <value>
                <fullName>NSW</fullName>
            </value>
            <value>
                <fullName>NT</fullName>
            </value>
            <value>
                <fullName>QLD</fullName>
            </value>
            <value>
                <fullName>SA</fullName>
            </value>
            <value>
                <fullName>TAS</fullName>
            </value>
            <value>
                <fullName>VIC</fullName>
            </value>
            <value>
                <fullName>WA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Account_Transferrable__c.field-meta.xml
<CustomField>
    <fullName>Account_Transferrable__c</fullName>
    <formula>IF( ISPICKVAL(Transfer_approval_status__c , &#39;Submitted for approval&#39;) || ISPICKVAL(Pricing_Assignment_Status__c , &#39;Pending Approval&#39;) , &#39;No&#39;, &#39;Yes&#39;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>There are accounts under approval.</inlineHelpText>
    <label>Account Transferrable</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Assigned_Store__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Assigned Store of a trade Specialist User</description>
    <label>Assigned Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Accounts (Assigned Store)</relationshipLabel>
    <relationshipName>Accounts3</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Bulk_Account_Transfer__c.field-meta.xml
<CustomField>
    <fullName>Bulk_Account_Transfer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To check if this account has been transferred using Bulk Account Transfer</description>
    <label>Bulk Account Transfer</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/On_Contract__c.field-meta.xml
<CustomField>
    <fullName>On_Contract__c</fullName>
    <description>Yes if any of related Contract is Active. No if NONE of any related Contract is Active</description>
    <label>On Contract</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Power_Pass_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Power_Pass_Account_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Power Pass Account Number</label>
    <length>32</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/PowerPass_Account_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>PowerPass_Account_Created_Date__c</fullName>
    <description>This field is populated when a PowerPass account is created</description>
    <label>PowerPass Account Created Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Primary_Segment__c.field-meta.xml
<CustomField>
    <fullName>Primary_Segment__c</fullName>
    <description>The primary segment of the account</description>
    <formula>Secondary_Segment__r.Primary__c</formula>
    <label>Primary Segment</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Secondary_Segment__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Segment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The secondary segment of the account</description>
    <label>Secondary Segment</label>
    <referenceTo>Segment__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Transfer_comments__c.field-meta.xml
<CustomField>
    <fullName>Transfer_comments__c</fullName>
    <label>Transfer comments</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Account_Request__c/Account_Request__c.object-meta.xml
<CustomObject>
    <label>Account Request</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Account Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Account_Request__c/fields/Transfer_comments__c.field-meta.xml
<CustomField>
    <fullName>Transfer_comments__c</fullName>
    <label>Transfer comments</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Various contracts associated to customers, projects and umbrellas. Use of custom object in place of standard considering future implementation of CPQ with contract and its line items.</description>
    <label>Contract</label>
    <nameField>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Contract__c/fields/New_Approver__c.field-meta.xml
<CustomField>
    <fullName>New_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contracts3</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract__c/fields/New_Reviewer__c.field-meta.xml
<CustomField>
    <fullName>New_Reviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Reviewer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contracts2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Customer_Contract__c/Customer_Contract__c.object-meta.xml
<CustomObject>
    <label>Customer Contract</label>
    <nameField>
        <displayFormat>CC-{00000000}</displayFormat>
        <label>Customer Contract</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Contract__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <description>Contract for customer contract</description>
    <inlineHelpText>Contract for customer contract</inlineHelpText>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Customer Contracts</relationshipLabel>
    <relationshipName>Customer_Contracts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Customer_Contract__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <description>Customer this customer contract is related to. Ref #CCRM-145</description>
    <inlineHelpText>Customer this customer contract is related to</inlineHelpText>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Contracts</relationshipLabel>
    <relationshipName>Customer_Contracts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Customer_Contract__c/fields/Power_Pass_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Power_Pass_Account_Number__c</fullName>
    <description>Account Power Pass Number</description>
    <formula>Customer__r.Power_Pass_Account_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Power Pass Account Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Segment__c/Segment__c.object-meta.xml
<CustomObject>
    <description>The segment of the account/lead. Contains the secondary and primary segment names.</description>
    <label>Segment</label>
    <nameField>
        <label>Secondary</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>Represents all frame and truss plants, small format stores, trade distribution centres and warehouses.</description>
    <label>Store</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/classes/SM_BulkAccountAndRelatedTransferBatch.cls
/*******************************************************************************************************
* Class Name      	: SM_BulkAccountAndRelatedTransferBatch
* Description		: Batch class for transfer bulk accounts
* Author          	: Bunnigs Dev
* Created On      	: 20/07/2024
* Modification Log  :
* -----------------------------------------------------------------------------------------------------
* Developer             Date            Modification ID     Description
* -----------------------------------------------------------------------------------------------------
* Buunings Dev          20/07/2024      1000                Initial version
* -----------------------------------------------------------------------------------------------------*/
public class SM_BulkAccountAndRelatedTransferBatch implements Database.Batchable<sObject>,Database.Stateful{
    String query;
    String transferFromId;
    String transferToId;
    String newContractOwnerId;
    String comments;
    
  
    List<Account> lSelectedAccounts = new List<Account>();
    List<Account_Request__c> lUpdateAccountRequests = new List<Account_Request__c>();
    Map<id,id> acctoAccReqMap = new Map<id,id>();

    public SM_BulkAccountAndRelatedTransferBatch(List<Account_Request__c> lUpdateAccountReqs, List<Account> lSelectedAccounts, Id transferFromUserId, Id transferToUserId, String newContractOwner, String comments,Map<id,id> acctoAccRequestMap) {
        
        
        transferFromId = transferFromUserId;
        transferToId = transferToUserId;
        newContractOwnerId = newContractOwner;
        comments = comments;
        lSelectedAccounts = lSelectedAccounts;
        lUpdateAccountRequests = lUpdateAccountReqs;
        acctoAccReqMap = acctoAccRequestMap;

        System.debug('transferFromId-->' +transferFromId);
        System.debug('transferToUserId-->' +transferToUserId);
        System.debug('this.newContractOwner-->' +newContractOwnerId);
        System.debug('lUpdateAccountRequests-->' +lUpdateAccountRequests);
        System.debug('acctoAccReqMap-->' +acctoAccReqMap);

            List<Id> sAccountIds = new List<Id>();
            for (Account acc : lSelectedAccounts){
                sAccountIds.add(acc.Id);
            }
            String idString= '\''+String.join(sAccountIds,'\',\'')+'\'';
            system.debug('sAccountIds ' +sAccountIds);
            query = 'SELECT Id, Name, Power_Pass_Account_Number__c, PowerPass_Account_Created_Date__c, On_Contract__c, '
                + ' Account_State__c, BillingAddress, Assigned_Store__r.Name, Primary_Segment__c, '
                + ' Secondary_Segment__r.Name, Account_Transferrable__c '
                + ' FROM Account'
                + ' WHERE Id IN (' +idString+ ')';
        
        
        System.debug('Query-->' +query);
    }
    
    public Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);

        
    }
    
    public void execute(Database.BatchableContext BC, List<Account> scope) {
        // execute code
        System.debug('Scope ::' +scope);
        
        try {
            List<Account> updateAcctList = new List<Account>();
            List<Account> acctList = new List<Account>();
            List<Contract__c> contractList = new List<Contract__c>();
            
            
            for(Account a : scope){
                if(a.Account_Transferrable__c == 'Yes'){
                    Account acc = new Account();
                    acc.Id = a.Id;
                    acc.OwnerId = transferToId;
                    acc.Bulk_Account_Transfer__c = true;
                    acc.Transfer_comments__c = comments;
                    updateAcctList.add(acc);
                      
                }
                
            }
            Set<Id> ownerIds = new Set<Id>();
            ownerIds.add(transferFromId);
            List<id> resultSet = new List<id>();
            List<id> resultSetError = new List<id>();
            
            if(updateAcctList!=null && !updateAcctList.isEmpty()){
                try {

                   
                        List<Database.SaveResult> accountResults = Database.update(updateAcctList, false);
                        
                        for (Database.SaveResult result : accountResults) {
                            if (result.isSuccess()){
                                resultSet.add(result.getId());
                            }
                        if (!result.isSuccess()){
                            for (Database.Error err : result.getErrors()){
                            resultSetError.add(result.getId());

                             ApplicationLogger.log('SM_BulkAccountAndRelatedTransferBatch.updateAccounts', 'AccountRequest', 'BulkBatch', result.getId() + ' ' + err.getStatusCode() + ' ' + err.getMessage()); 
                            System.debug('Error: '+ result.getId() + ' ' + err.getStatusCode() + ' ' + err.getMessage()); 
                            }
                        }
                        }
                 
                    system.debug('resultSet here :: '+resultSet);
                    List<Account> accListToUpdate = DM_Account.getAccounts(resultSet);
                   Map<id,id> accReqMap =new Map<id,id>();
                  
                   if( !resultSet.isEmpty() || resultSet != null){
                        for(id key : resultSet ){
                            accReqMap.put(acctoAccReqMap.get(key),key);

                        }
                    }

                        system.debug('accReqMap here :: '+accReqMap);
                    system.debug('lUpdateAccountRequests here :: '+lUpdateAccountRequests);
                    SM_AccountRequestTransfer.transferAccountRelatedRecords(accListToUpdate, transferFromId, transferToId,lUpdateAccountRequests,accReqMap);
                    
                    Set<Id> acctIds = new Set<Id>(resultSet);
                    if(acctIds!=null){
                        List<Customer_Contract__c> contracts = DM_CustomerContract.getNonExpiredCustContracts(acctIds, ownerIds);
                        System.debug('newContractOwnerId::' +newContractOwnerId);
                        User managerIdUser = DM_User.getUser(newContractOwnerId);
                        System.debug('managerIdUser-->' +managerIdUser);
                        if(contracts!=null && !contracts.isEmpty()){
                            for(Customer_Contract__c cusContract : contracts){
                                if(cusContract.Customer__r.Account_Transferrable__c == 'Yes'){
                                    Contract__c contract = new Contract__c();
                                    contract.Id = cusContract.Contract__r.Id;
                                    contract.OwnerId = newContractOwnerId;
                                    contract.New_Reviewer__c = newContractOwnerId;
                                    contract.New_Approver__c = managerIdUser.ManagerId;
                                    contractList.add(contract);
                                }
                            }
                        }
                    }
                   
                    if(contractList!=null && !contractList.isEmpty()){
                        system.debug('contractList here :: '+contractList);
                        List<Database.SaveResult> contractResults = Database.update(contractList, false);
                        for (Database.SaveResult result : contractResults) {
                        if (!result.isSuccess()){
                            for (Database.Error err : result.getErrors()){
                            ApplicationLogger.log('SM_BulkAccountAndRelatedTransferBatch.updateContracts', 'AccountRequest', 'BulkBatch', result.getId() + ' ' + err.getStatusCode() + ' ' + err.getMessage()); 
                            System.debug('Error: '+ result.getId() + ' ' + err.getStatusCode() + ' ' + err.getMessage()); 
                            }
                        }
                        }
                        
                    } 
                    
                    
                } catch (Exception ex) {
                    System.debug(ex.getStackTraceString());
                    SM_AccountRequestTransfer.sendBulkAccountTransferErrorNotification(transferFromId);
                }
            }
            
        } catch(Exception e) {
            System.debug(e.getMessage());
            System.debug(e.getStackTraceString());
        }
    }
    
    public void finish(Database.BatchableContext BC) {
        // finish code
        SM_AccountRequestTransfer.sendBulkAccountTransferNotification(transferToId);
    }
    

    
    
}