unpackaged/main/default/objects/Account/fields/Account_Transferrable__c.field-meta.xml
<CustomField>
    <fullName>Account_Transferrable__c</fullName>
    <formula>IF( ISPICKVAL(Transfer_approval_status__c , &#39;Submitted for approval&#39;) || ISPICKVAL(Pricing_Assignment_Status__c , &#39;Pending Approval&#39;) , &#39;No&#39;, &#39;Yes&#39;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>There are accounts under approval.</inlineHelpText>
    <label>Account Transferrable</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Power_Pass_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Power_Pass_Account_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Power Pass Account Number</label>
    <length>32</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/PowerPass_Account_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>PowerPass_Account_Created_Date__c</fullName>
    <description>This field is populated when a PowerPass account is created</description>
    <label>PowerPass Account Created Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/R12_Sales__c.field-meta.xml
<CustomField>
    <fullName>R12_Sales__c</fullName>
    <label>R12 Sales</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Spend_Band__c.field-meta.xml
<CustomField>
    <fullName>Spend_Band__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Spend Band for the Account</description>
    <label>Spend Band</label>
    <referenceTo>Spend_Band__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml
<CustomObject>
    <description>SFSUP - 306</description>
    <label>Account Plan</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Account Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Account_Request__c/Account_Request__c.object-meta.xml
<CustomObject>
    <label>Account Request</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Account Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Various contracts associated to customers, projects and umbrellas. Use of custom object in place of standard considering future implementation of CPQ with contract and its line items.</description>
    <label>Contract</label>
    <nameField>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Contract__c/Customer_Contract__c.object-meta.xml
<CustomObject>
    <label>Customer Contract</label>
    <nameField>
        <displayFormat>CC-{00000000}</displayFormat>
        <label>Customer Contract</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Contract__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <description>Contract for customer contract</description>
    <inlineHelpText>Contract for customer contract</inlineHelpText>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Customer Contracts</relationshipLabel>
    <relationshipName>Customer_Contracts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Customer_Contract__c/fields/Power_Pass_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Power_Pass_Account_Number__c</fullName>
    <description>Account Power Pass Number</description>
    <formula>Customer__r.Power_Pass_Account_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Power Pass Account Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Spend_Band__c/Spend_Band__c.object-meta.xml
<CustomObject>
    <description>Spend band ranges for customers.</description>
    <label>Spend Band</label>
    <nameField>
        <label>Spend Band</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spend Bands</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Spend_Band__c/fields/Spend_Band_ID__c.field-meta.xml
<CustomField>
    <fullName>Spend_Band_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Spend Band ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Spend_Band_Review__c/Spend_Band_Review__c.object-meta.xml
<CustomObject>
    <description>This Object represents the Spend Band Review table mastered in the Commercial Pricing System (CPS). CPS is the master of the Spend Band review data, Salesforce owns the Spend Band Review approval process.</description>
    <label>Spend Band Review</label>
    <nameField>
        <displayFormat>SBR-{0000000}</displayFormat>
        <label>Review Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Spend Band Reviews</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/classes/SM_BulkAccountRequestTransferBatchTest.cls
/*******************************************************************************************************
* Class Name      	: SM_BulkAccountRequestTransferBatchTest
* Description		: Test class for SM_BulkAccountRequestTransferBatch
******************************************************************************************************/

@isTest
private class SM_BulkAccountRequestTransferBatchTest {
        @testSetup 
    public static void testDataSetup() {
              
        Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1]; // Trade Specialist
        
        List<User> users = TestDataFactory.createUsers(4, p.Id);
        insert users;
        users[0].ManagerId = users[1].Id;
        users[0].isActive = true;
        users[1].ManagerId = users[2].Id;
         users[1].isActive = true;
        users[2].ManagerId = users[3].Id;
         users[2].isActive = true;
        update users;
        
        User u = users[0];
        
        System.runAs(users[0]) {
            List<Account> accounts = TestDataFactory.createAccounts(100);
        Integer var = 5;
        List<Account> toInsert = new List<Account>();
        for (Account acct: accounts ){
            acct.OwnerId = UserInfo.getUserId();
            acct.R12_Sales__c = 1;
            acct.Power_Pass_Account_Number__c = String.valueof(var);
            acct.PowerPass_Account_Created_Date__c = System.Today();
            toInsert.add(acct);
            var = var + 1;
        }
        insert toInsert;
            List<Account> accts = [SELECT Id, OwnerId, Account_Transferrable__c FROM Account WHERE Id =: toInsert[0].Id];
        Map<String,String> accReq  = new Map<String,String>();

        for(Account accnt : accounts){
            accReq.put(accnt.Power_Pass_Account_Number__c,u.id );
        }
        List<Account_Request__c> ars = TestDataFactory.createBulkAccountRequests(accReq);
        insert ars;
            Account a = accts[0];
            
            List<Task> tasks = TestDataFactory.createOpenTasksWithWhatId(a.Id, u.Id, 2);
            tasks.addAll(TestDataFactory.createClosedTasksWithWhatId(a.Id, u.Id, 2));
            insert tasks;
            
            List<Event> events = TestDataFactory.createOpenEventsWithWhatId(a.Id, u.Id, 3);
            events.addAll(TestDataFactory.createClosedEventsWithWhatId(a.Id, u.Id, 1));
            insert events;
            
            List<Opportunity> oppties = TestDataFactory.createOpenOpportunities(a.Id, u.Id, 110);
            oppties.addAll(TestDataFactory.createClosedOpportunities(a.Id, u.Id, 2));
            insert oppties;
            
            List<Contact> contacts = TestDataFactory.createContacts(a.Id, u.Id, 5);
            insert contacts;
            
            Contact con = contacts[0];
            
            List<Case> cases = TestDataFactory.createOpenCases(a.Id, u.Id, 6);
            cases.addAll(TestDataFactory.createClosedCases(a.Id, u.Id, 2));
            insert cases;
            
            List<Contract__c> contracts = TestDataFactory.createNoExpiredContracts(u.Id, 'Australia', 1);
            contracts.addAll(TestDataFactory.createExpiredContracts(u.Id, 'Australia', 3));
            insert contracts;
            
            List<Customer_Contract__c> ccs = TestDataFactory.createCustomerContracts(a.Id, new List<Id>((new Map<Id, Contract__c>(contracts)).keySet()));
            insert ccs;
            
            List<Spend_Band__c> sbs = TestDataFactory.createSpendBands(new List<Double>{4000, 5000}, new List<String>{'AT_TEST_01', 'AT_TEST_02'}, 'Australia');
            upsert sbs Spend_Band_ID__c;
            
            Spend_Band_Review__c sbr = TestDataFactory.createSpendBandReview(a.Id, sbs[0].Id, sbs[1].Id, 'Australia');
            insert new List<Spend_Band_Review__c>{sbr};    
             
                
            Account_Plan__c acp = TestDataFactory.createAccountPlan(a.Id, con.Id);
            insert acp; 
                
        }
            
    }
    
    @isTest
    private static void test_transferAllAccounts() {
                   
        Test.startTest();
        	Database.executebatch(new SM_BulkAccountRequestTransferBatch());
        Test.stopTest();
    }
    
     @isTest
    private static void test_transferAllAccountsErrorNotification() {
        User u = [Select id from User Limit 1];  
        Test.startTest();
        try{
           SM_AccountRequestTransfer.sendBulkAccountTransferErrorNotification(u.id); 
        
        }catch (Exception e){
            System.assert(TRUE);
        }

        Test.stopTest();
    }

}