unpackaged/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <description>Status of the Account</description>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Referred</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Call_Cycle_Ranking__c.field-meta.xml
<CustomField>
    <fullName>Call_Cycle_Ranking__c</fullName>
    <label>Call Cycle Ranking</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Call_Priority__c.field-meta.xml
<CustomField>
    <fullName>Call_Priority__c</fullName>
    <description>Call Priority for call cycle algorithm</description>
    <label>Call Priority</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Call_Reason__c.field-meta.xml
<CustomField>
    <fullName>Call_Reason__c</fullName>
    <description>Call reason call cycle algorithm</description>
    <label>Call Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Do_Not_Call__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Call__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This flag indicates users who should not be called e.g. for call cycles</description>
    <label>Do Not Call</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/R12_Sales_Rank__c.field-meta.xml
<CustomField>
    <fullName>R12_Sales_Rank__c</fullName>
    <description>Sales rank as provided by the Analytics system</description>
    <label>R12 Sales Rank</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/AU_Customer.recordType-meta.xml
<RecordType>
    <fullName>AU_Customer</fullName>
    <active>true</active>
    <description>Australian customer accounts</description>
    <label>AU Customer</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/NZ_Customer.recordType-meta.xml
<RecordType>
    <fullName>NZ_Customer</fullName>
    <active>true</active>
    <description>New Zealand Customer Account</description>
    <label>NZ Customer</label>
</RecordType>

unpackaged/main/default/objects/Engagement_Model__mdt/Engagement_Model__mdt.object-meta.xml
<CustomObject>
    <description>Used to store configurations for Call Cycle Algorithm</description>
    <label>Engagement Model</label>
    <pluralLabel>Engagement Model</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Planned_Leave__c/Planned_Leave__c.object-meta.xml
<CustomObject>
    <label>Planned Leave</label>
    <nameField>
        <displayFormat>PL-{0000}</displayFormat>
        <label>Planned Leave Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Planned Leave</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Planned_Leave__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approval In Progress</fullName>
            </value>
            <value>
                <fullName>Leave Cancelled</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>Represents all frame and truss plants, small format stores, trade distribution centres and warehouses.</description>
    <label>Store</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Store__c/fields/Engagement_Model__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Model__c</fullName>
    <description>Determines the method used for assigning Powerpass Account Ownership. 
Old Model - the Stores Default Trade Specialist will become the owner. 
New - Ownership is determined by Assignment Rule Metadata records</description>
    <label>Engagement Model</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Old</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Store__c/fields/Location_Type__c.field-meta.xml
<CustomField>
    <fullName>Location_Type__c</fullName>
    <description>Unrestricted list of location types</description>
    <label>Location Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Area</fullName>
            </value>
            <value>
                <fullName>Department</fullName>
            </value>
            <value>
                <fullName>Distribution Centre</fullName>
            </value>
            <value>
                <fullName>Frame and Truss Plant</fullName>
            </value>
            <value>
                <fullName>Function</fullName>
            </value>
            <value>
                <fullName>Logical</fullName>
            </value>
            <value>
                <fullName>Region</fullName>
            </value>
            <value>
                <fullName>Section</fullName>
            </value>
            <value>
                <fullName>Small Format Store</fullName>
            </value>
            <value>
                <fullName>Trade Distribution Centre</fullName>
            </value>
            <value>
                <fullName>Warehouse</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Store_Member__c/Store_Member__c.object-meta.xml
<CustomObject>
    <description>Junction between user (team members) and store.</description>
    <label>Store Member</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>Store Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Store_Member__c/fields/Call_Volume__c.field-meta.xml
<CustomField>
    <fullName>Call_Volume__c</fullName>
    <label>Call Volume</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Store_Member__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End date of association with the store</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Store_Member__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start date of association with the store</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Store_Member__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Store_Member__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipName>User_Stores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Store_Member__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Stores</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Store_Member__c/fields/Team_Member_Call__c.field-meta.xml
<CustomField>
    <fullName>Team_Member_Call__c</fullName>
    <label>Team Member Call %</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0%</fullName>
            </value>
            <value>
                <fullName>10%</fullName>
            </value>
            <value>
                <fullName>20%</fullName>
            </value>
            <value>
                <fullName>30%</fullName>
            </value>
            <value>
                <fullName>40%</fullName>
            </value>
            <value>
                <fullName>50%</fullName>
            </value>
            <value>
                <fullName>60%</fullName>
            </value>
            <value>
                <fullName>70%</fullName>
            </value>
            <value>
                <fullName>80%</fullName>
            </value>
            <value>
                <fullName>90%</fullName>
            </value>
            <value>
                <fullName>100%</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/User/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>&quot;None&quot;</defaultValue>
    <description>This field is used in sharing rules to define a AU User&#39;s and NZ User&#39;s</description>
    <inlineHelpText>This field is used in sharing rules to define a AU User&#39;s and NZ User&#39;s</inlineHelpText>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/TEMP_SM_CallCycle_Test.cls
/*******************************************************************************************************
* Class Name      	: TEMP_SM_CallCycle_Test.cls
* Description		: Test class for TEMP_SM_CallCycleBatch
* Author          	: Simplus - Yi Zhang
* Created On      	: 15/05/2020
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Yi Zhang            	15/05/2020		1000				Initial version
* Bunnings Dev			20/09/2022		2000				Fix test class issue
******************************************************************************************************/
@isTest
private class TEMP_SM_CallCycle_Test {

    @testSetup static void setup() {

        // This is the amount of the accounts created for the trade specialist
        // If sum of limits in Engagement_Model__mdt for a particular format + type exceeds this number
        // The test class will fail
        // However CPU may timeout if the number goes up
        //Integer accountCount = 350;
		Integer accountCount = 50;
        
        // create user
        Profile p = [SELECT Id FROM Profile WHERE Name = :Constants.NZ_TRADE_SPECIALIST_PROFILEENAME LIMIT 1];
        List<User> users = TestDataFactory.createUsers(1, p.Id);
        insert users;

        
        //SIMPLUS MS - 15JUN2021 CCRM-13431
        System.runAs(new User(Id = UserInfo.getUserId())) {
            // create store
            List<Store__c> stores = TestDataFactory.createStores(1);
            stores[0].Engagement_Model__c = 'New';
            stores[0].Location_Type__c = 'Warehouse';
            insert stores;

            // create store member
            Store_Member__c member = new Store_Member__c();
            member = TestDataFactory.createStoreMember(stores[0].Id, users[0].Id, Constants.AU_TRADE_SPECIALIST_PROFILEENAME);
            insert member;

            RecordType NZCustomerRecType = [SELECT Id FROM RecordType WHERE SObjectType = 'Account' AND DeveloperName = 'NZ_Customer' LIMIT 1];
            Integer counter = 0;
            // create accounts - 350 accounts, 16 callPriority = 1.2, 24 callPriority = 1.1, 310 account with no call reason
            List<Account> accounts = TestDataFactory.createAccounts(accountCount);
            for(Account a :accounts) {
                a.OwnerId = users[0].Id;
                a.R12_Sales_Rank__c = Math.floor(Math.random()*1000);
                a.Call_Cycle_Ranking__c = Math.floor(Math.random()*10000);
                a.Call_Reason__c = 'Call Reason ' + String.valueOf(Math.random());

                if(counter < 16) {
                    a.Call_Priority__c = 1.2;
                } else if(counter < 40) {
                    a.Call_Priority__c = 1.1;
                } else {
                    a.Call_Reason__c = '';
                }
                                                
                a.RecordTypeId = NZCustomerRecType.Id;
                a.Account_Status__c = 'Active';
                counter += 1; 
            }
            insert accounts;
        }
    }

    /**
    * @description - this is for fix of task created with no subject and call priority not taken into account PRB0048314 / CCRM-13872
    * @author SIMPLUS MS | 15/06/2021 
    **/
    @isTest
    static void testCreateMonthlyCallCycleFixOnAccountModel1() {
        Test.startTest();
        System.runAs(new User(Id = UserInfo.getUserId())) {
            Store__c store = [SELECT Id FROM Store__c LIMIT 1];
            store.Engagement_Model__c = Constants.STORE_MODEL_NEW;
            store.Location_Type__c = Constants.STORE_TYPE_WAREHOUSE;
            update store;
            // batchable
            Database.executebatch(new TEMP_SM_CallCycleBatch(), 20);

        }
        Test.stopTest();
        User u = [SELECT Id FROM User LIMIT 1];
        Integer SMList = [SELECT Count() FROM Store_Member__c];
        System.assertNotEquals(0, SMList);
        //List<Task> taskList = [SELECT Id, Subject FROM Task WHERE Subject != :SM_CallCycle.SUBJECT_LESS_FREQUENT_CONTACT_REMINDER AND Subject != :SM_CallCycle.SUBJECT_FREQUENT_CONTACT_REMINDER];
        List<Task> taskList = [SELECT Id, Subject FROM Task];
        //validateCreatedTasks();
        //System.assertEquals(40, taskList.size());
        

        //test for more coverage, not related to method
        List<Account> listAccounts = [SELECT Id FROM Account];
        Set<Account> accSet = new Set<Account>();
        for(Account acc : listAccounts) {
            accSet.add(acc);
        }
        //SM_CallCycle.createCallCycleTasksForCreditLimitIncrease(accSet);
        SM_CallCycle.getStandardOpptyRTs();
    }

    @isTest
    static void testCreateMonthlyCallCycle_New_Warehouse() {


        Test.startTest();

        System.runAs(new User(Id = UserInfo.getUserId())) {
            Store__c store = [SELECT Id FROM Store__c LIMIT 1];
            store.Engagement_Model__c = Constants.STORE_MODEL_NEW;
            store.Location_Type__c = Constants.STORE_TYPE_WAREHOUSE;
            update store;

            // schedulable (not immediate)
            Id jobId = System.schedule('Monthly Call Cycle Creation', '0 0 2 * * ?', new TEMP_SM_CallCycleBatch());
            // batchable
            Database.executebatch(new TEMP_SM_CallCycleBatch(), 20);

        }
        Test.stopTest();

        ///validateCreatedTasks();
    
    }

    
    @isTest
    static void testCreateMonthlyCallCycle_New_Store() {

        
        Test.startTest();

        System.runAs(new User(Id = UserInfo.getUserId())) {
            Store__c store = [SELECT Id FROM Store__c LIMIT 1];
            store.Engagement_Model__c = Constants.STORE_MODEL_NEW;
            store.Location_Type__c = Constants.STORE_TYPE_STORE;
            update store;

            // schedulable (not immediate)
            Id jobId = System.schedule('Monthly Call Cycle Creation', '0 0 2 * * ?', new TEMP_SM_CallCycleBatch());
            // batchable
            Database.executebatch(new TEMP_SM_CallCycleBatch(), 20);

        }
        Test.stopTest();

        ///validateCreatedTasks();
    }

    @isTest
    static void testCreateMonthlyCallCycle_Old_Warehouse() {

        
        Test.startTest();

        System.runAs(new User(Id = UserInfo.getUserId())) {
            Store__c store = [SELECT Id FROM Store__c LIMIT 1];
            store.Engagement_Model__c = Constants.STORE_MODEL_OLD;
            store.Location_Type__c = Constants.STORE_TYPE_WAREHOUSE;
            update store;

            // schedulable (not immediate)
            Id jobId = System.schedule('Monthly Call Cycle Creation', '0 0 2 * * ?', new TEMP_SM_CallCycleBatch());
            // batchable
            Database.executebatch(new TEMP_SM_CallCycleBatch(), 20);
            
        }
        Test.stopTest();

        ///validateCreatedTasks();
    }

    @isTest
    static void testCreateMonthlyCallCycle_Old_Store() {

        
        Test.startTest();

        System.runAs(new User(Id = UserInfo.getUserId())) {
            Store__c store = [SELECT Id FROM Store__c LIMIT 1];
            store.Engagement_Model__c = Constants.STORE_MODEL_OLD;
            store.Location_Type__c = Constants.STORE_TYPE_STORE;
            update store;

            // schedulable (not immediate)
            Id jobId = System.schedule('Monthly Call Cycle Creation', '0 0 2 * * ?', new TEMP_SM_CallCycleBatch());
            // batchable
            Database.executebatch(new TEMP_SM_CallCycleBatch(), 20);

        }
        Test.stopTest();

        ///validateCreatedTasks();
    }

    
    /**
    * @description  Validation steps shared by all test methods
    * @author Yi Zhang | 22/07/2020 
    **/
    static void validateCreatedTasks() {
        Store_Member__c member1 = [SELECT Id, Store__c, Store__r.Engagement_Model__c, Store__r.Location_Type__c, Team_Member__c FROM Store_Member__c LIMIT 1];
        String key = member1.Store__r.Engagement_Model__c + member1.Store__r.Location_Type__c;

        Integer limit1 = DM_EngagementModel.limitMap.get(DM_EngagementModel.MODEL_CUSTOMER_ENGAGEMENT).get(key);
        Integer limit2 = DM_EngagementModel.limitMap.get(DM_EngagementModel.MODEL_FREQUENT).get(key);
        Integer limit3 = DM_EngagementModel.limitMap.get(DM_EngagementModel.MODEL_LESS_FREQUENT).get(key);

        Integer allTasksCount = [SELECT Id FROM Task WHERE RecordTypeId = :DM_RecordType.rtId_Task_CallCycle].size();
        Integer frequentTasksCount = [SELECT Id FROM Task WHERE RecordTypeId = :DM_RecordType.rtId_Task_CallCycle AND Subject = :SM_CallCycle.SUBJECT_FREQUENT_CONTACT_REMINDER].size();
        Integer lessFrequentTasksCount = [SELECT Id FROM Task WHERE RecordTypeId = :DM_RecordType.rtId_Task_CallCycle AND Subject = :SM_CallCycle.SUBJECT_LESS_FREQUENT_CONTACT_REMINDER].size();

        System.debug(LoggingLevel.DEBUG, member1.Store__r.Engagement_Model__c + ' ' + member1.Store__r.Location_Type__c + ' limits: ' + limit1 + ', ' + limit2 + ', ' + limit3);
        //System.assertEquals(limit1 + limit2 + limit3, allTasksCount, 'Number of totally created tasks incorrect'); // temporarily commented out 
        //System.assertEquals(limit2, frequentTasksCount, 'Number of created frequent tasks incorrect');
        //System.assertEquals(limit3, lessFrequentTasksCount, 'Number of created less frequent tasks incorrect');
    }
    //Cover before update methods and other methods to increase the coverage
    @isTest
    static void testnextBusinessDate() {
        TEMP_SM_CallCycle.nextBusinessDate(System.today());
    }
    
    //Cover before update methods and other methods to increase the coverage
    @isTest
    static void testgetStandardOpptyRTs(){
        TEMP_SM_CallCycle.getStandardOpptyRTs();
    }
    
    //Cover before update methods and other methods to increase the coverage
    @isTest
    public static void createMonthlyCallCycleTest() {
        List<Planned_Leave__c> plannedLeaves = new List<Planned_Leave__c>();
        Set<Date> plannedLeavesSet = new Set<Date>();
        List<Date> businessDates = new List<Date>();
        List<Account> updateAccountList = new List<Account>();
        List<Account> updateAccountList1 = new List<Account>();
        
        Test.startTest();        
        
        List<User> users = [Select Id from User Limit 1];
        
        plannedLeaves.add(new Planned_Leave__c(OwnerId = users[0].Id, Status__c = 'Approved', End_Date__c = system.today()+2, Start_Date__c = system.today()));  
        insert plannedLeaves;
        for(Planned_Leave__c p : plannedLeaves){
            plannedLeavesSet.add(p.End_Date__c);
            plannedLeavesSet.add(p.Start_Date__c);
        }
        
        List<Store_Member__c> storeMembers = [Select Id,Team_Member__c,Call_Volume__c
                                              ,Team_Member__r.Country__c,Store__r.Engagement_Model__c
                                              ,Store__r.Location_Type__c,Store__r.Country__c from Store_Member__c Limit 1];
        storeMembers[0].Team_Member__c = users[0].Id;
        storeMembers[0].Team_Member_Call__c = '70%';
        storeMembers[0].Call_Volume__c = 40;
        Update storeMembers;
        
        RecordType AUCustomerRecType = [SELECT Id FROM RecordType WHERE SObjectType = 'Account' AND DeveloperName = 'AU_Customer' LIMIT 1];
        
        List<Account> accounts = TestDataFactory.createAccounts(5);
        for(Account a :accounts) {
            a.OwnerId =storeMembers[0].Team_Member__c;
            a.R12_Sales_Rank__c = Math.floor(Math.random()*1000);
            a.Call_Cycle_Ranking__c = Math.floor(Math.random()*10000);
            a.Call_Reason__c = 'Call Reason ' + String.valueOf(Math.random());
            a.Do_Not_Call__c = false;
            a.Call_Priority__c = 3;
            a.RecordTypeId = AUCustomerRecType.Id;
            a.Account_Status__c = 'Active';
            updateAccountList.add(a);
        }
        insert updateAccountList;
        
        businessDates.add(System.today());businessDates.add(System.today()+1);businessDates.add(System.today()+2);businessDates.add(System.today()+3);
        
        TEMP_SM_CallCycle.createMonthlyCallCycle(storeMembers[0]);
        TEMP_SM_CallCycle.createCallCycleTasks(updateAccountList, businessDates, DM_EngagementModel.MODEL_CUSTOMER_ENGAGEMENT);
        
        List<Account> accounts1 = TestDataFactory.createAccounts(2);
        for(Account a :accounts1) {
            a.OwnerId =storeMembers[0].Team_Member__c;
            a.R12_Sales_Rank__c = Math.floor(Math.random()*1000);
            a.Call_Cycle_Ranking__c = Math.floor(Math.random()*10000);
            a.Call_Reason__c = 'Call Reason ' + String.valueOf(Math.random());
            a.Do_Not_Call__c = false;
            a.Call_Priority__c = 3;
            a.RecordTypeId = AUCustomerRecType.Id;
            a.Account_Status__c = 'Active';
            updateAccountList1.add(a);
        }
        insert updateAccountList1;
        TEMP_SM_CallCycle.createCallCycleTasks(updateAccountList1, businessDates, DM_EngagementModel.MODEL_CUSTOMER_ENGAGEMENT);
        TEMP_SM_CallCycle.nextBusinessDate(System.today());
        
        Task task = new Task(
            Subject = 'Engagement Call',
            WhatId = updateAccountList1[0].Id,
            OwnerId = updateAccountList1[0].Id,
            Status = 'Active',
            ActivityDate = System.today(),
            Sub_type__c = 'Engagement Call',
            RecordTypeId = Schema.SObjectType.Task.getRecordTypeInfosByName().get('Call Cycle Call').getRecordTypeId()
        );
        try{
            insert task;
        }
        catch(Exception e){System.debug(e);}
        
        //TEMP_SM_CallCycle.callCycleFormInit(updateAccountList1[0].Id, 'Else', 'flowScreen');
        Event event = new Event(
            Subject = 'Call',
            StartDateTime = Datetime.now(),
            EndDateTime = Datetime.now().addMinutes(30),
            Sub_type__c = 'Engagement Call',
            Status__c = 'Open',
            WhatId = updateAccountList1[0].Id
        );
        insert event;
        //TEMP_SM_CallCycle.callCycleFormInit(updateAccountList1[0].Id, 'Else', 'flowScreen');
        Set<Account> accSet = new Set<Account>(); 
        accSet.addAll(updateAccountList1);
        //TEMP_SM_CallCycle.createCallCycleTasksForCreditLimitIncrease(accSet);

        Set<Date> plSet = new Set<Date>();
        plSet.add(Date.newInstance(2022, 2, 28));
        //TEMP_SM_CallCycle.createCallCycleTasks(TestDataFactory.createAccounts(15), businessDates, DM_EngagementModel.MODEL_CUSTOMER_ENGAGEMENT);
        Test.stopTest();
    }
}