unpackaged/main/default/objects/Account/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <externalId>true</externalId>
    <label>Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <description>Status of the Account</description>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Referred</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Call_Cycle_Ranking__c.field-meta.xml
<CustomField>
    <fullName>Call_Cycle_Ranking__c</fullName>
    <label>Call Cycle Ranking</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Call_Priority__c.field-meta.xml
<CustomField>
    <fullName>Call_Priority__c</fullName>
    <description>Call Priority for call cycle algorithm</description>
    <label>Call Priority</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Call_Reason__c.field-meta.xml
<CustomField>
    <fullName>Call_Reason__c</fullName>
    <description>Call reason call cycle algorithm</description>
    <label>Call Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Do_Not_Call__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Call__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This flag indicates users who should not be called e.g. for call cycles</description>
    <label>Do Not Call</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Home_Store__c.field-meta.xml
<CustomField>
    <fullName>Home_Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Home Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Onboarding_Status__c.field-meta.xml
<CustomField>
    <fullName>Onboarding_Status__c</fullName>
    <label>Onboarding Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Onboarding Task Created</fullName>
            </value>
            <value>
                <fullName>Onboarding Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Power_Pass_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Power_Pass_Account_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Power Pass Account Number</label>
    <length>32</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/PowerPass_Account_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>PowerPass_Account_Created_Date__c</fullName>
    <description>This field is populated when a PowerPass account is created</description>
    <label>PowerPass Account Created Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account_Extension__c/Account_Extension__c.object-meta.xml
<CustomObject>
    <label>Account Extension</label>
    <nameField>
        <displayFormat>AE-{0000}</displayFormat>
        <label>Account Extension Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Extensions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Account_Extension__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Power Pass Account Number</description>
    <externalId>true</externalId>
    <inlineHelpText>Power Pass Account Number</inlineHelpText>
    <label>Account Number</label>
    <length>32</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/classes/SM_AssociateAccountExtensionBatch.cls
/*******************************************************************************************************
* Class Name      	: SM_AssociateAccountExtensionBatch
* Description		: Batch class to associate Account Extension Record to Account record per PowerPass Number
* Author          	: Bunnings Salesforce Team
* Created On      	: 25/05/2022
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Bunnings SFDC Team 	25/05/2022		1000				Initial version for SFSUP-725
******************************************************************************************************/
public class SM_AssociateAccountExtensionBatch implements Database.Batchable<sObject>, Schedulable{
	
    String accountQuery;
	
	public SM_AssociateAccountExtensionBatch(){
        accountQuery = 'Select Id,Account_Extension__c, Account_Status__c,Home_Store__c,Country__c,Power_Pass_Account_Number__c,Do_Not_Call__c,';
        accountQuery += 'Onboarding_Status__c,ParentId,OwnerId,';
        accountQuery += 'Call_Cycle_Ranking__c,Call_Priority__c,Call_Reason__c,PowerPass_Account_Created_Date__c From Account ';
        accountQuery += 'Where Account_Status__c != \'' + 'Inactive' +'\' ';
        accountQuery += 'AND Account_Status__c != \'' + 'Terminated' +'\' ';
        accountQuery += 'AND RecordType.Name != \'' + 'Person Account' +'\' ';
        accountQuery += 'AND Country__c != null AND Power_Pass_Account_Number__c != null AND Account_Extension__c = null';
	}
    
    public Database.QueryLocator start(Database.BatchableContext BC) {                     
        System.debug('accountQuery>> '+accountQuery);
        return Database.getQueryLocator(accountQuery);
    }

    public void execute(Database.BatchableContext BC, List<Account> accList) {
        
        if(accList.isEmpty()){
            return;
        }
        
        Set<String> accIdSet = New Set<String>(); 
        List<Account_Extension__c> accntExtList = New List<Account_Extension__c>();
        List<Account> accntToUpdateList = New List<Account>();
        Map<String, Id> accntExtMap = New Map<String, Id>();
        
        for(Account accnt : accList){
            accIdSet.add(accnt.Power_Pass_Account_Number__c);
        }
        
        accntExtList = [SELECT Id, Account_Number__c FROM Account_Extension__c WHERE Account_Number__c IN:accIdSet];
        
        if(accntExtList.isEmpty()){
            return;
        }
        
        for(Account_Extension__c accExtRecord : accntExtList){
            accntExtMap.put(accExtRecord.Account_Number__c, accExtRecord.Id); 
        }
        
        for(Account accnt : accList){
            if(accntExtMap.containsKey (accnt.Power_Pass_Account_Number__c) ){
                accnt.Account_Extension__c = accntExtMap.get(accnt.Power_Pass_Account_Number__c);
                accntToUpdateList.add(accnt);
            }
        }
        
        if(accntToUpdateList.size() != 0){
            /*try{
            	update accntToUpdateList;                
            } catch(Exception e) {
            	ApplicationLogger.log('SM_AssociateAccountExtensionBatch', 'Account', 'Batch', e);
        	}*/
            List<Database.SaveResult> results = Database.update(accntToUpdateList, false);
            for (Database.SaveResult result : results) {
              if (!result.isSuccess()){
                for (Database.Error err : result.getErrors()){
                  System.debug('Error: '+ result.getId() + ' ' + err.getStatusCode() + ' ' + err.getMessage()); 
                }
              }
            }
        } 
    }

    public void finish(Database.BatchableContext BC) {
		AsyncApexJob asyncJob = [SELECT 
									Id, 
									Status, 
									NumberOfErrors, 
									JobItemsProcessed,
									TotalJobItems, CreatedBy.Email
								FROM AsyncApexJob WHERE Id =:BC.getJobId()];
						
	    // Send an email to the Apex job's submitter notifying of job completion.
	    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
	    String[] toAddresses = new String[] {asyncJob.CreatedBy.Email};
	    mail.setToAddresses(toAddresses);
	    mail.setSubject('SM_AssociateAccountExtensionBatch ' + asyncJob.Status);
	    mail.setPlainTextBody
	    ('The batch Apex job processed ' + asyncJob.TotalJobItems +
	    ' batches with '+ asyncJob.NumberOfErrors + ' failures.');
	    Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    }
    
    public void execute(SchedulableContext SC) {
        Database.executeBatch(new SM_AssociateAccountExtensionBatch(), 10);
    }    
}