unpackaged/main/default/objects/Account/fields/Assigned_Store__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Assigned Store of a trade Specialist User</description>
    <label>Assigned Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Accounts (Assigned Store)</relationshipLabel>
    <relationshipName>Accounts3</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>Represents all frame and truss plants, small format stores, trade distribution centres and warehouses.</description>
    <label>Store</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Store__c/fields/Engagement_Model__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Model__c</fullName>
    <description>Determines the method used for assigning Powerpass Account Ownership. 
Old Model - the Stores Default Trade Specialist will become the owner. 
New - Ownership is determined by Assignment Rule Metadata records</description>
    <label>Engagement Model</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Old</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Store__c/fields/Location_Type__c.field-meta.xml
<CustomField>
    <fullName>Location_Type__c</fullName>
    <description>Unrestricted list of location types</description>
    <label>Location Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Area</fullName>
            </value>
            <value>
                <fullName>Department</fullName>
            </value>
            <value>
                <fullName>Distribution Centre</fullName>
            </value>
            <value>
                <fullName>Frame and Truss Plant</fullName>
            </value>
            <value>
                <fullName>Function</fullName>
            </value>
            <value>
                <fullName>Logical</fullName>
            </value>
            <value>
                <fullName>Region</fullName>
            </value>
            <value>
                <fullName>Section</fullName>
            </value>
            <value>
                <fullName>Small Format Store</fullName>
            </value>
            <value>
                <fullName>Trade Distribution Centre</fullName>
            </value>
            <value>
                <fullName>Warehouse</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Store_Member__c/Store_Member__c.object-meta.xml
<CustomObject>
    <description>Junction between user (team members) and store.</description>
    <label>Store Member</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>Store Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Store_Member__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipName>User_Stores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/TEMP_SM_AssignedStoreBatch_Test.cls
@isTest
private class TEMP_SM_AssignedStoreBatch_Test {
    
    @testSetup static void setup() {
        
        // create user
        Profile p = [SELECT Id FROM Profile WHERE Name = :Constants.AU_TRADE_SPECIALIST_PROFILEENAME LIMIT 1];
        List<User> users = TestDataFactory.createUsers(1, p.Id);
        insert users;
        
        System.runAs(new User(Id = UserInfo.getUserId())) {
            // create store
            List<Store__c> stores = TestDataFactory.createStores(2);
            stores[0].Name = 'Test Store';
            stores[0].Engagement_Model__c = 'New';
            stores[0].Location_Type__c = 'Warehouse';
            stores[1].Name = 'Test Store';
            stores[1].Engagement_Model__c = 'New';
            stores[1].Location_Type__c = 'Warehouse';
            insert stores;
            
            // create store member
            Store_Member__c member = new Store_Member__c();
            member = TestDataFactory.createStoreMember(stores[0].Id, users[0].Id, Constants.AU_TRADE_SPECIALIST_PROFILEENAME);
            insert member;
            
            //create account
            List<Account> accounts = TestDataFactory.createAccounts(2);
            for (Account acct : accounts){
                acct.OwnerId = users[0].Id;
                acct.Assigned_Store__c = stores[0].Id;
            }
            insert accounts;
        }
    }
    
    @isTest
    static void testAssignedStore() {
        Test.startTest();
        
        Database.executeBatch(new TEMP_SM_AssignedStoreBatch());
        
        Test.stopTest();
    }
    
}