unpackaged/main/default/objects/Account/fields/Assigned_Store__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Assigned Store of a trade Specialist User</description>
    <label>Assigned Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Accounts (Assigned Store)</relationshipLabel>
    <relationshipName>Accounts3</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Assigned_Store__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A lookup to the related Store.</description>
    <label>Assigned Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Contact_Number__c.field-meta.xml
<CustomField>
    <fullName>Contact_Number__c</fullName>
    <description>This pulls in the Mobile number of the Delivery Contact</description>
    <formula>ShipToContact.MobilePhone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/COS_ID__c.field-meta.xml
<CustomField>
    <fullName>COS_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>COS ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Assigned_Store__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Store the Quote is assigned to in COS</description>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Assigned Quotes</relationshipLabel>
    <relationshipName>Assigned_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/COS_ID__c.field-meta.xml
<CustomField>
    <fullName>COS_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>COS ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Staging_Object__c/Staging_Object__c.object-meta.xml
<CustomObject>
    <description>Staging object for migrating records by object name</description>
    <label>Staging Object</label>
    <nameField>
        <displayFormat>SO-{00000000}</displayFormat>
        <label>Staging Object Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staging Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Staging_Object__c/fields/AccountID__c.field-meta.xml
<CustomField>
    <fullName>AccountID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AccountID</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Staging Objects</relationshipLabel>
    <relationshipName>Staging_Objects</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Staging_Object__c/fields/Assigned_Store__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Staging Objects</relationshipLabel>
    <relationshipName>Staging_Objects</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Staging_Object__c/fields/COS_ID__c.field-meta.xml
<CustomField>
    <fullName>COS_ID__c</fullName>
    <externalId>true</externalId>
    <label>COS ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Staging_Object__c/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <label>Received Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Staging_Object__c/fields/Log_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Log_Object_Name__c</fullName>
    <label>Log Object Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Staging_Object__c/fields/Log_Type__c.field-meta.xml
<CustomField>
    <fullName>Log_Type__c</fullName>
    <label>Log Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Outbound message</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Staging_Object__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Payment_Required</fullName>
                <label>Payment Required</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Staging_Object__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>QuoteId</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Staging Objects</relationshipLabel>
    <relationshipName>Staging_Objects</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Staging_Object__c/fields/Source_Type__c.field-meta.xml
<CustomField>
    <fullName>Source_Type__c</fullName>
    <label>Source Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Staging_Object__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>With Error</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>Represents all frame and truss plants, small format stores, trade distribution centres and warehouses.</description>
    <label>Store</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/classes/TEMP_SM_OrderBatch_Test.cls
/*******************************************************************************************************
* Class Name      	: TEMP_SM_OrderBatch_Test
* Description		: Test class for TEMP_SM_OrderBatch
* Author          	: Simplus MS
* Created On      	: 11/10/2021
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer			  		Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Simplus MS                11/10/2021		1000				Initial version
******************************************************************************************************/
@isTest
private with sharing class TEMP_SM_OrderBatch_Test {
    @TestSetup
    static void makeData(){
        //Create Account
        List<Account> accts = TestDataFactory.createAccounts(1);
        insert accts;

        //Create Oppty
        List<Opportunity> opps = TestDataFactory.createOpenOpportunities(accts[0].Id, UserInfo.getUserId(), 1);
        insert opps;

        //Create Quote
        List<Quote> qtes = TestDataFactory.createQuotes(opps[0].Id, 'Submitted', 1);
        insert qtes;

        //Create Store
        List<Store__c> stres = TestDataFactory.createStores(1);
        insert stres;

        //Create Orders
        List<Order> orders = new List<Order> {
            new Order(AccountId=accts[0].Id, COS_ID__c='1', QuoteId=qtes[0].Id, Assigned_Store__c=stres[0].Id, Status='Submitted', EffectiveDate=Date.today()),
            new Order(AccountId=accts[0].Id, COS_ID__c='2', QuoteId=qtes[0].Id, Assigned_Store__c=stres[0].Id, Status='Submitted', EffectiveDate=Date.today())
        };
        insert orders;

        //Create Staging Orders
        List<Staging_Object__c> stOrders = new List<Staging_Object__c>();

        //Staging orders with matching COS ID to test UPDATE operation
        for(Integer i=1;i<3;i++) {
            Staging_Object__c so = new Staging_Object__c();
            so.Object_Name__c = 'Order';
            so.Status__c = 'Open';
            so.AccountID__c = accts[0].Id;
            so.QuoteId__c = qtes[0].Id;
            so.Assigned_Store__c = stres[0].Id;
            so.COS_ID__c = String.valueOf(i);
            so.Effective_Date__c = Date.today();
            so.Order_Status__c = 'Submitted';
            so.Comments__c = 'Sample comment';
            so.Contact_Number__c = '8877669944';

            stOrders.add(so);
        }
        
        //Staging orders without matching COS ID to test INSERT operation                                
        for(Integer i=3;i<5;i++) {
            Staging_Object__c so = new Staging_Object__c();
            so.Object_Name__c = 'Order';
            so.Status__c = 'Open';
            so.AccountID__c = accts[0].Id;
            so.QuoteId__c = qtes[0].Id;
            so.Assigned_Store__c = stres[0].Id;
            so.COS_ID__c = String.valueOf(i);
            so.Effective_Date__c = Date.today();
            so.Order_Status__c = 'Submitted';
            so.Contact_Number__c = '9988776655';

            stOrders.add(so);
        }

        //Staging order with missing fields to test ERROR operation
        stOrders.add(new Staging_Object__c(Object_Name__c = 'Order',
                                           Status__c = 'Open',
                                           AccountID__c = accts[0].Id,
                                           COS_ID__c = '5'));
        
        //Staging order from failed to successful operation
        stOrders.add(new Staging_Object__c(Object_Name__c = 'Order',
                                           Status__c = 'With Error',
                                           AccountID__c = accts[0].Id,
                                           COS_ID__c = '6',
                                           Order_Status__c = 'Submitted',
                                           Effective_Date__c = Date.today(),
                    					   Error_Message__c = 'Sample Error Message',
                                           Log_Type__c = 'Exception',
                                           Source_Type__c = 'Batch',
                                           Log_Object_Name__c = 'Order'));
        
        insert stOrders;
    }
    @isTest static void testSyncOrders() {
        Test.startTest();
            Database.executeBatch(new TEMP_SM_OrderBatch());
        Test.stopTest();
        
        Set<String> completedCOSIds = new Set<String>();
        Set<String> withErrorCOSIds = new Set<String>();
        List<Staging_Object__c> scope = [SELECT COS_ID__c, Status__c FROM Staging_Object__c WHERE Object_Name__c = 'Order' AND COS_ID__c != null];
        
        for(Staging_Object__c so : scope) {
            if(so.Status__c == 'Completed') {
                completedCOSIds.add(so.COS_ID__c);
            } else {
                withErrorCOSIds.add(so.COS_ID__c);
            }
        }
  
        Integer ordersProcessed = [SELECT COS_ID__c FROM Order WHERE COS_ID__c IN :completedCOSIds].size();
        Integer ordersFailed = scope.size() - ordersProcessed;
        
        //Asserts number of processed staging records and actual number of order records
        System.assertEquals(completedCOSIds.size(), ordersProcessed, 'Order records processed does not match number of completed staging records');
        System.assertEquals(withErrorCOSIds.size(), ordersFailed, 'Failed Order records does not match number of staging records with error');
    }   
}