unpackaged/main/default/objects/Account/fields/Assigned_Store__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Assigned Store of a trade Specialist User</description>
    <label>Assigned Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Accounts (Assigned Store)</relationshipLabel>
    <relationshipName>Accounts3</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/COS_Number__c.field-meta.xml
<CustomField>
    <fullName>COS_Number__c</fullName>
    <formula>SyncedQuote.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>COS Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/COS_Opportunity_ID__c.field-meta.xml
<CustomField>
    <fullName>COS_Opportunity_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>External ID for COS Opportunities</description>
    <externalId>true</externalId>
    <label>COS_Opportunity_ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Assigned_Store__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Store the Quote is assigned to in COS</description>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Assigned Quotes</relationshipLabel>
    <relationshipName>Assigned_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/COS_Date__c.field-meta.xml
<CustomField>
    <fullName>COS_Date__c</fullName>
    <label>COS Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/COS_ID__c.field-meta.xml
<CustomField>
    <fullName>COS_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>COS ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Quote/fields/COS_Token__c.field-meta.xml
<CustomField>
    <fullName>COS_Token__c</fullName>
    <description>to be used in relation to CCRM-6892/6890</description>
    <label>COS Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of Quote</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Enquiry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Staging_Object__c/Staging_Object__c.object-meta.xml
<CustomObject>
    <description>Staging object for migrating records by object name</description>
    <label>Staging Object</label>
    <nameField>
        <displayFormat>SO-{00000000}</displayFormat>
        <label>Staging Object Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staging Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Staging_Object__c/fields/Assigned_Store__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Staging Objects</relationshipLabel>
    <relationshipName>Staging_Objects</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Staging_Object__c/fields/COS_Date__c.field-meta.xml
<CustomField>
    <fullName>COS_Date__c</fullName>
    <label>COS Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Staging_Object__c/fields/COS_ID__c.field-meta.xml
<CustomField>
    <fullName>COS_ID__c</fullName>
    <externalId>true</externalId>
    <label>COS ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Staging_Object__c/fields/COS_Number__c.field-meta.xml
<CustomField>
    <fullName>COS_Number__c</fullName>
    <label>COS Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Staging_Object__c/fields/COS_Opportunity_ID__c.field-meta.xml
<CustomField>
    <fullName>COS_Opportunity_ID__c</fullName>
    <externalId>true</externalId>
    <label>COS Opportunity ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Staging_Object__c/fields/COS_Token__c.field-meta.xml
<CustomField>
    <fullName>COS_Token__c</fullName>
    <label>COS Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Staging_Object__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Staging_Object__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OpportunityId</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Staging Objects</relationshipLabel>
    <relationshipName>Staging_Objects</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Staging_Object__c/fields/Quote_Status__c.field-meta.xml
<CustomField>
    <fullName>Quote_Status__c</fullName>
    <label>Quote Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enquiry</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pricing_Only_Quote</fullName>
                <label>Pricing Only Quote</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Staging_Object__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>With Error</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Staging_Object__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Enquiry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>Represents all frame and truss plants, small format stores, trade distribution centres and warehouses.</description>
    <label>Store</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/classes/TEMP_SM_QuoteBatch_Test.cls
/*******************************************************************************************************
* Class Name        : TEMP_SM_QuoteBatch_Test
* Description       : Test class for TEMP_SM_QuoteBatch
* Author            : Simplus MS
* Created On        : 11/10/2021
* Modification Log  :
* -----------------------------------------------------------------------------------------------------
* Developer            Date             Modification ID     Description
* -----------------------------------------------------------------------------------------------------
* Simplus MS           11/10/2021       1000                Initial version
******************************************************************************************************/
@isTest
private with sharing class TEMP_SM_QuoteBatch_Test {
    
    @testSetup
    static void setup(){
        
        //Create Account
        List<Account> accts = TestDataFactory.createAccounts(1);
        insert accts;
        
        //Create Oppty
        List<Opportunity> opps = TestDataFactory.createOpenOpportunities(accts[0].Id, UserInfo.getUserId(), 3);
        insert opps;
        
        //Create Store
        List<Store__c> stores = TestDataFactory.createStores(1);
        insert stores;
        
        //Create Quotes
        List<Quote> quotes = new List<Quote> {
            new Quote(OpportunityId = opps[0].Id, COS_ID__c='1', RecordTypeId = CSUtils.getRecordTypeId('Quote', 'COS Quote'), 
                      Name = '3553', Assigned_Store__c=stores[0].Id, Status='Submitted', ExpirationDate=Date.today()),
                      new Quote(OpportunityId = opps[1].Id, COS_ID__c='26', RecordTypeId = CSUtils.getRecordTypeId('Quote', 'COS Quote'), 
                                Name = '2244', Assigned_Store__c=stores[0].Id, Status='Cancelled', ExpirationDate=Date.today())
                };
        insert quotes;
        
        //Update Opp to populate COS_Opportunity_ID__c
        String COS_OPP_ID_PREFIX = Label.BN_OPP_ID_Prefix;
        List<Opportunity> oppList = [SELECT Id, COS_Opportunity_ID__c FROM Opportunity LIMIT 10];
        for(Integer i = 1; i < quotes.size(); i++){
            oppList[i].COS_Opportunity_ID__c = COS_OPP_ID_PREFIX + quotes[i].COS_ID__c;
        }
        
        update oppList;

        //Create Staging Quotes
        List<Staging_Object__c> stgQuotes = new List<Staging_Object__c>();
        
        //Staging Quotes with matching COS ID to test UPDATE operation
        for(Integer i=0;i<3;i++) {
            Staging_Object__c stgObj = new Staging_Object__c();
            stgObj.Object_Name__c = 'Quote';
            stgObj.Status__c = 'Open';
            //stgObj.OpportunityId__c = opps[3].Id;
            stgObj.Type__c = 'Quote';
            stgObj.Country__c = 'Australia';
            stgObj.Assigned_Store__c = stores[0].Id;
            stgObj.COS_ID__c = String.valueOf(i);
            stgObj.COS_Number__c = String.valueOf(i) + 20;
            stgObj.COS_Date__c = Date.today()+3;
            stgObj.Quote_Status__c = 'Submitted';
            stgObj.Comments__c = 'Sample comment';
            stgObj.Record_Type__c = CSUtils.getRecordTypeId('Quote', 'COS Quote');
            stgObj.Expiration_Date__c = Date.today()+5;
            stgObj.COS_Token__c = '645774'+i;
            stgObj.Error_Message__c = 'Sample Error Message';
            
            stgQuotes.add(stgObj);
        }

        //Staging Quote with missing fields to test ERROR operation
        stgQuotes.add(new Staging_Object__c(Object_Name__c = 'Quote',
                                           Status__c = 'Open',
                                           Assigned_Store__c = stores[0].Id,
                                           COS_ID__c = '2',
                                           OpportunityId__c = opps[2].Id));
        
        insert stgQuotes;
    }
    
    @isTest static void testSyncQuotes() {
        
        Test.startTest();
        Database.executeBatch(new TEMP_SM_QuoteBatch());
        Test.stopTest();
        
        Set<String> completedCOSIds = new Set<String>();
        Set<String> withErrorCOSIds = new Set<String>();
        List<Staging_Object__c> scope = [SELECT COS_ID__c, Status__c FROM Staging_Object__c WHERE Object_Name__c = 'Quote' AND COS_ID__c != null];
        
        for(Staging_Object__c so : scope) {
            if(so.Status__c == 'Completed') {
                completedCOSIds.add(so.COS_ID__c);
            } else {
                withErrorCOSIds.add(so.COS_ID__c);
            }
        }
        
        Integer quotesProcessed = [SELECT COS_ID__c FROM Quote WHERE COS_ID__c IN :completedCOSIds].size();
        Integer quotesFailed = scope.size() - quotesProcessed;
        
        //Asserts number of processed staging records and actual number of Quote records
        System.assertEquals(completedCOSIds.size(), quotesProcessed, 'Quote records processed does not match number of completed staging records');
        System.assertEquals(withErrorCOSIds.size(), quotesFailed -1, 'Failed Quote records does not match number of staging records with error');
    }
    
    @isTest static void testFailedOppInsert(){
        List<Staging_Object__c> stQuotes = [SELECT COS_ID__c, Status__c,Expiration_Date__c FROM Staging_Object__c WHERE Object_Name__c = 'Quote' AND COS_ID__c != null];
        
        for(Staging_Object__c stQuote : stQuotes){
            stQuote.Expiration_Date__c = null;
        }
        
        update stQuotes;
        
        Test.startTest();
        Database.executeBatch(new TEMP_SM_QuoteBatch());
        Test.stopTest();
        
        Set<String> completedCOSIds = new Set<String>();
        Set<String> withErrorCOSIds = new Set<String>();
        List<Staging_Object__c> scope = [SELECT COS_ID__c, Status__c FROM Staging_Object__c WHERE Object_Name__c = 'Quote' AND COS_ID__c != null];
        
        for(Staging_Object__c so : scope) {
            if(so.Status__c == 'Completed') {
                completedCOSIds.add(so.COS_ID__c);
            } else {
                withErrorCOSIds.add(so.COS_ID__c);
            }
        }
        
        Integer quotesProcessed = [SELECT COS_ID__c FROM Quote WHERE COS_ID__c IN :completedCOSIds].size();
        Integer quotesFailed = scope.size() - quotesProcessed;
        
        //Asserts number of processed staging records and actual number of Quote records
        System.assertEquals(completedCOSIds.size(), quotesProcessed, 'Quote records processed does not match number of completed staging records');
        System.assertEquals(withErrorCOSIds.size(), quotesFailed-1, 'Failed Quote records does not match number of staging records with error');
    }
    
    @isTest static void testRunBatchWithParams(){
        Test.startTest();
       	Database.executeBatch(new TEMP_SM_QuoteBatch('Test Batch 1'));
        Test.stopTest();
        
        Set<String> completedCOSIds = new Set<String>();
        Set<String> withErrorCOSIds = new Set<String>();
        List<Staging_Object__c> scope = [SELECT COS_ID__c, Status__c FROM Staging_Object__c WHERE Object_Name__c = 'Quote' AND COS_ID__c != null];
        
        for(Staging_Object__c so : scope) {
            if(so.Status__c == 'Completed') {
                completedCOSIds.add(so.COS_ID__c);
            } else {
                withErrorCOSIds.add(so.COS_ID__c);
            }
        }
        
        Integer quotesProcessed = [SELECT COS_ID__c FROM Quote WHERE COS_ID__c IN :completedCOSIds].size();
        Integer quotesFailed = scope.size() - quotesProcessed;
        
        //Asserts number of processed staging records and actual number of Quote records
        System.assertEquals(completedCOSIds.size(), quotesProcessed, 'Quote records processed does not match number of completed staging records');
        System.assertEquals(withErrorCOSIds.size(), quotesFailed-1, 'Failed Quote records does not match number of staging records with error');
    }
    
}