unpackaged/main/default/objects/Account/fields/Batch_Update__c.field-meta.xml
<CustomField>
    <fullName>Batch_Update__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Update of legacy data</description>
    <label>Batch Update</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Contract_Group__c.field-meta.xml
<CustomField>
    <fullName>Contract_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent Account for the contract group</description>
    <label>Contract Group</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contract Group Associations</relationshipLabel>
    <relationshipName>Contract_Group_Association</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Various contracts associated to customers, projects and umbrellas. Use of custom object in place of standard considering future implementation of CPQ with contract and its line items.</description>
    <label>Contract</label>
    <nameField>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Contract__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Date when the contract started</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the contract</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contract_Group__c/Contract_Group__c.object-meta.xml
<CustomObject>
    <description>A logical contract grouping that defines customer accounts it is applied to.</description>
    <label>Contract Group</label>
    <nameField>
        <label>Contract Group</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Group</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Contract__c/Customer_Contract__c.object-meta.xml
<CustomObject>
    <label>Customer Contract</label>
    <nameField>
        <displayFormat>CC-{00000000}</displayFormat>
        <label>Customer Contract</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Contract__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <description>Contract for customer contract</description>
    <inlineHelpText>Contract for customer contract</inlineHelpText>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Customer Contracts</relationshipLabel>
    <relationshipName>Customer_Contracts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Customer_Price_List__c/Customer_Price_List__c.object-meta.xml
<CustomObject>
    <description>Junction between Price List and Customers</description>
    <label>Customer Price List</label>
    <nameField>
        <displayFormat>CPL-{0000000000}</displayFormat>
        <label>Customer Price List Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Price Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Price_List__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>The customer</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Price Lists</relationshipLabel>
    <relationshipName>Customer_Price_Lists</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Customer_Price_List__c/fields/Customer_Price_List_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_Price_List_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Definition Id of the price list assoicated to a customer</description>
    <externalId>true</externalId>
    <label>Customer Price List ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Customer_Price_List__c/fields/Price_List__c.field-meta.xml
<CustomField>
    <fullName>Price_List__c</fullName>
    <description>The price list</description>
    <label>Price List</label>
    <referenceTo>Price_List__c</referenceTo>
    <relationshipLabel>Customer Price Lists</relationshipLabel>
    <relationshipName>Customer_Price_Lists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Customer_Price_List__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Customer Price Lists Start Date</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Customer_Price_List__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This field determines whether a Price List is active (checked) or In active (unchecked) for the related Customer.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Price_List__c/Price_List__c.object-meta.xml
<CustomObject>
    <description>This Object represents the header level of an externally mastered pricing table, which applies item level discounts for a pre-defined list of products within specific Cost Zones.</description>
    <label>Price List</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Price List Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Price_List__c/fields/Price_List_Definition__c.field-meta.xml
<CustomField>
    <fullName>Price_List_Definition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Price List Definition</description>
    <label>Price List Definition</label>
    <referenceTo>Price_List_Definition__c</referenceTo>
    <relationshipLabel>Price Lists</relationshipLabel>
    <relationshipName>Price_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Price_List__c/fields/Price_List_Header_ID__c.field-meta.xml
<CustomField>
    <fullName>Price_List_Header_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>External ID Reference for Price List</description>
    <externalId>true</externalId>
    <label>Price List Header ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Price_List__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Date when Price List would start</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Price_List__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Price List</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Price_List_Definition__c/Price_List_Definition__c.object-meta.xml
<CustomObject>
    <label>Price List Definition</label>
    <nameField>
        <displayFormat>PLD-{000000}</displayFormat>
        <label>Price List Definition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price List Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/TEMP_SM_ContractGroupBatch_Test.cls
/*******************************************************************************************************
* Class Name      	: TEMP_SM_ContractGroupBatch_Test
* Description		: Temporary batch class to Update legacy accounts for CCRM15-103
* Author          	: Simplus MS
* Created On      	: 27/08/2021
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer			  		Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Simplus.MS                27/08/2021		1000				Initial version
******************************************************************************************************/
@isTest
public with sharing class TEMP_SM_ContractGroupBatch_Test {
   
    @testSetup static void setup() {

        List<Contract__c> contracts = TestDataFactory.createContracts(2);
        contracts[0].RecordTypeId = CSUtils.getRecordTypeId('Contract__c', 'AU Contract');
        contracts[1].RecordTypeId = CSUtils.getRecordTypeId('Contract__c', 'AU Contract');
        insert contracts;

        List<Account> parentAccountsList = TestDataFactory.createAccounts(5);
        insert parentAccountsList;

        Price_List_Definition__c pld = new Price_List_Definition__c();
        insert pld;

        Price_List__c pb1 = new Price_List__c(Status__c = 'Active', Price_List_Definition__c = pld.Id, Price_List_Header_ID__c = String.valueOf(Math.random()));
        insert pb1;
        Price_List__c pb2 = new Price_List__c(Status__c = 'Active', Price_List_Definition__c = pld.Id, Price_List_Header_ID__c = String.valueOf(Math.random()));
        insert pb2;
        Customer_Price_List__c cpl1 = new Customer_Price_List__c(Price_List__c = pb1.Id, Account__c = parentAccountsList[0].Id,
                                                               Status__c = 'Active', Customer_Price_List_ID__c = '45426');
        insert cpl1;
        Customer_Price_List__c cpl2 = new Customer_Price_List__c(Price_List__c = pb2.Id, Account__c = parentAccountsList[0].Id,
                                                               Status__c = 'Active', Customer_Price_List_ID__c = '77655');
        insert cpl2;

        Customer_Price_List__c cplFuture = new Customer_Price_List__c(Price_List__c = pb1.Id, Account__c = parentAccountsList[0].Id, Start_Date__c = System.today().addDays(1),
                                                               Status__c = 'Inactive', Customer_Price_List_ID__c = '45456');
        insert cplFuture;

        List<Id> accountIdsList = new List<Id>();
        for(Account acc:parentAccountsList){
            accountIdsList.add(acc.Id);
        }
        List<Customer_Contract__c> accCustomerContractsList = TestDataFactory.createAccCustomerContracts(accountIdsList, new List<Id>{contracts[0].Id});
        insert accCustomerContractsList;

        List<Account> childAccounts = TestDataFactory.createAccounts(2);
        Integer i = 0;
        
        for(Account acc:childAccounts){
            acc.Contract_Group__c = parentAccountsList[i].Id;
            acc.Batch_Update__c = True;
            i++;
        }
        insert childAccounts;

        List<Account> childAccounts1 = TestDataFactory.createAccounts(2);
        Integer j = 0;
        
        for(Account acc:childAccounts1){
            acc.Contract_Group__c = parentAccountsList[j].Id;
            acc.Batch_Update__c = True;
            j++;
        }
        insert childAccounts1;

        Price_List__c pbChild = new Price_List__c(Status__c = 'Active', Price_List_Definition__c = pld.Id, Price_List_Header_ID__c = String.valueOf(Math.random()));
        insert pbChild;
        Customer_Price_List__c cplChild = new Customer_Price_List__c(Price_List__c = pbChild.Id, Account__c = childAccounts[0].Id,
                                                               Status__c = 'Active', Customer_Price_List_ID__c = '87654');
        insert cplChild;

        List<Id> childAccountIdsList = new List<Id>();
        for(Account acc:childAccounts){
            childAccountIdsList.add(acc.Id);
        }
        List<Customer_Contract__c> accCustomerContractsChildList = TestDataFactory.createAccCustomerContracts(childAccountIdsList, new List<Id>{contracts[1].Id});
        insert accCustomerContractsChildList;
    }

    @isTest
    static void testCustContractAndCPLPopulatedOnChild() {
        
        Test.startTest();
            Database.executeBatch(new TEMP_SM_ContractGroupBatch());
        Test.stopTest();
    }
}