unpackaged/main/default/objects/Account/fields/Batch_Update__c.field-meta.xml
<CustomField>
    <fullName>Batch_Update__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Update of legacy data</description>
    <label>Batch Update</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Contract_Group__c.field-meta.xml
<CustomField>
    <fullName>Contract_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent Account for the contract group</description>
    <label>Contract Group</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contract Group Associations</relationshipLabel>
    <relationshipName>Contract_Group_Association</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/On_Contract__c.field-meta.xml
<CustomField>
    <fullName>On_Contract__c</fullName>
    <description>Yes if any of related Contract is Active. No if NONE of any related Contract is Active</description>
    <label>On Contract</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Various contracts associated to customers, projects and umbrellas. Use of custom object in place of standard considering future implementation of CPQ with contract and its line items.</description>
    <label>Contract</label>
    <nameField>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Contract_Group__c/Contract_Group__c.object-meta.xml
<CustomObject>
    <description>A logical contract grouping that defines customer accounts it is applied to.</description>
    <label>Contract Group</label>
    <nameField>
        <label>Contract Group</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Group</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Contract__c/Customer_Contract__c.object-meta.xml
<CustomObject>
    <label>Customer Contract</label>
    <nameField>
        <displayFormat>CC-{00000000}</displayFormat>
        <label>Customer Contract</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Contract__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <description>Contract for customer contract</description>
    <inlineHelpText>Contract for customer contract</inlineHelpText>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Customer Contracts</relationshipLabel>
    <relationshipName>Customer_Contracts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Customer_Contract__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <description>Customer this customer contract is related to. Ref #CCRM-145</description>
    <inlineHelpText>Customer this customer contract is related to</inlineHelpText>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Contracts</relationshipLabel>
    <relationshipName>Customer_Contracts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Customer_Price_List__c/Customer_Price_List__c.object-meta.xml
<CustomObject>
    <description>Junction between Price List and Customers</description>
    <label>Customer Price List</label>
    <nameField>
        <displayFormat>CPL-{0000000000}</displayFormat>
        <label>Customer Price List Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Price Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Price_List__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>The customer</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Price Lists</relationshipLabel>
    <relationshipName>Customer_Price_Lists</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Customer_Price_List__c/fields/Price_List__c.field-meta.xml
<CustomField>
    <fullName>Price_List__c</fullName>
    <description>The price list</description>
    <label>Price List</label>
    <referenceTo>Price_List__c</referenceTo>
    <relationshipLabel>Customer Price Lists</relationshipLabel>
    <relationshipName>Customer_Price_Lists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Price_List__c/Price_List__c.object-meta.xml
<CustomObject>
    <description>This Object represents the header level of an externally mastered pricing table, which applies item level discounts for a pre-defined list of products within specific Cost Zones.</description>
    <label>Price List</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Price List Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/classes/TEMP_SM_ContractGroupBatch.cls
/*******************************************************************************************************
* Class Name      	: TEMP_SM_ContractGroupBatch
* Description		: Temporary batch class to Update legacy accounts for CCRM15-103
* Author          	: Simplus MS
* Created On      	: 25/08/2021
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer			  		Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Simplus.MS                25/08/2021		1000				Initial version
******************************************************************************************************/
public class TEMP_SM_ContractGroupBatch implements Database.Batchable<sObject> {
    
    String query;
    
    public TEMP_SM_ContractGroupBatch() {
        query = 'SELECT Id, Name, Contract_Group__c, ' +
                '(SELECT Customer__c, Contract__c FROM Customer_Contracts__r), ' +
                '(SELECT Account__c, Price_List__c FROM Customer_Price_Lists__r)' +
                'From Account ' +
                'Where Contract_Group__c != null AND Batch_Update__c = True';
    }
    
    public Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query); 
    }
    
    public void execute(Database.BatchableContext BC, List<Account> scope) {
        // execute code
        system.debug('Scope :: ' +scope);

        Set<Id> childAccounts = new Set<Id>();
        Set<Id> parentAccounts = new Set<Id>();
        List<Account> accountsToUpdate = new List<Account>();
        List<Customer_Price_List__c> toInsertCloneCPLList = new List<Customer_Price_List__c>();
        List<Customer_Contract__c> toInsertCloneCustContractList  = new List<Customer_Contract__c>();

        try {
            for(Account childAcc : scope) {
                childAccounts.add(childAcc.Id);
                parentAccounts.add(childAcc.Contract_Group__c );
            }

            Map<Id, Account> parentAccWithCustContractsAndCPLMap = DM_Account.getParentAccWithCustContractsAndCPL(parentAccounts);
            system.debug('parentAccWithCustContractsAndCPLMap :: ' +parentAccWithCustContractsAndCPLMap);
            Map<Id, Account> childAccWithCustContractsAndCPLMap = DM_Account.getChildAccWithCustContractsAndCPL(childAccounts);
            system.debug('childAccWithCustContractsAndCPLMap :: ' +childAccWithCustContractsAndCPLMap);

            Map<Id, Map<Id, Id>> childAccContractsMap = new Map<Id, Map<Id, Id>>();
            Map<Id, Map<Id, Id>> childAccCPLMap = new Map<Id, Map<Id, Id>>();
            
            for(Account newAcc : childAccWithCustContractsAndCPLMap.values()) {
                
                Map<Id, Id> contractsMap = new Map<Id, Id>();
                Map<Id, Id> cplMap = new Map<Id, Id>();

                for(Customer_Contract__c custContract : newAcc.Customer_Contracts__r){
                    contractsMap.put(custContract.Contract__c, newAcc.Contract_Group__c);
                    childAccContractsMap.put(newAcc.Id, contractsMap);
                }

                for(Customer_Price_List__c cpl : newAcc.Customer_Price_Lists__r){
                    cplMap.put(cpl.Price_List__c, newAcc.Contract_Group__c);
                    childAccCPLMap.put(newAcc.Id, cplMap);
                }
            }
        
            for(Account newAcc : scope) {
                Account parentAccWithCustContractsAndCPL = parentAccWithCustContractsAndCPLMap.get(newAcc.Contract_Group__c);

                Map<Id, Id> childAccCustContracts = childAccContractsMap.get(newAcc.Id);
                Map<Id, Id> childAccCPLs = childAccCPLMap.get(newAcc.Id);

                if(parentAccWithCustContractsAndCPL != null){
                    if(parentAccWithCustContractsAndCPL.Customer_Contracts__r.size() > 0){
                        for(Customer_Contract__c custContract : parentAccWithCustContractsAndCPL.Customer_Contracts__r){

                            if (childAccCustContracts != null){
                                if(!childAccCustContracts.isEmpty() && !childAccCustContracts.containsKey(custContract.Contract__c))
                                {
                                Customer_Contract__c custContractClone = custContract.clone(false, false, false, false);
                                custContractClone.Customer__c = newAcc.Id;
                                toInsertCloneCustContractList.add(custContractClone);
                                system.debug('toInsertCloneCustContractList :: ' +toInsertCloneCustContractList);
                                }
                            }else{
                                Customer_Contract__c custContractClone = custContract.clone(false, false, false, false);
                                custContractClone.Customer__c = newAcc.Id;
                                toInsertCloneCustContractList.add(custContractClone);
                                system.debug('custContract :: ' +custContract);
                            }
                        }
                        //accountsToUpdate.add(new Account(Id = newAcc.Id, On_Contract__c = 'Yes'));
                    }
    
                    if(parentAccWithCustContractsAndCPL.Customer_Price_Lists__r.size() > 0){
                        for(Customer_Price_List__c cpl : parentAccWithCustContractsAndCPL.Customer_Price_Lists__r){

                            if (childAccCPLs != null){
                                if(!childAccCPLs.isEmpty() && !childAccCPLs.containsKey(cpl.Price_List__c))
                                {
                                Customer_Price_List__c cplClone = cpl.clone(false, false, false, false);
                                cplClone.Account__c = newAcc.Id;
                                toInsertCloneCPLList.add(cplClone);
                                system.debug('toInsertCloneCPLList :: ' +toInsertCloneCPLList);
                                }
                            }else{
                                Customer_Price_List__c cplClone = cpl.clone(false, false, false, false);
                                cplClone.Account__c = newAcc.Id;
                                toInsertCloneCPLList.add(cplClone);
                                system.debug('cpl :: ' +cpl);
                            }
                        }
                        //accountsToUpdate.add(new Account(Id = newAcc.Id, On_Contract__c = 'Yes'));
                    }
                    
                    if(parentAccWithCustContractsAndCPL.Customer_Contracts__r.size() > 0 
                        || parentAccWithCustContractsAndCPL.Customer_Price_Lists__r.size() > 0){
                            accountsToUpdate.add(new Account(Id = newAcc.Id, On_Contract__c = 'Yes', Batch_Update__c = False));
                    }
                }
            }

            system.debug('accountsToUpdate :: ' +accountsToUpdate);
            system.debug('toInsertCloneCPLList :: ' +toInsertCloneCPLList);
            system.debug('toInsertCloneCustContractList :: ' +toInsertCloneCustContractList);
            
            if(accountsToUpdate.size() > 0) {
                try {
                    Update accountsToUpdate;
                } catch(Exception e) {
                    ApplicationLogger.log('TEMP_SM_ContractGroupBatch', 'Account', 'Batch', e);
                }
            }
    
            if(toInsertCloneCPLList.size() > 0) {
                try {
                    Insert toInsertCloneCPLList;
                } catch(Exception e) {
                    ApplicationLogger.log('TEMP_SM_ContractGroupBatch', 'Account', 'Batch', e);
                }
            }
            
            if(toInsertCloneCustContractList.size() > 0) {
                try {
                    Insert toInsertCloneCustContractList;
                } catch(Exception e) {
                    ApplicationLogger.log('TEMP_SM_ContractGroupBatch', 'Account', 'Batch', e);
                }
            }

        } catch(Exception e) {
            ApplicationLogger.log('TEMP_SM_ContractGroupBatch', 'Account', 'Batch', e);
        }
    }
    
    public void finish(Database.BatchableContext BC) {
        // finish code
    }
    
}