unpackaged/main/default/objects/Account/fields/Contract_Group__c.field-meta.xml
<CustomField>
    <fullName>Contract_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent Account for the contract group</description>
    <label>Contract Group</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contract Group Associations</relationshipLabel>
    <relationshipName>Contract_Group_Association</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Contract_States__c.field-meta.xml
<CustomField>
    <fullName>Contract_States__c</fullName>
    <description>Unrestricted list of Bunnings states</description>
    <label>Contract State(s) - New Contract Only</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NATIONAL</fullName>
            </value>
            <value>
                <fullName>ACT</fullName>
            </value>
            <value>
                <fullName>NQ</fullName>
            </value>
            <value>
                <fullName>NSW</fullName>
            </value>
            <value>
                <fullName>NT</fullName>
            </value>
            <value>
                <fullName>QLD</fullName>
            </value>
            <value>
                <fullName>SA</fullName>
            </value>
            <value>
                <fullName>TAS</fullName>
            </value>
            <value>
                <fullName>VIC</fullName>
            </value>
            <value>
                <fullName>WA</fullName>
            </value>
            <value>
                <fullName>NI</fullName>
            </value>
            <value>
                <fullName>SI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Cost_Zones__c.field-meta.xml
<CustomField>
    <fullName>Cost_Zones__c</fullName>
    <description>Unrestricted list of contract applicable cost zones</description>
    <label>Cost Zone(s) - New Contract Only</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ALL</fullName>
            </value>
            <value>
                <fullName>AU CZ 1</fullName>
            </value>
            <value>
                <fullName>AU CZ 2</fullName>
            </value>
            <value>
                <fullName>AU CZ 3</fullName>
            </value>
            <value>
                <fullName>NZ CZ 1</fullName>
            </value>
            <value>
                <fullName>NZ CZ 2</fullName>
            </value>
            <value>
                <fullName>NZ CZ 3</fullName>
            </value>
            <value>
                <fullName>NZ CZ 4</fullName>
            </value>
            <value>
                <fullName>NZ CZ 5</fullName>
            </value>
            <value>
                <fullName>NZ CZ 6</fullName>
            </value>
            <value>
                <fullName>NZ CZ 7</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Run_Case_Assignment_via_Apex__c.field-meta.xml
<CustomField>
    <fullName>Run_Case_Assignment_via_Apex__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used as a criteria field for the &quot;Case On Create&quot; Process Builder to fire Case Assignment Rules for the Case when True</description>
    <label>Run Case Assignment via Apex?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Subtype__c.field-meta.xml
<CustomField>
    <fullName>Subtype__c</fullName>
    <description>This field determines the subtype of the case and drives validation rules.</description>
    <label>Subtype</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Contract</fullName>
            </value>
            <value>
                <fullName>Contract Amendment</fullName>
            </value>
            <value>
                <fullName>Contract Review - Changes Required</fullName>
            </value>
            <value>
                <fullName>New Project Contract</fullName>
            </value>
            <value>
                <fullName>Update Project Contract Participants</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/recordTypes/NZ_Contract_Requests.recordType-meta.xml
<RecordType>
    <fullName>NZ_Contract_Requests</fullName>
    <active>true</active>
    <businessProcess>Contract Request</businessProcess>
    <description>Record type for NZ Contract Requests</description>
    <label>Contract Request</label>
</RecordType>

unpackaged/main/default/objects/Case/recordTypes/Quote_Request.recordType-meta.xml
<RecordType>
    <fullName>Quote_Request</fullName>
    <active>true</active>
    <businessProcess>Quote Request</businessProcess>
    <description>Record type for Quote Requests</description>
    <label>Quote Request</label>
</RecordType>

unpackaged/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Various contracts associated to customers, projects and umbrellas. Use of custom object in place of standard considering future implementation of CPQ with contract and its line items.</description>
    <label>Contract</label>
    <nameField>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Contract_Group__c/Contract_Group__c.object-meta.xml
<CustomObject>
    <description>A logical contract grouping that defines customer accounts it is applied to.</description>
    <label>Contract Group</label>
    <nameField>
        <label>Contract Group</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Group</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/classes/SM_Case_Test.cls
/*******************************************************************************************************
* Class Name      	: SM_Case_Test
* Description		: Test class for SM_Case
* Author          	: Simplus - Yi Zhang
* Created On      	: 01/10/2020
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Yi Zhang              01/10/2020		1000				Initial version
* MS Simplus            15/10/2020		2000				Added to Improve Test Coverage on Case Insert for Case Trigger
* MS Simplus            21/06/2021      3000                Added to cover 
* Jasper R. Galapon		20/06/2023		2000				BUNDIG-21197 - New/Renewal Contracts - No Case Created When A1 Rejects
******************************************************************************************************/
@isTest
private class SM_Case_Test {
    // BUNDIG-21197
    @isTest
    private static void testCreateCase() {
        Test.startTest();
            try {
                SM_Case.createCase(null, '');
            } catch(Exception e) {}
            
            Boolean result = SM_Case.createCase(new Contract__c(), 'Test comment');
            System.assertEquals(true, result, 'case should have been created successfully');
        Test.stopTest();
    }
    
    /**
    * @description Added to Improve Test Coverage on Case Insert for Case Trigger
    * @author MS Simplus | 15/06/2021 
    **/
    @isTest
    private static void testCaseInsert() {
        
        List<Account> accounts = TestDataFactory.createAccounts(2);
        accounts[0].Contract_Group__c = accounts[1].Id;
        insert accounts;
        Id caseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get(Constants.AU_CONTRACT_CASE).getRecordTypeId();
        List<Case> newList = new List<Case>();
        for(Integer i=0; i<2; i++ ){
            Case caseRec = new Case();
            caseRec.RecordTypeId = caseRecordTypeId;
			caseRec.AccountId = accounts[i].Id;       
            caseRec.Type = 'Contract Request';
            //caseRec.Subtype__c = 'Contract Review - Changes Required';
            caseRec.Description = 'Test comment'+i;
            caseRec.Run_Case_Assignment_via_Apex__c = true;
            caseRec.Contract_States__c = 'NATIONAL';
            caseRec.Cost_Zones__c = 'ALL';
            newList.add(caseRec);
        }
        
        Test.startTest();
        	insert newList;        	
        Test.stopTest();
    }

    /**
    * @description  - added to cover CaseTriggerHandler.checkContractGroupField method
    * @author Simplus MS | 21/06/2021 
    **/
    @isTest
    static void test_checkContractGroupField() {
        RecordType auCustomerRecType = [
            SELECT Id, Name 
            FROM RecordType 
            WHERE Name = 'AU Customer' 
            AND sObjectType='Account' LIMIT 1];

        insert new List<Account> {
            new Account(
            Name = 'test Account', RecordTypeId = auCustomerRecType.Id
            ),
            new Account(
            Name = 'test Account Master', RecordTypeId = auCustomerRecType.Id
            )
        };
        
        List<Account> accList = [SELECT Id, Name, Contract_Group__c FROM Account];
        Account masterAcc = new Account();
        Account nonMasterAcc = new Account();
        for(Account ac : accList) {
            if(ac.Name.contains('Master')) masterAcc = ac;
            else nonMasterAcc = ac; 
        }
        nonMasterAcc.Contract_Group__c = masterAcc.Id;
        update nonMasterAcc;

        Account acc = [SELECT Id FROM Account Where Name='test Account' LIMIT 1];
        List<RecordType> rts = [SELECT Id, DeveloperName from RecordType WHERE SObjectType='Case' AND DeveloperName IN ('NZ_Contract_Requests','Quote_Request')];
        Id rTAUContractReqId;
        Id rTnonContactRequestId;

        for(RecordType rt: rts) {
            if(rt.DeveloperName == 'NZ_Contract_Requests') rTAUContractReqId = rt.Id;
            else rTnonContactRequestId = rt.Id;
        }
        Test.startTest();
        try{ insert new Case(AccountId = acc.Id, RecordTypeId = rTAUContractReqId, Contract_States__c = 'NATIONAL', Cost_Zones__c = 'ALL' ); }
        catch(Exception e) {}

        insert new Case(AccountId = acc.Id, RecordTypeId = rTnonContactRequestId, Run_Case_Assignment_via_Apex__c = true, Contract_States__c = 'NATIONAL', Cost_Zones__c = 'ALL');

        Test.stopTest();
    }
}