unpackaged/main/default/objects/Account/fields/Contract_Group__c.field-meta.xml
<CustomField>
    <fullName>Contract_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent Account for the contract group</description>
    <label>Contract Group</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contract Group Associations</relationshipLabel>
    <relationshipName>Contract_Group_Association</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Pricing_Assignment_Status__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Assignment_Status__c</fullName>
    <label>Pricing Assignment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manager Actioned</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Actioned</fullName>
                <isActive>false</isActive>
                <label>Actioned</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Send_Data_to_CPS__c.field-meta.xml
<CustomField>
    <fullName>Send_Data_to_CPS__c</fullName>
    <defaultValue>false</defaultValue>
    <description>this checkbox will fire the Apex Web Service Callout to send the record to CPS for them to update.</description>
    <label>Send Data to CPS</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contract_Group__c/Contract_Group__c.object-meta.xml
<CustomObject>
    <description>A logical contract grouping that defines customer accounts it is applied to.</description>
    <label>Contract Group</label>
    <nameField>
        <label>Contract Group</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Group</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Price_List__c/Customer_Price_List__c.object-meta.xml
<CustomObject>
    <description>Junction between Price List and Customers</description>
    <label>Customer Price List</label>
    <nameField>
        <displayFormat>CPL-{0000000000}</displayFormat>
        <label>Customer Price List Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Price Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Price_List__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>The customer</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Price Lists</relationshipLabel>
    <relationshipName>Customer_Price_Lists</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Customer_Price_List__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <description>Result of the price list assignment action</description>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assignment</fullName>
            </value>
            <value>
                <fullName>Removal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Customer_Price_List__c/fields/CPL_Status__c.field-meta.xml
<CustomField>
    <fullName>CPL_Status__c</fullName>
    <formula>IF(TEXT(Price_List__r.Status__c) = &#39;Active&#39;, IF(Start_Date__c &lt;= TODAY()  &amp;&amp;  End_Date__c &gt;= TODAY(), &quot;Active&quot;,&quot;Inactive&quot;), &quot;Inactive&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Customer_Price_List__c/fields/Customer_Price_List_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_Price_List_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Definition Id of the price list assoicated to a customer</description>
    <externalId>true</externalId>
    <label>Customer Price List ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Customer_Price_List__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Customer Price Lists End Date</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Customer_Price_List__c/fields/Price_List__c.field-meta.xml
<CustomField>
    <fullName>Price_List__c</fullName>
    <description>The price list</description>
    <label>Price List</label>
    <referenceTo>Price_List__c</referenceTo>
    <relationshipLabel>Customer Price Lists</relationshipLabel>
    <relationshipName>Customer_Price_Lists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Customer_Price_List__c/fields/Pricing_Assignment_Status__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Assignment_Status__c</fullName>
    <label>Pricing Assignment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Assignment Approval</fullName>
            </value>
            <value>
                <fullName>Pending Removal Approval</fullName>
            </value>
            <value>
                <fullName>Submitted to CPS</fullName>
            </value>
            <value>
                <fullName>CPS Submission Failure</fullName>
            </value>
            <value>
                <fullName>CPS Approved</fullName>
            </value>
            <value>
                <fullName>Manager Actioned</fullName>
                <isActive>false</isActive>
                <label>Manager Actioned</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Customer_Price_List__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Customer Price Lists Start Date</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Customer_Price_List__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This field determines whether a Price List is active (checked) or In active (unchecked) for the related Customer.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Price_List__c/Price_List__c.object-meta.xml
<CustomObject>
    <description>This Object represents the header level of an externally mastered pricing table, which applies item level discounts for a pre-defined list of products within specific Cost Zones.</description>
    <label>Price List</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Price List Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Price_List__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Date when Price List would end</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Price_List__c/fields/Price_List_Definition__c.field-meta.xml
<CustomField>
    <fullName>Price_List_Definition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Price List Definition</description>
    <label>Price List Definition</label>
    <referenceTo>Price_List_Definition__c</referenceTo>
    <relationshipLabel>Price Lists</relationshipLabel>
    <relationshipName>Price_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Price_List__c/fields/Price_List_Header_ID__c.field-meta.xml
<CustomField>
    <fullName>Price_List_Header_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>External ID Reference for Price List</description>
    <externalId>true</externalId>
    <label>Price List Header ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Price_List__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Date when Price List would start</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Price_List__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Price List</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Price_List_Definition__c/Price_List_Definition__c.object-meta.xml
<CustomObject>
    <label>Price List Definition</label>
    <nameField>
        <displayFormat>PLD-{000000}</displayFormat>
        <label>Price List Definition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price List Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/CustomerPriceListTriggerHandlerTest.cls
/*******************************************************************************************************
* Class Name      	: CustomerPriceListTriggerHandlerTest
* Description		: CustomerPriceList test class
* Author          	: Simplus MS
* Created On      	: 17/12/2020
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Simplus MS           17/12/2020		1000				Initial version - CCRM-297
* Simplus MS           14/05/2021		2000				modifications CCRM-13728
* Simplus MS           29/06/2021		3000    		 	modifications CCRM-13792
* Jasper R Galapon	   03/01/2024		4000				modifications BUNDIG-26295
******************************************************************************************************/
@isTest
private class CustomerPriceListTriggerHandlerTest {
    @isTest
    private static void test_CPLDeletion(){
        List<Account> accounts = TestDataFactory.createAccounts(1);
        insert accounts;
        Price_List_Definition__c pld = new Price_List_Definition__c();
        insert pld;
        Price_List__c pb = new Price_List__c(Status__c = 'Active', Price_List_Definition__c = pld.Id, Price_List_Header_ID__c = String.valueOf(Math.random()));
        insert pb;
        Customer_Price_List__c cpl = new Customer_Price_List__c(Price_List__c = pb.Id, Account__c = [SELECT Id from Account LIMIT 1].Id,
                                                               Status__c = 'Active', Customer_Price_List_ID__c = '45426');
        insert cpl;

        Test.startTest();
        	// BUNDIG-26295
            //Test.setMock(HttpCalloutMock.class, new SM_RESTCalloutMock('{"example":"test"}', 200, false));
        	Test.setMock(HttpCalloutMock.class, new SM_RESTCalloutMock('{"statusCode":"S","statusDescription":"Successfull validation of customer assignment to pricelist"}', 200, false));
            cpl.Action__c = 'Removal';
            cpl.Pricing_Assignment_Status__c = 'Submitted to CPS';
            cpl.Start_Date__c = System.Date.today().addDays(5);
            update cpl;
        Test.stopTest();
    }
    
    @isTest
    private static void test_CPLAssignment(){
        List<Account> accounts = TestDataFactory.createAccounts(2);
        accounts[0].Send_Data_to_CPS__c = true;
        insert accounts;
        
        accounts[1].Contract_Group__c = accounts[0].Id;
        update accounts[1];
        
        Price_List_Definition__c pld = new Price_List_Definition__c();
        insert pld;
        Price_List__c pb = new Price_List__c(Status__c = 'Active', Price_List_Definition__c = pld.Id, Price_List_Header_ID__c = String.valueOf(Math.random()));
        insert pb;
        Customer_Price_List__c cpl = new Customer_Price_List__c(Price_List__c = pb.Id, Account__c = accounts[1].Id,
                                                               Status__c = 'Active', Customer_Price_List_ID__c = '', 
                                                                Pricing_Assignment_Status__c=null, Action__c='Assignment');
        insert cpl;
        
        Customer_Price_List__c cpl1 = new Customer_Price_List__c(Price_List__c = pb.Id, Account__c = [SELECT Id from Account LIMIT 1].Id,
                                                               Status__c = 'Active', Customer_Price_List_ID__c = '', 
                                                                Pricing_Assignment_Status__c=null, Action__c='Removal');
        insert cpl1;

        Test.startTest();
            // BUNDIG-26295
            //Test.setMock(HttpCalloutMock.class, new SM_RESTCalloutMock('{"example":"test"}', 200, false));
            Test.setMock(HttpCalloutMock.class, new SM_RESTCalloutMock('{"statusCode":"S","statusDescription":"Successfull validation of customer assignment to pricelist"}', 200, false));        
        
            cpl1.End_Date__c = System.today().addDays(30);
            cpl1.Change_Requested_On__c = System.today();
            cpl1.Action__c = 'Assignment';
            cpl1.Pricing_Assignment_Status__c = 'Submitted to CPS';
            update cpl1;
            cpl1.Status__c = 'Inactive';
            cpl1.Action__c = 'Assignment';
            update cpl1;
        Test.stopTest();
    }
    
    @isTest
    private static void test_afterUpdate() {
        List<Account> accounts = TestDataFactory.createAccounts(1);
        accounts[0].Send_Data_to_CPS__c = true;
        insert accounts;
        
        Price_List_Definition__c pld = new Price_List_Definition__c();
        insert pld;
        
        Price_List__c pb = new Price_List__c(Status__c = 'Active', Price_List_Definition__c = pld.Id, Price_List_Header_ID__c = String.valueOf(Math.random()));
        insert pb;
        
        Customer_Price_List__c cpl1 = new Customer_Price_List__c(Price_List__c = pb.Id, Account__c = [SELECT Id FROM Account LIMIT 1].Id,
			Status__c = 'Expired', Customer_Price_List_ID__c = '45426', Start_Date__c = Date.today() - 1, End_Date__c = Date.today() + 400);
        Customer_Price_List__c cpl2 = new Customer_Price_List__c(Price_List__c = pb.Id, Account__c = [SELECT Id FROM Account LIMIT 1].Id,
			Status__c = 'Active', Customer_Price_List_ID__c = '45427', Start_Date__c = Date.today() - 1, End_Date__c = Date.today() + 365);
        insert new List<Customer_Price_List__c>{cpl1, cpl2};
                                        
		Test.startTest();
        	List<Customer_Price_List__c> cpl = [SELECT Id, CPL_Status__c FROM Customer_Price_List__c];        	
        	cpl[0].Status__c = 'Active';
        	update cpl;        	
        Test.stopTest();
    }
    
    @isTest
    private static void test_afterDelete() {
        List<Account> accounts = TestDataFactory.createAccounts(1);
        accounts[0].Send_Data_to_CPS__c = true;
        insert accounts;
        
        Price_List_Definition__c pld = new Price_List_Definition__c();
        insert pld;
        
        Price_List__c pb = new Price_List__c(Status__c = 'Active', Price_List_Definition__c = pld.Id, Price_List_Header_ID__c = String.valueOf(Math.random()));
        insert pb;
        
        Customer_Price_List__c cpl1 = new Customer_Price_List__c(Price_List__c = pb.Id, Account__c = [SELECT Id FROM Account LIMIT 1].Id,
			Status__c = 'Expired', Customer_Price_List_ID__c = '45426', Start_Date__c = Date.today() - 1, End_Date__c = Date.today() + 400);
        Customer_Price_List__c cpl2 = new Customer_Price_List__c(Price_List__c = pb.Id, Account__c = [SELECT Id FROM Account LIMIT 1].Id,
			Status__c = 'Active', Customer_Price_List_ID__c = '45427', Start_Date__c = Date.today() - 1, End_Date__c = Date.today() + 365);
        insert new List<Customer_Price_List__c>{cpl1, cpl2};
                                        
		Test.startTest();
        	List<Customer_Price_List__c> cpl = [SELECT Id, CPL_Status__c FROM Customer_Price_List__c LIMIT 1];
        	delete cpl;        	
        Test.stopTest();
    }
}