unpackaged/main/default/objects/Account/fields/Contract_Group__c.field-meta.xml
<CustomField>
    <fullName>Contract_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent Account for the contract group</description>
    <label>Contract Group</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contract Group Associations</relationshipLabel>
    <relationshipName>Contract_Group_Association</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Home_Store__c.field-meta.xml
<CustomField>
    <fullName>Home_Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Home Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/On_Contract__c.field-meta.xml
<CustomField>
    <fullName>On_Contract__c</fullName>
    <description>Yes if any of related Contract is Active. No if NONE of any related Contract is Active</description>
    <label>On Contract</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Power_Pass_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Power_Pass_Account_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Power Pass Account Number</label>
    <length>32</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Various contracts associated to customers, projects and umbrellas. Use of custom object in place of standard considering future implementation of CPQ with contract and its line items.</description>
    <label>Contract</label>
    <nameField>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Contract__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Associated Project</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Date when the contract started</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the contract</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contract_Group__c/Contract_Group__c.object-meta.xml
<CustomObject>
    <description>A logical contract grouping that defines customer accounts it is applied to.</description>
    <label>Contract Group</label>
    <nameField>
        <label>Contract Group</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Group</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Contract__c/Customer_Contract__c.object-meta.xml
<CustomObject>
    <label>Customer Contract</label>
    <nameField>
        <displayFormat>CC-{00000000}</displayFormat>
        <label>Customer Contract</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Contract__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <description>Contract for customer contract</description>
    <inlineHelpText>Contract for customer contract</inlineHelpText>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Customer Contracts</relationshipLabel>
    <relationshipName>Customer_Contracts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Customer_Contract__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <description>Customer this customer contract is related to. Ref #CCRM-145</description>
    <inlineHelpText>Customer this customer contract is related to</inlineHelpText>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Contracts</relationshipLabel>
    <relationshipName>Customer_Contracts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Customer_Contract__c/fields/Power_Pass_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Power_Pass_Account_Number__c</fullName>
    <description>Account Power Pass Number</description>
    <formula>Customer__r.Power_Pass_Account_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Power Pass Account Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>This object is used for grouping Opportunities related to a single construction project.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The Status of the Project eg. Quotation</description>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Documentation</fullName>
            </value>
            <value>
                <fullName>Tender</fullName>
            </value>
            <value>
                <fullName>Post Tender</fullName>
            </value>
            <value>
                <fullName>Builder Appointed</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Closed - Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Project_Participant__c/Project_Participant__c.object-meta.xml
<CustomObject>
    <description>This junction object captures the relationship between an Account and a construction Project. This object also captures the relationship between a &quot;Project Specific Contract&quot;, and the Accounts with Access to the Project Specific Pricing.</description>
    <label>Project Participant</label>
    <nameField>
        <displayFormat>PP-{00000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Project_Participant__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A lookup to the related Contract.</description>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipName>Project_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Project_Participant__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>A lookup to the related Project.</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Project_Groups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Project_Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active - Not on Contract</fullName>
                <default>true</default>
                <label>Active - Not on Contract</label>
            </value>
            <value>
                <fullName>Active - On Contract</fullName>
            </value>
            <value>
                <fullName>Request for Contract Addition</fullName>
            </value>
            <value>
                <fullName>Request for Contract Change</fullName>
            </value>
            <value>
                <fullName>Request for Contract Removal</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>.</fullName>
                <isActive>false</isActive>
                <label>.</label>
            </value>
            <value>
                <fullName>Active</fullName>
                <isActive>false</isActive>
                <label>Active</label>
            </value>
            <value>
                <fullName>On Contract</fullName>
                <isActive>false</isActive>
                <label>On Contract</label>
            </value>
            <value>
                <fullName>Request tor Contract</fullName>
                <isActive>false</isActive>
                <label>Request tor Contract</label>
            </value>
            <value>
                <fullName>Request tor Contract Addition</fullName>
                <isActive>false</isActive>
                <label>Request tor Contract Addition</label>
            </value>
            <value>
                <fullName>Request tor Contract Change</fullName>
                <isActive>false</isActive>
                <label>Request tor Contract Change</label>
            </value>
            <value>
                <fullName>Request tor Contract Removal</fullName>
                <isActive>false</isActive>
                <label>Request tor Contract Removal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>Represents all frame and truss plants, small format stores, trade distribution centres and warehouses.</description>
    <label>Store</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Store__c/fields/Engagement_Model__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Model__c</fullName>
    <description>Determines the method used for assigning Powerpass Account Ownership. 
Old Model - the Stores Default Trade Specialist will become the owner. 
New - Ownership is determined by Assignment Rule Metadata records</description>
    <label>Engagement Model</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Old</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/CustomerContractTrigger_Test.cls
/*******************************************************************************************************
* Class Name      	: CustomerContractTrigger_Test
* Description		: Test class for CustomerContractTrigger
* Author          	: Simplus - John Paul Peñaflor
* Created On      	: 22/08/2020
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* John Paul Peñaflor    22/08/2020		1000				Initial version
* Simplus MS 			07/07/2021		1001				Increased test coverage for CCRM-13792
* Bunnings Dev			11/03/2022		1002				Increased test coverage for SFSUP-373
******************************************************************************************************/
@IsTest
public class CustomerContractTrigger_Test {
    /**
    * @description 
    * @author John Paul Peñaflor | 08-22-2020 
    **/
    @isTest
    public static void testGetContacts() {

        Profile p = [SELECT Id FROM Profile WHERE Name =: Constants.NATIONAL_MANAGER_PROFILEENAME LIMIT 1];
        list<User> users = TestDataFactory.createUsers(1, p.Id);
        users[0].FirstName = 'Bob';
        users[0].LastName = 'Vuksan';
		
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
		System.runAs (thisUser) {
            insert users;
			//insert userSysAd;
        }

        List<Store__c> stores = TestDataFactory.createStores(1);
        stores[0].Engagement_Model__c = 'New';

        insert stores;
            								
        List<Account> accounts = TestDataFactory.createAccounts(1);
        accounts[0].Power_Pass_Account_Number__c = 'Test-1001';
        accounts[0].Home_Store__c = stores[0].Id;

        insert accounts;

        List<Project__c> projects = TestDataFactory.createProject(2);
        projects[0].RecordTypeId = CSUtils.getRecordTypeId('Project__c', 'AU Project');
        projects[1].RecordTypeId = CSUtils.getRecordTypeId('Project__c', 'AU Project');

        insert projects;

        List<Contract__c> contracts = TestDataFactory.createContracts(1);
        contracts[0].RecordTypeId = CSUtils.getRecordTypeId('Contract__c', 'AU Contract');
        contracts[0].Project__c = projects[0].Id;

        insert contracts;

        Test.startTest();

        List<Customer_Contract__c> customerContracts = TestDataFactory.createCustomerContracts(accounts[0].Id, new List<Id>{contracts[0].Id});
		// Initiate Customer Contract initiation
		// Expected: 1 Project participant to be created.
        insert customerContracts;
        
        List<Project_Participant__c> projectParticipants = DM_ProjectParticipant.getProjectParticipants(new Set<String>{contracts[0].Id});
        
        System.assertEquals(contracts[0].Id, projectParticipants[0].Contract__c, 'Project Participant not linked to Contract');
        System.assertEquals(1, projectParticipants.size(), 'Created Project Participant should only be 1');
        System.assertEquals(SM_Contract.PROJECTPARTICIPANT_STATUS_ACTIVE_ON_CONTRACT, projectParticipants[0].Status__c, 'Project Participant Status not updated');
        
        // Delete Initiated Customer Contract 
		// Expected: 1 Project participant to be deassociate to Contract. Contract = null.
        delete customerContracts;
        
        List<Project_Participant__c> oldProjectParticipants = DM_ProjectParticipant.getNoContractProjectParticipants(new Set<String>{projects[0].Id}, new Set<String>{accounts[0].Id});
        
        System.assertEquals(null, oldProjectParticipants[0].Contract__c, 'Contract not deassociated to Project Participant');
        System.assertEquals(SM_Contract.PROJECTPARTICIPANT_STATUS_ACTIVE_NOT_ON_CONTRACT, oldProjectParticipants[0].Status__c, 'Project Participant Status not updated');
        
        List<Customer_Contract__c> newCustomerContracts = TestDataFactory.createCustomerContracts(accounts[0].Id, new List<Id>{contracts[0].Id});
        // Reinsert 1 Customer Contract with same values
		// Expected: 1 Project participant to be reassociated to Contract.
        insert newCustomerContracts;
        
        List<Project_Participant__c> updatedProjectParticipants = DM_ProjectParticipant.getProjectParticipants(new Set<String>{contracts[0].Id});
        
        System.assertEquals(contracts[0].Id, updatedProjectParticipants[0].Contract__c, 'Project Participant not linked to Contract');
        System.assertEquals(SM_Contract.PROJECTPARTICIPANT_STATUS_ACTIVE_ON_CONTRACT, updatedProjectParticipants[0].Status__c, 'Project Participant Status not updated');
        System.assertEquals(projectParticipants[0].Id, updatedProjectParticipants[0].Id, 'A new Project Participant should not be created');
        System.assertEquals(1, updatedProjectParticipants.size(), 'Related Project Participant should only be 1 as Customer Contract is recreated with same values.');
        
        List<Customer_Contract__c> duplicateCustomerContracts = TestDataFactory.createCustomerContracts(accounts[0].Id, new List<Id>{contracts[0].Id});
        // Create 1 Customer Contract with same values
		// Expected: No creation of new Project Participant as there is an existing one. Preventing Duplicates
        insert duplicateCustomerContracts;
        
        updatedProjectParticipants = DM_ProjectParticipant.getProjectParticipants(new Set<String>{contracts[0].Id});
        
        System.assertEquals(1, updatedProjectParticipants.size(), 'Related Project Participant should only be 1 as Customer Contract is new Customer Contract is a duplicate');
        System.assertEquals(SM_Contract.PROJECTPARTICIPANT_STATUS_ACTIVE_ON_CONTRACT, updatedProjectParticipants[0].Status__c, 'Project Participant Status should be active');
        System.assertEquals(projectParticipants[0].Id, updatedProjectParticipants[0].Id, 'A new Project Participant should not be created ');

        Test.stopTest();
    }

    /**
    * @description CCRM-13792: Test Any updates to the master account customer contract are 
    *                           also updated on the child account customer contract.
    * @author Simplus MS | 07/07/2021 
    **/
    @isTest
    public static void updateChildAccCustomerContractTest() {

        List<Contract__c> contracts = TestDataFactory.createContracts(1);
        contracts[0].RecordTypeId = CSUtils.getRecordTypeId('Contract__c', 'AU Contract');
        //contracts[0].Project__c = projects[0].Id;

        insert contracts;

        List<Account> parentAccounts = TestDataFactory.createAccounts(5);
        insert parentAccounts;
        List<Id> accountIds = new List<Id>();
        for(Account acc:parentAccounts){
            accountIds.add(acc.Id);
        }

        List<Account> childAccounts = TestDataFactory.createAccounts(5);
        Integer i = 0;
        for(Account acc:childAccounts){
            acc.Contract_Group__c = parentAccounts[i].Id;
            i++;
        }
        insert childAccounts;

        Test.startTest();
        List<Customer_Contract__c> accCustomerContracts = TestDataFactory.createAccCustomerContracts(accountIds, new List<Id>{contracts[0].Id});
        insert accCustomerContracts;
        List<Account> accList = [SELECT Id, (SELECT Id FROM Customer_Contracts__r) 
                                FROM Account
                                WHERE Name Like 'TestContract%' AND Contract_Group__c != null];
        for(Account acc:accList){
            System.assertEquals(1, acc.Customer_Contracts__r.size(), 'Child Account Customer Contracts not updated successfully');
        }
        Test.stopTest();
    }

    @isTest
    public static void checkAccountContracts_Test() {
        List<Account> accounts = TestDataFactory.createAccounts(1);
        insert accounts;

        List<Contract__c> contracts = TestDataFactory.createContracts(1);
        contracts[0].RecordTypeId = CSUtils.getRecordTypeId('Contract__c', 'AU Contract');
        contracts[0].Status__c = Label.Active;
        insert contracts;

        List<Customer_Contract__c> customerContracts = TestDataFactory.createCustomerContracts(accounts[0].Id, new List<Id>{contracts[0].Id});		
        insert customerContracts;

        Test.startTest();
            List<Customer_Contract__c> lstCC = [SELECT Id, Customer__c, Contract__c, Start_Date__c, Contract__r.Status__c
				FROM Customer_Contract__c WHERE Id =:customerContracts[0].Id];
            Map<Id, Customer_Contract__c> newMap = new Map<Id, Customer_Contract__c>(lstCC);

            for (Customer_Contract__c cc : newMap.values())
                cc.Start_Date__c = Date.newInstance(Date.today().year(), Date.today().month(), Date.today().day());

        	CustomerContractTriggerHandler.checkAccountContracts(newMap.values());
            List<Account> acc = [SELECT On_Contract__c FROM Account WHERE Id =: accounts[0].Id LIMIT 1];
            System.assertEquals(acc[0].On_Contract__c, 'Yes');
        Test.stopTest();

    }


    


}