unpackaged/main/default/objects/Account/fields/Family_Tree_Discount_Approval__c.field-meta.xml
<CustomField>
    <fullName>Family_Tree_Discount_Approval__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Family Tree Discount Approval</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Family_Tree_Discount_Changed__c.field-meta.xml
<CustomField>
    <fullName>Family_Tree_Discount_Changed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When Family Tree Discount change</description>
    <label>Family Tree Discount Changed</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Power_Pass_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Power_Pass_Account_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Power Pass Account Number</label>
    <length>32</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/Pricing_Assignment_Approval_Submitter__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Assignment_Approval_Submitter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pricing Assignment Approval Submitter</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Pricing_Assignment_Status__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Assignment_Status__c</fullName>
    <label>Pricing Assignment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manager Actioned</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Actioned</fullName>
                <isActive>false</isActive>
                <label>Actioned</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Send_Data_to_CPS__c.field-meta.xml
<CustomField>
    <fullName>Send_Data_to_CPS__c</fullName>
    <defaultValue>false</defaultValue>
    <description>this checkbox will fire the Apex Web Service Callout to send the record to CPS for them to update.</description>
    <label>Send Data to CPS</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Customer_Family_Tree_Discount__c/Customer_Family_Tree_Discount__c.object-meta.xml
<CustomObject>
    <description>Junction between Family Tree Discounts and the Customers</description>
    <label>Customer Family Tree Discount</label>
    <nameField>
        <displayFormat>CFD-{0000000000}</displayFormat>
        <label>Customer Family Tree Discount Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Family Tree Discounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Family_Tree_Discount__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Family Tree Discounts</relationshipLabel>
    <relationshipName>Customer_Family_Tree_Discounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Customer_Family_Tree_Discount__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <description>Result of the family tree assignment action</description>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assignment</fullName>
            </value>
            <value>
                <fullName>Removal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Customer_Family_Tree_Discount__c/fields/Customer_Family_Tree_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_Family_Tree_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Customer Family Tree ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Customer_Family_Tree_Discount__c/fields/Family_Tree_Discount__c.field-meta.xml
<CustomField>
    <fullName>Family_Tree_Discount__c</fullName>
    <label>Family Tree Discount</label>
    <referenceTo>Family_Tree_Discount__c</referenceTo>
    <relationshipLabel>Customer Family Tree Discounts</relationshipLabel>
    <relationshipName>Customer_Family_Tree_Discounts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Family_Tree_Discount__c/Family_Tree_Discount__c.object-meta.xml
<CustomObject>
    <description>This Object represents a discount structure mastered by an external system. The discount is applied to all products within externally defined product categories.</description>
    <label>Family Tree Discount</label>
    <nameField>
        <label>Family Tree Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Family Tree Discount</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Family_Tree_Discount__c/fields/Family_Tree_Discount_ID__c.field-meta.xml
<CustomField>
    <fullName>Family_Tree_Discount_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Family Tree Discount ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/User/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>&quot;None&quot;</defaultValue>
    <description>This field is used in sharing rules to define a AU User&#39;s and NZ User&#39;s</description>
    <inlineHelpText>This field is used in sharing rules to define a AU User&#39;s and NZ User&#39;s</inlineHelpText>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/User/fields/Team_Member_ID__c.field-meta.xml
<CustomField>
    <fullName>Team_Member_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>External ID used to identify the team member.</description>
    <externalId>true</externalId>
    <label>Team Member Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/classes/CustomerFTDTriggerHandler.cls
/*******************************************************************************************************
* Class Name        : CustomerFTDTriggerHandler
* Description       : Customer Family Tree Discount trigger handler
* Author            : Bunnings Dev
* Created On        : 20/02/2023
* Modification Log  :
* -----------------------------------------------------------------------------------------------------
* Developer             Date            Modification ID     Description
* -----------------------------------------------------------------------------------------------------
* Jasper R. Galapon     20/02/2023      1000                Initial version - BUNDIG-14164
******************************************************************************************************/

public without sharing class CustomerFTDTriggerHandler {
    
    public static void afterUpdate(Map<Id, Customer_Family_Tree_Discount__c> oldMap, Map<Id, Customer_Family_Tree_Discount__c> newMap) {
        System.debug('***AFTER UPDATE - Customer Familty Tree Discount');
        handleFTDAssignment(oldMap, newMap);
    }


    private static void handleFTDAssignment(Map<Id, Customer_Family_Tree_Discount__c> oldMap, Map<Id, Customer_Family_Tree_Discount__c> newMap) {
        Set<Id> acctIds = new Set<Id>();
        Set<Id> cftdIds = new Set<Id>();
        Map<Id, Account> accountMap = new Map<Id, Account>();
        Map<Id, Family_Tree_Discount__c> ftdMap;

        Map<Id, Map<String, String>> cftdMap = new Map<Id, Map<String, String>>();
        Map<Id, Map<String, String>> delcftdMap = new Map<Id, Map<String, String>>();

        for (Id cftdId : newMap.keySet()) {
            acctIds.add(newMap.get(cftdId).Account__c);
            cftdIds.add(newMap.get(cftdId).Family_Tree_Discount__c);
        }

        ftdMap = new Map<Id, Family_Tree_Discount__c>([SELECT Id, Family_Tree_Discount_ID__c FROM Family_Tree_Discount__c WHERE Id IN :cftdIds]);

        for (Account acc : [SELECT Id, Power_Pass_Account_Number__c, RecordType.DeveloperName, Country__c, Family_Tree_Discount_Changed__c, Family_Tree_Discount_Approval__c,
                            LastModifiedBy.Team_Member_ID__c, Send_Data_to_CPS__c, Pricing_Assignment_Approval_Submitter__r.Team_Member_ID__c
                            FROM Account
                            WHERE Id IN : acctIds]) {
            accountMap.put(acc.Id, acc);
        }
        System.debug('***accountMap: '+accountMap.values());

        for (Id cftdId : oldMap.keySet()) {
            
            Customer_Family_Tree_Discount__c oldCFTD = oldMap.get(cftdId);
            Customer_Family_Tree_Discount__c newCFTD = newMap.get(cftdId);
            Account acct = accountMap.get(newCFTD.Account__c);
            Family_Tree_Discount__c familyTreeDiscount = ftdMap.get(newCFTD.Family_Tree_Discount__c);

            String action = String.isBlank(newCFTD.Action__c) ? '' : newCFTD.Action__c;
            String assignmentStat = String.isBlank(newCFTD.Pricing_Assignment_Status__c) ? '' : newCFTD.Pricing_Assignment_Status__c;
            String oldAction = String.isBlank(oldCFTD.Action__c) ? '' : oldCFTD.Action__c;
            String oldAssignmentStat = String.isBlank(oldCFTD.Pricing_Assignment_Status__c) ? '' : oldCFTD.Pricing_Assignment_Status__c;            

            Map<String, String> paramMap = new Map<String, String>();

            System.debug('***JASPER: '+action+' - '+oldAction+' - '+assignmentStat+' - '+oldAssignmentStat+' - '+acct.Family_Tree_Discount_Approval__c);
        
            if (acct.Country__c == 'New Zealand') {
                if (action != oldAction || assignmentStat != oldAssignmentStat) {
                    if (assignmentStat == 'Submitted to CPS' || !acct.Family_Tree_Discount_Approval__c) {
                        paramMap.put('FamilyTreeDiscountId', familyTreeDiscount.Family_Tree_Discount_ID__c);                    
                        paramMap.put('AccountId' , newCFTD.Account__c);
                        paramMap.put('CustomerId' , acct.Power_Pass_Account_Number__c);                
                        paramMap.put('CountryCode' , 'NZ');

                        String teamMbrId = String.isBlank(acct.Pricing_Assignment_Approval_Submitter__r.Team_Member_ID__c) ? '0' : acct.Pricing_Assignment_Approval_Submitter__r.Team_Member_ID__c;
                        paramMap.put('TMNumber', teamMbrId);

                        System.debug('***paramMap: '+paramMap);
                    }
                }

                // if (action == 'Assignment' && String.isBlank(newCFTD.Customer_Family_Tree_Id__c) && acct.Send_Data_to_CPS__c) {
                if (action == 'Assignment' && String.isBlank(newCFTD.Customer_Family_Tree_Id__c)) {
                    cftdMap.put(newCFTD.Family_Tree_Discount__c, paramMap);                    
                // } else if (action == 'Removal'&& !String.isBlank(newCFTD.Customer_Family_Tree_Id__c)) {
                } else if (assignmentStat == 'Pending Removal Approval'&& !String.isBlank(newCFTD.Customer_Family_Tree_Id__c)) {
                    delcftdMap.put(newCFTD.Family_Tree_Discount__c, paramMap);
                }
            }            
        }

        System.debug('***cftdMap: '+cftdMap);
        System.debug('***delcftdMap: '+delcftdMap);

        if (cftdMap != null && cftdMap.size() > 0) 
            invokeCustomerFamilyTreeDiscountServiceServiceAssignmentAsync(JSON.serialize(cftdMap));

        if (delcftdMap != null && delcftdMap.size() > 0)
            invokeCustomerFamilyTreeDiscountServiceDeletionAsync(JSON.serialize(delcftdMap));
        
    }

    @future(callout=true)
    public static void invokeCustomerFamilyTreeDiscountServiceServiceAssignmentAsync(String cftdMapText) {
        Map<Id, Map<String, String>> cftdMap = (Map<id, Map<String, String>>) JSON.deserialize(cftdMapText, Map<Id, Map<String, String>>.class);
        SM_CustomerFamilyTreeDiscount.invokeCustomerFamilyTreeDiscountServiceServiceAssignment(cftdMap);
    }

    @future(callout=true)
    public static void invokeCustomerFamilyTreeDiscountServiceDeletionAsync(String cftdMapText) {
        Map<Id, Map<String, String>> cftdMap = (Map<id, Map<String, String>>) JSON.deserialize(cftdMapText, Map<Id, Map<String, String>>.class);
        SM_CustomerFamilyTreeDiscount.invokeCustomerFamilyTreeDiscountServiceDeletion(cftdMap);
    }
}