unpackaged/main/default/objects/Account/fields/Home_Store__c.field-meta.xml
<CustomField>
    <fullName>Home_Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Home Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Power_Pass_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Power_Pass_Account_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Power Pass Account Number</label>
    <length>32</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Case/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used for Project Contract Request Cases</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Various contracts associated to customers, projects and umbrellas. Use of custom object in place of standard considering future implementation of CPQ with contract and its line items.</description>
    <label>Contract</label>
    <nameField>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Contract__c/fields/Approver__c.field-meta.xml
<CustomField>
    <fullName>Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Approver as provided by CPS.</description>
    <label>Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract__c/fields/Original_Approver__c.field-meta.xml
<CustomField>
    <fullName>Original_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Original approver of the contract. This will help determine who to return the review to after delegation is completed.</description>
    <label>Original Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>OriginalApprover</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract__c/fields/Original_Reviewer__c.field-meta.xml
<CustomField>
    <fullName>Original_Reviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Original reviwer of the contract. This will help determine who to return the review to after delegation is completed.</description>
    <label>Original Reviewer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>OriginalReviewer</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Associated Project</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract__c/fields/Project_Address__c.field-meta.xml
<CustomField>
    <fullName>Project_Address__c</fullName>
    <description>Adress Line 1 &amp; 2 (Street address)</description>
    <label>Project Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contract__c/fields/Project_Postcode__c.field-meta.xml
<CustomField>
    <fullName>Project_Postcode__c</fullName>
    <label>Project Postcode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contract__c/fields/Project_State__c.field-meta.xml
<CustomField>
    <fullName>Project_State__c</fullName>
    <label>Project State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contract__c/fields/Reviewer__c.field-meta.xml
<CustomField>
    <fullName>Reviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reviewer as provided by CPS - First level approver</description>
    <label>Reviewer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contracts1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Unrestricted list of Bunnings states</description>
    <label>State</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NATIONAL</fullName>
            </value>
            <value>
                <fullName>ACT</fullName>
            </value>
            <value>
                <fullName>NQ</fullName>
            </value>
            <value>
                <fullName>NSW</fullName>
            </value>
            <value>
                <fullName>NT</fullName>
            </value>
            <value>
                <fullName>QLD</fullName>
            </value>
            <value>
                <fullName>SA</fullName>
            </value>
            <value>
                <fullName>TAS</fullName>
            </value>
            <value>
                <fullName>VIC</fullName>
            </value>
            <value>
                <fullName>WA</fullName>
            </value>
            <value>
                <fullName>NI</fullName>
            </value>
            <value>
                <fullName>SI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contract_Line_Item__c/Contract_Line_Item__c.object-meta.xml
<CustomObject>
    <description>Line items associated to a contract.</description>
    <label>Contract Line Item</label>
    <nameField>
        <label>Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Contract_Line_Item__c/fields/Approver__c.field-meta.xml
<CustomField>
    <fullName>Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Level 2 appover of the contract</description>
    <label>Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contract_Line_Approver</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract_Line_Item__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <description>The associated contract</description>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Contract Line Items</relationshipLabel>
    <relationshipName>Contract_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Contract_Line_Item__c/fields/Original_Approver__c.field-meta.xml
<CustomField>
    <fullName>Original_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Original approver of the amendment contract line. This will help determine who to return the review to after delegation is completed.</description>
    <label>Original Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>OriginalApproverLineItem</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract_Line_Item__c/fields/Original_Reviewer__c.field-meta.xml
<CustomField>
    <fullName>Original_Reviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Original reviewer of the amendment contract line. This will help determine who to return the review to after delegation is completed.</description>
    <label>Original Reviewer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>OriginalReviewerLineItem</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract_Line_Item__c/fields/Reviewer__c.field-meta.xml
<CustomField>
    <fullName>Reviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Level 1 approver of the contract</description>
    <label>Reviewer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contract_Line_Reviewer</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Customer_Contract__c/Customer_Contract__c.object-meta.xml
<CustomObject>
    <label>Customer Contract</label>
    <nameField>
        <displayFormat>CC-{00000000}</displayFormat>
        <label>Customer Contract</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Contract__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <description>Contract for customer contract</description>
    <inlineHelpText>Contract for customer contract</inlineHelpText>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Customer Contracts</relationshipLabel>
    <relationshipName>Customer_Contracts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Customer_Contract__c/fields/Power_Pass_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Power_Pass_Account_Number__c</fullName>
    <description>Account Power Pass Number</description>
    <formula>Customer__r.Power_Pass_Account_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Power Pass Account Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>This object is used for grouping Opportunities related to a single construction project.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Project__c/fields/Postcode__c.field-meta.xml
<CustomField>
    <fullName>Postcode__c</fullName>
    <label>Postcode</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Project_Address__c.field-meta.xml
<CustomField>
    <fullName>Project_Address__c</fullName>
    <description>The Address where the Project is taking place.</description>
    <externalId>true</externalId>
    <label>Project Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Project_Participant__c/Project_Participant__c.object-meta.xml
<CustomObject>
    <description>This junction object captures the relationship between an Account and a construction Project. This object also captures the relationship between a &quot;Project Specific Contract&quot;, and the Accounts with Access to the Project Specific Pricing.</description>
    <label>Project Participant</label>
    <nameField>
        <displayFormat>PP-{00000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Project_Participant__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Project Participants</relationshipLabel>
    <relationshipName>Project_Groups</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Project_Participant__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A lookup to the related Contract.</description>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipName>Project_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Project_Participant__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>A lookup to the related Project.</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Project_Groups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>Represents all frame and truss plants, small format stores, trade distribution centres and warehouses.</description>
    <label>Store</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Store__c/fields/Engagement_Model__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Model__c</fullName>
    <description>Determines the method used for assigning Powerpass Account Ownership. 
Old Model - the Stores Default Trade Specialist will become the owner. 
New - Ownership is determined by Assignment Rule Metadata records</description>
    <label>Engagement Model</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Old</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Store__c/fields/Postcode__c.field-meta.xml
<CustomField>
    <fullName>Postcode__c</fullName>
    <description>The store&#39;s postcode</description>
    <label>Postcode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/SM_Contract_Test.cls
/*******************************************************************************************************
* Class Name      	: SM_Contract_Test
* Description		: Test class for SM_Contract
* Author          	: Simplus - Yi Zhang
* Created On      	: 28/07/2020
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Yi Zhang              28/07/2020		1000				Initial version (Moved Phil's codes from SM_ContractReview_Test)
* Jasper R Galapon		13/04/2023		2000				BUNDIG-17527 - Test class for blocking Integration user updates
* Jasper R. Galapon		20/06/2023		3000				BUNDIG-21197 - New/Renewal Contracts - No Case Created When A1 Rejects
* Jasper R. Galapon     30/06/2023      6000                BUNDIG-22401 / BUNDIG-22402 - New/Renewal Contract / Contract Amendments - Email Notifications
* Jasper R. Galapon		19/10/2023		7000				BUNDIG-26279 - Test Class failures in PROD
******************************************************************************************************/
@isTest
private class SM_Contract_Test {
    @isTest
    private static void updateContractProjectAddress() {
        /**
         * 
        Create 1 account
        Create 2 project with different addresses
        Create 2 project participants linking account 1 with project 1&2 respectively
        Create a contract with same address as project 1
        Test starts:
        Create 1 customer contract linking account 1 with contract
        Expected result: contract’s project is populated correctly
        Change contract’s address to match project 2
        Expected result: contract’s project is updated, and project participants updated
         */
        List<Account> accounts = TestDataFactory.createAccounts(3);
        insert accounts;
        List<Project__c> projects = TestDataFactory.createProject(2);
        projects[0].Project_Address__c = 'A1';
        projects[0].State__c = 'VIC';
        projects[0].Postcode__c = '3000';
        projects[1].Project_Address__c = 'A2';
        projects[1].State__c = 'SA';
        projects[1].Postcode__c = '5000';
        insert projects;
        List<Project_Participant__c> participants = new List<Project_Participant__c>{
            new Project_Participant__c(Account__c = accounts[0].Id, Project__c = projects[0].Id),
            new Project_Participant__c(Account__c = accounts[0].Id, Project__c = projects[1].Id)
        };
        insert participants;
        List<Contract__c> contracts = TestDataFactory.createContracts(1);
        contracts[0].Project_Address__c = 'A1';
        contracts[0].Project_State__c = 'VIC';
        contracts[0].Project_Postcode__c = '3000';
        insert contracts;

        List<Customer_Contract__c> ccs = TestDataFactory.createCustomerContracts(accounts[0].Id, new List<Id>{contracts[0].Id});
        Test.startTest();
        insert ccs;
        System.assertEquals(projects[0].Id, [SELECT Id, Project__c FROM Contract__c WHERE Id = :contracts[0].Id].Project__c, 'Project not set properly.');
        
        contracts[0].Project_Address__c = projects[1].Project_Address__c;
        contracts[0].Project_State__c = projects[1].State__c;
        contracts[0].Project_Postcode__c = projects[1].Postcode__c;
        update contracts;
        System.assertEquals(projects[1].Id, [SELECT Id, Project__c FROM Contract__c WHERE Id = :contracts[0].Id].Project__c, 'Project not updated properly.');

        contracts[0].Project_Address__c = null;
        update contracts;
        System.assertEquals(null, [SELECT Id, Project__c FROM Contract__c WHERE Id = :contracts[0].Id].Project__c, 'Project not set to null.');
        
        contracts[0].Project_Address__c = projects[1].Project_Address__c;
        update contracts;
        System.assertEquals(projects[1].Id, [SELECT Id, Project__c FROM Contract__c WHERE Id = :contracts[0].Id].Project__c, 'Project not updated from null properly.');

        Test.stopTest();

    }
    @isTest
    private static void updateOriginalApproverReviewer() {
        Profile p = [SELECT Id FROM Profile WHERE Name =: Constants.AU_TRADE_SPECIALIST_PROFILEENAME LIMIT 1];
        
        List<User> users = TestDataFactory.createUsers(3, p.Id);
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
		System.runAs (thisUser) {
        	insert users[2];
        	insert users[1];
            users[0].DelegatedApproverId = users[1].Id;
        	insert users[0];
        }
        
        list<Contract__c> contracts = TestDataFactory.createContracts(1);
        contracts[0].Original_Approver__c = users[2].Id;
        contracts[0].Original_Reviewer__c = users[2].Id;
        contracts[0].Approver__c = users[2].Id;
        contracts[0].Reviewer__c = users[2].Id;
        insert contracts;
        
        Test.startTest();
        
        contracts[0].Original_Approver__c = users[0].Id;
        contracts[0].Original_Reviewer__c = users[0].Id;
        update contracts;
        
        Test.stopTest();
        
        Contract__c c = DM_Contract.getContract(contracts[0].Id);
        system.assertEquals(users[1].Id,c.Approver__c,'Contract approver not updated to new original approvers delegated approver');
        system.assertEquals(users[1].Id,c.Reviewer__c,'Contract reviewer not updated to new original reviewers delegated approver');
    }

    @isTest
    private static void testProjectParticipantUpdate() {
        Profile p = [SELECT Id FROM Profile WHERE Name =: Constants.NATIONAL_MANAGER_PROFILEENAME LIMIT 1];
        list<User> users = TestDataFactory.createUsers(1, p.Id);
        users[0].FirstName = 'Bob';
        users[0].LastName = 'Vuksan';
		
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
		System.runAs (thisUser) {
            insert users;
			//insert userSysAd;
        }

        List<Store__c> stores = TestDataFactory.createStores(1);
        stores[0].Engagement_Model__c = 'New';

        insert stores;
            								
        List<Account> accounts = TestDataFactory.createAccounts(1);
        accounts[0].Power_Pass_Account_Number__c = 'Test-1001';
        accounts[0].Home_Store__c = stores[0].Id;

        insert accounts;

        List<Project__c> projects = TestDataFactory.createProject(2);
        projects[0].RecordTypeId = CSUtils.getRecordTypeId('Project__c', 'AU Project');
        projects[1].RecordTypeId = CSUtils.getRecordTypeId('Project__c', 'AU Project');

        insert projects;

        List<Contract__c> contracts = TestDataFactory.createContracts(1);
        contracts[0].RecordTypeId = CSUtils.getRecordTypeId('Contract__c', 'AU Contract');
        contracts[0].Project__c = projects[0].Id;

        insert contracts;

        List<Customer_Contract__c> customerContracts = TestDataFactory.createCustomerContracts(accounts[0].Id, new List<Id>{contracts[0].Id});

        insert customerContracts;

        Test.startTest();

        contracts[0].Project__c = projects[1].Id;
        update contracts;

        List<Project_Participant__c> deassociatedProjectParticipants = DM_ProjectParticipant.getNoContractProjectParticipants(new Set<String>{projects[0].Id}, new Set<String>{accounts[0].Id});
        List<Project_Participant__c> newProjectParticipants = DM_ProjectParticipant.getProjectParticipants(new Set<String>{projects[1].Id}, new Set<String>{accounts[0].Id});

        System.assertEquals(1, deassociatedProjectParticipants.size(), 'Deassociated Project Participant should be 1');
        System.assertEquals(1, newProjectParticipants.size(), 'New Associated Project Participant should be 1');
        System.assertEquals(null, deassociatedProjectParticipants[0].Contract__c, 'Project Participant not deassociated to Contract');
        System.assertEquals(contracts[0].Id, newProjectParticipants[0].Contract__c, 'New Project Participant not linked to Contract');
        System.assertEquals(SM_Contract.PROJECTPARTICIPANT_STATUS_ACTIVE_NOT_ON_CONTRACT, deassociatedProjectParticipants[0].Status__c, 'Deassociated Project Participant Status not updated');
        System.assertEquals(SM_Contract.PROJECTPARTICIPANT_STATUS_ACTIVE_ON_CONTRACT, newProjectParticipants[0].Status__c, 'New Project Participant Status not updated');

        contracts[0].Project__c = null;
        update contracts;

        deassociatedProjectParticipants = DM_ProjectParticipant.getNoContractProjectParticipants(new Set<String>{projects[0].Id, projects[1].Id}, new Set<String>{accounts[0].Id});

        System.assertEquals(2, deassociatedProjectParticipants.size(), 'Deassociated Project Participant should be 2');

        contracts[0].Project__c = projects[0].Id;
        update contracts;
        List<Project_Participant__c> reassociatedProjectParticipants = DM_ProjectParticipant.getProjectParticipants(new Set<String>{projects[0].Id}, new Set<String>{accounts[0].Id});
        System.assertEquals(1, reassociatedProjectParticipants.size(), 'Reassociated Project Participant should be 1');
        System.assertEquals(SM_Contract.PROJECTPARTICIPANT_STATUS_ACTIVE_ON_CONTRACT, reassociatedProjectParticipants[0].Status__c, 'Reassociated Project Participant Status not updated');
        System.assertEquals(contracts[0].Id, reassociatedProjectParticipants[0].Contract__c, 'Reassociated Project Participant not linked to Contract');

        contracts[0].Name = 'Test Name change';
        update contracts;

        List<Project_Participant__c> updatedProjectParticipants = DM_ProjectParticipant.getProjectParticipants(new Set<String>{projects[0].Id}, new Set<String>{accounts[0].Id});
        System.assertEquals(1, updatedProjectParticipants.size(), 'Updated Project Participant should be 1');
        System.assertEquals(SM_Contract.PROJECTPARTICIPANT_STATUS_REQUEST_CONTRACT_CHANGE, updatedProjectParticipants[0].Status__c, 'Updated Project Participant Status not updated');
        System.assertEquals(contracts[0].Id, updatedProjectParticipants[0].Contract__c, 'Updated Project Participant not linked to Contract');

        Test.stopTest();
        
    }
    
    @isTest
    private static void testExceptionsBeforeUpdate() {
        Test.startTest();
        try {
            SM_Contract.beforeUpdate(null, null);
        }catch(Exception e){
            System.assert(TRUE);
        }
        Test.stopTest();
    }
    
    @isTest
    private static void testResetReviewersApprovers() {
        Test.startTest();
        try {
            Profile p = [SELECT Id FROM Profile WHERE Name =: Constants.AU_TRADE_SPECIALIST_PROFILEENAME LIMIT 1];
            
            List<User> users = TestDataFactory.createUsers(3, p.Id);
            User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
            System.runAs (thisUser) {
                insert users[2];
                insert users[1];
                users[0].DelegatedApproverId = users[1].Id;
                insert users[0];
            }
            
            List<Contract__c> contracts = TestDataFactory.createContracts(1);
            contracts[0].Reviewer__c = users[0].Id;
            contracts[0].Approver__c = users[1].Id;
            insert contracts;
            System.debug('***CONTRACT: '+contracts);
            
            Set<Id> userIdSet = new Set<Id>();
            for (User u : [Select Id From User]){
                userIdSet.add(u.Id);
            }
            SM_Contract.resetReviewersApprovers(userIdSet);
            DM_Contract.getContractsbyReviewerApprover(userIdSet);
        }catch(Exception e){
            System.assert(TRUE);
        }
        Test.stopTest();
    }
    
    // BUNDIG-17527
    @isTest
    private static void blockUpdate_Test() {
        Test.startTest();
        	// BUNDIG-26279
            // Id intId = [SELECT Id FROM User WHERE Name = 'Integration User'].Id;
        	Id intId = [SELECT Id FROM User WHERE Name = 'Integration User' AND Profile.Name = 'Integrations User' LIMIT 1].Id;
                    
            SM_Configs__c config = new SM_Configs__c(Integration_User_Id__c = intId);
            insert config;
            
            List<Contract__c> contracts = TestDataFactory.createContracts(1);
            contracts[0].Contract_Approval_Status__c = 'Customer Approved';
            insert contracts;
                    
            User thisUser = [SELECT Id FROM User WHERE Name = 'Integration User' AND Profile.Name = 'Integrations User' LIMIT 1];
           
            System.runAs (thisUser) {
                contracts[0].Contract_Approval_Status__c = 'Pending';
                contracts[0].Reviewer_Action__c = 'A';
                contracts[0].Approver_Action__c = 'A';
                contracts[0].Reviewer_Action_Date__c = Date.today();
                contracts[0].Approver_Action_Date__c = Date.today();
                contracts[0].Reviewer_Comments__c = 'Approved by reviewer';
                contracts[0].Approver_Comments__c = 'Approved by approver';            
                update contracts;                
            }
        Test.stopTest();
    }
    
    // BUNDIG-21197
    @isTest
    private static void testCreateCase() {
        List<Contract__c> contracts = TestDataFactory.createContracts(1);
        contracts[0].Status__c = 'Pending';
        insert contracts;
        
        Test.startTest();
        	contracts[0].Status__c = 'Rejected';
        	update contracts;
        Test.stopTest();
    }
    
    @isTest
    private static void testrenewedContractEmailNotification() {
        Test.startTest();
        	Profile p = [SELECT Id FROM Profile WHERE Name =: Constants.AU_TRADE_SPECIALIST_PROFILEENAME LIMIT 1];            
            List<User> users = TestDataFactory.createUsers(1, p.Id);
        	users[0].isActive = true;
        	users[0].email = 'jasper@test.com.au';
        	System.runAs(new User(Id = UserInfo.getUserId())) {
            	insert users;
            }
        	
        	List<Contract__c> contracts = TestDataFactory.createContracts(1);
        	contracts[0].Contract_Name__c =  'Test Contract';
        	contracts[0].Status__c = 'Pending';
        	contracts[0].Reviewer__c = users[0].Id;
        	contracts[0].Reviewer_Action__c = null;
        	insert contracts;        	
        Test.stopTest();
    }
            
    @isTest
    private static void testcontractEmailNotification() {
        Test.startTest();
        	Profile p = [SELECT Id FROM Profile WHERE Name =: Constants.AU_TRADE_SPECIALIST_PROFILEENAME LIMIT 1];            
            List<User> users = TestDataFactory.createUsers(2, p.Id);
        	users[0].isActive = true;
        	users[1].isActive = true;
        	System.runAs(new User(Id = UserInfo.getUserId())) {
            	insert users;
            }
        
			List<Contract__c> contracts = TestDataFactory.createContracts(1);
        	contracts[0].Contract_Name__c =  'Test Contract';
        	contracts[0].Status__c = 'Draft';
        	contracts[0].Reviewer__c = users[0].Id;
        	contracts[0].Approver__c = users[1].Id;
        	contracts[0].Reviewer_Action__c = null;
        	insert contracts;
        
        	contracts[0].Status__c = 'Pending';
        	update contracts;
        
        	contracts[0].Status__c = 'Reviewed';
        	update contracts;
        
        	contracts[0].Status__c = 'Approved';
        	update contracts;
        
        	contracts[0].Status__c = 'Pending';
        	contracts[0].Approver_Action__c = 'R';
        	update contracts;
        
        	// Test Contract Line Item
        	List<Contract_Line_Item__c> items1 = TestDataFactory.createContractLineItems(contracts[0].Id, Constants.CLI_LINE_TYPE_AMENDMENT, 'A1', null, 1);
        	insert items1;
        
        	List<Contract_Line_Item__c> items2 = TestDataFactory.createContractLineItems(contracts[0].Id, Constants.CLI_LINE_TYPE_AMENDMENT, 'A2', null, 1);
        	insert items2;
        	
        Test.stopTest();
    }
}