unpackaged/main/default/objects/Account/fields/Home_Store__c.field-meta.xml
<CustomField>
    <fullName>Home_Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Home Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Powerpass_Account_Manager__c.field-meta.xml
<CustomField>
    <fullName>Powerpass_Account_Manager__c</fullName>
    <description>This field stores the freetext Account Manager value captured in Power Pass signup </description>
    <label>Powerpass Account Manager</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>Represents all frame and truss plants, small format stores, trade distribution centres and warehouses.</description>
    <label>Store</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Store__c/fields/Location_Code__c.field-meta.xml
<CustomField>
    <fullName>Location_Code__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Location Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Store__c/fields/Operations_Region_Code__c.field-meta.xml
<CustomField>
    <fullName>Operations_Region_Code__c</fullName>
    <description>The store&#39;s operations region code</description>
    <label>Operations Region Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/Location_Code__c.field-meta.xml
<CustomField>
    <fullName>Location_Code__c</fullName>
    <description>Location code that maps to the external ID on the store object</description>
    <label>Location Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/Location_Name__c.field-meta.xml
<CustomField>
    <fullName>Location_Name__c</fullName>
    <description>Name of the location</description>
    <label>Location Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/SM_UpdateSObjectsQueueableTest.cls
/*******************************************************************************************************
* Class Name        : SM_UpdateSObjectsQueueableTest
* Description       : Test class of SM_UpdateSObjectsQueueable
* Author            : Simplus - MS
* Created On        : 09/12/2021
* Modification Log  :
* -----------------------------------------------------------------------------------------------------
* Developer             Date            Modification ID     Description
* -----------------------------------------------------------------------------------------------------
* Simplus - MS          09/12/2021      1000                Initial version
******************************************************************************************************/
@isTest
public class SM_UpdateSObjectsQueueableTest {
    
    @testSetup static void dataSetup() {
        
        List<Store__c> storeList = TestDataFactory.createStores(1);
        storeList[0].Operations_Region_Code__c = 'NSW';
        insert storeList;
        
        Profile p = [SELECT Id FROM Profile WHERE Name =: Constants.AU_TRADE_SPECIALIST_PROFILEENAME LIMIT 1];
        list<User> users = TestDataFactory.createUsers(2, p.Id);
        users[0].Location_Name__c = storeList[0].Name;
        users[1].Location_Code__c = storeList[0].Location_Code__c;

        
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        System.runAs (thisUser) {
            insert users;
        }
                                            
        List<Account> accounts = TestDataFactory.createAccounts(2);
        accounts[0].RecordTypeId = CSUtils.getRecordTypeId('Account', 'AU Customer');
        accounts[0].OwnerId = users[0].ID;
        accounts[0].Home_Store__c = storeList[0].Id;
        accounts[0].Powerpass_Account_Manager__c = 'Test';
        accounts[1].RecordTypeId = CSUtils.getRecordTypeId('Account', 'AU Prospect');
        accounts[1].OwnerId = users[1].ID;
        accounts[1].Home_Store__c = storeList[0].Id;
        accounts[1].Powerpass_Account_Manager__c = 'Test';

        insert accounts;
    }

    static testmethod void testQueueable() {
        // query for test data to pass to queueable class
        List<Account> accounts = [select id, name from account];
        // Create our Queueable instance
        SM_UpdateSObjectsQueueable sObjectspQueueable = new SM_UpdateSObjectsQueueable(accounts,'Test Class', TRUE, 'Account');
        
        Test.startTest();
        System.enqueueJob(sObjectspQueueable);
        system.debug('accounts :: '+accounts);
        Test.stopTest();
    }
}