unpackaged/main/default/objects/Account/fields/On_Contract__c.field-meta.xml
<CustomField>
    <fullName>On_Contract__c</fullName>
    <description>Yes if any of related Contract is Active. No if NONE of any related Contract is Active</description>
    <label>On Contract</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Various contracts associated to customers, projects and umbrellas. Use of custom object in place of standard considering future implementation of CPQ with contract and its line items.</description>
    <label>Contract</label>
    <nameField>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the contract</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Customer_Contract__c/Customer_Contract__c.object-meta.xml
<CustomObject>
    <label>Customer Contract</label>
    <nameField>
        <displayFormat>CC-{00000000}</displayFormat>
        <label>Customer Contract</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Contract__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <description>Contract for customer contract</description>
    <inlineHelpText>Contract for customer contract</inlineHelpText>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Customer Contracts</relationshipLabel>
    <relationshipName>Customer_Contracts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/AccountOnContractUpdate_Test.cls
/*******************************************************************************************************
* Class Name      	: AccountOnContractUpdate_Test
* Description		: Test class for AccountOnContractUpdate
* Author          	: Simplus - Francis Benzon
* Created On      	: 04/06/2020
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Francis Benzon        04/06/2020		1000				Initial version
******************************************************************************************************/
@isTest
public with sharing class AccountOnContractUpdate_Test {
    @isTest
    public static void testContractActivation() {
        
        List<Account> accounts = TestDataFactory.createAccounts(1);
        accounts[0].On_Contract__c = Label.No;
        insert accounts;
        
        List<Contract__c> contracts = TestDataFactory.createContracts(1);
        contracts[0].Status__c = Label.Active;
        insert contracts;
        
        List<Customer_Contract__c> customerConList = TestDataFactory.createCustomerContracts(accounts[0].ID, new List<ID> {contracts[0].ID});
        insert customerConList; 

        Test.startTest();
        
        AccountOnContractUpdate.pbInputs argument;
        argument = new AccountOnContractUpdate.pbInputs();
        argument.accountSObj = accounts[0];
        argument.objectName = Label.CustomerContract;

        AccountOnContractUpdate.checkInvokeSourceObject(
            new List<AccountOnContractUpdate.pbInputs>{ argument }
        );
        
        //System.AssertEquals('Yes', accounts[0].On_Contract__c);
        
        
        contracts[0].Status__c = 'Expired';
        update contracts;
        
        AccountOnContractUpdate.pbInputs argument1;
        argument1 = new AccountOnContractUpdate.pbInputs();
        argument1.contractSObj = contracts[0];
        argument1.objectName = Label.Contract;

        AccountOnContractUpdate.checkInvokeSourceObject(
            new List<AccountOnContractUpdate.pbInputs>{ argument1 }
        );
        
        
        //System.AssertEquals('No', accounts[0].On_Contract__c);
        
        
        contracts[0].Status__c = 'Active';
        update contracts;
        
        AccountOnContractUpdate.pbInputs argument2;
        argument2 = new AccountOnContractUpdate.pbInputs();
        argument2.contractSObj = contracts[0];
        argument2.objectName = Label.Contract;

        AccountOnContractUpdate.checkInvokeSourceObject(
            new List<AccountOnContractUpdate.pbInputs>{ argument2 }
        );
        
        
        //System.AssertEquals('Yes', accounts[0].On_Contract__c);
        
        Test.stopTest();
    }
}