unpackaged/main/default/objects/Account/fields/On_Contract__c.field-meta.xml
<CustomField>
    <fullName>On_Contract__c</fullName>
    <description>Yes if any of related Contract is Active. No if NONE of any related Contract is Active</description>
    <label>On Contract</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Various contracts associated to customers, projects and umbrellas. Use of custom object in place of standard considering future implementation of CPQ with contract and its line items.</description>
    <label>Contract</label>
    <nameField>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the contract</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Customer_Contract__c/Customer_Contract__c.object-meta.xml
<CustomObject>
    <label>Customer Contract</label>
    <nameField>
        <displayFormat>CC-{00000000}</displayFormat>
        <label>Customer Contract</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Contract__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <description>Contract for customer contract</description>
    <inlineHelpText>Contract for customer contract</inlineHelpText>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Customer Contracts</relationshipLabel>
    <relationshipName>Customer_Contracts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/DM_CustomerContract_Test.cls
/*******************************************************************************************************
* Class Name      	: DM_CustomerContract_Test
* Description		: Test class for DM_CustomerContract
* Author          	: Simplus - Yi Zhang
* Created On      	: 2020-06-15
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Yi Zhang              2020-06-15		1000				Initial version
* Simplus MS            2021-01-04      1001                CCRM-170 - Changes made to cover the DM_CustomerContract methods.
******************************************************************************************************/
@isTest
public class DM_CustomerContract_Test {
    
    /**
    * @description - New changes made to cover the DM_CustomerContract methods
    * @author Simplus MS | 25/01/2021 
    **/
    @isTest
    public static void testGetCustomerContracts() {

        List<Account> accounts = TestDataFactory.createAccounts(1);
        accounts[0].On_Contract__c = Label.No;
        insert accounts;
        
        List<Contract__c> contracts = TestDataFactory.createContracts(1);
        contracts[0].Status__c = Label.Active;
        insert contracts;
        
        List<Customer_Contract__c> customerConList = TestDataFactory.createCustomerContracts(accounts[0].ID, new List<ID> {contracts[0].ID});
        insert customerConList; 

        Profile p_lcm = [SELECT Id FROM Profile WHERE Name =: Constants.AU_LIGHT_COMMERCIAL_MANAGER_PROFILEENAME LIMIT 1];
		List<User> user_lcm = TestDataFactory.createUsers(1, p_lcm.Id);
		
        User thisUser_lcm = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
		System.runAs (thisUser_lcm) {
            insert user_lcm;
        }

        Set<Id> ownerIds = new Set<Id>();
        for(User u : user_lcm){
            ownerIds.add(u.Id);
        }

        Set<Id> acctIds = new Set<Id>();
        Set<String> contractIds = new Set<String>();

        for(Account a : accounts){
            acctIds.add(a.Id);
        }

        for(Customer_Contract__c cc : customerConList){
            contractIds.add(cc.Id);
        }
        
        Test.startTest();
        System.assertEquals(0, DM_CustomerContract.getNonExpiredCustomerContracts(null).size(), 'no customer contract created, no customer contract retrieved');
        System.assertEquals(0, DM_CustomerContract.getNonExpiredCustomerContracts(new Set<Id>{null}, new Set<Id>{null}).size(), 'no customer contract created, no customer contract retrieved');
        
        DM_CustomerContract.getCustomerContracts(accounts[0].Id);
        DM_CustomerContract.getNonExpiredCustContracts(acctIds, ownerIds);
        DM_CustomerContract.getNonExpiredCustomerContracts(accounts[0].Id);
        DM_CustomerContract.getCustomerContracts(contractIds);

        Test.stopTest();

    }
}