unpackaged/main/default/objects/Account/fields/Operations_Region__c.field-meta.xml
<CustomField>
    <fullName>Operations_Region__c</fullName>
    <description>The operations region code from assigned store</description>
    <formula>Assigned_Store__r.Operations_Region_Code__c</formula>
    <label>Assigned Region</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Spend_Band__c.field-meta.xml
<CustomField>
    <fullName>Spend_Band__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Spend Band for the Account</description>
    <label>Spend Band</label>
    <referenceTo>Spend_Band__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account_Group__c/Account_Group__c.object-meta.xml
<CustomObject>
    <description>This object is to assist the reporting of a group of accounts.</description>
    <label>Account Group</label>
    <nameField>
        <label>Account Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ApplicationLog__c/ApplicationLog__c.object-meta.xml
<CustomObject>
    <description>Object that contains unhandled exception errors &amp; outbound message</description>
    <label>Application Log</label>
    <nameField>
        <displayFormat>Log-{000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Assisted_Sales__c/Assisted_Sales__c.object-meta.xml
<CustomObject>
    <description>Assisted sales by team members for a customer based on sales from a specific store.</description>
    <label>Assisted Sale</label>
    <nameField>
        <displayFormat>Sale-{0000000}</displayFormat>
        <label>Assisted Sales Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assisted Sales</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Call_Plan_Leave__c/Call_Plan_Leave__c.object-meta.xml
<CustomObject>
    <description>Leaves taken by AMs to pause and adjust their planned call targets.</description>
    <label>Call Plan Leave</label>
    <nameField>
        <displayFormat>CPL-{0000}</displayFormat>
        <label>Call Plan Leave ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Plan Leave</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Call_Targets__c/Call_Targets__c.object-meta.xml
<CustomObject>
    <description>Call targets for Account Managers.</description>
    <label>Call Targets</label>
    <nameField>
        <displayFormat>CT-{000}</displayFormat>
        <label>Call Target ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Case/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used for Project Contract Request Cases</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Various contracts associated to customers, projects and umbrellas. Use of custom object in place of standard considering future implementation of CPQ with contract and its line items.</description>
    <label>Contract</label>
    <nameField>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Contract__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Associated Project</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Family_Tree_Discount__c/Family_Tree_Discount__c.object-meta.xml
<CustomObject>
    <description>This Object represents a discount structure mastered by an external system. The discount is applied to all products within externally defined product categories.</description>
    <label>Family Tree Discount</label>
    <nameField>
        <label>Family Tree Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Family Tree Discount</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Lead/fields/Umbrella_Group__c.field-meta.xml
<CustomField>
    <fullName>Umbrella_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Umbrella Group</description>
    <label>Umbrella Group</label>
    <referenceTo>Umbrella_Group__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Operations_Region__c/Operations_Region__c.object-meta.xml
<CustomObject>
    <description>Maps operation region with their corresponding roles.</description>
    <label>Operations Region Role</label>
    <nameField>
        <label>Operations Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Operations Region Roles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Associated project for this Opportunity</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Post_Code__c/Post_Code__c.object-meta.xml
<CustomObject>
    <description>This object is used for Lead and Project Ownership assignment; When Run_Postcode_Assignment__c is checked and the Suburb and Postcode of the relevant object/record matches the Suburb and Postcode of a record for this object, the Owner of the Post Code record is set as the owner of the other record.</description>
    <label>Postcode</label>
    <nameField>
        <label>Postcode</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Postcodes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Price_List__c/Price_List__c.object-meta.xml
<CustomObject>
    <description>This Object represents the header level of an externally mastered pricing table, which applies item level discounts for a pre-defined list of products within specific Cost Zones.</description>
    <label>Price List</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Price List Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Price_List__c/fields/Price_List_Definition__c.field-meta.xml
<CustomField>
    <fullName>Price_List_Definition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Price List Definition</description>
    <label>Price List Definition</label>
    <referenceTo>Price_List_Definition__c</referenceTo>
    <relationshipLabel>Price Lists</relationshipLabel>
    <relationshipName>Price_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Price_List__c/fields/Spend_Band__c.field-meta.xml
<CustomField>
    <fullName>Spend_Band__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Spend Band</label>
    <referenceTo>Spend_Band__c</referenceTo>
    <relationshipLabel>Price Lists</relationshipLabel>
    <relationshipName>Price_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Price_List_Definition__c/Price_List_Definition__c.object-meta.xml
<CustomObject>
    <label>Price List Definition</label>
    <nameField>
        <displayFormat>PLD-{000000}</displayFormat>
        <label>Price List Definition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price List Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Price_List_Definition__c/fields/Spend_Band__c.field-meta.xml
<CustomField>
    <fullName>Spend_Band__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Associated spend band</description>
    <label>Spend Band</label>
    <referenceTo>Spend_Band__c</referenceTo>
    <relationshipLabel>Price List Definitions</relationshipLabel>
    <relationshipName>Price_List_Definitions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Pricing_Assignment_Visibility__c/Pricing_Assignment_Visibility__c.object-meta.xml
<CustomObject>
    <description>This Object controls the visibility of Price Lists and Family Tree Discount records on the Accounts &quot;Pricing Assignment&quot; flow component. Each record makes one Price List or Family Tree Discount record visible for a single Profile.</description>
    <label>Pricing Assignment Visibility</label>
    <nameField>
        <displayFormat>PAV-{00000}</displayFormat>
        <label>Pricing Assignment Visibility Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricing Assignment Visibility</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Pricing_Assignment_Visibility__c/fields/Family_Tree_Discount__c.field-meta.xml
<CustomField>
    <fullName>Family_Tree_Discount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Family Tree Discount</label>
    <referenceTo>Family_Tree_Discount__c</referenceTo>
    <relationshipLabel>Pricing Assignment Viisbility</relationshipLabel>
    <relationshipName>Pricing_Assignment_Viisbility</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Pricing_Assignment_Visibility__c/fields/Price_List__c.field-meta.xml
<CustomField>
    <fullName>Price_List__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Price list considered for visibility</description>
    <label>Price List</label>
    <referenceTo>Price_List__c</referenceTo>
    <relationshipName>Price_List_Viisbility</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Pricing_Assignment_Visibility__c/fields/Price_List_Definition__c.field-meta.xml
<CustomField>
    <fullName>Price_List_Definition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Setting visbility based on the definition of the pice list</description>
    <label>Price List Definition</label>
    <referenceTo>Price_List_Definition__c</referenceTo>
    <relationshipLabel>Pricing Assignment Visibility</relationshipLabel>
    <relationshipName>Pricing_Assignment_Visbility</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product_Sub_Department__c/Product_Sub_Department__c.object-meta.xml
<CustomObject>
    <description>Master Detail of Category Assist Object and related to Assisted Sales</description>
    <label>Product Sub Department</label>
    <nameField>
        <label>Sub Department</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Sub Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>This object is used for grouping Opportunities related to a single construction project.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Sales_Rep__c/Sales_Rep__c.object-meta.xml
<CustomObject>
    <description>Bunnings&#39; Sales Rep ID assigned to team members and stores for attribution. This is based from a legacy definition of sales rep hierrachy and ids.</description>
    <label>Sales Rep</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Sales Rep ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Rep</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Sales_Rep_Sales_Summary__c/Sales_Rep_Sales_Summary__c.object-meta.xml
<CustomObject>
    <description>Team member&#39;s actual and budget summaries</description>
    <label>Sales Rep Sales Summary</label>
    <nameField>
        <displayFormat>SS-{0000000000}</displayFormat>
        <label>Sales Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Rep Sales Summaries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Segment__c/Segment__c.object-meta.xml
<CustomObject>
    <description>The segment of the account/lead. Contains the secondary and primary segment names.</description>
    <label>Segment</label>
    <nameField>
        <label>Secondary</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Special_Buy__c/Special_Buy__c.object-meta.xml
<CustomObject>
    <description>This Object is a header representation of an external pricing table, used to group a number of Special Buy Lines (Products purchased for a non-standard Cost Price) purchased from a single supplier</description>
    <label>Special Buy</label>
    <nameField>
        <label>Special Buy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Special Buys</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Spend_Band__c/Spend_Band__c.object-meta.xml
<CustomObject>
    <description>Spend band ranges for customers.</description>
    <label>Spend Band</label>
    <nameField>
        <label>Spend Band</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spend Bands</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Spend_Band_Review__c/Spend_Band_Review__c.object-meta.xml
<CustomObject>
    <description>This Object represents the Spend Band Review table mastered in the Commercial Pricing System (CPS). CPS is the master of the Spend Band review data, Salesforce owns the Spend Band Review approval process.</description>
    <label>Spend Band Review</label>
    <nameField>
        <displayFormat>SBR-{0000000}</displayFormat>
        <label>Review Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Spend Band Reviews</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>Represents all frame and truss plants, small format stores, trade distribution centres and warehouses.</description>
    <label>Store</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Umbrella_Group__c/Umbrella_Group__c.object-meta.xml
<CustomObject>
    <description>This is used to represent the parent/owner of a group of affiliated Accounts operating within the same Industry/segment that have grouped together for increased purchasing power and pricing leverage.</description>
    <label>Umbrella Group</label>
    <nameField>
        <displayFormat>UG-{00000}</displayFormat>
        <label>Umbrella Group Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Umbrella Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/classes/SM_DeleteAllBatch.cls
//************************************************************************************************ */
// Important Note  - This class should not be deployed to Production. This is an interim solution
//                   to purge data as needed for regression testing.
//
// Notes for Admin - Have this as a class when ever you need to delete all data for testing. 
//                   Execute the batch job from developer console.
//                   Developer Console -> Execute Anonymous -> Paste the following :
//
//                   Id batchJobId = Database.executeBatch(new SM_DeleteAllBatch(), 2000);
//
// Author : Purba Ghosh | Date : 25-09-2020
//************************************************************************************************ */
global class SM_DeleteAllBatch implements Database.Batchable<sObject>, Schedulable {

    // Initialisations
	String countQuery;
    String query;
	String objName;
	Integer objectSerialNo;
	Integer totalRecords;
	Map<Integer,String> objectOrderMap = new Map<Integer,String>();

    // Constructor
    global SM_DeleteAllBatch() {
	
		this.objectSerialNo = 1;
        
        // Please include standalone objects as Detail object records 
        // get deleted when their Masters get deleted. Please remember 
        // dependency order while adding to the map as you can not  
        // delete a record which is deemed mandatory by another record.
		objectOrderMap.put(1,'Store__c');
		objectOrderMap.put(2,'Operations_Region__c');
		objectOrderMap.put(3,'Sales_Rep__c');
		objectOrderMap.put(4,'Sales_Rep_Sales_Summary__c');
		objectOrderMap.put(5,'Segment__c');
		objectOrderMap.put(6,'Pricing_Assignment_Visibility__c');
		objectOrderMap.put(7,'Price_List__c');
		objectOrderMap.put(8,'Price_List_Definition__c');
		objectOrderMap.put(9,'Family_Tree_Discount__c');
		objectOrderMap.put(10,'Special_Buy__c');
		objectOrderMap.put(11,'Project__c');
		objectOrderMap.put(12,'Contract__c');
		objectOrderMap.put(13,'Spend_Band_Review__c');
		objectOrderMap.put(14,'Spend_Band__c');
		objectOrderMap.put(15,'Umbrella_Group__c');
		objectOrderMap.put(16,'Campaign');
		objectOrderMap.put(17,'Call_Plan_Leave__c');
		objectOrderMap.put(18,'Call_Targets__c');
		objectOrderMap.put(19,'Assisted_Sales__c');
		objectOrderMap.put(20,'Product_Sub_Department__c');
		objectOrderMap.put(21,'Lead');
		objectOrderMap.put(22,'Post_Code__c');
		objectOrderMap.put(23,'Opportunity');
        objectOrderMap.put(24,'Case');
        objectOrderMap.put(25,'Task');
		objectOrderMap.put(26,'Event');
		objectOrderMap.put(27,'Contact');
		objectOrderMap.put(28,'Account_Group__c');
		objectOrderMap.put(29,'Account');
		objectOrderMap.put(30,'ApplicationLog__c');
		
		objName = objectOrderMap.get(objectSerialNo);
		query = 'SELECT Id FROM ' + objName;
    }
    
    // Parameterised Constructor for subsequent batch invocations
	global SM_DeleteAllBatch(Integer objectSerialNo, Map<Integer,String> objectOrderMap) {
        this.objectSerialNo = objectSerialNo;
        this.objectOrderMap = objectOrderMap;
        
		objName = objectOrderMap.get(objectSerialNo);
		query = 'SELECT Id FROM ' + objName;
	}

    // Batch start method to query scope
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }

    // Batch execute method to delete the queried scope of records
    public void execute(Database.BatchableContext BC, List<sObject> scope) {
		Delete scope;
    }
 
    // Batch finish method to trigger any further invocations of the same
    public void finish(Database.BatchableContext BC) {
        countQuery = 'SELECT Count() FROM ' + objName;
        totalRecords = Database.countQuery(countQuery);
        
		if(totalRecords == 0 ) {
			objectSerialNo++;
        }
        
        if(objectOrderMap.containsKey(objectSerialNo)) {
            Database.executeBatch(new SM_DeleteAllBatch(objectSerialNo,objectOrderMap), 2000);
        }
    }

    // Batch execute method for scheduling if needed
    public void execute(SchedulableContext SC) {
        Database.executeBatch(new SM_DeleteAllBatch(), 2000);
    }
}