unpackaged/main/default/objects/Account/fields/Operations_Region__c.field-meta.xml
<CustomField>
    <fullName>Operations_Region__c</fullName>
    <description>The operations region code from assigned store</description>
    <formula>Assigned_Store__r.Operations_Region_Code__c</formula>
    <label>Assigned Region</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Operations_Region__c/Operations_Region__c.object-meta.xml
<CustomObject>
    <description>Maps operation region with their corresponding roles.</description>
    <label>Operations Region Role</label>
    <nameField>
        <label>Operations Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Operations Region Roles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>Represents all frame and truss plants, small format stores, trade distribution centres and warehouses.</description>
    <label>Store</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Store__c/fields/Operations_Region_Code__c.field-meta.xml
<CustomField>
    <fullName>Operations_Region_Code__c</fullName>
    <description>The store&#39;s operations region code</description>
    <label>Operations Region Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Umbrella_Beneficiary__c/Umbrella_Beneficiary__c.object-meta.xml
<CustomObject>
    <description>This object is for capturing an Accounts membership to an Umbrella Group.</description>
    <label>Umbrella Beneficiary</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Umbrella Beneficiaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Umbrella_Beneficiary__c/fields/Umbrella_Group__c.field-meta.xml
<CustomField>
    <fullName>Umbrella_Group__c</fullName>
    <description>A lookup to the related Umbrella Group.</description>
    <label>Umbrella Group</label>
    <referenceTo>Umbrella_Group__c</referenceTo>
    <relationshipLabel>Umbrella Beneficiaries</relationshipLabel>
    <relationshipName>Umbrella_Beneficiaries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Umbrella_Group__c/Umbrella_Group__c.object-meta.xml
<CustomObject>
    <description>This is used to represent the parent/owner of a group of affiliated Accounts operating within the same Industry/segment that have grouped together for increased purchasing power and pricing leverage.</description>
    <label>Umbrella Group</label>
    <nameField>
        <displayFormat>UG-{00000}</displayFormat>
        <label>Umbrella Group Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Umbrella Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/classes/TopicAssignmentTriggerTest.cls
/*******************************************************************************************************
* Class Name      	: TopicAssignmentTriggerTest
* Description		: Topic Assignment trigger test
* Author          	: Simplus - Francis Benzon
* Created On      	: 24/06/2020
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Francis Benzon        24/06/2020		1000				Initial version
******************************************************************************************************/
@IsTest
private class TopicAssignmentTriggerTest {
    /**
    *  Method name  :  dataSetup
    *  Description  :  Setup data for test class
    *  Author       :  Francis Benzon
    **/
    @testSetup static void dataSetup() {
		//create Umbrella groups
		List<Umbrella_Group__c> ugList = TestDataFactory.createUmbrellaGroups(1);
		insert ugList;
		
		//create Account
		List<Account> acctList = TestDataFactory.createAccounts(1);
		insert acctList;
		
		//create Umbrella Beneficiries
		List<Umbrella_Beneficiary__c> ubList = TestDataFactory.createUmbrellaBeneficiaries(acctList[0].ID, ugList[0].ID, 1);
		insert ubList;
		
		//create Umbrella Beneficiries
		List<Topic> topicList = TestDataFactory.createTopics(1);
        topicList[0].Name = 'Test' + String.valueOf(Math.random());
		insert topicList;
		
		Profile p = [SELECT Id FROM Profile WHERE Name =: Constants.AU_TRADE_SPECIALIST_PROFILEENAME LIMIT 1];
		list<User> users = TestDataFactory.createUsers(2, p.Id);
        
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
		System.runAs (thisUser) {
            insert users;
        }
            
        List<Store__c> storeList = TestDataFactory.createStores(1);
        storeList[0].Operations_Region_Code__c = 'NSW';
        insert storeList;

		Operations_Region__c newOR = TestDataFactory.createOperationsRegion(storeList[0].Operations_Region_Code__c, null, null);
		insert newOR;
		
    }

    @IsTest
    static void testBehavior() {
        ID umbrellaGroupID = [SELECT ID FROM Umbrella_Group__c].ID;
		ID recTopicID = [SELECT ID FROM Topic].ID;
		ID orID = [SELECT ID FROM Operations_Region__c].ID;
		List<TopicAssignment> taList = new List<TopicAssignment>();

        Test.startTest();
        
		//create topic for Umbrella Group 
		TopicAssignment ta = new TopicAssignment();
		ta.EntityId = umbrellaGroupID; 
		ta.topicId = recTopicID;

        taList.add(ta);
		
		
		TopicAssignment ta1 = new TopicAssignment();
		ta1.EntityId = orID; 
		ta1.topicId = recTopicID;

        taList.add(ta1);
		
		insert taList;
		System.assert(taList.size() == 2);
		
		delete taList;
		
        Test.stopTest();

    }
}