unpackaged/main/default/objects/Account/fields/PL_FTD_Summary__c.field-meta.xml
<CustomField>
    <fullName>PL_FTD_Summary__c</fullName>
    <description>A summary of PLs and FTDs for NZ prospect</description>
    <label>PL/FTD Summary</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Pricing_Assignment_Status__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Assignment_Status__c</fullName>
    <label>Pricing Assignment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manager Actioned</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Actioned</fullName>
                <isActive>false</isActive>
                <label>Actioned</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Proposed_Spend_Band__c.field-meta.xml
<CustomField>
    <fullName>Proposed_Spend_Band__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proposed Spend Band</label>
    <referenceTo>Spend_Band__c</referenceTo>
    <relationshipLabel>Accounts (Proposed Spend Band)</relationshipLabel>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Record_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_Name__c</fullName>
    <description>Name of the record type</description>
    <formula>RecordType.DeveloperName</formula>
    <inlineHelpText>Name of the record type</inlineHelpText>
    <label>Record Type Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Spend_Band__c.field-meta.xml
<CustomField>
    <fullName>Spend_Band__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Spend Band for the Account</description>
    <label>Spend Band</label>
    <referenceTo>Spend_Band__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Customer_Family_Tree_Discount__c/Customer_Family_Tree_Discount__c.object-meta.xml
<CustomObject>
    <description>Junction between Family Tree Discounts and the Customers</description>
    <label>Customer Family Tree Discount</label>
    <nameField>
        <displayFormat>CFD-{0000000000}</displayFormat>
        <label>Customer Family Tree Discount Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Family Tree Discounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Family_Tree_Discount__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Family Tree Discounts</relationshipLabel>
    <relationshipName>Customer_Family_Tree_Discounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Customer_Family_Tree_Discount__c/fields/Family_Tree_Discount__c.field-meta.xml
<CustomField>
    <fullName>Family_Tree_Discount__c</fullName>
    <label>Family Tree Discount</label>
    <referenceTo>Family_Tree_Discount__c</referenceTo>
    <relationshipLabel>Customer Family Tree Discounts</relationshipLabel>
    <relationshipName>Customer_Family_Tree_Discounts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Customer_Price_List__c/Customer_Price_List__c.object-meta.xml
<CustomObject>
    <description>Junction between Price List and Customers</description>
    <label>Customer Price List</label>
    <nameField>
        <displayFormat>CPL-{0000000000}</displayFormat>
        <label>Customer Price List Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Price Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Price_List__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>The customer</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Price Lists</relationshipLabel>
    <relationshipName>Customer_Price_Lists</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Customer_Price_List__c/fields/Price_List__c.field-meta.xml
<CustomField>
    <fullName>Price_List__c</fullName>
    <description>The price list</description>
    <label>Price List</label>
    <referenceTo>Price_List__c</referenceTo>
    <relationshipLabel>Customer Price Lists</relationshipLabel>
    <relationshipName>Customer_Price_Lists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Customer_Price_List__c/fields/Price_List_Name__c.field-meta.xml
<CustomField>
    <fullName>Price_List_Name__c</fullName>
    <formula>Price_List__r.Price_List_Name__c</formula>
    <label>Price List Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Customer_Price_List__c/fields/Pricing_Assignment_Status__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Assignment_Status__c</fullName>
    <label>Pricing Assignment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Assignment Approval</fullName>
            </value>
            <value>
                <fullName>Pending Removal Approval</fullName>
            </value>
            <value>
                <fullName>Submitted to CPS</fullName>
            </value>
            <value>
                <fullName>CPS Submission Failure</fullName>
            </value>
            <value>
                <fullName>CPS Approved</fullName>
            </value>
            <value>
                <fullName>Manager Actioned</fullName>
                <isActive>false</isActive>
                <label>Manager Actioned</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Customer_Price_List__c/fields/Spend_Band__c.field-meta.xml
<CustomField>
    <fullName>Spend_Band__c</fullName>
    <formula>Price_List__r.Spend_Band__r.Name</formula>
    <label>Spend Band</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Customer_Price_List__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This field determines whether a Price List is active (checked) or In active (unchecked) for the related Customer.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Family_Tree_Discount__c/Family_Tree_Discount__c.object-meta.xml
<CustomObject>
    <description>This Object represents a discount structure mastered by an external system. The discount is applied to all products within externally defined product categories.</description>
    <label>Family Tree Discount</label>
    <nameField>
        <label>Family Tree Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Family Tree Discount</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Price_List__c/Price_List__c.object-meta.xml
<CustomObject>
    <description>This Object represents the header level of an externally mastered pricing table, which applies item level discounts for a pre-defined list of products within specific Cost Zones.</description>
    <label>Price List</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Price List Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Price_List__c/fields/Price_List_Name__c.field-meta.xml
<CustomField>
    <fullName>Price_List_Name__c</fullName>
    <description>Price List Names can be up to 100 chars</description>
    <label>Price List Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Price_List__c/fields/Spend_Band__c.field-meta.xml
<CustomField>
    <fullName>Spend_Band__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Spend Band</label>
    <referenceTo>Spend_Band__c</referenceTo>
    <relationshipLabel>Price Lists</relationshipLabel>
    <relationshipName>Price_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Price_List__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Price List</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Spend_Band__c/Spend_Band__c.object-meta.xml
<CustomObject>
    <description>Spend band ranges for customers.</description>
    <label>Spend Band</label>
    <nameField>
        <label>Spend Band</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spend Bands</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/classes/AccountsPriceListsFamilyTree.cls
/*******************************************************************************************************
* Class Name      	: AccountsPriceListsFamilyTree
* Description		: Controller for AccountsForApproval component
* Author          	: Simplus - Francis Benzon
* Created On      	: 06/03/2020
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Francis Benzon        06/03/2020		1000				Initial version
* Francis Benzon        12/05/2020		2000				Tracked with update Pricing Assignment
******************************************************************************************************/
global without sharing class AccountsPriceListsFamilyTree{
    
    String cpsApproved = System.Label.CPSApproved;
    String inActive = System.Label.Inactive;
    String active = System.Label.Active;    
    
    global String accountId{get;set;}
    
    global Account account{
        get {
            account = [Select Id, Name, Country__c, Spend_Band__c, Spend_Band__r.Name, 
                        Proposed_Spend_Band__r.Name, Proposed_Spend_Band__c, PL_FTD_Summary__c, Record_Type_Name__c
                        FROM Account where ID =: accountId];
            return account; 
        }
       set;
    }
    
    global List<Price_List__c> priceLists {
        get {
            priceLists = new List<Price_List__c>();
			Set<String> pricingStatusSet = new Set<String>{cpsApproved, 'Pending Removal Approval'};
                    
            List<Price_List__c> plLst = new List<Price_List__c>();
            plLst = [SELECT Id, Name, Price_List_Name__c  
                        FROM Price_List__c 
                        WHERE ID IN (SELECT Price_List__c FROM Customer_Price_List__c 
                        WHERE Account__c = :accountId 
                        AND Pricing_Assignment_Status__c NOT IN :pricingStatusSet
                        AND Status__c = :inActive)];
                      
            if(!plLst.isEmpty()) {
                for(Price_List__c pl : plLst) {
                    priceLists.add(pl);
                }                               
            }
            return priceLists;          
        }
        set;
    }

    global List<Price_List__c> forRemovalPriceList {
        get {
            forRemovalPriceList = new List<Price_List__c>();
			Set<String> pricingStatusSet = new Set<String>{ 'Pending Removal Approval'};
                    
            List<Price_List__c> plLst = new List<Price_List__c>();
            plLst = [SELECT Id, Name, Price_List_Name__c  
                        FROM Price_List__c 
                        WHERE ID IN (SELECT Price_List__c FROM Customer_Price_List__c 
                        WHERE Account__c = :accountId 
                        AND Pricing_Assignment_Status__c IN :pricingStatusSet
                        AND Status__c = :active)];
                      
            if(!plLst.isEmpty()) {
                for(Price_List__c pl : plLst) {
                    forRemovalPriceList.add(pl);
                }                               
            }
            return forRemovalPriceList;          
        }
        set;
    }

    global String prospectPricing{
        get{
            prospectPricing = account.PL_FTD_Summary__c;
            return prospectPricing;
        }
        set;
    }
    
    global List<Price_List__c> currentPriceLists {
        get {
            currentPriceLists = new List<Price_List__c>();
                       
            List<Price_List__c> currentPList = new List<Price_List__c>();
            currentPList = [SELECT Id, Name, Price_List_Name__c
                        FROM Price_List__c 
                        WHERE ID IN (SELECT Price_List__c FROM Customer_Price_List__c 
                        WHERE Account__c = :accountId
                        AND Status__c = :active)];
            
            if(!currentPList.isEmpty()) {
                for(Price_List__c pl : currentPList) {
                    currentPriceLists.add(pl);
                }                               
            }
            return currentPriceLists;          
        }
        set;
    }
    
    
    global List<Family_Tree_Discount__c> famTreeDisc {
        get {
            famTreeDisc = new List<Family_Tree_Discount__c>();
            Set<String> pricingStatusSet = new Set<String>{cpsApproved, 'Pending Removal Approval'};
            
            List<Family_Tree_Discount__c> famTreeLst = new List<Family_Tree_Discount__c>();
            famTreeLst = [SELECT Id, Name FROM Family_Tree_Discount__c 
                            WHERE ID IN (SELECT Family_Tree_Discount__c FROM Customer_Family_Tree_Discount__c
                            WHERE Account__c = :accountId 
                            AND Pricing_Assignment_Status__c NOT IN: pricingStatusSet
                            AND Status__c = :inActive)];
 
            if(!famTreeLst.isEmpty()) { 
                for(Family_Tree_Discount__c ftd : famTreeLst) {
                    famTreeDisc.add(ftd);
                }                               
            }
            return famTreeDisc;         
        }
        set;
    }

    global List<Family_Tree_Discount__c> forRemovalFamilyTreeDiscount {
        get {
            forRemovalFamilyTreeDiscount = new List<Family_Tree_Discount__c>();
            Set<String> pricingStatusSet = new Set<String>{'Pending Removal Approval'};
            
            List<Family_Tree_Discount__c> famTreeLst = new List<Family_Tree_Discount__c>();
            famTreeLst = [SELECT Id, Name FROM Family_Tree_Discount__c 
                            WHERE ID IN (SELECT Family_Tree_Discount__c FROM Customer_Family_Tree_Discount__c
                            WHERE Account__c = :accountId 
                            AND Pricing_Assignment_Status__c IN: pricingStatusSet
                            AND Status__c = :active)];
 
            if(!famTreeLst.isEmpty()) { 
                for(Family_Tree_Discount__c ftd : famTreeLst) {
                    forRemovalFamilyTreeDiscount.add(ftd);
                }                               
            }
            return forRemovalFamilyTreeDiscount;         
        }
        set;
    }
    
    global List<Family_Tree_Discount__c> activeFamTreeDisc {   
        get {
            activeFamTreeDisc = new List<Family_Tree_Discount__c>();
            
            List<Family_Tree_Discount__c> famTreeLst = new List<Family_Tree_Discount__c>();
            famTreeLst = [SELECT Id, Name FROM Family_Tree_Discount__c 
                            WHERE ID IN (SELECT Family_Tree_Discount__c FROM Customer_Family_Tree_Discount__c
                            WHERE Account__c = :accountId 
                            AND Status__c = :active)];
 
            if(!famTreeLst.isEmpty()) { 
                for(Family_Tree_Discount__c ftd : famTreeLst) {
                    activeFamTreeDisc.add(ftd);
                }                               
            }
            return activeFamTreeDisc;         
        }
        set;
    }
    
    
    global  AccountsPriceListsFamilyTree() {
        //constructor
    }
    
     global String NewLine {
        get { return '\r\n'; }
        set;
    }
            
}