unpackaged/main/default/objects/Account/fields/Power_Pass_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Power_Pass_Account_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Power Pass Account Number</label>
    <length>32</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Customer_Price_List__c/Customer_Price_List__c.object-meta.xml
<CustomObject>
    <description>Junction between Price List and Customers</description>
    <label>Customer Price List</label>
    <nameField>
        <displayFormat>CPL-{0000000000}</displayFormat>
        <label>Customer Price List Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Price Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Price_List__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>The customer</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Price Lists</relationshipLabel>
    <relationshipName>Customer_Price_Lists</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Customer_Price_List__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Customer Price Lists End Date</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Customer_Price_List__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Customer Price Lists Start Date</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Customer_Price_List__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This field determines whether a Price List is active (checked) or In active (unchecked) for the related Customer.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/cplDeleteTempQueueable.cls
/*******************************************************************************************************
* Class Name        : cplDeleteTempQueueable
* Description       : Delete Customer Price List Temp Record
* Author            : Jasper R. Galapon
* Created On        : 27/12/2023
* Modification Log  :
* -----------------------------------------------------------------------------------------------------
* Developer             Date            Modification ID     Description
* -----------------------------------------------------------------------------------------------------
* Bunnings Dev          27/12/2023      1000                BUNDIG-26295 - Initial version
******************************************************************************************************/

public class cplDeleteTempQueueable implements Queueable {
    private String custId;

    public cplDeleteTempQueueable(String custId) {
        this.custId = custId;
    }

    public void execute(QueueableContext context) {
        try {
            System.debug('***INSIDE cplDeleteTempQueueable');

            List<Customer_Price_List__c> cplToDelete = [SELECT Id FROM Customer_Price_List__c WHERE (Start_Date__c = NULL AND End_Date__c = NULL) AND Status__c = 'Inactive' AND Account__r.Power_Pass_Account_Number__c =:custId];
            System.debug(LoggingLevel.FINEST, '***cplToDelete: ' + cplToDelete);

            // DO WE NEED TO LOG SUCCESSFUL DELETION??
            DELETE cplToDelete;

        } catch(Exception e) {
            // Create Application Log
            ApplicationLogger.log('cplDeleteTempQueueable', 'Customer_Price_List__c', 'Queueable', e);
        }
    }

}