unpackaged/main/default/objects/Account/fields/Pricing_Assignment_Status__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Assignment_Status__c</fullName>
    <label>Pricing Assignment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manager Actioned</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Actioned</fullName>
                <isActive>false</isActive>
                <label>Actioned</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Customer_Family_Tree_Discount__c/Customer_Family_Tree_Discount__c.object-meta.xml
<CustomObject>
    <description>Junction between Family Tree Discounts and the Customers</description>
    <label>Customer Family Tree Discount</label>
    <nameField>
        <displayFormat>CFD-{0000000000}</displayFormat>
        <label>Customer Family Tree Discount Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Family Tree Discounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Family_Tree_Discount__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Family Tree Discounts</relationshipLabel>
    <relationshipName>Customer_Family_Tree_Discounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Customer_Family_Tree_Discount__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <description>Result of the family tree assignment action</description>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assignment</fullName>
            </value>
            <value>
                <fullName>Removal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Customer_Family_Tree_Discount__c/fields/Change_Requested_On__c.field-meta.xml
<CustomField>
    <fullName>Change_Requested_On__c</fullName>
    <description>Date the pricing assignment/removal change was requested</description>
    <label>Change Requested On</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Customer_Family_Tree_Discount__c/fields/Family_Tree_Discount__c.field-meta.xml
<CustomField>
    <fullName>Family_Tree_Discount__c</fullName>
    <label>Family Tree Discount</label>
    <referenceTo>Family_Tree_Discount__c</referenceTo>
    <relationshipLabel>Customer Family Tree Discounts</relationshipLabel>
    <relationshipName>Customer_Family_Tree_Discounts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Family_Tree_Discount__c/Family_Tree_Discount__c.object-meta.xml
<CustomObject>
    <description>This Object represents a discount structure mastered by an external system. The discount is applied to all products within externally defined product categories.</description>
    <label>Family Tree Discount</label>
    <nameField>
        <label>Family Tree Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Family Tree Discount</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/classes/CustomerFamilyTreeDiscountsHelper.cls
/**
*   =======================================================================================
*   Class Name          : CustomerFamilyTreeDiscountsHelper
*   Description         : Helper for functions associated to customer family tree discounts
*   Author              : Simplus - Purba Ghosh
*   Created On          : 01 Mar 2020
*   Modification Log    : 02 Mar 2020 FrancisBenzon : added soql 
*   =======================================================================================
*   Developer       Date            Modification ID         Description
*   =======================================================================================
*   Purba Ghosh     01 Mar 2020     1000                    Initial version
*   =======================================================================================
*/
public without sharing class CustomerFamilyTreeDiscountsHelper {
  /**
   *  Method name  :  getPendingCustomerFamilyTreeDiscounts
   *  Description  :  Get Customer Family Tree Discount record
   *  Author       :  Francis Benzon
   *  Return Type  :  List<Customer_Family_Tree_Discount__c>
   *  Parameter    :  String accountId
   *                  - Record Id of the account
   *                  String recordStatus
   *                  - Status of the customer price list 
   */   
   
    public static List<Customer_Family_Tree_Discount__c> getPendingCustomerPriceFiles(String accountId, String recordStatus) {     
        List<Customer_Family_Tree_Discount__c> customerFamilyTreeDiscounts = new List<Customer_Family_Tree_Discount__c>();   String cpsApproved = System.Label.CPSApproved;
        String inActive = System.Label.Inactive; 
        
        if(accountId != null) {
            try {
                customerFamilyTreeDiscounts = [SELECT Id, Name, Account__c, End_Date__c, Family_Tree_Discount__c,
                                    Family_Tree_Discount__r.Name, Start_Date__c, Status__c, Pricing_Assignment_Status__c,
                                    Change_Requested_On__c, Action__c
                                    From Customer_Family_Tree_Discount__c 
                                    WHERE Pricing_Assignment_Status__c != :cpsApproved
                                    AND Status__c = :inActive
                                    AND Account__c = :accountId];                                    
            } catch (exception e) {
                ApplicationLogger.log('getPendingCustomerPriceFiles', 'Customer_Family_Tree_Discount__c', 'CustomerFamilyTreeDiscountsHelper', e);
            }
        }
        return customerFamilyTreeDiscounts;
   }

   /**
   * @description 
   * @author John Paul Peñaflor | 7/2/2020 
   * @param String accountId 
   * @return List<Customer_Family_Tree_Discount__c> 
   **/
   public static List<Customer_Family_Tree_Discount__c> getRelatedCustomerFamilyTreeDiscount(String accountId) {     
    List<Customer_Family_Tree_Discount__c> customerFamilyTreeDiscounts = new List<Customer_Family_Tree_Discount__c>();
    
    try {
        customerFamilyTreeDiscounts = [SELECT Id, Name, Account__c, End_Date__c, Family_Tree_Discount__c,
                            Family_Tree_Discount__r.Name, Start_Date__c, Status__c, Pricing_Assignment_Status__c,
                            Change_Requested_On__c, Action__c
                            From Customer_Family_Tree_Discount__c 
                            WHERE Account__c = :accountId];                                    
    } catch (exception e) {
        ApplicationLogger.log('getPendingCustomerPriceFiles', 'Customer_Family_Tree_Discount__c', 'CustomerFamilyTreeDiscountsHelper', e);
    }

    return customerFamilyTreeDiscounts;
}
}