unpackaged/main/default/objects/Account/fields/Pricing_Assignment_Status__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Assignment_Status__c</fullName>
    <label>Pricing Assignment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manager Actioned</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Actioned</fullName>
                <isActive>false</isActive>
                <label>Actioned</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Send_Data_to_CPS__c.field-meta.xml
<CustomField>
    <fullName>Send_Data_to_CPS__c</fullName>
    <defaultValue>false</defaultValue>
    <description>this checkbox will fire the Apex Web Service Callout to send the record to CPS for them to update.</description>
    <label>Send Data to CPS</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Customer_Family_Tree_Discount__c/Customer_Family_Tree_Discount__c.object-meta.xml
<CustomObject>
    <description>Junction between Family Tree Discounts and the Customers</description>
    <label>Customer Family Tree Discount</label>
    <nameField>
        <displayFormat>CFD-{0000000000}</displayFormat>
        <label>Customer Family Tree Discount Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Family Tree Discounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Family_Tree_Discount__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Family Tree Discounts</relationshipLabel>
    <relationshipName>Customer_Family_Tree_Discounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Customer_Family_Tree_Discount__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <description>Result of the family tree assignment action</description>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assignment</fullName>
            </value>
            <value>
                <fullName>Removal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Customer_Family_Tree_Discount__c/fields/Customer_Family_Tree_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_Family_Tree_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Customer Family Tree ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Customer_Family_Tree_Discount__c/fields/Family_Tree_Discount__c.field-meta.xml
<CustomField>
    <fullName>Family_Tree_Discount__c</fullName>
    <label>Family Tree Discount</label>
    <referenceTo>Family_Tree_Discount__c</referenceTo>
    <relationshipLabel>Customer Family Tree Discounts</relationshipLabel>
    <relationshipName>Customer_Family_Tree_Discounts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Family_Tree_Discount__c/Family_Tree_Discount__c.object-meta.xml
<CustomObject>
    <description>This Object represents a discount structure mastered by an external system. The discount is applied to all products within externally defined product categories.</description>
    <label>Family Tree Discount</label>
    <nameField>
        <label>Family Tree Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Family Tree Discount</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Family_Tree_Discount__c/fields/Family_Tree_Discount_ID__c.field-meta.xml
<CustomField>
    <fullName>Family_Tree_Discount_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Family Tree Discount ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/classes/CustomerFTDTriggerHandlerTest.cls
/*******************************************************************************************************
* Class Name        : CustomerFTDTriggerHandlerTest
* Description       : Customer Family Tree Discount trigger handler test class
* Author            : Bunnings Dev
* Created On        : 28/02/2023
* Modification Log  :
* -----------------------------------------------------------------------------------------------------
* Developer             Date            Modification ID     Description
* -----------------------------------------------------------------------------------------------------
* Jasper R. Galapon     28/02/2023      1000                Initial version
******************************************************************************************************/
@isTest
private class CustomerFTDTriggerHandlerTest {
    
    @isTest
    private static void test_CFTDAssignment() {
        List<Account> accounts = TestDataFactory.createAccounts(1);
        accounts[0].Send_Data_to_CPS__c = true;
        accounts[0].Country__c = 'New Zealand';
        insert accounts;

        Family_Tree_Discount__c ftd = new Family_Tree_Discount__c(Name = 'Test Family Tree Discount', Country__c = 'New Zealand', Status__c = 'Active', Family_Tree_Discount_Id__c = String.valueOf(Math.random()));
        insert ftd;

        Customer_Family_Tree_Discount__c cftd = new Customer_Family_Tree_Discount__c(Account__c = [SELECT Id FROM Account LIMIT 1].Id, Family_Tree_Discount__c = ftd.Id, Status__c = 'Active',
            Customer_Family_Tree_Id__c = '', Pricing_Assignment_Status__c = null, Action__c = 'Assignment');
        insert cftd;

        Test.startTest();
            Test.setMock(HttpCalloutMock.class, new SM_RESTCalloutMock('{"example":"test"}', 200, false));
        	cftd.Pricing_Assignment_Status__c = 'Submitted to CPS';
        	cftd.Action__c = 'Assignment';
        	update cftd;            
        Test.stopTest();
    }
    
    @isTest
    private static void test_CFTDRemoval() {
        List<Account> accounts = TestDataFactory.createAccounts(1);
        accounts[0].Send_Data_to_CPS__c = true;
        accounts[0].Country__c = 'New Zealand';
        insert accounts;
        
        Family_Tree_Discount__c ftd = new Family_Tree_Discount__c(Name = 'Test Family Tree Discount', Country__c = 'New Zealand', Status__c = 'Active', Family_Tree_Discount_Id__c = String.valueOf(Math.random()));
        insert ftd;

        Customer_Family_Tree_Discount__c cftd = new Customer_Family_Tree_Discount__c(Account__c = [SELECT Id FROM Account LIMIT 1].Id, Family_Tree_Discount__c = ftd.Id, Status__c = 'Active',
            Customer_Family_Tree_Id__c = 'T123', Pricing_Assignment_Status__c = null, Action__c = 'Assignment');
        insert cftd;
        
        Test.startTest();
            Test.setMock(HttpCalloutMock.class, new SM_RESTCalloutMock('{"example":"test"}', 200, false));
        	cftd.Pricing_Assignment_Status__c = 'Pending Removal Approval';
        	cftd.Action__c = 'Removal';
        	update cftd;            
        Test.stopTest();
    }
    
}