unpackaged/main/default/objects/Account/fields/Pricing_Assignment_Status__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Assignment_Status__c</fullName>
    <label>Pricing Assignment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manager Actioned</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Actioned</fullName>
                <isActive>false</isActive>
                <label>Actioned</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Proposed_Spend_Band__c.field-meta.xml
<CustomField>
    <fullName>Proposed_Spend_Band__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proposed Spend Band</label>
    <referenceTo>Spend_Band__c</referenceTo>
    <relationshipLabel>Accounts (Proposed Spend Band)</relationshipLabel>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Spend_Band__c.field-meta.xml
<CustomField>
    <fullName>Spend_Band__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Spend Band for the Account</description>
    <label>Spend Band</label>
    <referenceTo>Spend_Band__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Customer_Family_Tree_Discount__c/Customer_Family_Tree_Discount__c.object-meta.xml
<CustomObject>
    <description>Junction between Family Tree Discounts and the Customers</description>
    <label>Customer Family Tree Discount</label>
    <nameField>
        <displayFormat>CFD-{0000000000}</displayFormat>
        <label>Customer Family Tree Discount Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Family Tree Discounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Family_Tree_Discount__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Family Tree Discounts</relationshipLabel>
    <relationshipName>Customer_Family_Tree_Discounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Customer_Family_Tree_Discount__c/fields/Family_Tree_Discount__c.field-meta.xml
<CustomField>
    <fullName>Family_Tree_Discount__c</fullName>
    <label>Family Tree Discount</label>
    <referenceTo>Family_Tree_Discount__c</referenceTo>
    <relationshipLabel>Customer Family Tree Discounts</relationshipLabel>
    <relationshipName>Customer_Family_Tree_Discounts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Customer_Price_List__c/Customer_Price_List__c.object-meta.xml
<CustomObject>
    <description>Junction between Price List and Customers</description>
    <label>Customer Price List</label>
    <nameField>
        <displayFormat>CPL-{0000000000}</displayFormat>
        <label>Customer Price List Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Price Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Price_List__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>The customer</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Price Lists</relationshipLabel>
    <relationshipName>Customer_Price_Lists</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Customer_Price_List__c/fields/Price_List__c.field-meta.xml
<CustomField>
    <fullName>Price_List__c</fullName>
    <description>The price list</description>
    <label>Price List</label>
    <referenceTo>Price_List__c</referenceTo>
    <relationshipLabel>Customer Price Lists</relationshipLabel>
    <relationshipName>Customer_Price_Lists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Customer_Price_List__c/fields/Price_List_Name__c.field-meta.xml
<CustomField>
    <fullName>Price_List_Name__c</fullName>
    <formula>Price_List__r.Price_List_Name__c</formula>
    <label>Price List Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Customer_Price_List__c/fields/Pricing_Assignment_Status__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Assignment_Status__c</fullName>
    <label>Pricing Assignment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Assignment Approval</fullName>
            </value>
            <value>
                <fullName>Pending Removal Approval</fullName>
            </value>
            <value>
                <fullName>Submitted to CPS</fullName>
            </value>
            <value>
                <fullName>CPS Submission Failure</fullName>
            </value>
            <value>
                <fullName>CPS Approved</fullName>
            </value>
            <value>
                <fullName>Manager Actioned</fullName>
                <isActive>false</isActive>
                <label>Manager Actioned</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Customer_Price_List__c/fields/Spend_Band__c.field-meta.xml
<CustomField>
    <fullName>Spend_Band__c</fullName>
    <formula>Price_List__r.Spend_Band__r.Name</formula>
    <label>Spend Band</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Customer_Price_List__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This field determines whether a Price List is active (checked) or In active (unchecked) for the related Customer.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Family_Tree_Discount__c/Family_Tree_Discount__c.object-meta.xml
<CustomObject>
    <description>This Object represents a discount structure mastered by an external system. The discount is applied to all products within externally defined product categories.</description>
    <label>Family Tree Discount</label>
    <nameField>
        <label>Family Tree Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Family Tree Discount</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Price_List__c/Price_List__c.object-meta.xml
<CustomObject>
    <description>This Object represents the header level of an externally mastered pricing table, which applies item level discounts for a pre-defined list of products within specific Cost Zones.</description>
    <label>Price List</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Price List Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Price_List__c/fields/Price_List_Name__c.field-meta.xml
<CustomField>
    <fullName>Price_List_Name__c</fullName>
    <description>Price List Names can be up to 100 chars</description>
    <label>Price List Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Price_List__c/fields/Spend_Band__c.field-meta.xml
<CustomField>
    <fullName>Spend_Band__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Spend Band</label>
    <referenceTo>Spend_Band__c</referenceTo>
    <relationshipLabel>Price Lists</relationshipLabel>
    <relationshipName>Price_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Price_List__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Unrestricted list of Bunnings states</description>
    <label>State</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NATIONAL</fullName>
            </value>
            <value>
                <fullName>ACT</fullName>
            </value>
            <value>
                <fullName>NQ</fullName>
            </value>
            <value>
                <fullName>NSW</fullName>
            </value>
            <value>
                <fullName>NT</fullName>
            </value>
            <value>
                <fullName>QLD</fullName>
            </value>
            <value>
                <fullName>SA</fullName>
            </value>
            <value>
                <fullName>TAS</fullName>
            </value>
            <value>
                <fullName>VIC</fullName>
            </value>
            <value>
                <fullName>WA</fullName>
            </value>
            <value>
                <fullName>NI</fullName>
            </value>
            <value>
                <fullName>SI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Price_List__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Price List</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Spend_Band__c/Spend_Band__c.object-meta.xml
<CustomObject>
    <description>Spend band ranges for customers.</description>
    <label>Spend Band</label>
    <nameField>
        <label>Spend Band</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spend Bands</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Spend_Band__c/fields/Max_Amount__c.field-meta.xml
<CustomField>
    <fullName>Max_Amount__c</fullName>
    <description>Max Spend Band Spend Amount, populated from Commercial Pricing System</description>
    <label>Max Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Spend_Band__c/fields/Min_Amount__c.field-meta.xml
<CustomField>
    <fullName>Min_Amount__c</fullName>
    <defaultValue>0.00</defaultValue>
    <description>spend band min amount</description>
    <label>Min Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/classes/PricingAssignmentsTest.cls
/*******************************************************************************************************
* Class Name      	: PricingAssignmentsTest
* Description		: PricingAssignment code coverage
* Author          	: Simplus - Francis Benzon
* Created On      	: 16/03/2020
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Francis Benzon        16/03/2020		1000				Initial version
******************************************************************************************************/
@isTest
public class PricingAssignmentsTest {
    
    static testMethod void callAccountController() {
        //variables for returns
        List<Customer_Price_List__c>  customerPriceList = new List<Customer_Price_List__c>();
        List<Customer_Family_Tree_Discount__c> familyTreeDiscountLst = new List<Customer_Family_Tree_Discount__c>();
        
        //SPEND BAND Recs
        List<Spend_Band__c> spendBandList = new List<Spend_Band__c>();
        Spend_Band__c sb2 = new Spend_Band__c();
        sb2.Name = '2';
        sb2.Min_Amount__c = 25001;
        sb2.Max_Amount__c = 50000;
        spendBandList.add(sb2);
        
        Spend_Band__c sb3 = new Spend_Band__c();
        sb3.Name = '3';
        sb3.Min_Amount__c = 50001;
        sb3.Max_Amount__c = 100000;
        spendBandList.add(sb3);
        
        try {
            insert spendBandList;
        }catch(Exception e){
            //ExceptionLogger.logException('callAccountController', 'PricingAssignmentsTest', 'SpendBandCreation', e);
        }
        
        //PRICE LISTS
        List<Price_List__c> plList = new List<Price_List__c>();
        Price_List__c pl = new Price_List__c();
        pl.Price_List_Name__c = 'Price List 1';
        pl.Spend_Band__c = spendBandList[0].ID;
        //pl.State__c = 'WA';
        plList.add(pl);
        
        Price_List__c pl2 = new Price_List__c();
        pl2.Price_List_Name__c = 'Price List 2';
        pl2.Spend_Band__c = spendBandList[1].ID;
        //pl2.State__c = 'VIC';
        plList.add(pl2);
        
        try {
            insert plList;
        }catch(Exception e){
            //ExceptionLogger.logException('callAccountController', 'PricingAssignmentsTest', 'PriceListCreation', e);
        }
        
        //ACCOUNT Recs
        List<Account> acctList = TestDataFactory.createAccounts(2);
        //AU Account
        acctList[0].Country__c = 'Australia';
        acctList[0].Pricing_Assignment_Status__c = 'Pending Approval';
        acctList[0].Spend_Band__c = spendBandList[0].ID;    
        acctList[0].Proposed_Spend_Band__c = spendBandList[1].ID;
        acctList[0].RecordTypeId = CSUtils.getRecordTypeId('Account', 'AU Prospect');
        //NZ Account
        acctList[1].Country__c = 'New Zealand';
        acctList[1].RecordTypeId = CSUtils.getRecordTypeId('Account', 'NZ Prospect');
        
        try {
            upsert acctList;             
        }catch(Exception e){
            //ExceptionLogger.logException('callAccountController', 'PricingAssignmentsTest', 'AccountQuery', e);
        }
        
        
        //CUSTOMER PRICE LISTS
        List<Customer_Price_List__c> cplList = new List<Customer_Price_List__c>();
        Customer_Price_List__c cpl = new Customer_Price_List__c();      
        cpl.Account__c = acctList[0].ID;
        cpl.Price_List__c = plList[0].ID;
        cpl.Status__c = 'Inactive';
        cpl.Pricing_Assignment_Status__c = 'Pending Assignment Approval';
        cplList.add(cpl);
        
        Customer_Price_List__c cpl2 = new Customer_Price_List__c(); 
        cpl2.Account__c = acctList[0].ID;
        cpl2.Price_List__c = plList[1].ID;
        cpl2.Status__c = 'Active';
        cpl2.Pricing_Assignment_Status__c = 'CPS Approved';
        cplList.add(cpl2);
        
        try {
            insert cplList;
        }catch(Exception e){
            //ExceptionLogger.logException('callAccountController', 'PricingAssignmentsTest', 'PriceListCreation', e);
        }
                
        //FAMILY TREE DISCOUNTS
        List<Family_Tree_Discount__c> ftdList = new List<Family_Tree_Discount__c>();
        Family_Tree_Discount__c ftd1 = new Family_Tree_Discount__c();
        ftd1.Name = 'Oceania Retirement Villages';
        ftdList.add(ftd1);
        
        Family_Tree_Discount__c ftd2 = new Family_Tree_Discount__c();
        ftd2.Name = 'NZCPDG Pricefile';
        ftdList.add(ftd2);
        
        try {
            insert ftdList;
        }catch(Exception e){
            //ExceptionLogger.logException('callAccountController', 'PricingAssignmentsTest', 'PriceListCreation', e);
        }
        
        //CUSTOMER FAMILY TREE DISCOUNTS
        List<Customer_Family_Tree_Discount__c> cftdList = new List<Customer_Family_Tree_Discount__c>();
        Customer_Family_Tree_Discount__c cftd1 = new Customer_Family_Tree_Discount__c();
        cftd1.Account__c = acctList[1].ID;
        cftd1.Family_Tree_Discount__c = ftdList[0].ID;
        cftd1.Status__c = 'Active';
        cftd1.Pricing_Assignment_Status__c = 'CPS Approved';
        cftdList.add(cftd1);
        
        Customer_Family_Tree_Discount__c cftd2 = new Customer_Family_Tree_Discount__c();
        cftd1.Account__c = acctList[1].ID;
        cftd1.Family_Tree_Discount__c = ftdList[1].ID;
        cftd1.Status__c = 'Inactive';
        cftd1.Pricing_Assignment_Status__c = 'Pending Assignment Approval';
        cftdList.add(cftd2);
        
        try {
            insert cftdList;
        }catch(Exception e){
            //ExceptionLogger.logException('callAccountController', 'PricingAssignmentsTest', 'PriceListCreation', e);
        }
        
        String auAcctID = String.valueOf(acctList[0].ID);
        String nzAcctID = String.valueOf(acctList[1].ID);
        String pendingApproval = 'Pending Assignment Approval';
        
        Test.StartTest();
        
        Account acct = AccountController.getAccountDetails(auAcctID);
        customerPriceList = AccountController.getCustomerPriceLists(auAcctID, pendingApproval);
        familyTreeDiscountLst = AccountController.getPendingCustomerPriceFiles(nzAcctID, pendingApproval);
        
        //for email templates
        AccountsPriceListsFamilyTree controllerclass = new AccountsPriceListsFamilyTree();
        //price lists
        controllerclass.accountId = auAcctID;
        Account acct2 = controllerclass.account;
        List<Price_List__c> inactivePriceLists = controllerclass.priceLists;
        List<Price_List__c> activePriceLists = controllerclass.currentPriceLists;
        
        //family tree discounts
        controllerclass.accountId = nzAcctID;
        List<Family_Tree_Discount__c> inactivefamTrees = controllerclass.famTreeDisc;
        List<Family_Tree_Discount__c> activefamTrees = controllerclass.activeFamTreeDisc;
        Test.StopTest();
    }
}