unpackaged/main/default/objects/Account/fields/Pricing_Assignment_Status__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Assignment_Status__c</fullName>
    <label>Pricing Assignment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manager Actioned</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Actioned</fullName>
                <isActive>false</isActive>
                <label>Actioned</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Customer_Price_List__c/Customer_Price_List__c.object-meta.xml
<CustomObject>
    <description>Junction between Price List and Customers</description>
    <label>Customer Price List</label>
    <nameField>
        <displayFormat>CPL-{0000000000}</displayFormat>
        <label>Customer Price List Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Price Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Price_List__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>The customer</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Price Lists</relationshipLabel>
    <relationshipName>Customer_Price_Lists</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Customer_Price_List__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <description>Result of the price list assignment action</description>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assignment</fullName>
            </value>
            <value>
                <fullName>Removal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Customer_Price_List__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Customer Price Lists End Date</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Customer_Price_List__c/fields/Price_List__c.field-meta.xml
<CustomField>
    <fullName>Price_List__c</fullName>
    <description>The price list</description>
    <label>Price List</label>
    <referenceTo>Price_List__c</referenceTo>
    <relationshipLabel>Customer Price Lists</relationshipLabel>
    <relationshipName>Customer_Price_Lists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Customer_Price_List__c/fields/Price_List_Name__c.field-meta.xml
<CustomField>
    <fullName>Price_List_Name__c</fullName>
    <formula>Price_List__r.Price_List_Name__c</formula>
    <label>Price List Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Customer_Price_List__c/fields/Pricing_Assignment_Status__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Assignment_Status__c</fullName>
    <label>Pricing Assignment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Assignment Approval</fullName>
            </value>
            <value>
                <fullName>Pending Removal Approval</fullName>
            </value>
            <value>
                <fullName>Submitted to CPS</fullName>
            </value>
            <value>
                <fullName>CPS Submission Failure</fullName>
            </value>
            <value>
                <fullName>CPS Approved</fullName>
            </value>
            <value>
                <fullName>Manager Actioned</fullName>
                <isActive>false</isActive>
                <label>Manager Actioned</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Customer_Price_List__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Customer Price Lists Start Date</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Customer_Price_List__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This field determines whether a Price List is active (checked) or In active (unchecked) for the related Customer.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Price_List__c/Price_List__c.object-meta.xml
<CustomObject>
    <description>This Object represents the header level of an externally mastered pricing table, which applies item level discounts for a pre-defined list of products within specific Cost Zones.</description>
    <label>Price List</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Price List Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Price_List__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Date when Price List would end</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Price_List__c/fields/Price_List_Name__c.field-meta.xml
<CustomField>
    <fullName>Price_List_Name__c</fullName>
    <description>Price List Names can be up to 100 chars</description>
    <label>Price List Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Price_List__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Date when Price List would start</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Price_List__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Price List</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/CustomerPriceListHelper.cls
/**
*   =====================================================================================
*   Class Name          : CustomerPriceListHelper
*   Description         : Helper for functions associated to customer price lists
*   Author              : Simplus - Purba Ghosh
*   Created On          : 01 Mar 2020
*   Modification Log    :
*   =====================================================================================
*   Developer       Date            Modification ID         Description
*   =====================================================================================
*   Purba Ghosh     01 Mar 2020     1000                    Initial version
*   =====================================================================================
*/
public without sharing class CustomerPriceListHelper {
  /**
   *  Method name  :  getCustomerPriceLists
   *  Description  :  Get PriceList record
   *  Author       :  Francis Benzon
   *  Return Type  :  List<Customer_Price_List__c>
   *  Parameter    :  String accountId
   *                  - Record Id of the account
   *                  String recordStatus
   *                  - Status of the customer price list 
   */   
    public static List<Customer_Price_List__c> getCustomerPriceLists(String accountId, String recordStatus) {      
        List<Customer_Price_List__c> customerPriceList = new List<Customer_Price_List__c>();
        String cpsApproved = System.Label.CPSApproved;
        String inActive = System.Label.Inactive; 
        if(accountId != null) {
            try {
                customerPriceList = [SELECT Id, Name, Account__c, End_Date__c, Price_List__c,
                                    Price_List__r.Price_List_Name__c, Start_Date__c, Status__c, Pricing_Assignment_Status__c,
                                    Change_Requested_On__c, Action__c
                                    From Customer_Price_List__c 
                                    WHERE Pricing_Assignment_Status__c != :cpsApproved
                                    AND Account__c = :accountId
                                    AND Status__c = :inActive
                                    ];                                    
            } catch (exception e) {
                ApplicationLogger.log('getCustomerPriceLists', 'Customer_Price_List__c', 'CustomerPriceListHelper', e);
            }
        }
        return customerPriceList;
    }

    /**
    * @description 
    * @author John Paul Peñaflor | 7/2/2020 
    * @param String accountId 
    * @return List<Customer_Price_List__c> 
    **/
    public static List<Customer_Price_List__c> getRelatedCustomerPriceLists(String accountId){
        List<Customer_Price_List__c> customerPriceList = new List<Customer_Price_List__c>();

        try{
            customerPriceList = [SELECT Id, Name, Account__c, End_Date__c, Price_List__c,
                                    Price_List__r.Price_List_Name__c, Start_Date__c, Status__c, Pricing_Assignment_Status__c,
                                    Change_Requested_On__c, Action__c
                                    From Customer_Price_List__c 
                                    WHERE Account__c = :accountId
                                    ];

        } catch (exception e) {
            ApplicationLogger.log('getCustomerPriceLists', 'Customer_Price_List__c', 'CustomerPriceListHelper', e);
        }
        
        return customerPriceList;
    }
}