unpackaged/main/default/objects/Account/fields/Supplier_Region__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Region__c</fullName>
    <description>For NZ supplier accounts</description>
    <label>Supplier Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Supplier_Region</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Supplier_Region__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Region__c</fullName>
    <description>For NZ opportunities</description>
    <label>Supplier Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Supplier_Region</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Supplier_Quote__c/Supplier_Quote__c.object-meta.xml
<CustomObject>
    <label>Supplier Quote</label>
    <nameField>
        <displayFormat>SQ-{000000}</displayFormat>
        <label>Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/globalValueSets/Supplier_Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Area 1 - Northland</fullName>
    </customValue>
    <customValue>
        <fullName>Area 1, 2, 3 - Auckland</fullName>
    </customValue>
    <customValue>
        <fullName>Area 4</fullName>
    </customValue>
    <customValue>
        <fullName>Area 5</fullName>
    </customValue>
    <customValue>
        <fullName>Area 6</fullName>
    </customValue>
    <customValue>
        <fullName>Area 7</fullName>
    </customValue>
    <customValue>
        <fullName>Area 8</fullName>
    </customValue>
    <description>For NZ account and opportunity picklists</description>
    <masterLabel>Supplier Region</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/DM_SupplierQuote_Test.cls
/*******************************************************************************************************
* Class Name      	: DM_SupplierQuote_Test
* Description		: Data Layer - test calss for  DM_SupplierQuote
* Author          	: Bunnings Dev  
* Created On      	: 2024-11-21
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Bunnings Dev          2024-11-21		1000				Initial version
* Bunnings Dev          21/11/2024		2000				
******************************************************************************************************/
@isTest
public class DM_SupplierQuote_Test {
 @testSetup 
    static void testDataSetup() {
        List<Account> accList = TestDataFactory.createAccounts(1);
        accList[0].RecordTypeId = CSUtils.getRecordTypeId('Account', 'NZ Supplier');
        accList[0].Supplier_Region__c = 'Area 4';
        accList[0].Country__c='New Zealand';
        insert accList;
        list<Opportunity> oppList = TestDataFactory.createOpenOpportunities(accList[0].Id, UserInfo.getUserId(), 1);
        oppList[0].RecordTypeId = CSUtils.getRecordTypeId('Opportunity', 'NZ Standard Opportunity');
        insert oppList;
         List<Supplier_Quote__c> supQuoList = TestDataFactory.createSupplierQuotes(oppList[0].Id, accList[0].id, 2);
        insert supQuoList;
    }
    
    
    static testmethod void testgetSupplierQuotesbyOpportunity() {
        Opportunity opp = [Select id,name from Opportunity limit 1];
        
        Test.startTest();
        DM_SupplierQuote.getSupplierQuotesbyOpportunity(opp.id);
        Test.stopTest();
    }
    
    static testmethod void testgetSupplierQuotesbyOpportunities() {
        List<Opportunity> oppList = [Select id,name from Opportunity];
        Set<id> oppset = new Set<id>();
        for(Opportunity op : oppList){
            oppset.add(op.id);
        }
        Test.startTest();
        DM_SupplierQuote.getSupplierQuotesbyOpportunities(oppset);
        Test.stopTest();
    }
}