unpackaged/main/default/objects/Project_Contract_Matching_Field__mdt/Project_Contract_Matching_Field__mdt.object-meta.xml
<CustomObject>
    <description>Used to define fields to compare between project and contract when trying to populate project field on contract.</description>
    <label>Project Contract Matching Field</label>
    <pluralLabel>Project Contract Matching Fields</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Project_Contract_Matching_Field__mdt/fields/Destination_Field__c.field-meta.xml
<CustomField>
    <fullName>Destination_Field__c</fullName>
    <description>The field of Project__c object</description>
    <inlineHelpText>The field of Project__c object</inlineHelpText>
    <label>Destination Field</label>
    <metadataRelationshipControllingField>Project_Contract_Matching_Field__mdt.Destination_Object__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>Project_Contract_Matching_Fields1</relationshipLabel>
    <relationshipName>Project_Contract_Matching_Fields1</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

unpackaged/main/default/objects/Project_Contract_Matching_Field__mdt/fields/Source_Field__c.field-meta.xml
<CustomField>
    <fullName>Source_Field__c</fullName>
    <description>The field of Contract__c object</description>
    <inlineHelpText>The field of Contract__c object</inlineHelpText>
    <label>Source Field</label>
    <metadataRelationshipControllingField>Project_Contract_Matching_Field__mdt.Source_Object__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>Project_Contract_Matching_Fields</relationshipLabel>
    <relationshipName>Project_Contract_Matching_Fields</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

unpackaged/main/default/classes/DM_ProjectContractMatchingField.cls
/*******************************************************************************************************
* Class Name      	: DM_ProjectContractMatchingField
* Description		: Data Layer - Selector for Custom Metadata Type Project_Contract_Matching_Field__mdt
* Author          	: Simplus - Yi Zhang
* Created On      	: 01/10/2020
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Yi Zhang              01/10/2020		1000				Initial version
******************************************************************************************************/
public with sharing class DM_ProjectContractMatchingField {
    /**
    * @description 
    * @author Yi Zhang | 01/10/2020 
    * @return List<Project_Contract_Matching_Field__mdt> 
    **/
    public static List<Project_Contract_Matching_Field__mdt> matchingFields {
        get {
            if(matchingFields == null) {
                matchingFields = new List<Project_Contract_Matching_Field__mdt>([
                    SELECT Id, 
                    Source_Field__r.QualifiedApiName, 
                    Destination_Field__r.QualifiedApiName 
                    FROM Project_Contract_Matching_Field__mdt
                    ]);
            }
            return matchingFields;
        } set;
    }
}