unpackaged/main/default/objects/Operations_Region__c/Operations_Region__c.object-meta.xml
<CustomObject>
    <description>Maps operation region with their corresponding roles.</description>
    <label>Operations Region Role</label>
    <nameField>
        <label>Operations Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Operations Region Roles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Operations_Region_TS_Role__mdt/Operations_Region_TS_Role__mdt.object-meta.xml
<CustomObject>
    <description>Used to populate TS user role based on Operations Region to which associated store (through location code) belong</description>
    <label>Operations Region TS Role</label>
    <pluralLabel>Operations Region TS Roles</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Operations_Region_TS_Role__mdt/fields/Operations_Region__c.field-meta.xml
<CustomField>
    <fullName>Operations_Region__c</fullName>
    <label>Operations Region</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Operations_Region_TS_Role__mdt/fields/Trade_Specialist_Role__c.field-meta.xml
<CustomField>
    <fullName>Trade_Specialist_Role__c</fullName>
    <label>Trade Specialist Role</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/DM_OperationsRegionTSRole.cls
/*******************************************************************************************************
* Class Name      	: DM_OperationsRegionTSRole
* Description		: Data Layer - Selector for custom metadata Operations_Region_TS_Role__mdt
* Author          	: Simplus - Yi Zhang
* Created On      	: 03/09/2020
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Yi Zhang              03/09/2020		1000				Initial version
******************************************************************************************************/
public with sharing class DM_OperationsRegionTSRole {
    /**
    * @description 
    * @author Yi Zhang | 03/09/2020 
    * @param opRegCodes 
    * @return List<Operations_Region_TS_Role__mdt> 
    **/
    public static List<Operations_Region_TS_Role__mdt> getRecordsByOpRegCode(List<String> opRegCodes) {
        return new List<Operations_Region_TS_Role__mdt>([
            SELECT Id, Operations_Region__c, Trade_Specialist_Role__c 
            FROM Operations_Region_TS_Role__mdt 
            WHERE Operations_Region__c IN :opRegCodes
            ]);
    }
}