unpackaged/main/default/objects/Operations_Region__c/Operations_Region__c.object-meta.xml
<CustomObject>
    <description>Maps operation region with their corresponding roles.</description>
    <label>Operations Region Role</label>
    <nameField>
        <label>Operations Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Operations Region Roles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Operations_Region__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <formula>RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Operations_Region__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Area BDM</fullName>
            </value>
            <value>
                <fullName>CCS Manager</fullName>
            </value>
            <value>
                <fullName>RCM</fullName>
            </value>
            <value>
                <fullName>SSM</fullName>
            </value>
            <value>
                <fullName>CCS</fullName>
                <isActive>false</isActive>
                <label>CCS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Operations_Region__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Operations_RegionTM</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>Represents all frame and truss plants, small format stores, trade distribution centres and warehouses.</description>
    <label>Store</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Store__c/fields/Engagement_Model__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Model__c</fullName>
    <description>Determines the method used for assigning Powerpass Account Ownership. 
Old Model - the Stores Default Trade Specialist will become the owner. 
New - Ownership is determined by Assignment Rule Metadata records</description>
    <label>Engagement Model</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Old</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Store__c/fields/Location_Type__c.field-meta.xml
<CustomField>
    <fullName>Location_Type__c</fullName>
    <description>Unrestricted list of location types</description>
    <label>Location Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Area</fullName>
            </value>
            <value>
                <fullName>Department</fullName>
            </value>
            <value>
                <fullName>Distribution Centre</fullName>
            </value>
            <value>
                <fullName>Frame and Truss Plant</fullName>
            </value>
            <value>
                <fullName>Function</fullName>
            </value>
            <value>
                <fullName>Logical</fullName>
            </value>
            <value>
                <fullName>Region</fullName>
            </value>
            <value>
                <fullName>Section</fullName>
            </value>
            <value>
                <fullName>Small Format Store</fullName>
            </value>
            <value>
                <fullName>Trade Distribution Centre</fullName>
            </value>
            <value>
                <fullName>Warehouse</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Store__c/fields/Operations_Region_Code__c.field-meta.xml
<CustomField>
    <fullName>Operations_Region_Code__c</fullName>
    <description>The store&#39;s operations region code</description>
    <label>Operations Region Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Store__c/fields/Sales_Rep_ID__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep_ID__c</fullName>
    <description>Sales rep ID that is used to define the role of the trade specialist.</description>
    <label>Sales Rep ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Store__c/fields/Store_Call__c.field-meta.xml
<CustomField>
    <fullName>Store_Call__c</fullName>
    <label>Store Call %</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0%</fullName>
            </value>
            <value>
                <fullName>10%</fullName>
            </value>
            <value>
                <fullName>20%</fullName>
            </value>
            <value>
                <fullName>30%</fullName>
            </value>
            <value>
                <fullName>40%</fullName>
            </value>
            <value>
                <fullName>50%</fullName>
            </value>
            <value>
                <fullName>60%</fullName>
            </value>
            <value>
                <fullName>70%</fullName>
            </value>
            <value>
                <fullName>80%</fullName>
            </value>
            <value>
                <fullName>90%</fullName>
            </value>
            <value>
                <fullName>100%</fullName>
                <default>true</default>
                <label>100%</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Store_Member__c/Store_Member__c.object-meta.xml
<CustomObject>
    <description>Junction between user (team members) and store.</description>
    <label>Store Member</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>Store Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Store_Member__c/fields/Call_Volume__c.field-meta.xml
<CustomField>
    <fullName>Call_Volume__c</fullName>
    <label>Call Volume</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Store_Member__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ASM</fullName>
            </value>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Area BDM</fullName>
            </value>
            <value>
                <fullName>CCS Manager</fullName>
            </value>
            <value>
                <fullName>RCM</fullName>
            </value>
            <value>
                <fullName>Trade Specialist</fullName>
            </value>
            <value>
                <fullName>SSM</fullName>
            </value>
            <value>
                <fullName>CCS</fullName>
                <isActive>false</isActive>
                <label>CCS</label>
            </value>
            <value>
                <fullName>Team Member</fullName>
                <isActive>false</isActive>
                <label>Team Member</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Store_Member__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipName>User_Stores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Store_Member__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Stores</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Store_Member__c/fields/Team_Member_Call__c.field-meta.xml
<CustomField>
    <fullName>Team_Member_Call__c</fullName>
    <label>Team Member Call %</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0%</fullName>
            </value>
            <value>
                <fullName>10%</fullName>
            </value>
            <value>
                <fullName>20%</fullName>
            </value>
            <value>
                <fullName>30%</fullName>
            </value>
            <value>
                <fullName>40%</fullName>
            </value>
            <value>
                <fullName>50%</fullName>
            </value>
            <value>
                <fullName>60%</fullName>
            </value>
            <value>
                <fullName>70%</fullName>
            </value>
            <value>
                <fullName>80%</fullName>
            </value>
            <value>
                <fullName>90%</fullName>
            </value>
            <value>
                <fullName>100%</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/User/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>&quot;None&quot;</defaultValue>
    <description>This field is used in sharing rules to define a AU User&#39;s and NZ User&#39;s</description>
    <inlineHelpText>This field is used in sharing rules to define a AU User&#39;s and NZ User&#39;s</inlineHelpText>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/User/fields/Sales_Rep_ID__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep_ID__c</fullName>
    <description>Unique sales rep number assigned to the user either from legacy system sequence or newly generated in Salesforce</description>
    <label>Sales Rep ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/SM_Store_Test.cls
/*******************************************************************************************************
* Class Name      	: SM_Store_Test
* Description		: Test class for SM_Store
* Author          	: Simplus - Philip Clark
* Created On      	: 19/06/2020
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Philip Clark          19/06/2020		1000				Initial version
* Yi Zhang          	19/08/2020		2000				Revamp all resulted from requirement change
* Simplus MS            22/10/2021      3000                Added test logic for CCRM15-79: Update store record to trigger recalculation of call volume on store members
******************************************************************************************************/
@isTest
private class SM_Store_Test {

    @isTest
    private static void testCreateStore() {

        // create users
        Profile profileSSM = [SELECT Id FROM Profile WHERE Name = :Constants.AU_SALES_MANAGER_PROFILEENAME LIMIT 1];
        Profile profileRCM = [SELECT Id FROM Profile WHERE Name = :Constants.AU_LIGHT_COMMERCIAL_MANAGER_PROFILEENAME LIMIT 1];
        Profile profileAreaBDM = [SELECT Id FROM Profile WHERE Name = :Constants.ORG_SALES_MANAGER_PROFILEENAME LIMIT 1];
        Profile profileCCSManager = [SELECT Id FROM Profile WHERE Name = :Constants.NATIONAL_MANAGER_PROFILEENAME LIMIT 1];
        Profile profileTS = [SELECT Id FROM Profile WHERE Name = :Constants.AU_TRADE_SPECIALIST_PROFILEENAME LIMIT 1];
        List<User> users = TestDataFactory.createUsers(5, null);
        users[0].ProfileId = profileSSM.Id;
        users[1].ProfileId = profileRCM.Id;
        users[2].ProfileId = profileAreaBDM.Id;
        users[3].ProfileId = profileCCSManager.Id;
        users[4].ProfileId = profileTS.Id;
        System.runAs(new User(Id = UserInfo.getUserId())) {
            insert users;
        }
        
        // create operations regions
        List<Operations_Region__c> opRegs = new List<Operations_Region__c>();
        opRegs.add(new Operations_Region__c(Name = 'NSW', Role__c = 'SSM', Team_Member__c = users[0].Id));
        opRegs.add(new Operations_Region__c(Name = 'NSW', Role__c = 'RCM', Team_Member__c = users[1].Id));
        opRegs.add(new Operations_Region__c(Name = 'NSW', Role__c = 'Area BDM', Team_Member__c = users[2].Id));
        opRegs.add(new Operations_Region__c(Name = 'NSW', Role__c = 'CCS Manager', Team_Member__c = users[3].Id));
        insert opRegs;

        // create store
        List<Store__c> storeList = TestDataFactory.createStores(1);
        storeList[0].Operations_Region_Code__c = 'NSW';

        Test.startTest();
        insert storeList;
        Test.stopTest();
        System.assertEquals(4, [SELECT Id FROM Store_Member__c WHERE Store__c = :storeList[0].Id].size(), 'Store members not created as expected');
    }

    @isTest
    private static void testAfterUpdateStore() {

        // Create user with TS profile
        Profile profileTS = [SELECT Id FROM Profile WHERE Name = :Constants.AU_TRADE_SPECIALIST_PROFILEENAME LIMIT 1];
        User usr = TestDataFactory.createUsers(1, profileTS.Id)[0];
        System.runAs(new User(Id = UserInfo.getUserId())) {
            insert usr;
        }

        // Create store records with related store members and populate fields needed for call volume calculation
        List<Store__c> storeList = TestDataFactory.createStores(3);
        List<Store_Member__c> storeMemberList = new List<Store_Member__c>();

        for(Store__c st : storeList) {
            st.Country__c = Constants.COUNTRY_AU;
            st.Location_Type__c = Constants.STORE_TYPE_STORE;
            st.Engagement_Model__c = Constants.STORE_MODEL_NEW;
            st.Store_Call__c = '50%';
        }
        insert storeList;

        for(Store__c st : storeList) {
            Store_Member__c sm = TestDataFactory.createStoreMember(st.Id, usr.Id, Constants.STOREMEMBER_TS_ROLENAME);
            sm.Team_Member_Call__c = '10%';
            storeMemberList.add(sm);
        }
        storeMemberList[0].Team_Member_Call__c = '';
        insert storeMemberList;
       
        //Create map of store records with store members for assertion
        Map<Id, Map<Id, Store_Member__c>> storeWithMembersMap = new Map<Id, Map<Id, Store_Member__c>> ();
        List<Store__c> insertedStoresWithMembers = [SELECT Id, (SELECT Id, Call_Volume__c FROM User_Stores__r) 
        FROM Store__c];
        for(Store__c st : insertedStoresWithMembers) {
            storeWithMembersMap.put(st.Id, new Map<Id, Store_Member__c>(st.User_Stores__r));
        }     

        //Update store records to trigger after update method
        for(Store__c st : storeList) {
            st.Engagement_Model__c = 'Old';
        }
        storeList[0].Engagement_Model__c = 'New'; //No record change and will be excluded
        storeList[0].Sales_Rep_ID__c = '500';
        
        Test.startTest();
        update storeList;
        Test.stopTest();

        //Retrieve list of updated store records with store members and perform assertion
        List<Store__c> updatedStoresWithMembers = [SELECT Id, (SELECT Id, Call_Volume__c FROM User_Stores__r) 
                                                   FROM Store__c WHERE Engagement_Model__c = 'Old'];
        System.assertEquals(2, updatedStoresWithMembers.size(), 'Number of store records updated does not match expected number');

        //Call volume is expected to be recalculated with the update of store engagement model
        for(Store__c st : updatedStoresWithMembers) {
            for(Store_Member__c sm : st.User_Stores__r) {
                System.assert(sm.Call_Volume__c != storeWithMembersMap.get(st.Id).get(sm.Id).Call_Volume__c, 'Call volume did not recalculate');
            }
        }
    } 
}