unpackaged/main/default/objects/Operations_Region__c/Operations_Region__c.object-meta.xml
<CustomObject>
    <description>Maps operation region with their corresponding roles.</description>
    <label>Operations Region Role</label>
    <nameField>
        <label>Operations Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Operations Region Roles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Operations_Region__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <formula>RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Operations_Region__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Area BDM</fullName>
            </value>
            <value>
                <fullName>CCS Manager</fullName>
            </value>
            <value>
                <fullName>RCM</fullName>
            </value>
            <value>
                <fullName>SSM</fullName>
            </value>
            <value>
                <fullName>CCS</fullName>
                <isActive>false</isActive>
                <label>CCS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Operations_Region__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Operations_RegionTM</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Sales_Rep__c/Sales_Rep__c.object-meta.xml
<CustomObject>
    <description>Bunnings&#39; Sales Rep ID assigned to team members and stores for attribution. This is based from a legacy definition of sales rep hierrachy and ids.</description>
    <label>Sales Rep</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Sales Rep ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Rep</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Sales_Rep__c/fields/Assigned_to_Store__c.field-meta.xml
<CustomField>
    <fullName>Assigned_to_Store__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Store the sales rep id is assigned to</description>
    <label>Assigned to Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Sales Rep</relationshipLabel>
    <relationshipName>Sales_Rep</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Sales_Rep__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>This field is used in conjunction with custom metadata type (Sales Rep Category Mapping) and user&#39;s Bunnings Job Role, Location Code field to determine the Sales Rep Id for the store member TS.</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Default</fullName>
                <default>true</default>
                <label>Default</label>
            </value>
            <value>
                <fullName>Landscape</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Sales_Rep__c/fields/Current_Sales_Rep_ID__c.field-meta.xml
<CustomField>
    <fullName>Current_Sales_Rep_ID__c</fullName>
    <description>If the leagcy sales rep id is assigned then it is considered as sales rep number else newly generated auto number sales rep id from Salesforce is used</description>
    <formula>IF(ISBLANK(Sales_Rep_Legacy_ID__c),  Name , Sales_Rep_Legacy_ID__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Current Sales Rep ID</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Sales_Rep__c/fields/Sales_Rep_Legacy_ID__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep_Legacy_ID__c</fullName>
    <description>Legacy Sales Rep ID as obtained form CCRM.</description>
    <label>Sales Rep Legacy ID</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Sales_Rep__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACT</fullName>
            </value>
            <value>
                <fullName>NSW</fullName>
            </value>
            <value>
                <fullName>QLD</fullName>
            </value>
            <value>
                <fullName>WA</fullName>
            </value>
            <value>
                <fullName>VIC</fullName>
            </value>
            <value>
                <fullName>NQ</fullName>
            </value>
            <value>
                <fullName>TAS</fullName>
            </value>
            <value>
                <fullName>SA</fullName>
            </value>
            <value>
                <fullName>NT</fullName>
            </value>
            <value>
                <fullName>NI</fullName>
            </value>
            <value>
                <fullName>SI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>Represents all frame and truss plants, small format stores, trade distribution centres and warehouses.</description>
    <label>Store</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Store__c/fields/Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_1__c</fullName>
    <description>The store&#39;s address line 1</description>
    <label>Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Store__c/fields/Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_2__c</fullName>
    <description>The store&#39;s address line 2</description>
    <label>Address Line 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Store__c/fields/Address_Line_3__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_3__c</fullName>
    <description>The store&#39;s address line 3</description>
    <label>Address Line 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Store__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>The store&#39;s city</description>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Store__c/fields/Location_Code__c.field-meta.xml
<CustomField>
    <fullName>Location_Code__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Location Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Store__c/fields/Location_Type__c.field-meta.xml
<CustomField>
    <fullName>Location_Type__c</fullName>
    <description>Unrestricted list of location types</description>
    <label>Location Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Area</fullName>
            </value>
            <value>
                <fullName>Department</fullName>
            </value>
            <value>
                <fullName>Distribution Centre</fullName>
            </value>
            <value>
                <fullName>Frame and Truss Plant</fullName>
            </value>
            <value>
                <fullName>Function</fullName>
            </value>
            <value>
                <fullName>Logical</fullName>
            </value>
            <value>
                <fullName>Region</fullName>
            </value>
            <value>
                <fullName>Section</fullName>
            </value>
            <value>
                <fullName>Small Format Store</fullName>
            </value>
            <value>
                <fullName>Trade Distribution Centre</fullName>
            </value>
            <value>
                <fullName>Warehouse</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Store__c/fields/Operations_Region_Code__c.field-meta.xml
<CustomField>
    <fullName>Operations_Region_Code__c</fullName>
    <description>The store&#39;s operations region code</description>
    <label>Operations Region Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Store__c/fields/Postcode__c.field-meta.xml
<CustomField>
    <fullName>Postcode__c</fullName>
    <description>The store&#39;s postcode</description>
    <label>Postcode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Store__c/fields/Sales_Rep_ID__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep_ID__c</fullName>
    <description>Sales rep ID that is used to define the role of the trade specialist.</description>
    <label>Sales Rep ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Store__c/fields/Trade_Specialist_Email__c.field-meta.xml
<CustomField>
    <fullName>Trade_Specialist_Email__c</fullName>
    <label>Trade Specialist Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Store_Member__c/Store_Member__c.object-meta.xml
<CustomObject>
    <description>Junction between user (team members) and store.</description>
    <label>Store Member</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>Store Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Store_Member__c/fields/Location_Code__c.field-meta.xml
<CustomField>
    <fullName>Location_Code__c</fullName>
    <formula>Store__r.Location_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Location Code</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Store_Member__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ASM</fullName>
            </value>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Area BDM</fullName>
            </value>
            <value>
                <fullName>CCS Manager</fullName>
            </value>
            <value>
                <fullName>RCM</fullName>
            </value>
            <value>
                <fullName>Trade Specialist</fullName>
            </value>
            <value>
                <fullName>SSM</fullName>
            </value>
            <value>
                <fullName>CCS</fullName>
                <isActive>false</isActive>
                <label>CCS</label>
            </value>
            <value>
                <fullName>Team Member</fullName>
                <isActive>false</isActive>
                <label>Team Member</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Store_Member__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start date of association with the store</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Store_Member__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Store_Member__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipName>User_Stores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Store_Member__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Stores</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/User/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>&quot;None&quot;</defaultValue>
    <description>This field is used in sharing rules to define a AU User&#39;s and NZ User&#39;s</description>
    <inlineHelpText>This field is used in sharing rules to define a AU User&#39;s and NZ User&#39;s</inlineHelpText>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/User/fields/Location_Code__c.field-meta.xml
<CustomField>
    <fullName>Location_Code__c</fullName>
    <description>Location code that maps to the external ID on the store object</description>
    <label>Location Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/Sales_Rep_ID__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep_ID__c</fullName>
    <description>Unique sales rep number assigned to the user either from legacy system sequence or newly generated in Salesforce</description>
    <label>Sales Rep ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/Store_Email__c.field-meta.xml
<CustomField>
    <fullName>Store_Email__c</fullName>
    <description>Email from Trade_Specialist_Email__c in Store object.</description>
    <label>Store Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/classes/SM_Store.cls
/*******************************************************************************************************
* Class Name      	: SM_Store
* Description		: Domain / Service layer for Store
* Author          	: Simplus - Philip Clark
* Created On      	: 19/06/2020
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Philip Clark          19/06/2020		1000				Initial version
* Yi Zhang              19/08/2020		2000				Revamp all resulted from requirement change
* Simplus MS            18/10/2021      3000                Added logic for CCRM15-79: Update related store member records 
* Simplus MS 			18/01/2022		4000				Updated methods: updateUserAddress, storeAddressUpdated for CCRM15-566:  TS onboarding email - Update fields for user's email address
******************************************************************************************************/
public without sharing class SM_Store { 
    
    public static final List<String> STORE_LOCATION_TYPES_WITH_SALES_REP = new List<String>{
        'Small Format Store', 'Frame and Truss Plant', 'Trade Distribution Centre', 'Warehouse'
    };
    public static final List<String> STORE_LOCATION_TYPES_FOR_ADDRESS_UPDATE = new List<String>{
        'Small Format Store', 'Trade Distribution Centre', 'Warehouse'
    };
	
    /**
    * @description 
    * @author Philip Clark | 19/06/2020 
    * @param newMap
    **/
    public static void afterInsert(Map<Id,Store__c> newMap) {

        createStoreMembers(newMap);

        createSalesReps(newMap);

    }

    /**
    * @description 
    * @author Yi Zhang | 27/08/2020 
    * @param oldMap 
    * @param newMap 
    **/
    public static void afterUpdate(Map<Id, Store__c> oldMap, Map<Id, Store__c> newMap) {

        updateSalesRepIds(oldMap, newMap);

        updateUserAddress(oldMap, newMap);
        
        updateStoreMembers(oldMap, newMap); //CCRM15-79: Update store member records to recalculate team member call % if store call % is changed
    }

    /**
    * @description 
    * @author Yi Zhang | 24/08/2020 
    * @param newMap 
    **/
    public static void createSalesReps(Map<Id, Store__c> newMap) {
        // get sales rep record type & country based on store's country
        Map<Id, Sales_Rep__c> salesReps = new Map<Id, Sales_Rep__c>();  // key is store Id
        for(Store__c store : newMap.values()) {
            if(String.isNotBlank(store.Location_Type__c) && STORE_LOCATION_TYPES_WITH_SALES_REP.contains(store.Location_Type__c)) {
                Sales_Rep__c sr = new Sales_Rep__c();
                sr.RecordTypeId = (store.Country__c == Constants.COUNTRY_NZ) ? DM_RecordType.rtId_SalesRep_Nz : DM_RecordType.rtId_SalesRep_Au;
                sr.Country__c = (store.Country__c == Constants.COUNTRY_NZ) ? Constants.COUNTRY_NZ : Constants.COUNTRY_AU;
                sr.Status__c = Constants.STATUS_ACTIVE;
                sr.Assigned_to_Store__c = store.Id;
                sr.Sales_Rep_Legacy_ID__c = store.Sales_Rep_ID__c;

                salesReps.put(store.Id, sr);    
            }
        }

        System.debug(LoggingLevel.DEBUG, 'salesReps: ' + JSON.serialize(salesReps));

        if(salesReps.size() > 0) {
            try {
                insert salesReps.values();
            } catch(Exception e) {
                ApplicationLogger.log('SM_Store.createSalesReps', 'Store__c', 'Trigger', e);
            }
        }
    }

    /**
    * @description 
    * @author Yi Zhang | 20/08/2020 
    * @param newMap 
    **/
    public static void createStoreMembers(Map<Id,Store__c> newMap) {
        // collect all operations region codes, and stores with codes
        List<String> opRegCodes = new List<String>();
        List<Store__c> storesWithOpRegCode = new List<Store__c>();
        for(Store__c store : newMap.values()) {
            if(String.isNotBlank(store.Operations_Region_Code__c)) {
                storesWithOpRegCode.add(store);
                opRegCodes.add(store.Operations_Region_Code__c);
            }
        }
        if(opRegCodes.isEmpty()) {
            return;
        }

         
        List<String> roles = new List<String>{Constants.STOREMEMBER_SSM_ROLENAME, Constants.STOREMEMBER_RCM_ROLENAME, Constants.STOREMEMBER_AREA_BDM_ROLENAME, Constants.STOREMEMBER_CCS_MANAGER_ROLENAME};
        // get related operations regions
        List<Operations_Region__c> opRegs = DM_OperationsRegion.getOpRegs(opRegCodes, roles);
        if(opRegs.isEmpty()) {
            return;
        }
        

        // group opRegs into Map
        Map<String, List<Operations_Region__c>> opRegCodeUsersMap = new Map<String, List<Operations_Region__c>>();
        for(Operations_Region__c opReg : opRegs) {
            if(opRegCodeUsersMap.containsKey(opReg.Name) == false) {
                opRegCodeUsersMap.put(opReg.Name, new List<Operations_Region__c>());
            }
            opRegCodeUsersMap.get(opReg.Name).add(opReg);
        }

        List<Store_Member__c> members = new List<Store_Member__c>();
        List<Task> tasks = new List<Task>();
        for(Store__c store : storesWithOpRegCode) {
            if(opRegCodeUsersMap.containsKey(store.Operations_Region_Code__c)) {
                for(Operations_Region__c opReg : opRegCodeUsersMap.get(store.Operations_Region_Code__c)) {
                    members.add(new Store_Member__c(
                        Store__c = store.Id,
                        Role__c = opReg.Role__c,
                        Status__c = Constants.STOREMEMBER_ACTIVE_STATUS,
                        Start_Date__c = Date.today(),
                        Team_Member__c = opReg.Team_Member__c
                    ));
                    if(opReg.Role__c == Constants.STOREMEMBER_SSM_ROLENAME) {
                        tasks.add(SM_Task.createTask(
                            store.Id, 
                            opReg.Team_Member__c,
                            'Assign ASM', 
                            'Please assign an ASM for store '+ store.Name, 
                            Date.today()));
                    }
                }
            }
        }

        try {
            if(members.size() > 0) {
                insert members;
            }
            if(tasks.size() > 0) {
                insert tasks;
            }
        } catch(Exception e) {
            ApplicationLogger.log('SM_Store.afterInsert', 'Store__c', 'Trigger', e);
        }
    }
    
    /**
    * @description      Update corresponding Sales Rep records' Sales Rep Legacy Id when Sales Rep ID on Store changes
    * @author Yi Zhang | 27/08/2020 
    * @param oldMap 
    * @param newMap 
    **/
    public static void updateSalesRepIds(Map<Id, Store__c> oldMap, Map<Id, Store__c> newMap) {
        List<Id> storeIds = new List<Id>();
        for(Store__c oldStore : oldMap.values()) {
            Store__c newStore = newMap.get(oldStore.Id);
            if(oldStore.Sales_Rep_ID__c != newStore.Sales_Rep_ID__c) {
                storeIds.add(newStore.Id);
            }
        }
        if(storeIds.isEmpty()) {
            return;
        }

        // System.debug(LoggingLevel.DEBUG, 'storeIds: ' + storeIds);

        // System.debug(LoggingLevel.DEBUG, 'salesReps: ' + DM_SalesRep.getActiveSalesRepsWithStoreIds(storeIds));

        // find all active sales reps associated
        List<Sales_Rep__c> salesReps = new List<Sales_Rep__c>();
        for(Sales_Rep__c salesRep : DM_SalesRep.getActiveSalesRepsWithStoreIds(storeIds)) {
            // only when the Current Sales Rep ID not the same as Store's, do the update on Legacy Id
            // this is to avoid looping
            if(salesRep.Category__c == SM_SalesRep.CATEGORY_DEFAULT && salesRep.Current_Sales_Rep_ID__c != salesRep.Assigned_to_Store__r.Sales_Rep_ID__c) {
                salesRep.Sales_Rep_Legacy_ID__c = salesRep.Assigned_to_Store__r.Sales_Rep_ID__c;
                salesReps.add(salesRep);
            }
        }

        System.debug(LoggingLevel.DEBUG, 'salesReps: ' + salesReps);

        if(salesReps.size() > 0) {
            try {
                update salesReps;
            } catch(Exception e) {
                ApplicationLogger.log('SM_Store.updateSalesRepIds', 'Store__c', 'Trigger', e);
            }
        }
    }
    

    /**
    * @description 
    * @author Yi Zhang | 22/10/2020 
    * @param oldMap 
    * @param newMap 
    **/
    public static void updateUserAddress(Map<Id, Store__c> oldMap, Map<Id, Store__c> newMap) {
        // key = location code
        Map<String, Store__c> storesAddressUpdatedMap = new Map<String, Store__c>();
        for(Store__c newStore : newMap.values()) {
            Store__c oldStore = oldMap.get(newStore.Id);
            if(storeAddressUpdated(oldStore, newStore)) {
                storesAddressUpdatedMap.put(newStore.Location_Code__c, newStore);
            }
        }
        if(storesAddressUpdatedMap.isEmpty()) {
            return;
        }

        // query all active users based on location code
        List<User> usersToUpdate = new List<User>();
        for(User user : [SELECT Id, Location_Code__c, Store_Email__c FROM User WHERE Location_Code__c IN :storesAddressUpdatedMap.keySet() AND isActive = true]) {
            usersToUpdate.add(SM_User.mapStoreAddressToUserAddress(user, storesAddressUpdatedMap.get(user.Location_Code__c)));
        }
        if(usersToUpdate.isEmpty() == false) {
            SM_User.updateUsersAsync(JSON.serialize(usersToUpdate), 'SM_Store.updateUserAddress', 'Store__c');
        }
    }

    private static Boolean storeAddressUpdated(Store__c oldStore, Store__c newStore) {
        // store's address changed
        // store is active
        // store location type is one of 3
        // store's location code is not empty
        // store's TS email changed
        return 
            (oldStore.Address_Line_1__c != newStore.Address_Line_1__c || 
            oldStore.Address_Line_2__c != newStore.Address_Line_2__c || 
            oldStore.Address_Line_3__c != newStore.Address_Line_3__c || 
            oldStore.City__c != newStore.City__c || 
            oldStore.State__c != newStore.State__c || 
            oldStore.Postcode__c != newStore.Postcode__c || 
            oldStore.Country__c != newStore.Country__c ||
			oldStore.Trade_Specialist_Email__c != newStore.Trade_Specialist_Email__c) //Added by Simplus MS 18.Jan.2022 for CCRM15-566
            && STORE_LOCATION_TYPES_FOR_ADDRESS_UPDATE.contains(newStore.Location_Type__c)
            && newStore.Status__c == Constants.STATUS_ACTIVE
            && String.isNotBlank(newStore.Location_Code__c)
            ;
    }
    
    /**
    * @description Update related store member records
    * @author Simplus MS | 20/10/2021 
    * @param oldMap, newMap
    **/
	public static void updateStoreMembers(Map<Id, Store__c> oldMap, Map<Id, Store__c> newMap) {
		Set<Id> storeIdSet = new Set<Id>();
        for(Store__c oldStMem : oldMap.values()) {
            Store__c newStMem = newMap.get(oldStMem.Id);
            if(oldStMem.Store_Call__c != newStMem.Store_Call__c ||
               oldStMem.Country__c != newStMem.Country__c ||
               oldStMem.Location_Type__c != newStMem.Location_Type__c ||
               oldStMem.Engagement_Model__c != newStMem.Engagement_Model__c) 
            {
            	storeIdSet.add(newStMem.Id);
            }
        }      
        
        List<Store_Member__c> members = [SELECT Id, Store__c, Team_Member_Call__c, Call_Volume__c 
                                           FROM Store_Member__c 
                                          WHERE Store__c IN: storeIdSet AND Role__c = :Constants.STOREMEMBER_TS_ROLENAME ];
		System.debug('members*'+members);
        try {
            if(members.size() > 0) {
                update members;
            }
        } catch(Exception e) {
            ApplicationLogger.log('SM_Store.afterUpdate', 'Store_Member__c', 'Trigger', e);
        }  
    }
}