unpackaged/main/default/objects/Application_Log__e/Application_Log__e.object-meta.xml
<CustomObject>
    <description>Object that contains unhandled exception errors &amp; outbound message</description>
    <label>Application Log PE</label>
    <pluralLabel>Application Logs</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Application_Log__e/fields/Endpoint_URL__c.field-meta.xml
<CustomField>
    <fullName>Endpoint_URL__c</fullName>
    <label>Endpoint URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application_Log__e/fields/Function_Name__c.field-meta.xml
<CustomField>
    <fullName>Function_Name__c</fullName>
    <label>Function Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ApplicationLog__c/ApplicationLog__c.object-meta.xml
<CustomObject>
    <description>Object that contains unhandled exception errors &amp; outbound message</description>
    <label>Application Log</label>
    <nameField>
        <displayFormat>Log-{000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ApplicationLog__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <inlineHelpText>JSON or XML body</inlineHelpText>
    <label>Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/ApplicationLog__c/fields/Endpoint_URL__c.field-meta.xml
<CustomField>
    <fullName>Endpoint_URL__c</fullName>
    <label>Endpoint URL</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/ApplicationLog__c/fields/Function_Name__c.field-meta.xml
<CustomField>
    <fullName>Function_Name__c</fullName>
    <description>Function where the error occurred.</description>
    <label>Function Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ApplicationLog__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ApplicationLog__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <inlineHelpText>Source of outbound message</inlineHelpText>
    <label>Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ApplicationLog__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Outbound message</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
            <value>
                <fullName>Inbound message</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/ApplicationLogETriggerHandler.cls
/*******************************************************************************************************
* Class Name      	: ApplicationLogETriggerHandler
* Description		: Trigger Handler for Application 
* Author          	: Bunnings Dev
* Created On      	: 31/03/2022
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Bunnings Dev          31/03/2022		1000				SFSUP-289 - Log COS API Callout details
******************************************************************************************************/
public class ApplicationLogETriggerHandler {

    public static void afterInsert(Map<Id, Application_Log__e> oldMap, Map<Id, Application_Log__e> newMap) {
        createApplicationLog(newMap.values());
    }

    private static List<ApplicationLog__c> createApplicationLog(List<Application_Log__e> newList) {
        List<ApplicationLog__c> appLogToInsert = new List<ApplicationLog__c>();

        if (newList.isEmpty()) {
            return null;
        }

        for (Application_Log__e appLog : newList) {
            if (appLog.Source__c.contains('SM_ClientCredProvider')) {                
                appLogToInsert.add(new ApplicationLog__c(Source__c = appLog.Source__c, Type__c = appLog.Type__c, Method__c = appLog.Method__c, 
                    Function_Name__c = appLog.Function_Name__c, Endpoint_URL__c = appLog.Endpoint_URL__c, Body__c = appLog.Body__c));
            }
        }
        
        if (!appLogToInsert.isEmpty()) {
            try {
                INSERT appLogToInsert;
            } catch (Exception e) {
                ApplicationLogger.log('ApplicationLogETriggerHandler.createApplicationLog', 'Application Log Platform Event', 'Trigger', e);
            }
        }

        return appLogToInsert;
    }
}