unpackaged/main/default/objects/Call_Targets__c/Call_Targets__c.object-meta.xml
<CustomObject>
    <description>Call targets for Account Managers.</description>
    <label>Call Targets</label>
    <nameField>
        <displayFormat>CT-{000}</displayFormat>
        <label>Call Target ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Call_Targets__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>TM_Call_Target</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Call_Targets__c/fields/Total_Target__c.field-meta.xml
<CustomField>
    <fullName>Total_Target__c</fullName>
    <formula>Phone_Target__c + In_Store_TC_Target__c + Out_of_Store_Target__c + Any_Target__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Target</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/DM_CallTargets.cls
/*******************************************************************************************************
* Class Name        : DM_CallTargets
* Description       : Data Layer - Selector for Sobject Call_Targets__c
* Author            : Simplus - Yi Zhang
* Created On        : 2020-06-18
* Modification Log  :
* -----------------------------------------------------------------------------------------------------
* Developer             Date            Modification ID     Description
* -----------------------------------------------------------------------------------------------------
* Yi Zhang              2020-06-18      1000                Initial version
******************************************************************************************************/
public with sharing class DM_CallTargets {
    /**
    * @description 
    * @author Yi Zhang | 18/06/2020 
    * @param accountManagerIds 
    * @param callTargetsIds 
    * @return List<Call_Targets__c> 
    **/
    public static List<Call_Targets__c> getRelatedCallTargets(Set<Id> accountManagerIds, Set<Id> callTargetsIds) {
        return new List<Call_Targets__c>([
            SELECT Id, Start_Date__c, End_Date__c, Team_Member__c, Total_Target__c
            FROM Call_Targets__c
            WHERE Team_Member__c IN :accountManagerIds
            AND Id NOT IN :callTargetsIds
        ]);
    }
}