unpackaged/main/default/objects/Sales_Rep_Category_Mapping__mdt/Sales_Rep_Category_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>Used to determine the category of the sales rep record (multiple records per store) to map to trade specialist&#39;s sales rep id.</description>
    <label>Sales Rep Category Mapping</label>
    <pluralLabel>Sales Rep Category Mappings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Sales_Rep_Category_Mapping__mdt/fields/Job_Role__c.field-meta.xml
<CustomField>
    <fullName>Job_Role__c</fullName>
    <description>The Bunnings job role value on User object</description>
    <inlineHelpText>The Bunnings job role value on User object</inlineHelpText>
    <label>Job Role</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Sales_Rep_Category_Mapping__mdt/fields/Sales_Rep_Category__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep_Category__c</fullName>
    <description>The category on Sales Rep object</description>
    <inlineHelpText>The category on Sales Rep object</inlineHelpText>
    <label>Sales Rep Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Landscape</fullName>
                <default>true</default>
                <label>Landscape</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/DM_SalesRepCategoryMapping.cls
/*******************************************************************************************************
* Class Name      	: DM_SalesRepCategoryMapping
* Description		: Data Layer - Selector for Custom Metadata Type Sales_Rep_Category_Mapping__mdt
* Author          	: Simplus - Yi Zhang
* Created On      	: 16/10/2020
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Yi Zhang              16/10/2020		1000				Initial version
******************************************************************************************************/
public with sharing class DM_SalesRepCategoryMapping {
    /**
    * @description 
    * @author Yi Zhang | 16/10/2020 
    * @return Map<String, String> key is Bunnings Job Role on User, value is Category on Sales Rep
    **/
    public static Map<String, String> jobRoleSalesRepCategoryMap {
        get {
            if(jobRoleSalesRepCategoryMap == null) {
                jobRoleSalesRepCategoryMap = new Map<String, String>();
                for(Sales_Rep_Category_Mapping__mdt mapping: [SELECT Id, Job_Role__c, Sales_Rep_Category__c FROM Sales_Rep_Category_Mapping__mdt]) {
                    jobRoleSalesRepCategoryMap.put(mapping.Job_Role__c, mapping.Sales_Rep_Category__c);
                }
            }
            return jobRoleSalesRepCategoryMap;
        } set;
    }
}