unpackaged/main/default/objects/Umbrella_Beneficiary__c/Umbrella_Beneficiary__c.object-meta.xml
<CustomObject>
    <description>This object is for capturing an Accounts membership to an Umbrella Group.</description>
    <label>Umbrella Beneficiary</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Umbrella Beneficiaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Umbrella_Beneficiary__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Part of Umbrella Groups</relationshipLabel>
    <relationshipName>Umbrella_Beneficiaries</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Umbrella_Beneficiary__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Active&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
            <value>
                <fullName>Transferred</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active - Sales Not Attributed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Umbrella_Beneficiary__c/fields/Umbrella_Group__c.field-meta.xml
<CustomField>
    <fullName>Umbrella_Group__c</fullName>
    <description>A lookup to the related Umbrella Group.</description>
    <label>Umbrella Group</label>
    <referenceTo>Umbrella_Group__c</referenceTo>
    <relationshipLabel>Umbrella Beneficiaries</relationshipLabel>
    <relationshipName>Umbrella_Beneficiaries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Umbrella_Group__c/Umbrella_Group__c.object-meta.xml
<CustomObject>
    <description>This is used to represent the parent/owner of a group of affiliated Accounts operating within the same Industry/segment that have grouped together for increased purchasing power and pricing leverage.</description>
    <label>Umbrella Group</label>
    <nameField>
        <displayFormat>UG-{00000}</displayFormat>
        <label>Umbrella Group Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Umbrella Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/classes/UmbrellaBeneficiaryTriggerHandler_Test.cls
/*******************************************************************************************************
* Class Name      	: UmbrellaBeneficiaryTriggerHandler_Test
* Description		: Test Class for UmbrellaBeneficiaryTriggerHandler
* Author          	: Simplus MS
* Created On      	: 18/01/2022
* Modification Log	: 
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Simplus MS            18/01/2022		1000				Initial version
******************************************************************************************************/
@IsTest
public with sharing class UmbrellaBeneficiaryTriggerHandler_Test {

    @testSetup
    static void testDataSetup(){
        
        //Create Account
        List<Account> accts = TestDataFactory.createAccounts(1);
        insert accts;

        // umbrella group
        List<Umbrella_Group__c> groups = TestDataFactory.createUmbrellaGroups(1);
        insert groups;

        // umbrella beneficiary
        List<Umbrella_Beneficiary__c> beneficiaries = TestDataFactory.createUmbrellaBeneficiaries(accts[0].Id, groups[0].Id, 1);
        insert beneficiaries;


    }

    @isTest 
    static void TestAvoidActiveDuplicateUmbrellaBeneficiaries() {
        
        Id accId = [Select Id From Account Limit 1].Id;
        Id groupId = [Select Id From Umbrella_Group__c Limit 1].Id;

        Test.startTest();
            List<Umbrella_Beneficiary__c> beneficiaries = TestDataFactory.createUmbrellaBeneficiaries(accId, groupId, 1);
            try{
                insert beneficiaries;
            }catch(Exception e){
                System.debug(e.getMessage());
                System.assertEquals(true, e.getMessage().contains(System.Label.Avoid_Duplicate_Umbrella_Beneficiaries), 'Failed to Avoid Duplicate Umbrella Beneficiaries');
            }
        Test.stopTest();
    }

    @isTest 
    static void TestAvoidInactiveDuplicateUmbrellaBeneficiaries() {
        
        Id accId = [Select Id From Account Limit 1].Id;
        Id groupId = [Select Id From Umbrella_Group__c Limit 1].Id;

        Test.startTest();
            Umbrella_Beneficiary__c umb = [Select Id, Status__c From Umbrella_Beneficiary__c Limit 1];
            umb.Status__c = 'Inactive';
            update umb;

            List<Umbrella_Beneficiary__c> beneficiaries = TestDataFactory.createUmbrellaBeneficiaries(accId, groupId, 1);
            try{
                insert beneficiaries;
            }catch(Exception e){
                System.debug(e.getMessage());
            }
        Test.stopTest();
        
        List<Umbrella_Beneficiary__c> umbList = [Select Id, Status__c From Umbrella_Beneficiary__c Where Account__c =: accId];
        System.assertEquals(2, umbList.size(), 'Failed to Avoid Duplicate Umbrella Beneficiaries');
    }
}