unpackaged/main/default/objects/Umbrella_Beneficiary__c/Umbrella_Beneficiary__c.object-meta.xml
<CustomObject>
    <description>This object is for capturing an Accounts membership to an Umbrella Group.</description>
    <label>Umbrella Beneficiary</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Umbrella Beneficiaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Umbrella_Beneficiary__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Part of Umbrella Groups</relationshipLabel>
    <relationshipName>Umbrella_Beneficiaries</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Umbrella_Beneficiary__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Active&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
            <value>
                <fullName>Transferred</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active - Sales Not Attributed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Umbrella_Beneficiary__c/fields/Umbrella_Group__c.field-meta.xml
<CustomField>
    <fullName>Umbrella_Group__c</fullName>
    <description>A lookup to the related Umbrella Group.</description>
    <label>Umbrella Group</label>
    <referenceTo>Umbrella_Group__c</referenceTo>
    <relationshipLabel>Umbrella Beneficiaries</relationshipLabel>
    <relationshipName>Umbrella_Beneficiaries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Umbrella_Group__c/Umbrella_Group__c.object-meta.xml
<CustomObject>
    <description>This is used to represent the parent/owner of a group of affiliated Accounts operating within the same Industry/segment that have grouped together for increased purchasing power and pricing leverage.</description>
    <label>Umbrella Group</label>
    <nameField>
        <displayFormat>UG-{00000}</displayFormat>
        <label>Umbrella Group Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Umbrella Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/classes/DM_UmbrellaBeneficiary.cls
/*******************************************************************************************************
* Class Name      	: DM_UmbrellaBeneficiary
* Description		: Data Layer - Selector for Sobject Umbrella_Beneficiary__c
* Author          	: Simplus - John Paul Peñaflor
* Created On      	: 24/06/2020
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* John Paul Peñaflor    24/06/2020		1000				Initial version
******************************************************************************************************/
public class DM_UmbrellaBeneficiary {
    public static List<Umbrella_Beneficiary__c> getActiveUmbrellaBeneficiariesWithGroupOwners(String accountId){
        return new List<Umbrella_Beneficiary__c>([
            SELECT Id, Umbrella_Group__r.OwnerId 
            FROM Umbrella_Beneficiary__c 
            WHERE Account__c =: accountId AND Status__c = 'Active'
        ]);
    }
}