unpackaged/main/default/objects/Umbrella_Beneficiary__c/Umbrella_Beneficiary__c.object-meta.xml
<CustomObject>
    <description>This object is for capturing an Accounts membership to an Umbrella Group.</description>
    <label>Umbrella Beneficiary</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Umbrella Beneficiaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Umbrella_Beneficiary__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Part of Umbrella Groups</relationshipLabel>
    <relationshipName>Umbrella_Beneficiaries</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Umbrella_Beneficiary__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Active&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
            <value>
                <fullName>Transferred</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active - Sales Not Attributed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Umbrella_Beneficiary__c/fields/Umbrella_Group__c.field-meta.xml
<CustomField>
    <fullName>Umbrella_Group__c</fullName>
    <description>A lookup to the related Umbrella Group.</description>
    <label>Umbrella Group</label>
    <referenceTo>Umbrella_Group__c</referenceTo>
    <relationshipLabel>Umbrella Beneficiaries</relationshipLabel>
    <relationshipName>Umbrella_Beneficiaries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Umbrella_Group__c/Umbrella_Group__c.object-meta.xml
<CustomObject>
    <description>This is used to represent the parent/owner of a group of affiliated Accounts operating within the same Industry/segment that have grouped together for increased purchasing power and pricing leverage.</description>
    <label>Umbrella Group</label>
    <nameField>
        <displayFormat>UG-{00000}</displayFormat>
        <label>Umbrella Group Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Umbrella Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/classes/UmbrellaBeneficiaryTriggerHandler.cls
/*******************************************************************************************************
* Class Name      	: UmbrellaBeneficiaryTriggerHandler
* Description		: Trigger Handler for UmbrellaBeneficiaryTrigger
* Author          	: Simplus MS
* Created On      	: 17/01/2022
* Modification Log	: 
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Simplus MS            17/01/2022		1000				Initial version
******************************************************************************************************/
public with sharing class UmbrellaBeneficiaryTriggerHandler {
    
    public static final String ERROR_AVOID_DUPLICATE_UMBRELLA_BENEFICIARIES = System.Label.Avoid_Duplicate_Umbrella_Beneficiaries;

    /**
    * @description 
    * @author Simplus MS | 17/01/2022 
    * @param newList 
    **/
    public static void beforeInsert(List<Umbrella_Beneficiary__c> newList) {
        System.debug('beforeInsert Umbrella Beneficiary** ');
        avoidDuplicateUmbrellaBeneficiaries(newList);
    }

    
    /**
    * @description 
    * @author Simplus MS | 17/01/2022 
    * @param oldMap 
    * @param newMap
    **/
    public static void beforeUpdate(Map<Id, Umbrella_Beneficiary__c> oldMap, Map<Id, Umbrella_Beneficiary__c> newMap) {
        System.debug('beforeUpdate Umbrella Beneficiary** ');
        avoidDuplicateUmbrellaBeneficiaries(newMap.values());
    }


    /**
    * @description Added for CCRM15-205
    * @author Simplus MS | 17/01/2022 
    * @param umbrellaBeneficiarys List
    **/
    public static void avoidDuplicateUmbrellaBeneficiaries(List<Umbrella_Beneficiary__c> umbrellaBeneficiaries) {
        system.debug('avoidDuplicateUmbrellaBeneficiaries'+umbrellaBeneficiaries);
        
        if(umbrellaBeneficiaries.isEmpty()) {
            return;
        }
        
        Set<Id> accounts = new Set<Id>();
        Set<Id> umgroups = new Set<Id>();
        Set<Id> umbs = new Set<Id>();

        for (Umbrella_Beneficiary__c umb : umbrellaBeneficiaries){
            umbs.add(umb.Id);
            accounts.add(umb.Account__c);
            umgroups.add(umb.Umbrella_Group__c);
        }
        
        Map<Id, Umbrella_Beneficiary__c> mapOfUmbrellaBeneficiary = new Map<Id, Umbrella_Beneficiary__c>();
        for (Umbrella_Beneficiary__c umbrellaBeneficiary : [SELECT Id, Name, Account__c, Umbrella_Group__c, Status__c 
                                                            FROM Umbrella_Beneficiary__c 
                                                            WHERE Account__c In :accounts 
                                                            AND Umbrella_Group__c IN :umgroups
                                                            AND Status__c =: Constants.STATUS_ACTIVE
                                                            AND Id NOT IN :umbs]){
            if (umbrellaBeneficiary.Status__c == Constants.STATUS_ACTIVE){
                mapOfUmbrellaBeneficiary.put(umbrellaBeneficiary.Account__c, umbrellaBeneficiary);  
            }
        }

        for(Umbrella_Beneficiary__c umbrellaBeneficiary : umbrellaBeneficiaries) {
            if((umbrellaBeneficiary.Status__c == Constants.STATUS_ACTIVE)
               && (mapOfUmbrellaBeneficiary.containsKey(umbrellaBeneficiary.Account__c)) 
               && (mapOfUmbrellaBeneficiary.get(umbrellaBeneficiary.Account__c).Umbrella_Group__c == umbrellaBeneficiary.Umbrella_Group__c)
               && (mapOfUmbrellaBeneficiary.get(umbrellaBeneficiary.Account__c).Account__c == umbrellaBeneficiary.Account__c)) {
                    umbrellaBeneficiary.addError(ERROR_AVOID_DUPLICATE_UMBRELLA_BENEFICIARIES +' Umbrella Beneficiary: '+ mapOfUmbrellaBeneficiary.get(umbrellaBeneficiary.Account__c).Name);

                    //umbrellaBeneficiary.addError('ERROR TRM100: There is already an identical record: <a href=\'https://bunnings--buildsb.lightning.force.com/lightning/r/Umbrella_Beneficiary__c/' + mapOfUmbrellaBeneficiary.get(umbrellaBeneficiary.Account__c).Id + '/view'+'>'+ mapOfUmbrellaBeneficiary.get(umbrellaBeneficiary.Account__c).Name +'</a>',  false);

                    //https://bunnings--buildsb.lightning.force.com/lightning/r/Umbrella_Beneficiary__c/a0F9D000004vehGUAQ/view

                    //String link = ' <a href="https://bunnings--buildsb.lightning.force.com/lightning/r/Umbrella_Beneficiary__c/'+ mapOfUmbrellaBeneficiary.get(umbrellaBeneficiary.Account__c).Id +'/view" target="_blank">'+ mapOfUmbrellaBeneficiary.get(umbrellaBeneficiary.Account__c).Name + '</a>';

                    //umbrellaBeneficiary.addError(ERROR_AVOID_DUPLICATE_UMBRELLA_BENEFICIARIES + link, false);

                    //umbrellaBeneficiary.addError('Same Combination of Record already Inserted in System: <a href=\'/'+ mapOfUmbrellaBeneficiary.get(umbrellaBeneficiary.Account__c).Id +'\'>'+mapOfUmbrellaBeneficiary.get(umbrellaBeneficiary.Account__c).Name+'</a>', false);
               }
        }        
    }
}