unpackaged/main/default/objects/Price_List__c/Price_List__c.object-meta.xml
<CustomObject>
    <description>This Object represents the header level of an externally mastered pricing table, which applies item level discounts for a pre-defined list of products within specific Cost Zones.</description>
    <label>Price List</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Price List Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Price_List__c/fields/Price_List_Definition__c.field-meta.xml
<CustomField>
    <fullName>Price_List_Definition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Price List Definition</description>
    <label>Price List Definition</label>
    <referenceTo>Price_List_Definition__c</referenceTo>
    <relationshipLabel>Price Lists</relationshipLabel>
    <relationshipName>Price_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Price_List__c/fields/Price_List_Header_ID__c.field-meta.xml
<CustomField>
    <fullName>Price_List_Header_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>External ID Reference for Price List</description>
    <externalId>true</externalId>
    <label>Price List Header ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Price_List__c/fields/Spend_Band__c.field-meta.xml
<CustomField>
    <fullName>Spend_Band__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Spend Band</label>
    <referenceTo>Spend_Band__c</referenceTo>
    <relationshipLabel>Price Lists</relationshipLabel>
    <relationshipName>Price_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Price_List__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Price List</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Price_List_Definition__c/Price_List_Definition__c.object-meta.xml
<CustomObject>
    <label>Price List Definition</label>
    <nameField>
        <displayFormat>PLD-{000000}</displayFormat>
        <label>Price List Definition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price List Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Price_List_Definition__c/fields/Spend_Band__c.field-meta.xml
<CustomField>
    <fullName>Spend_Band__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Associated spend band</description>
    <label>Spend Band</label>
    <referenceTo>Spend_Band__c</referenceTo>
    <relationshipLabel>Price List Definitions</relationshipLabel>
    <relationshipName>Price_List_Definitions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Pricing_Assignment_Visibility__c/Pricing_Assignment_Visibility__c.object-meta.xml
<CustomObject>
    <description>This Object controls the visibility of Price Lists and Family Tree Discount records on the Accounts &quot;Pricing Assignment&quot; flow component. Each record makes one Price List or Family Tree Discount record visible for a single Profile.</description>
    <label>Pricing Assignment Visibility</label>
    <nameField>
        <displayFormat>PAV-{00000}</displayFormat>
        <label>Pricing Assignment Visibility Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricing Assignment Visibility</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Pricing_Assignment_Visibility__c/fields/Price_List__c.field-meta.xml
<CustomField>
    <fullName>Price_List__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Price list considered for visibility</description>
    <label>Price List</label>
    <referenceTo>Price_List__c</referenceTo>
    <relationshipName>Price_List_Viisbility</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Pricing_Assignment_Visibility__c/fields/Price_List_Definition__c.field-meta.xml
<CustomField>
    <fullName>Price_List_Definition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Setting visbility based on the definition of the pice list</description>
    <label>Price List Definition</label>
    <referenceTo>Price_List_Definition__c</referenceTo>
    <relationshipLabel>Pricing Assignment Visibility</relationshipLabel>
    <relationshipName>Pricing_Assignment_Visbility</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Spend_Band__c/Spend_Band__c.object-meta.xml
<CustomObject>
    <description>Spend band ranges for customers.</description>
    <label>Spend Band</label>
    <nameField>
        <label>Spend Band</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spend Bands</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Spend_Band__c/fields/Max_Amount__c.field-meta.xml
<CustomField>
    <fullName>Max_Amount__c</fullName>
    <description>Max Spend Band Spend Amount, populated from Commercial Pricing System</description>
    <label>Max Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Spend_Band__c/fields/Min_Amount__c.field-meta.xml
<CustomField>
    <fullName>Min_Amount__c</fullName>
    <defaultValue>0.00</defaultValue>
    <description>spend band min amount</description>
    <label>Min Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Spend_Band__c/fields/Spend_Band_ID__c.field-meta.xml
<CustomField>
    <fullName>Spend_Band_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Spend Band ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/classes/DM_PriceList_Test.cls
/*******************************************************************************************************
* Class Name      	: DM_PriceList_Test
* Description		: Test class for DM_PriceList
* Author          	: Simplus - Yi Zhang
* Created On      	: 01/10/2020
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Yi Zhang              01/10/2020		1000				Initial version
* Bunnings Dev          24/10/2022      2000                BUNDIG-11664 - Test method to cover new method
******************************************************************************************************/
@isTest
private class DM_PriceList_Test {
    @isTest
    private static void testGetAvailablePriceList() {
        // Price_List_Definition__c
        Price_List_Definition__c pld = new Price_List_Definition__c();
        insert pld;
        // Price_List__c
        Price_List__c pb = new Price_List__c(Status__c = 'Active', Price_List_Definition__c = pld.Id, Price_List_Header_ID__c = String.valueOf(Math.random()));
        insert pb;
        // Pricing_Assignment_Visibility__c
        Pricing_Assignment_Visibility__c pav = new Pricing_Assignment_Visibility__c(Profile__c = 'System Administrator', Price_List_Definition__c = pld.Id);
        insert pav;
        Test.startTest();
        try {
            DM_PriceList.getAvailablePriceList(null);
        } catch(Exception e) {
        }

        DM_PriceList.getAvailablePriceList(new List<String>{'System Administrator'});
        Test.stopTest();
    }
    
    @isTest
    private static void testGetSpendBandCurrent() {
        Spend_Band__c sb = new Spend_Band__c(Name = 'Test', Min_Amount__c = 25001, Max_Amount__c = 50000, Spend_Band_Id__c = 'TEST12345');
        insert sb;
        
        Test.startTest();
        	DM_PriceList.getSpendBandCurrent(sb.Id);
        Test.stopTest();
    }
}