unpackaged/main/default/objects/Price_List__c/Price_List__c.object-meta.xml
<CustomObject>
    <description>This Object represents the header level of an externally mastered pricing table, which applies item level discounts for a pre-defined list of products within specific Cost Zones.</description>
    <label>Price List</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Price List Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Price_List__c/fields/Price_List_Definition__c.field-meta.xml
<CustomField>
    <fullName>Price_List_Definition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Price List Definition</description>
    <label>Price List Definition</label>
    <referenceTo>Price_List_Definition__c</referenceTo>
    <relationshipLabel>Price Lists</relationshipLabel>
    <relationshipName>Price_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Price_List__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Price List</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Price_List_Definition__c/Price_List_Definition__c.object-meta.xml
<CustomObject>
    <label>Price List Definition</label>
    <nameField>
        <displayFormat>PLD-{000000}</displayFormat>
        <label>Price List Definition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price List Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Price_List_Definition__c/fields/Duplicate_Active_Price_List__c.field-meta.xml
<CustomField>
    <fullName>Duplicate_Active_Price_List__c</fullName>
    <label>Duplicate Active Price List</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/PriceListTriggerHandler.cls
/*******************************************************************************************************
* Trigger Name      : PriceListTriggerHandler
* Description       : Handler for PriceListTrigger
* Author            : Jasper R. Galapon
* Created On        : 19/12/2023
* Modification Log  :
* -----------------------------------------------------------------------------------------------------
* Developer             Date            Modification ID     Description
* -----------------------------------------------------------------------------------------------------
* Jasper R. Galapon     19/12/2023      1000                BUNDIG-28056 - Initial Version
******************************************************************************************************/

public class PriceListTriggerHandler {
    
    public static void afterInsert(List<Price_List__c> newList) {
        countPriceList(newList);
    }

    public static void afterUpdate(List<Price_List__c> newList) {
        countPriceList(newList);
    }

    public static void afterDelete(List<Price_List__c> newList) {
        countPriceList(newList);
    }

    private static void countPriceList(List<Price_List__c> plList) {
        Set<Id> pldIds = new Set<Id>();
        Map<Id, Integer> parentRecordCountMap = new Map<Id, Integer>();

        for (Price_List__c pl : plList) {
            if (pl.Status__c == 'Active') {
                pldIds.add(pl.Price_List_Definition__c);
            }
        }

        for (AggregateResult aggregateResult : [SELECT Price_List_Definition__c, COUNT(Id) pldCount
            FROM Price_List__c WHERE Price_List_Definition__c IN :pldIds
            AND Status__c = 'Active'
            GROUP BY Price_List_Definition__c]) {
                Id parentId = (Id) aggregateResult.get('Price_List_Definition__c');
                Integer intCount = (Integer) aggregateResult.get('pldCount');

                // Don't count if only 1 Price List is present
                if (intCount > 1)
                    parentRecordCountMap.put(parentId, intCount);
        }

        List<Price_List_Definition__c> pldToUpdate = new List<Price_List_Definition__c>();
        for (Id pldId : pldIds) {
            Price_List_Definition__c pld = new Price_List_Definition__c(Id = pldId, Duplicate_Active_Price_List__c = parentRecordCountMap.get(pldId));
            pldToUpdate.add(pld);
        }
        update pldToUpdate;

    }

}