unpackaged/main/default/objects/Price_List__c/Price_List__c.object-meta.xml
<CustomObject>
    <description>This Object represents the header level of an externally mastered pricing table, which applies item level discounts for a pre-defined list of products within specific Cost Zones.</description>
    <label>Price List</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Price List Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Price_List__c/fields/Cost_Zone__c.field-meta.xml
<CustomField>
    <fullName>Cost_Zone__c</fullName>
    <description>Unrestricted list of cost zones</description>
    <label>Cost Zone</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ALL</fullName>
            </value>
            <value>
                <fullName>AU CZ 1</fullName>
            </value>
            <value>
                <fullName>AU CZ 2</fullName>
            </value>
            <value>
                <fullName>AU CZ 3</fullName>
            </value>
            <value>
                <fullName>NZ CZ 1</fullName>
            </value>
            <value>
                <fullName>NZ CZ 2</fullName>
            </value>
            <value>
                <fullName>NZ CZ 3</fullName>
            </value>
            <value>
                <fullName>NZ CZ 4</fullName>
            </value>
            <value>
                <fullName>NZ CZ 5</fullName>
            </value>
            <value>
                <fullName>NZ CZ 6</fullName>
            </value>
            <value>
                <fullName>NZ CZ 7</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Price_List__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Describes the Price List purpose or currency</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Price_List__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Date when Price List would end</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Price_List__c/fields/Price_List_Definition__c.field-meta.xml
<CustomField>
    <fullName>Price_List_Definition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Price List Definition</description>
    <label>Price List Definition</label>
    <referenceTo>Price_List_Definition__c</referenceTo>
    <relationshipLabel>Price Lists</relationshipLabel>
    <relationshipName>Price_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Price_List__c/fields/Price_List_Header_ID__c.field-meta.xml
<CustomField>
    <fullName>Price_List_Header_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>External ID Reference for Price List</description>
    <externalId>true</externalId>
    <label>Price List Header ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Price_List__c/fields/Price_List_Name__c.field-meta.xml
<CustomField>
    <fullName>Price_List_Name__c</fullName>
    <description>Price List Names can be up to 100 chars</description>
    <label>Price List Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Price_List__c/fields/Primary_Segment__c.field-meta.xml
<CustomField>
    <fullName>Primary_Segment__c</fullName>
    <description>The Primary Segment of the Price List</description>
    <label>Primary Segment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Price_List__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>State/Country</description>
    <label>Region</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Price_List__c/fields/Secondary_Segment__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Segment__c</fullName>
    <description>The Secondary Segment of the Price List</description>
    <label>Secondary Segment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Price_List__c/fields/Spend_Band__c.field-meta.xml
<CustomField>
    <fullName>Spend_Band__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Spend Band</label>
    <referenceTo>Spend_Band__c</referenceTo>
    <relationshipLabel>Price Lists</relationshipLabel>
    <relationshipName>Price_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Price_List__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Date when Price List would start</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Price_List__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Unrestricted list of Bunnings states</description>
    <label>State</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NATIONAL</fullName>
            </value>
            <value>
                <fullName>ACT</fullName>
            </value>
            <value>
                <fullName>NQ</fullName>
            </value>
            <value>
                <fullName>NSW</fullName>
            </value>
            <value>
                <fullName>NT</fullName>
            </value>
            <value>
                <fullName>QLD</fullName>
            </value>
            <value>
                <fullName>SA</fullName>
            </value>
            <value>
                <fullName>TAS</fullName>
            </value>
            <value>
                <fullName>VIC</fullName>
            </value>
            <value>
                <fullName>WA</fullName>
            </value>
            <value>
                <fullName>NI</fullName>
            </value>
            <value>
                <fullName>SI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Price_List__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Price List</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Price_List_Definition__c/Price_List_Definition__c.object-meta.xml
<CustomObject>
    <label>Price List Definition</label>
    <nameField>
        <displayFormat>PLD-{000000}</displayFormat>
        <label>Price List Definition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price List Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Price_List_Definition__c/fields/Cost_Zone__c.field-meta.xml
<CustomField>
    <fullName>Cost_Zone__c</fullName>
    <description>Cost zone the price list is associated to</description>
    <label>Cost Zone</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ALL</fullName>
            </value>
            <value>
                <fullName>AU CZ 1</fullName>
            </value>
            <value>
                <fullName>AU CZ 2</fullName>
            </value>
            <value>
                <fullName>AU CZ 3</fullName>
            </value>
            <value>
                <fullName>NZ CZ 1</fullName>
            </value>
            <value>
                <fullName>NZ CZ 2</fullName>
            </value>
            <value>
                <fullName>NZ CZ 3</fullName>
            </value>
            <value>
                <fullName>NZ CZ 4</fullName>
            </value>
            <value>
                <fullName>NZ CZ 5</fullName>
            </value>
            <value>
                <fullName>NZ CZ 6</fullName>
            </value>
            <value>
                <fullName>NZ CZ 7</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Price_List_Definition__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Country the prcie list is related to</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Price_List_Definition__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of the price list</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Price_List_Definition__c/fields/Price_List_Name__c.field-meta.xml
<CustomField>
    <fullName>Price_List_Name__c</fullName>
    <description>Name of the price list</description>
    <label>Price List Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Price_List_Definition__c/fields/Primary_Segment__c.field-meta.xml
<CustomField>
    <fullName>Primary_Segment__c</fullName>
    <description>Primary segment associated to the price list</description>
    <label>Primary Segment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Price_List_Definition__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Region of the price list</description>
    <label>Region</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Price_List_Definition__c/fields/Secondary_Segment__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Segment__c</fullName>
    <description>Secondary segment associated to the price list. Flat text field association. Any updates to segments on price lists to be catered by source system integration.</description>
    <label>Secondary Segment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Price_List_Definition__c/fields/Spend_Band__c.field-meta.xml
<CustomField>
    <fullName>Spend_Band__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Associated spend band</description>
    <label>Spend Band</label>
    <referenceTo>Spend_Band__c</referenceTo>
    <relationshipLabel>Price List Definitions</relationshipLabel>
    <relationshipName>Price_List_Definitions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Price_List_Definition__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Operational state associated to the price list</description>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NATIONAL</fullName>
            </value>
            <value>
                <fullName>ACT</fullName>
            </value>
            <value>
                <fullName>NQ</fullName>
            </value>
            <value>
                <fullName>NSW</fullName>
            </value>
            <value>
                <fullName>NT</fullName>
            </value>
            <value>
                <fullName>QLD</fullName>
            </value>
            <value>
                <fullName>SA</fullName>
            </value>
            <value>
                <fullName>TAS</fullName>
            </value>
            <value>
                <fullName>VIC</fullName>
            </value>
            <value>
                <fullName>WA</fullName>
            </value>
            <value>
                <fullName>NI</fullName>
            </value>
            <value>
                <fullName>SI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Pricing_Assignment_Visibility__c/Pricing_Assignment_Visibility__c.object-meta.xml
<CustomObject>
    <description>This Object controls the visibility of Price Lists and Family Tree Discount records on the Accounts &quot;Pricing Assignment&quot; flow component. Each record makes one Price List or Family Tree Discount record visible for a single Profile.</description>
    <label>Pricing Assignment Visibility</label>
    <nameField>
        <displayFormat>PAV-{00000}</displayFormat>
        <label>Pricing Assignment Visibility Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricing Assignment Visibility</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Pricing_Assignment_Visibility__c/fields/Price_List__c.field-meta.xml
<CustomField>
    <fullName>Price_List__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Price list considered for visibility</description>
    <label>Price List</label>
    <referenceTo>Price_List__c</referenceTo>
    <relationshipName>Price_List_Viisbility</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Pricing_Assignment_Visibility__c/fields/Price_List_Definition__c.field-meta.xml
<CustomField>
    <fullName>Price_List_Definition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Setting visbility based on the definition of the pice list</description>
    <label>Price List Definition</label>
    <referenceTo>Price_List_Definition__c</referenceTo>
    <relationshipLabel>Pricing Assignment Visibility</relationshipLabel>
    <relationshipName>Pricing_Assignment_Visbility</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Pricing_Assignment_Visibility__c/fields/Price_List_Name__c.field-meta.xml
<CustomField>
    <fullName>Price_List_Name__c</fullName>
    <formula>Price_List_Definition__r.Price_List_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Price List Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Spend_Band__c/Spend_Band__c.object-meta.xml
<CustomObject>
    <description>Spend band ranges for customers.</description>
    <label>Spend Band</label>
    <nameField>
        <label>Spend Band</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spend Bands</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/classes/DM_PriceList.cls
/*******************************************************************************************************
* Class Name      	: DM_PriceList
* Description		: Data Layer - Selector for Sobject Price_List__c
* Author          	: Simplus - John Paul Peñaflor
* Created On      	: 27/07/2020
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* John Paul Peñaflor    27/07/2020		1000				Initial version
* Bunnings Dev          24/10/2022      2000                BUNDIG-11664 - Allow to move next if Base Spend Band is selected
******************************************************************************************************/
public without sharing class DM_PriceList {

    @InvocableMethod
    public static List<List<Price_List__c>> getAvailablePriceList(List<String> profileName){

        List<List<Price_List__c>> availablePriceList = new List<List<Price_List__c>>();

        try {
            List<Price_List__c> priceLists = new List<Price_List__c>();

            //get all associated Pricing Visibility Record
            List<Pricing_Assignment_Visibility__c> pricingAssignmentVisibilityList = new List<Pricing_Assignment_Visibility__c>([Select Id, Price_List_Definition__c, Profile__c 
                                                                                                                                FROM Pricing_Assignment_Visibility__c 
                                                                                                                                WHERE Profile__c =: profileName[0]]);

            Set<Id> priceListDefinitionIds = new Set<Id>();                                                                                                          
            //Iterate to get Price List Definition Ids
            for(Pricing_Assignment_Visibility__c pricingAssignmentVisibility : pricingAssignmentVisibilityList){
                if(pricingAssignmentVisibility.Price_List_Definition__c != null){
                    priceListDefinitionIds.add(pricingAssignmentVisibility.Price_List_Definition__c);
                }
            }

            //Get all Price List definition Ids with Child Price List
            List<Price_List_Definition__c> priceListDefinitions = new List<Price_List_Definition__c>([Select Id, (Select Id, Name, CreatedById, CreatedDate, Description__c, End_Date__c, OwnerId, Price_List_Header_ID__c, Region__c, Spend_Band__c, Start_Date__c, Status__c, Cost_Zone__c, Country__c, Primary_Segment__c, Secondary_Segment__c, Price_List_Name__c, State__c
                                                                                                                    FROM Price_Lists__r
                                                                                                                    WHERE Status__c = 'Active')
                                                                                                        FROM Price_List_Definition__c
                                                                                                        WHERE Id IN: priceListDefinitionIds]);

            // iterate to get all children

            for(Price_List_Definition__c priceListDefinition : priceListDefinitions){
                List<Price_List__c> tempPL = new List<Price_List__c>(priceListDefinition.Price_Lists__r);
                if(!tempPL.isEmpty()){
                    priceLists.addAll(tempPL);
                }
            }

            availablePriceList.add(priceLists);
            
            return priceLists.size() > 0 ? availablePriceList : null; 
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    // BUNDIG-11664
    @AuraEnabled
    public static Spend_Band__c getSpendBandCurrent(String spendBandId) {
        return [
            SELECT Id, Name, Status__c
            FROM Spend_Band__c
            WHERE Id =:spendBandId
        ];
    }
}