unpackaged/main/default/objects/Price_List__c/Price_List__c.object-meta.xml
<CustomObject>
    <description>This Object represents the header level of an externally mastered pricing table, which applies item level discounts for a pre-defined list of products within specific Cost Zones.</description>
    <label>Price List</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Price List Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Price_List__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Date when Price List would end</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Price_List__c/fields/Price_List_Definition__c.field-meta.xml
<CustomField>
    <fullName>Price_List_Definition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Price List Definition</description>
    <label>Price List Definition</label>
    <referenceTo>Price_List_Definition__c</referenceTo>
    <relationshipLabel>Price Lists</relationshipLabel>
    <relationshipName>Price_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Price_List__c/fields/Price_List_Header_ID__c.field-meta.xml
<CustomField>
    <fullName>Price_List_Header_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>External ID Reference for Price List</description>
    <externalId>true</externalId>
    <label>Price List Header ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Price_List__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Date when Price List would start</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Price_List__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Price List</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Price_List_Definition__c/Price_List_Definition__c.object-meta.xml
<CustomObject>
    <label>Price List Definition</label>
    <nameField>
        <displayFormat>PLD-{000000}</displayFormat>
        <label>Price List Definition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price List Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/PriceListTriggerHandler_Test.cls
/*******************************************************************************************************
* Class Name      	: PriceListTriggerHandler_Test
* Description		: Test class for PriceListTriggerHandler
* Author          	: Jasper R. Galapon
* Created On      	: 19/12/2023
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Jasper R. Galapon     19/12/2023		1000				Initial version
******************************************************************************************************/

@isTest
public with sharing class PriceListTriggerHandler_Test {
    
    @isTest static void test_countPriceList() {

        Price_List_Definition__c pld = new Price_List_Definition__c();
        insert pld;

        Price_List__c pb1 = new Price_List__c(Status__c = 'Active', Price_List_Definition__c = pld.Id, Price_List_Header_ID__c = String.valueOf(Math.random()), Start_Date__c = (Date.today()), End_Date__c = Date.newInstance(2024, 12, 31));
        Price_List__c pb2 = new Price_List__c(Status__c = 'Active', Price_List_Definition__c = pld.Id, Price_List_Header_ID__c = String.valueOf(Math.random()), Start_Date__c = (Date.today()), End_Date__c = Date.newInstance(2024, 6, 30));
        Price_List__c pb3 = new Price_List__c(Status__c = 'Active', Price_List_Definition__c = pld.Id, Price_List_Header_ID__c = String.valueOf(Math.random()), Start_Date__c = (Date.today()), End_Date__c = Date.newInstance(2024, 7, 30));
        insert new List<Price_List__c>{pb1, pb2, pb3};
            
       	pb1.Status__c = 'Expired';
        update pb1;
        
        delete pb3;        
    }
}