unpackaged/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Various contracts associated to customers, projects and umbrellas. Use of custom object in place of standard considering future implementation of CPQ with contract and its line items.</description>
    <label>Contract</label>
    <nameField>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Contract__c/fields/Approver__c.field-meta.xml
<CustomField>
    <fullName>Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Approver as provided by CPS.</description>
    <label>Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract__c/fields/Contract_Name__c.field-meta.xml
<CustomField>
    <fullName>Contract_Name__c</fullName>
    <description>Name of the contract</description>
    <label>Contract Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contract__c/fields/Reviewer__c.field-meta.xml
<CustomField>
    <fullName>Reviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reviewer as provided by CPS - First level approver</description>
    <label>Reviewer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contracts1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract_Line_Item__c/Contract_Line_Item__c.object-meta.xml
<CustomObject>
    <description>Line items associated to a contract.</description>
    <label>Contract Line Item</label>
    <nameField>
        <label>Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Contract_Line_Item__c/fields/Approver__c.field-meta.xml
<CustomField>
    <fullName>Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Level 2 appover of the contract</description>
    <label>Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contract_Line_Approver</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract_Line_Item__c/fields/Auto_Approval_Eligibility__c.field-meta.xml
<CustomField>
    <fullName>Auto_Approval_Eligibility__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that the line item qualifies for automatic approval.</description>
    <label>Auto Approval Eligibility</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contract_Line_Item__c/fields/Auto_Approved__c.field-meta.xml
<CustomField>
    <fullName>Auto_Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that a line item has been automatically approved.</description>
    <label>Auto Approved</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contract_Line_Item__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <description>The associated contract</description>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Contract Line Items</relationshipLabel>
    <relationshipName>Contract_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Contract_Line_Item__c/fields/Contract_Item_ID__c.field-meta.xml
<CustomField>
    <fullName>Contract_Item_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Will hold contract line number (to be used as the external identifier)</description>
    <externalId>true</externalId>
    <label>Contract Item ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Contract_Line_Item__c/fields/Line_Status__c.field-meta.xml
<CustomField>
    <fullName>Line_Status__c</fullName>
    <description>This is only used on contract amendments

A1: Pending Level 1 Approval
A2: Pending Level 2 Approval
R1: Level 1 rejection
A : Approved (final)
R : Rejected (final)
C : Complete</description>
    <label>Line Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A1</fullName>
            </value>
            <value>
                <fullName>A2</fullName>
            </value>
            <value>
                <fullName>R1</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>X</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contract_Line_Item__c/fields/Line_Type__c.field-meta.xml
<CustomField>
    <fullName>Line_Type__c</fullName>
    <description>Contract represents the line while it is pending review of a new contract or renewal, or has been approved. Amendment represents an amendment to a line on an Active contract.</description>
    <label>Line Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Amendment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contract_Line_Item__c/fields/Reviewer__c.field-meta.xml
<CustomField>
    <fullName>Reviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Level 1 approver of the contract</description>
    <label>Reviewer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contract_Line_Reviewer</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/DM_ContractLineItem_Test.cls
/*******************************************************************************************************
* Class Name      	: DM_ContractLineItem_Test
* Description		: Test class for DM_ContractLineItem
* Author          	: Bunnings Dev
* Created On      	: 13/06/2023
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Jasper R. Galapon     13/06/2023		1000				Initial version
* Jasper R. Galapon		11/09/2024		1001				BUNDIG-35762 - Increase test coverage
******************************************************************************************************/
@isTest
public class DM_ContractLineItem_Test {
        
    @isTest
    public static void test_getItems() {
        Test.startTest();
        	System.assertEquals(0, DM_ContractLineItem.getItems(new List<String>{'test'}).size(),'aa');
        Test.stopTest();
    }
    
    @isTest
    public static void test_getItemsForDynamicFiltering() {
        Test.startTest();
        	System.assertEquals(0, DM_ContractLineItem.getItemsForDynamicFiltering('test').size(), 'no contract line item found');
        Test.stopTest();
    }
    
    @isTest
    public static void test_getAmendmentItems() {
        Test.startTest();
        	System.assertEquals(0, DM_ContractLineItem.getAmendmentItems('test'));
        Test.stopTest();
    }

    @isTest
    public static void test_getItemsWithSpecialBuyItems() {
        Test.startTest();        	
        	System.assertEquals(0, DM_ContractLineItem.getItemsWithSpecialBuyItems('TESTID', new List<String>{'Contract'}, new List<String>{'Pending'}).size(), 'No contract found');
        Test.stopTest();
    }
    
    @isTest
    public static void test_getItem() {
        Contract__c con = new Contract__c(Name = 'Test Contract');
        insert con;
        
        Contract_Line_Item__c cli_Item = new Contract_Line_Item__c(Name = 'Test Item', Contract__c = con.Id, Contract_Item_Id__c = 'TESTITEMID');
        insert cli_Item;
        
        Test.startTest();
        	Contract_Line_Item__c cli = DM_ContractLineItem.getItem(cli_Item.Id);        	
        Test.stopTest();
        
        System.assertEquals(cli_Item.Id, cli.Id, 'The retrieved item ID should match the test item ID');
        System.assertEquals(cli_Item.Name, cli.Name, 'The retrieved item Name should match the test item Name');        
    }
    
    @isTest
    public static void test_getAmendmentItemsByReviewOrApprover() {
        Id profileId = [SELECT Id FROM Profile WHERE NAME = 'Account Manager' LIMIT 1].Id;
        List<User> users = TestDataFactory.createUsers(1, profileId);
        System.runAs(new User(Id = UserInfo.getUserId())) {
        	insert users;
        }
        
        List<Contract__c> contracts = TestDataFactory.createContracts(1);
        contracts[0].Contract_Name__c = 'Test Name';
		contracts[0].Reviewer__c = users[0].Id;
        contracts[0].Approver__c = users[0].Id;
		insert contracts;
        
        Contract_Line_Item__c items = new Contract_Line_Item__c(Name = 'Test Item', Line_Type__c = 'Amendment', Line_Status__c = 'A1',
			Contract_Item_Id__c = 'TestItemId', Contract__c = contracts[0].Id);
        insert items;
        
        Test.startTest();
        	List<Contract_Line_Item__c> cli = DM_ContractLineItem.getAmendmentItemsByReviewOrApprover(contracts[0].Id, new List<String>{'Amendment'}, new List<String>{'A1'}, users[0].Id);
        Test.stopTest();
        
        System.assertEquals(1, cli.size(), 'Expected 1 Contract Line Item to be returned');
    }
    
    @isTest
    public static void test_countAmendmentLines() {
        Id profileId = [SELECT Id FROM Profile WHERE NAME = 'Account Manager' LIMIT 1].Id;
        List<User> users = TestDataFactory.createUsers(1, profileId);
        System.runAs(new User(Id = UserInfo.getUserId())) {
        	insert users;
        }
        
        List<Contract__c> contracts = TestDataFactory.createContracts(1);
        contracts[0].Contract_Name__c = 'Test Name';
		contracts[0].Reviewer__c = users[0].Id;
        contracts[0].Approver__c = users[0].Id;
		insert contracts;
        
        Contract_Line_Item__c items = new Contract_Line_Item__c(Name = 'Test Item', Line_Type__c = 'Amendment', Line_Status__c = 'A1',
			Contract_Item_Id__c = 'TestItemId', Contract__c = contracts[0].Id, Auto_Approval_Eligibility__c = true, Auto_Approved__c = false);
        insert items;               
        
        Test.startTest();
        	List<Contract_Line_Item__c> cli = DM_ContractLineItem.countAmendmentLines(contracts[0].Id, 'A1');
        Test.stopTest();
        
        System.assertEquals(1, cli.size(), 'Expected one Contract Line Item to be returned');
    }
}