unpackaged/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Various contracts associated to customers, projects and umbrellas. Use of custom object in place of standard considering future implementation of CPQ with contract and its line items.</description>
    <label>Contract</label>
    <nameField>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Contract__c/fields/Approver__c.field-meta.xml
<CustomField>
    <fullName>Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Approver as provided by CPS.</description>
    <label>Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract__c/fields/Approver_Action__c.field-meta.xml
<CustomField>
    <fullName>Approver_Action__c</fullName>
    <description>Approver action - Approved / Rejected</description>
    <label>Approver Action</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contract__c/fields/Approver_Action_Date__c.field-meta.xml
<CustomField>
    <fullName>Approver_Action_Date__c</fullName>
    <description>The date the approver took action on the contract.</description>
    <label>Approver Action Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contract__c/fields/Approver_Comments__c.field-meta.xml
<CustomField>
    <fullName>Approver_Comments__c</fullName>
    <description>Any comments from the approver.</description>
    <label>Approver Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contract__c/fields/Contract_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Contract_Approval_Status__c</fullName>
    <label>Customer Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Load</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>Customer Rejected</fullName>
            </value>
            <value>
                <fullName>Customer Approved</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <isActive>false</isActive>
                <label>Active</label>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Expired</fullName>
                <isActive>false</isActive>
                <label>Expired</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <isActive>false</isActive>
                <label>Rejected</label>
            </value>
            <value>
                <fullName>Reviewed</fullName>
                <isActive>false</isActive>
                <label>Reviewed</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
                <isActive>false</isActive>
                <label>Submitted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contract__c/fields/Contract_Locked__c.field-meta.xml
<CustomField>
    <fullName>Contract_Locked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Always populated and updated by CPS - used to lock a contract from being updated during the review process</description>
    <label>Contract Locked</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contract__c/fields/Contract_Name__c.field-meta.xml
<CustomField>
    <fullName>Contract_Name__c</fullName>
    <description>Name of the contract</description>
    <label>Contract Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contract__c/fields/Cost_Zone__c.field-meta.xml
<CustomField>
    <fullName>Cost_Zone__c</fullName>
    <label>Cost Zone</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ALL</fullName>
            </value>
            <value>
                <fullName>AU CZ 1</fullName>
            </value>
            <value>
                <fullName>AU CZ 2</fullName>
            </value>
            <value>
                <fullName>AU CZ 3</fullName>
            </value>
            <value>
                <fullName>NZ CZ 1</fullName>
            </value>
            <value>
                <fullName>NZ CZ 2</fullName>
            </value>
            <value>
                <fullName>NZ CZ 3</fullName>
            </value>
            <value>
                <fullName>NZ CZ 4</fullName>
            </value>
            <value>
                <fullName>NZ CZ 5</fullName>
            </value>
            <value>
                <fullName>NZ CZ 6</fullName>
            </value>
            <value>
                <fullName>NZ CZ 7</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contract__c/fields/Original_Approver__c.field-meta.xml
<CustomField>
    <fullName>Original_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Original approver of the contract. This will help determine who to return the review to after delegation is completed.</description>
    <label>Original Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>OriginalApprover</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract__c/fields/Original_Reviewer__c.field-meta.xml
<CustomField>
    <fullName>Original_Reviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Original reviwer of the contract. This will help determine who to return the review to after delegation is completed.</description>
    <label>Original Reviewer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>OriginalReviewer</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract__c/fields/Previous_Approver_Record__c.field-meta.xml
<CustomField>
    <fullName>Previous_Approver_Record__c</fullName>
    <description>Store Approvers comments, action date, action and name.</description>
    <label>Previous Approver Record</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Contract__c/fields/Previous_Header_ID__c.field-meta.xml
<CustomField>
    <fullName>Previous_Header_ID__c</fullName>
    <description>Populated when a contract comes in for renewal.</description>
    <label>Previous Header ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contract__c/fields/Previous_Reviewer_Record__c.field-meta.xml
<CustomField>
    <fullName>Previous_Reviewer_Record__c</fullName>
    <description>Store Reviewer comments, action date, action and name.</description>
    <label>Previous Reviewer Record</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contract__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Associated Project</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract__c/fields/Reviewer__c.field-meta.xml
<CustomField>
    <fullName>Reviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reviewer as provided by CPS - First level approver</description>
    <label>Reviewer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contracts1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract__c/fields/Reviewer_Action__c.field-meta.xml
<CustomField>
    <fullName>Reviewer_Action__c</fullName>
    <description>Reviewer Action - Approved / Rejected</description>
    <label>Reviewer Action</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contract__c/fields/Reviewer_Action_Date__c.field-meta.xml
<CustomField>
    <fullName>Reviewer_Action_Date__c</fullName>
    <description>The date that the Approver took action on the Contract.</description>
    <label>Reviewer Action Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contract__c/fields/Reviewer_Comments__c.field-meta.xml
<CustomField>
    <fullName>Reviewer_Comments__c</fullName>
    <description>Any comments from the Approver.</description>
    <label>Reviewer Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contract__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Unrestricted list of Bunnings states</description>
    <label>State</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NATIONAL</fullName>
            </value>
            <value>
                <fullName>ACT</fullName>
            </value>
            <value>
                <fullName>NQ</fullName>
            </value>
            <value>
                <fullName>NSW</fullName>
            </value>
            <value>
                <fullName>NT</fullName>
            </value>
            <value>
                <fullName>QLD</fullName>
            </value>
            <value>
                <fullName>SA</fullName>
            </value>
            <value>
                <fullName>TAS</fullName>
            </value>
            <value>
                <fullName>VIC</fullName>
            </value>
            <value>
                <fullName>WA</fullName>
            </value>
            <value>
                <fullName>NI</fullName>
            </value>
            <value>
                <fullName>SI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the contract</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>This object is used for grouping Opportunities related to a single construction project.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Project__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The Status of the Project eg. Quotation</description>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Documentation</fullName>
            </value>
            <value>
                <fullName>Tender</fullName>
            </value>
            <value>
                <fullName>Post Tender</fullName>
            </value>
            <value>
                <fullName>Builder Appointed</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Closed - Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/User/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>&quot;None&quot;</defaultValue>
    <description>This field is used in sharing rules to define a AU User&#39;s and NZ User&#39;s</description>
    <inlineHelpText>This field is used in sharing rules to define a AU User&#39;s and NZ User&#39;s</inlineHelpText>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/DM_Contract.cls
/*******************************************************************************************************
* Class Name      	: DM_Contract
* Description		: Data Layer - Selector for Sobject Contract__c
* Author          	: Simplus - Yi Zhang
* Created On      	: 2020-05-21
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Yi Zhang              2020-05-21		1000				Initial version
* Philip Clark			01/07/2020		1001				getContractsbyOrigReviewerApprover
* Yi Zhang              2020-07-16		1002			    Remove 4 deleted fields from all queries
* Simplus Ms            2022-02-24		1003			    Logic added for SFSUP-361 - Contract review - History comment from A1 & A2
******************************************************************************************************/
public with sharing class DM_Contract {
    
    /**
    * @description 
    * @author Yi Zhang | 21/05/2020 
    * @param contractIds 
    * @return List<Contract__c> 
    **/
    public static List<Contract__c> getContracts(List<String> contractIds) {
        // Contract Number, Contract Name, State, Cost Zone to start with
        return [
            SELECT Id, Contract_Name__c, Name, State__c, Cost_Zone__c, Country__c, Status__c,
            Previous_Header_ID__c, Contract_Locked__c, 
            Original_Approver__c, Approver__c, Approver__r.Name, Approver_Action__c, Approver_Action_Date__c, Approver_Comments__c,
            Original_Reviewer__c, Reviewer__c, Reviewer__r.Name, Reviewer_Action__c, Reviewer_Action_Date__c, Reviewer_Comments__c, 
            Contract_Approval_Status__c, Project__c, Previous_Approver_Record__c,Previous_Reviewer_Record__c
            FROM Contract__c
            WHERE Id IN :contractIds
        ];
    }

    /**
    * @description 
    * @author Simplus Ms | 24/02/2022 
    * @param contractId 
    * @return List<Contract__History> 
    **/
    public static List<Contract__History> getContractHistory(Id contractId) {
        return [
            SELECT Id, CreatedDate, Field, CreatedBy.Name, OldValue, NewValue, Parent.Name FROM Contract__History WHERE ParentId = :contractId
            ORDER BY CreatedDate DESC
        ];
    }
    
    /**
    * @description 
    * @author Philip Clark | 01/07/2020 
    * @param userIds 
    * @return List<Contract__c> 
    **/
    public static List<Contract__c> getContractsbyReviewerApprover(set<Id> userIds) {
        // Contract Number, Contract Name, State, Cost Zone to start with
        return [
            SELECT Id, Contract_Name__c, Name, State__c, Cost_Zone__c, Country__c, Status__c,
            Previous_Header_ID__c, Contract_Locked__c, 
            Original_Approver__c, Approver__c, Approver__r.Name, Approver_Action__c, Approver_Action_Date__c, Approver_Comments__c,
            Original_Reviewer__c, Reviewer__c, Reviewer__r.Name, Reviewer_Action__c, Reviewer_Action_Date__c, Reviewer_Comments__c, 
            Contract_Approval_Status__c, Previous_Approver_Record__c, Previous_Reviewer_Record__c
            FROM Contract__c
            WHERE Approver__c IN :userIds OR Reviewer__c IN :userIds
        ];
    }
    
    /**
    * @description 
    * @author Philip Clark | 01/07/2020 
    * @param userIds 
    * @return List<Contract__c> 
    **/
    public static List<Contract__c> getContractsbyOrigReviewerApprover(set<Id> userIds) {
        // Contract Number, Contract Name, State, Cost Zone to start with
        return [
            SELECT Id, Contract_Name__c, Name, State__c, Cost_Zone__c, Country__c, Status__c,
            Previous_Header_ID__c, Contract_Locked__c, 
            Original_Approver__c, Approver__c, Approver__r.Name, Approver_Action__c, Approver_Action_Date__c, Approver_Comments__c,
            Original_Reviewer__c, Reviewer__c, Reviewer__r.Name, Reviewer_Action__c, Reviewer_Action_Date__c, Reviewer_Comments__c, 
            Contract_Approval_Status__c, Previous_Approver_Record__c, Previous_Reviewer_Record__c
            FROM Contract__c
            WHERE Original_Approver__c IN :userIds OR Original_Reviewer__c IN :userIds
        ];
    }

    /**
    * @description 
    * @author Yi Zhang | 21/05/2020 
    * @param contractId 
    * @return Contract__c 
    **/
    public static Contract__c getContract(String contractId) {
        return getContracts(new List<String>{contractId})[0];
    }
}