unpackaged/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Various contracts associated to customers, projects and umbrellas. Use of custom object in place of standard considering future implementation of CPQ with contract and its line items.</description>
    <label>Contract</label>
    <nameField>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Contract__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Associated Project</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the contract</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>This object is used for grouping Opportunities related to a single construction project.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The Status of the Project eg. Quotation</description>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Documentation</fullName>
            </value>
            <value>
                <fullName>Tender</fullName>
            </value>
            <value>
                <fullName>Post Tender</fullName>
            </value>
            <value>
                <fullName>Builder Appointed</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Closed - Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Project_Participant__c/Project_Participant__c.object-meta.xml
<CustomObject>
    <description>This junction object captures the relationship between an Account and a construction Project. This object also captures the relationship between a &quot;Project Specific Contract&quot;, and the Accounts with Access to the Project Specific Pricing.</description>
    <label>Project Participant</label>
    <nameField>
        <displayFormat>PP-{00000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Project_Participant__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Project Participants</relationshipLabel>
    <relationshipName>Project_Groups</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Project_Participant__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A lookup to the related Contract.</description>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipName>Project_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Project_Participant__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>A lookup to the related Project.</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Project_Groups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Project_Participant__c/fields/Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Type__c</fullName>
    <label>Relationship Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary Builder</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>Estimator</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Project_Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active - Not on Contract</fullName>
                <default>true</default>
                <label>Active - Not on Contract</label>
            </value>
            <value>
                <fullName>Active - On Contract</fullName>
            </value>
            <value>
                <fullName>Request for Contract Addition</fullName>
            </value>
            <value>
                <fullName>Request for Contract Change</fullName>
            </value>
            <value>
                <fullName>Request for Contract Removal</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>.</fullName>
                <isActive>false</isActive>
                <label>.</label>
            </value>
            <value>
                <fullName>Active</fullName>
                <isActive>false</isActive>
                <label>Active</label>
            </value>
            <value>
                <fullName>On Contract</fullName>
                <isActive>false</isActive>
                <label>On Contract</label>
            </value>
            <value>
                <fullName>Request tor Contract</fullName>
                <isActive>false</isActive>
                <label>Request tor Contract</label>
            </value>
            <value>
                <fullName>Request tor Contract Addition</fullName>
                <isActive>false</isActive>
                <label>Request tor Contract Addition</label>
            </value>
            <value>
                <fullName>Request tor Contract Change</fullName>
                <isActive>false</isActive>
                <label>Request tor Contract Change</label>
            </value>
            <value>
                <fullName>Request tor Contract Removal</fullName>
                <isActive>false</isActive>
                <label>Request tor Contract Removal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/DM_ProjectParticipant.cls
/*******************************************************************************************************
* Class Name      	: DM_ProjectParticipant
* Description		: Data Layer - Selector for Sobject Project Participant
* Author          	: Simplus - John Paul Peñaflor
* Created On      	: 17/08/2020
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* John Paul Peñaflor    17/08/2020		1000				Initial version
******************************************************************************************************/
public class DM_ProjectParticipant {
	
    /**
    * @description 
    * @author John Paul Peñaflor | 17/08/2020
    * @param contractIds 
    * @return List<Project_Participant__c> 
    **/
    public static List<Project_Participant__c> getProjectParticipants(Set<String> contractIds){
        
        return new List<Project_Participant__c>([SELECT Id, Name, Contract__c, Project__c, Status__c, Relationship_Type__c, Account__c 
                                                                                                    FROM Project_Participant__c 
                                                                                                    WHERE Contract__c IN: contractIds]);                                                 
    }

    /**
    * @description 
    * @author John Paul Peñaflor | 17/08/2020
    * @param projectIds 
    * @param accountIds 
    * @return List<Project_Participant__c> 
    **/
    public static List<Project_Participant__c> getProjectParticipants(Set<String> projectIds, Set<String> accountIds){
        return new List<Project_Participant__c>([SELECT Id, Name, Contract__c, Project__c, Status__c, Relationship_Type__c, Account__c 
                                                                                                    FROM Project_Participant__c 
                                                                                                    WHERE Project__c IN: projectIds AND Account__c IN: accountIds]);
    }

    /**
    * @description 
    * @author John Paul Peñaflor | 17/08/2020
    * @param projectIds 
    * @param accountIds 
    * @return List<Project_Participant__c> 
    **/
    public static List<Project_Participant__c> getNoContractProjectParticipants(Set<String> projectIds, Set<String> accountIds){
        return new List<Project_Participant__c>([SELECT Id, Name, Contract__c, Project__c, Status__c, Relationship_Type__c, Account__c 
                                                                                                    FROM Project_Participant__c 
                                                                                                    WHERE Project__c IN: projectIds AND Account__c IN: accountIds AND Contract__c = null]);
    }
}