unpackaged/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Various contracts associated to customers, projects and umbrellas. Use of custom object in place of standard considering future implementation of CPQ with contract and its line items.</description>
    <label>Contract</label>
    <nameField>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Contract__c/fields/Contract_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Contract_Approval_Status__c</fullName>
    <label>Customer Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Load</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>Customer Rejected</fullName>
            </value>
            <value>
                <fullName>Customer Approved</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <isActive>false</isActive>
                <label>Active</label>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Expired</fullName>
                <isActive>false</isActive>
                <label>Expired</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <isActive>false</isActive>
                <label>Rejected</label>
            </value>
            <value>
                <fullName>Reviewed</fullName>
                <isActive>false</isActive>
                <label>Reviewed</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
                <isActive>false</isActive>
                <label>Submitted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contract_Line_Item__c/Contract_Line_Item__c.object-meta.xml
<CustomObject>
    <description>Line items associated to a contract.</description>
    <label>Contract Line Item</label>
    <nameField>
        <label>Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Contract_Line_Item__c/fields/Auto_Approval_Eligibility__c.field-meta.xml
<CustomField>
    <fullName>Auto_Approval_Eligibility__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that the line item qualifies for automatic approval.</description>
    <label>Auto Approval Eligibility</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contract_Line_Item__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <description>The associated contract</description>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Contract Line Items</relationshipLabel>
    <relationshipName>Contract_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Contract_Line_Item__c/fields/Contract_Item_ID__c.field-meta.xml
<CustomField>
    <fullName>Contract_Item_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Will hold contract line number (to be used as the external identifier)</description>
    <externalId>true</externalId>
    <label>Contract Item ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Contract_Line_Item__c/fields/Line_Status__c.field-meta.xml
<CustomField>
    <fullName>Line_Status__c</fullName>
    <description>This is only used on contract amendments

A1: Pending Level 1 Approval
A2: Pending Level 2 Approval
R1: Level 1 rejection
A : Approved (final)
R : Rejected (final)
C : Complete</description>
    <label>Line Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A1</fullName>
            </value>
            <value>
                <fullName>A2</fullName>
            </value>
            <value>
                <fullName>R1</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>X</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contract_Line_Item__c/fields/Line_Type__c.field-meta.xml
<CustomField>
    <fullName>Line_Type__c</fullName>
    <description>Contract represents the line while it is pending review of a new contract or renewal, or has been approved. Amendment represents an amendment to a line on an Active contract.</description>
    <label>Line Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Amendment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Object_Event_Bridge__c/Object_Event_Bridge__c.object-meta.xml
<CustomObject>
    <label>Object Event Bridge</label>
    <nameField>
        <displayFormat>OEBR{000000000}</displayFormat>
        <label>Object Event Bridge Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Object Event Bridges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/SM_CLIAutoApprovalBatchTest.cls
/*******************************************************************************************************
* Class Name      	: SM_CLIAutoApprovalBatchTest
* Description		: Test class for SM_CLIAutoApprovalBatch
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Jasper R. Galapon     30/07/2024		1000				BUNDIG-34611 - Initial version 
******************************************************************************************************/

@isTest
private class SM_CLIAutoApprovalBatchTest {

    @TestSetup
    static void makeData() {
        List<Contract__c> contracts = TestDataFactory.createContracts(1);
        contracts[0].Contract_Approval_Status__c = 'Customer Approved';
        insert contracts;
                
        List<Contract_Line_Item__c> clis = new List<Contract_Line_Item__c>();
        Integer index = 0;
        String rand = String.valueOf(Math.random());
        for (Integer i = 0; i < 5; i++) {
            Contract_Line_Item__c cli = new Contract_Line_Item__c(Contract__c = contracts[0].Id, Line_Status__c = 'A1', Line_Type__c = 'Amendment',
				Auto_Approval_Eligibility__c = TRUE, CreatedDate = Date.today().addDays(-10), Contract_Item_ID__c = rand + ' ' + i);
            clis.add(cli);
        }
        insert clis;        
    }
    
    @isTest
    static void CLIAutoApprovalBatchTest() {
        // Get the Contract Line Items
        List<Contract_Line_Item__c> clis = [SELECT Id FROM Contract_Line_Item__c];
        System.assertEquals(5, clis.size(), 'Expected 5 Contract Line Items');
        
        Test.startTest();
        	Date tmpDate = Date.today() - 10;
        	String strDate = String.valueOf(tmpDate);
            SM_CLIAutoApprovalBatch batch = new SM_CLIAutoApprovalBatch(strDate);
            Database.executeBatch(batch);
        Test.stopTest();
                
        List<Object_Event_Bridge__c> oebs = [SELECT Id FROM Object_Event_Bridge__c];
        System.assertEquals(5, oebs.size(), 'Expected 5 Object Event Bridge records');
    }
    
	@isTest
	static void SchedulerTest() {
        Test.startTest();
        	String jobId = System.schedule('Test SM_CLIAutoApprovalBatch', '0 0 23 * * ?', new SM_CLIAutoApprovalBatchScheduler());
        Test.stopTest();
                
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE Id = :jobId];
        System.assertEquals('0 0 23 * * ?', ct.CronExpression);
        System.assertEquals(0, ct.TimesTriggered);
    }

}