unpackaged/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Various contracts associated to customers, projects and umbrellas. Use of custom object in place of standard considering future implementation of CPQ with contract and its line items.</description>
    <label>Contract</label>
    <nameField>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Contract__c/fields/Original_Reviewer__c.field-meta.xml
<CustomField>
    <fullName>Original_Reviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Original reviwer of the contract. This will help determine who to return the review to after delegation is completed.</description>
    <label>Original Reviewer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>OriginalReviewer</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the contract</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Customer_Contract__c/Customer_Contract__c.object-meta.xml
<CustomObject>
    <label>Customer Contract</label>
    <nameField>
        <displayFormat>CC-{00000000}</displayFormat>
        <label>Customer Contract</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Contract__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <description>Contract for customer contract</description>
    <inlineHelpText>Contract for customer contract</inlineHelpText>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Customer Contracts</relationshipLabel>
    <relationshipName>Customer_Contracts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/SM_CustomerContract.cls
/*******************************************************************************************************
* Class Name      	: SM_CustomerContract
* Description		: Domain / Service Layer for Sobject Customer Contract
* Author          	: Simplus - Yi Zhang
* Created On      	: 14/05/2020
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Yi Zhang              14/05/2020		1000				Initial version
******************************************************************************************************/
public with sharing class SM_CustomerContract {
    /**
    * @description 
    * @author       Yi Zhang | 15/05/2020 
    * @param        contracts 
    * @param        ownerId 
    * @return       Integer 
    **/
    public static Integer getNumberOfContractsBelongTo(List<Customer_Contract__c> contracts, Id ownerId) {
        Integer n = 0;
        for(Customer_Contract__c cc : contracts) {
            if(cc.Contract__c != null && cc.Contract__r.OwnerId == ownerId) {
                n ++;
            }
        }
        return n;
    }

    /**
    * @description  Count the numbers of contracts which are non-expired
    * @author       Yi Zhang | 14/07/2020 
    * @param        contracts 
    * @return       Integer 
    **/
    public static Integer countNonExpiredContracts(List<Customer_Contract__c> contracts) {
        Integer n = 0;
        for(Customer_Contract__c cc : contracts) {
            if(cc.Contract__r.Status__c != Constants.CONTRACT_STATUS_EXPIRED) {
                n ++;
            }
        }
        return n;
    }

    /**
    * @description  Count the number of contracts which are: 1) non-expired, 2) orignal reviewer = account owner
    * @author       Yi Zhang | 14/07/2020 
    * @param        contracts 
    * @param        accountOwnerId 
    * @return       Integer 
    **/
    public static Integer countNonExpiredContractsWithOriginalReviewerSameAsAccountOwner(List<Customer_Contract__c> contracts, Id accountOwnerId) {
        Integer n = 0;
        for(Customer_Contract__c cc : contracts) {
            if(cc.Contract__r.Status__c != Constants.CONTRACT_STATUS_EXPIRED && cc.Contract__r.Original_Reviewer__c == accountOwnerId) {
                n ++;
            }
        }
        return n;
    }
}