unpackaged/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Various contracts associated to customers, projects and umbrellas. Use of custom object in place of standard considering future implementation of CPQ with contract and its line items.</description>
    <label>Contract</label>
    <nameField>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Contract__c/fields/Approver_Action__c.field-meta.xml
<CustomField>
    <fullName>Approver_Action__c</fullName>
    <description>Approver action - Approved / Rejected</description>
    <label>Approver Action</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contract__c/fields/Approver_Action_Date__c.field-meta.xml
<CustomField>
    <fullName>Approver_Action_Date__c</fullName>
    <description>The date the approver took action on the contract.</description>
    <label>Approver Action Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contract__c/fields/Approver_Comments__c.field-meta.xml
<CustomField>
    <fullName>Approver_Comments__c</fullName>
    <description>Any comments from the approver.</description>
    <label>Approver Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contract__c/fields/Contract_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Contract_Approval_Status__c</fullName>
    <label>Customer Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Load</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>Customer Rejected</fullName>
            </value>
            <value>
                <fullName>Customer Approved</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <isActive>false</isActive>
                <label>Active</label>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Expired</fullName>
                <isActive>false</isActive>
                <label>Expired</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <isActive>false</isActive>
                <label>Rejected</label>
            </value>
            <value>
                <fullName>Reviewed</fullName>
                <isActive>false</isActive>
                <label>Reviewed</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
                <isActive>false</isActive>
                <label>Submitted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contract__c/fields/Contract_Name__c.field-meta.xml
<CustomField>
    <fullName>Contract_Name__c</fullName>
    <description>Name of the contract</description>
    <label>Contract Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contract__c/fields/Reviewer_Action__c.field-meta.xml
<CustomField>
    <fullName>Reviewer_Action__c</fullName>
    <description>Reviewer Action - Approved / Rejected</description>
    <label>Reviewer Action</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contract__c/fields/Reviewer_Action_Date__c.field-meta.xml
<CustomField>
    <fullName>Reviewer_Action_Date__c</fullName>
    <description>The date that the Approver took action on the Contract.</description>
    <label>Reviewer Action Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contract__c/fields/Reviewer_Comments__c.field-meta.xml
<CustomField>
    <fullName>Reviewer_Comments__c</fullName>
    <description>Any comments from the Approver.</description>
    <label>Reviewer Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contract__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Unrestricted list of Bunnings states</description>
    <label>State</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NATIONAL</fullName>
            </value>
            <value>
                <fullName>ACT</fullName>
            </value>
            <value>
                <fullName>NQ</fullName>
            </value>
            <value>
                <fullName>NSW</fullName>
            </value>
            <value>
                <fullName>NT</fullName>
            </value>
            <value>
                <fullName>QLD</fullName>
            </value>
            <value>
                <fullName>SA</fullName>
            </value>
            <value>
                <fullName>TAS</fullName>
            </value>
            <value>
                <fullName>VIC</fullName>
            </value>
            <value>
                <fullName>WA</fullName>
            </value>
            <value>
                <fullName>NI</fullName>
            </value>
            <value>
                <fullName>SI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the contract</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contract_Line_Item__c/Contract_Line_Item__c.object-meta.xml
<CustomObject>
    <description>Line items associated to a contract.</description>
    <label>Contract Line Item</label>
    <nameField>
        <label>Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Contract_Line_Item__c/fields/Amendment_Type__c.field-meta.xml
<CustomField>
    <fullName>Amendment_Type__c</fullName>
    <description>Type of amendment.</description>
    <label>Amendment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Add</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contract_Line_Item__c/fields/Approver_Action__c.field-meta.xml
<CustomField>
    <fullName>Approver_Action__c</fullName>
    <label>Approver Action</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contract_Line_Item__c/fields/Approver_Action_Date__c.field-meta.xml
<CustomField>
    <fullName>Approver_Action_Date__c</fullName>
    <description>Date approver took the action.</description>
    <label>Approver Action Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contract_Line_Item__c/fields/Approver_Comments__c.field-meta.xml
<CustomField>
    <fullName>Approver_Comments__c</fullName>
    <description>Comments by approver.</description>
    <label>Approver Comments</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contract_Line_Item__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <description>The associated contract</description>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Contract Line Items</relationshipLabel>
    <relationshipName>Contract_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Contract_Line_Item__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <formula>TEXT(Contract__r.Country__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contract_Line_Item__c/fields/Reviewer_Action__c.field-meta.xml
<CustomField>
    <fullName>Reviewer_Action__c</fullName>
    <description>Approved / Rejected by reviewer.</description>
    <label>Reviewer Action</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contract_Line_Item__c/fields/Reviewer_Action_Date__c.field-meta.xml
<CustomField>
    <fullName>Reviewer_Action_Date__c</fullName>
    <description>Date reviewer took the action.</description>
    <label>Reviewer Action Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contract_Line_Item__c/fields/Reviewer_Comments__c.field-meta.xml
<CustomField>
    <fullName>Reviewer_Comments__c</fullName>
    <description>Comments by reviewer.</description>
    <label>Reviewer Comments</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Customer_Contract__c/Customer_Contract__c.object-meta.xml
<CustomObject>
    <label>Customer Contract</label>
    <nameField>
        <displayFormat>CC-{00000000}</displayFormat>
        <label>Customer Contract</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Contract__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <description>Contract for customer contract</description>
    <inlineHelpText>Contract for customer contract</inlineHelpText>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Customer Contracts</relationshipLabel>
    <relationshipName>Customer_Contracts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Customer_Contract__c/fields/Contract_Name__c.field-meta.xml
<CustomField>
    <fullName>Contract_Name__c</fullName>
    <description>Used in reporting</description>
    <formula>Contract__r.Contract_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contract Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SM_Configs__c/SM_Configs__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Org Configs</label>
</CustomObject>

unpackaged/main/default/objects/SM_Configs__c/fields/Integration_User_Id__c.field-meta.xml
<CustomField>
    <fullName>Integration_User_Id__c</fullName>
    <description>CCRM15-140</description>
    <label>Integration User Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>&quot;None&quot;</defaultValue>
    <description>This field is used in sharing rules to define a AU User&#39;s and NZ User&#39;s</description>
    <inlineHelpText>This field is used in sharing rules to define a AU User&#39;s and NZ User&#39;s</inlineHelpText>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/ContractLineItemTriggerHandlerTest.cls
/*******************************************************************************************************
* Class Name      	: ContractLineItemTriggerHandlerTest
* Description		: Test class for ContractLineItemTriggerHandler
* Author          	: Bunnings Dev
* Created On      	: 18/05/2023
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Jasper R Galapon		18/05/2023		1000				Initial Version
* Jasper R Galapon		19/10/2032		1001				BUNDIG-26279 - Test Class failures in PROD 
* Jasper R Galapon		06/08/2024		1002				BUNDIG-34608 - New Test class method for setAutoApprovalEligibility
******************************************************************************************************/

@isTest
private class ContractLineItemTriggerHandlerTest {
    
    @isTest
    private static void blockUpdate_Test() {
        Test.startTest();
        	// BUNDIG-26279
			// Id intId = [SELECT Id FROM User WHERE Name = 'Integration User'].Id;
        	Id intId = [SELECT Id FROM User WHERE Profile.Name = 'Integrations User' LIMIT 1].Id;
                    
            SM_Configs__c config = new SM_Configs__c(Integration_User_Id__c = intId);
            insert config;
            
            List<Contract__c> contracts = TestDataFactory.createContracts(1);
            contracts[0].Contract_Approval_Status__c = 'Customer Approved';
            insert contracts;
                    
            User thisUser = [SELECT Id FROM User WHERE Profile.Name = 'Integrations User' LIMIT 1];
                        
            List<Contract_Line_Item__c> items = TestDataFactory.createContractLineItems(contracts[0].Id, Constants.CLI_LINE_TYPE_CONTRACT, 'A1', null, 1);
        	items[0].Amendment_Type__c = 'U';
            insert items;
           
            System.runAs (thisUser) {                
                items[0].Reviewer_Action__c = 'A';
                items[0].Approver_Action__c = 'A';
                items[0].Reviewer_Action_Date__c = Date.today();
                items[0].Approver_Action_Date__c = Date.today();
                items[0].Reviewer_Comments__c = 'Approved by reviewer';
                items[0].Approver_Comments__c = 'Approved by approver';            
                update items;
                
                System.assertNotEquals('A', [SELECT Reviewer_Action__c FROM Contract_Line_Item__c WHERE Id = :items[0].Id].Reviewer_Action__c, 'not equals');
            }
        Test.stopTest();
    }
    
    @isTest
    private static void sendNotificationToReviewer_Test() {
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        
        Profile pAM = [SELECT Id FROM Profile WHERE Name =: 'Account Manager' LIMIT 1];
        Profile pSM = [SELECT Id FROM Profile WHERE Name =: 'Sales Manager' LIMIT 1];
                
        list<User> userAM = TestDataFactory.createUsers(1, pAM.Id);
        insert userAM;
        list<User> userSM = TestDataFactory.createUsers(1, pSM.Id);
        insert userSM;
        
        List<Contract__c> contracts = new List<Contract__c>{
            new Contract__c(Name = 'C1', Contract_Name__c = 'C1', Status__c = 'Pending', Country__c = 'Australia', State__c = 'VIC', Cost_Zone__c = 'ALL',
                           Reviewer__c = userAM[0].Id, Approver__c = userSM[0].Id)
        };
		System.runAs (thisUser) {
        	insert contracts;
        }
        
        List<Contract_Line_Item__c> items = new List<Contract_Line_Item__c>();
        items.addAll(TestDataFactory.createContractLineItems(contracts[0].Id, Constants.CLI_LINE_TYPE_AMENDMENT, 'A1', null, 1));
        //items[0].Line_Status__c = 'A1';
        items[0].Amendment_Type__c = 'U';
        System.runAs (thisUser) {
        	insert items;
        }
        
        Test.startTest();
        	items[0].Reviewer_Action__c = 'A';
        	items[0].Line_Status__c = 'A2';
        	System.runAs (thisUser) {
        		update items;
            }
        	items[0].Approver_Action__c = 'R';
        	items[0].Line_Status__c = 'R';
        	System.runAs (thisUser) {
        		update items;
            }
        Test.stopTest();
        
    }
    
    @isTest
    private static void setAutoApprovalEligibility_Eligible_Test() {
        List<Account> accounts = TestDataFactory.createAccounts(1);
        accounts[0].Power_Pass_Account_Number__c = 'JRG001';
        insert accounts;
        
        List<Contract__c> contracts = TestDataFactory.createContracts(1);
        contracts[0].Status__c = Label.Active;
        contracts[0].Country__c = 'Australia';
        insert contracts;
        
        List<Customer_Contract__c> customerConList = TestDataFactory.createCustomerContracts(accounts[0].ID, new List<ID> {contracts[0].ID});
        insert customerConList; 
        
        Test.startTest();
            List<Contract_Line_Item__c> cli = TestDataFactory.createContractLineItems(contracts[0].Id, Constants.CLI_LINE_TYPE_AMENDMENT, 'A1', null, 1);
            cli[0].Amendment_Type__c = 'U';
            insert cli;
		Test.stopTest();

        System.assertEquals(TRUE, [SELECT Auto_Approval_Eligibility__c FROM Contract_Line_Item__c WHERE Id = :cli[0].Id].Auto_Approval_Eligibility__c, 'Contract Line Item is eligible for auto approval');              
    }
    
    @isTest
    private static void setAutoApprovalEligibility_Ineligible_Test() {
        List<Account> accounts = TestDataFactory.createAccounts(1);
        accounts[0].Power_Pass_Account_Number__c = 'JRG001';
        insert accounts;
        
        List<Contract__c> contracts = TestDataFactory.createContracts(1);
        contracts[0].Status__c = Label.Active;
        contracts[0].Country__c = 'Australia';
        insert contracts;
        
        List<Customer_Contract__c> customerConList = TestDataFactory.createCustomerContracts(accounts[0].ID, new List<ID> {contracts[0].ID});
        insert customerConList;
        
        Account_Exclusion_List__c ael = new Account_Exclusion_List__c(Account_Reference__c = 'JRG001');
        insert ael;
        
        Supplier_Exclusion_List__c sel = new Supplier_Exclusion_List__c(Supplier_Reference__c = 'JRG002');
        insert sel;
        
        Test.startTest();
            List<Contract_Line_Item__c> cli = TestDataFactory.createContractLineItems(contracts[0].Id, Constants.CLI_LINE_TYPE_AMENDMENT, 'A1', null, 1);
            cli[0].Amendment_Type__c = 'U';
            insert cli;
		Test.stopTest();        
    }
    
}