unpackaged/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Various contracts associated to customers, projects and umbrellas. Use of custom object in place of standard considering future implementation of CPQ with contract and its line items.</description>
    <label>Contract</label>
    <nameField>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Contract__c/fields/Contract_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Contract_Approval_Status__c</fullName>
    <label>Customer Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Load</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>Customer Rejected</fullName>
            </value>
            <value>
                <fullName>Customer Approved</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <isActive>false</isActive>
                <label>Active</label>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Expired</fullName>
                <isActive>false</isActive>
                <label>Expired</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <isActive>false</isActive>
                <label>Rejected</label>
            </value>
            <value>
                <fullName>Reviewed</fullName>
                <isActive>false</isActive>
                <label>Reviewed</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
                <isActive>false</isActive>
                <label>Submitted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contract__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Date when the contract ended.</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the contract</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contract_Line_Item__c/Contract_Line_Item__c.object-meta.xml
<CustomObject>
    <description>Line items associated to a contract.</description>
    <label>Contract Line Item</label>
    <nameField>
        <label>Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Contract_Line_Item__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <description>The associated contract</description>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Contract Line Items</relationshipLabel>
    <relationshipName>Contract_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Contract_Line_Item__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End date of the contract line item.</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contract_Line_Item__c/fields/Line_Status__c.field-meta.xml
<CustomField>
    <fullName>Line_Status__c</fullName>
    <description>This is only used on contract amendments

A1: Pending Level 1 Approval
A2: Pending Level 2 Approval
R1: Level 1 rejection
A : Approved (final)
R : Rejected (final)
C : Complete</description>
    <label>Line Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A1</fullName>
            </value>
            <value>
                <fullName>A2</fullName>
            </value>
            <value>
                <fullName>R1</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>X</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contract_Line_Item__c/fields/Line_Type__c.field-meta.xml
<CustomField>
    <fullName>Line_Type__c</fullName>
    <description>Contract represents the line while it is pending review of a new contract or renewal, or has been approved. Amendment represents an amendment to a line on an Active contract.</description>
    <label>Line Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Amendment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/SM_ContractLineItemPurgeBatch.cls
/*******************************************************************************************************
* Class Name      	: SM_ContractLineItemPurgeBatch
* Description		: Batch / Schedule class to purge contract line items
* Author          	: Simplus - Yi Zhang
* Created On      	: 05/06/2020
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Yi Zhang              05/06/2020		1000				Initial version
******************************************************************************************************/
global class SM_ContractLineItemPurgeBatch implements Database.Batchable<sObject>, Schedulable {
    
    String query;

    global SM_ContractLineItemPurgeBatch() {
        query = 'SELECT Id FROM Contract_Line_Item__c '
         + ' WHERE Contract__r.Contract_Approval_Status__c = \'' + Constants.CONTRACT_APPROVAL_STATUS_DELETED + '\''
         + ' OR ( '
         + ' Contract__r.Status__c = \'' + Constants.CONTRACT_STATUS_ACTIVE + '\' '
         + ' AND ( '
         + ' ( '
         + ' Line_Type__c = \'' + Constants.CLI_LINE_TYPE_CONTRACT + '\' '
         + ' AND End_Date__c < TODAY '
         + ' ) '
         + ' OR ( '
         + ' Line_Type__c = \'' + Constants.CLI_LINE_TYPE_AMENDMENT + '\' '
         + ' AND Line_Status__c = \'' + Constants.CLI_LINE_STATUS_COMPLETED + '\' '
         + ' ) '
         + ' ) '
         + ' ) ';

         /**
         [
            SELECT Id 
            FROM Contract_Line_Item__c
            WHERE Contract__r.Contract_Approval_Status__c = 'Deleted' 
            OR (
                Contract__r.Status__c = 'Active'
                AND (
                    (
                        Line_Type__c = 'Contract' 
                        AND End_Date__c < TODAY
                    )
                    OR (
                        Line_Type__c = 'Amendment'
                        AND Line_Status__c = 'C'
                    )
                )
            )
         ] 
         */
    }

    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }

    /**
    * @description 
    * @author Yi Zhang | 05/06/2020 
    * @param BC 
    * @param scope 
    * @return void 
    **/
    global void execute(Database.BatchableContext BC, List<sObject> scope) {
        // execute code
        try {
            delete scope;
        } catch(Exception e) {
            ApplicationLogger.log('SM_ContractLineItemPurgeBatch.execute', 'Contract_Line_Item__c', 'Batch Job', e);
        }
    }

    /**
    * @description 
    * @author Yi Zhang | 05/06/2020 
    * @param BC 
    * @return void 
    **/
    global void finish(Database.BatchableContext BC) {
        // finish code
        // invoke another batch to purge deleted contracts
        database.executeBatch(new SM_ContractPurgeBatch());
    }
    
    /**
    * @description 
    * @author Yi Zhang | 05/06/2020 
    * @param SC 
    * @return void 
    **/
    global void execute(SchedulableContext SC) {
        database.executebatch(new SM_ContractLineItemPurgeBatch(), 1000);
    }
}