unpackaged/main/default/objects/Org_Limit__c/Org_Limit__c.object-meta.xml
<CustomObject>
    <label>Org Limit</label>
    <nameField>
        <displayFormat>OL{0000000000}</displayFormat>
        <label>Org Limits Entry Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Org Limits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Org_Limit__c/fields/HourlyPublishedPlatformEvents_Limit__c.field-meta.xml
<CustomField>
    <fullName>HourlyPublishedPlatformEvents_Limit__c</fullName>
    <label>HourlyPublishedPlatformEvents: Allotment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Org_Limit__c/fields/HourlyPublishedPlatformEvents_Used__c.field-meta.xml
<CustomField>
    <fullName>HourlyPublishedPlatformEvents_Used__c</fullName>
    <label>HourlyPublishedPlatformEvents: Consumed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Org_Limit__c/fields/HrlyPublishedStdVolPEs_Limit__c.field-meta.xml
<CustomField>
    <fullName>HrlyPublishedStdVolPEs_Limit__c</fullName>
    <label>HrlyPublishedStdVolPEs: Allotment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Org_Limit__c/fields/HrlyPublishedStdVolPEs_Used__c.field-meta.xml
<CustomField>
    <fullName>HrlyPublishedStdVolPEs_Used__c</fullName>
    <label>HrlyPublishedStdVolPEs: Consumed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Org_Limit__c/fields/MonthlyPlatformEvents_Limit__c.field-meta.xml
<CustomField>
    <fullName>MonthlyPlatformEvents_Limit__c</fullName>
    <label>MonthlyPlatformEvents: Allotment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Org_Limit__c/fields/MonthlyPlatformEvents_Used__c.field-meta.xml
<CustomField>
    <fullName>MonthlyPlatformEvents_Used__c</fullName>
    <label>MonthlyPlatformEvents: Consumed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/SM_OrgLimitFetch.cls
/*******************************************************************************************************
* Class Name      	: SM_OrgLimitFetch
* Description		: A schedulable class that feeds selected limit status into Org_Limit__c custom object
* Author          	: Simplus MS-AU
* Created On      	: 01-June-2021
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Simplus MS-AU			01/Jun/20201	1000				Initial version
******************************************************************************************************/
public class SM_OrgLimitFetch implements Schedulable {
    public void execute(SchedulableContext SC) {
         SM_OrgLimitFetch.populateLimits();
    }
    
    public static void populateLimits() {
        Map<String, String> remainingLimitFieldMap = new Map<String, String>{
            'HourlyPublishedPlatformEvents' => 'HourlyPublishedPlatformEvents_Used__c',
            'HourlyPublishedStandardVolumePlatformEvents' => 'HrlyPublishedStdVolPEs_Used__c',
            'MonthlyPlatformEventsUsageEntitlement' => 'MonthlyPlatformEvents_Used__c'
        };
            
        Map<String, String> limitFieldMap = new Map<String, String>{
            'HourlyPublishedPlatformEvents' => 'HourlyPublishedPlatformEvents_Limit__c',
            'HourlyPublishedStandardVolumePlatformEvents' => 'HrlyPublishedStdVolPEs_Limit__c',
            'MonthlyPlatformEventsUsageEntitlement' => 'MonthlyPlatformEvents_Limit__c'
        };            
        
        Org_Limit__c olimit = new Org_Limit__c();
        Map<String, OrgLimit> limitsMap = OrgLimits.getMap();
        for (String key : remainingLimitFieldMap.keySet()) {
            OrgLimit ol = limitsMap.get(key);
            olimit.put(remainingLimitFieldMap.get(key), ol.getValue());
            olimit.put(limitFieldMap.get(key), ol.getLimit());
        }         
        
        insert olimit;
    }
    
    public static void schedule(integer everyHour, String jobName) {
		String cron1 = string.valueOf(everyHour) + ' 0 * * * ?'; 
		SM_OrgLimitFetch job1 = new SM_OrgLimitFetch();
        System.schedule(jobName, cron1, job1);
    }
}