unpackaged/main/default/objects/Customer_Price_List__c/Customer_Price_List__c.object-meta.xml
<CustomObject>
    <description>Junction between Price List and Customers</description>
    <label>Customer Price List</label>
    <nameField>
        <displayFormat>CPL-{0000000000}</displayFormat>
        <label>Customer Price List Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Price Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Price_List__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>The customer</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Price Lists</relationshipLabel>
    <relationshipName>Customer_Price_Lists</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Customer_Price_List__c/fields/Customer_Price_List_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_Price_List_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Definition Id of the price list assoicated to a customer</description>
    <externalId>true</externalId>
    <label>Customer Price List ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Customer_Price_List__c/fields/Price_List__c.field-meta.xml
<CustomField>
    <fullName>Price_List__c</fullName>
    <description>The price list</description>
    <label>Price List</label>
    <referenceTo>Price_List__c</referenceTo>
    <relationshipLabel>Customer Price Lists</relationshipLabel>
    <relationshipName>Customer_Price_Lists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Customer_Price_List__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This field determines whether a Price List is active (checked) or In active (unchecked) for the related Customer.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Price_List__c/Price_List__c.object-meta.xml
<CustomObject>
    <description>This Object represents the header level of an externally mastered pricing table, which applies item level discounts for a pre-defined list of products within specific Cost Zones.</description>
    <label>Price List</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Price List Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Price_List__c/fields/Price_List_Definition__c.field-meta.xml
<CustomField>
    <fullName>Price_List_Definition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Price List Definition</description>
    <label>Price List Definition</label>
    <referenceTo>Price_List_Definition__c</referenceTo>
    <relationshipLabel>Price Lists</relationshipLabel>
    <relationshipName>Price_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Price_List__c/fields/Price_List_Header_ID__c.field-meta.xml
<CustomField>
    <fullName>Price_List_Header_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>External ID Reference for Price List</description>
    <externalId>true</externalId>
    <label>Price List Header ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Price_List__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Price List</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Price_List_Definition__c/Price_List_Definition__c.object-meta.xml
<CustomObject>
    <label>Price List Definition</label>
    <nameField>
        <displayFormat>PLD-{000000}</displayFormat>
        <label>Price List Definition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price List Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/SM_CustomerPriceListTest.cls
/*******************************************************************************************************
* Class Name      	: SM_CustomerPriceListTest
* Description		: Test class for SM_CustomerPriceList
* Author          	: Simplus MS
* Created On      	: 16/12/2020
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Simplus MS           16/12/2020		1000				Initial version
* Simplus MS           14/05/2021		2000				modifications CCRM-13728
******************************************************************************************************/
@isTest
private class SM_CustomerPriceListTest {
    
    class SecondCallBadMock implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HTTPResponse res = new HTTPResponse();
            res.setBody('{}');
            res.setStatusCode(200);            
            if (req.getEndpoint().endsWith('UPDATE')) {
                res.setStatusCode(202);
            }
            return res;
        }
    }        
    
    @isTest
    private static void test_invokeCustomerPriceListServiceAssignment_StatusSuccess(){
        List<Account> accounts = TestDataFactory.createAccounts(1);
        insert accounts;
        Price_List_Definition__c pld = new Price_List_Definition__c();
        insert pld;
        Price_List__c pb = new Price_List__c(Status__c = 'Active', Price_List_Definition__c = pld.Id, Price_List_Header_ID__c = String.valueOf(Math.random()));
        insert pb;
        Customer_Price_List__c cpl = new Customer_Price_List__c(Price_List__c = pb.Id, Account__c = [SELECT Id from Account LIMIT 1].Id,
                                                               Status__c = 'Active', Customer_Price_List_ID__c = '45426');
        insert cpl;
        
        Map<Id, Map<String, String>> maptoSerialize = new Map<Id, Map<String, String>>();
        maptoSerialize.put([SELECT Price_List__c from Customer_Price_List__c LIMIT 1].Price_List__c, new Map<String, String>{'CustomerId' => '3467367', 'PriceListId' => [SELECT Customer_Price_List_ID__c from Customer_Price_List__c LIMIT 1].Customer_Price_List_ID__c,
                                                                            'AccountId' => [SELECT Account__c from Customer_Price_List__c LIMIT 1].Account__c, 'TMNumber' => '67674',
                                                                            'CountryCode' => 'AU'});

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new SM_RESTCalloutMock('{"example":"test"}', 202, false));

        SM_CustomerPriceList.invokeCustomerPriceListServiceAssignment(maptoSerialize, true);

        Test.stopTest();
    }
    
    @isTest
    private static void test_invokeCustomerPriceListServiceAssignment_StatusError(){
        List<Account> accounts = TestDataFactory.createAccounts(1);
        insert accounts;
        Price_List_Definition__c pld = new Price_List_Definition__c();
        insert pld;
        Price_List__c pb = new Price_List__c(Status__c = 'Active', Price_List_Definition__c = pld.Id, Price_List_Header_ID__c = String.valueOf(Math.random()));
        insert pb;
        Customer_Price_List__c cpl = new Customer_Price_List__c(Price_List__c = pb.Id, Account__c = [SELECT Id from Account LIMIT 1].Id,
                                                               Status__c = 'Active', Customer_Price_List_ID__c = '45426');
        insert cpl;
        
        Map<Id, Map<String, String>> maptoSerialize = new Map<Id, Map<String, String>>();
        maptoSerialize.put([SELECT Price_List__c from Customer_Price_List__c LIMIT 1].Price_List__c, new Map<String, String>{'CustomerId' => '3467367', 'PriceListId' => [SELECT Customer_Price_List_ID__c from Customer_Price_List__c LIMIT 1].Customer_Price_List_ID__c,
                                                                            'AccountId' => [SELECT Account__c from Customer_Price_List__c LIMIT 1].Account__c, 'TMNumber' => '67674',
                                                                            'CountryCode' => 'AU'});

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new SM_RESTCalloutMock('{"example":"test"}', 200, false));

        SM_CustomerPriceList.invokeCustomerPriceListServiceAssignment(maptoSerialize, true);

        Test.stopTest();
    }
    
    @isTest
    private static void test_invokeCustomerPriceListServiceAssignment1(){
        List<Account> accounts = TestDataFactory.createAccounts(1);
        insert accounts;
        Price_List_Definition__c pld = new Price_List_Definition__c();
        insert pld;
        Price_List__c pb = new Price_List__c(Status__c = 'Active', Price_List_Definition__c = pld.Id, Price_List_Header_ID__c = String.valueOf(Math.random()));
        insert pb;
        Customer_Price_List__c cpl = new Customer_Price_List__c(Price_List__c = pb.Id, Account__c = [SELECT Id from Account LIMIT 1].Id,
                                                               Status__c = 'Active', Customer_Price_List_ID__c = '45426');
        insert cpl;
        
        Map<Id, Map<String, String>> maptoSerialize = new Map<Id, Map<String, String>>();
        maptoSerialize.put([SELECT Price_List__c from Customer_Price_List__c LIMIT 1].Price_List__c, new Map<String, String>{'CustomerId' => '3467367', 'PriceListId' => [SELECT Customer_Price_List_ID__c from Customer_Price_List__c LIMIT 1].Customer_Price_List_ID__c,
                                                                            'AccountId' => [SELECT Account__c from Customer_Price_List__c LIMIT 1].Account__c, 'TMNumber' => '67674',
                                                                            'CountryCode' => 'AU'});

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new SecondCallBadMock());

        SM_CustomerPriceList.invokeCustomerPriceListServiceAssignment(maptoSerialize, true);

        Test.stopTest();
    }    
    
    @isTest
    private static void test_invokeCustomerPriceListServiceAssignment2(){
        List<Account> accounts = TestDataFactory.createAccounts(1);
        insert accounts;
        Price_List_Definition__c pld = new Price_List_Definition__c();
        insert pld;
        Price_List__c pb = new Price_List__c(Status__c = 'Active', Price_List_Definition__c = pld.Id, Price_List_Header_ID__c = String.valueOf(Math.random()));
        insert pb;
        Customer_Price_List__c cpl = new Customer_Price_List__c(Price_List__c = pb.Id, Account__c = [SELECT Id from Account LIMIT 1].Id,
                                                               Status__c = 'Active', Customer_Price_List_ID__c = '45426');
        insert cpl;
        
        Map<Id, Map<String, String>> maptoSerialize = new Map<Id, Map<String, String>>();
        maptoSerialize.put([SELECT Price_List__c from Customer_Price_List__c LIMIT 1].Price_List__c, new Map<String, String>{'CustomerId' => '3467367', 'PriceListId' => [SELECT Customer_Price_List_ID__c from Customer_Price_List__c LIMIT 1].Customer_Price_List_ID__c,
                                                                            'AccountId' => [SELECT Account__c from Customer_Price_List__c LIMIT 1].Account__c, 'TMNumber' => '67674',
                                                                            'CountryCode' => 'AU'});

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new SM_RESTCalloutMock('{"example":"test"}', 202, false));
        SM_CustomerPriceList.invokeCustomerPriceListServiceAssignment(maptoSerialize, true);
        
        Test.setMock(HttpCalloutMock.class, new SM_RESTCalloutMock('{"example":"test"', 202, false));
        SM_CustomerPriceList.invokeCustomerPriceListServiceAssignment(maptoSerialize, true);        

        Test.stopTest();
    }       
    
     @isTest
    private static void test_invokeCustomerPriceListServiceDeletion_StatusSuccess(){
        List<Account> accounts = TestDataFactory.createAccounts(1);
        insert accounts;
        Price_List_Definition__c pld = new Price_List_Definition__c();
        insert pld;
        Price_List__c pb = new Price_List__c(Status__c = 'Active', Price_List_Definition__c = pld.Id, Price_List_Header_ID__c = String.valueOf(Math.random()));
        insert pb;
        Customer_Price_List__c cpl = new Customer_Price_List__c(Price_List__c = pb.Id, Account__c = [SELECT Id from Account LIMIT 1].Id,
                                                               Status__c = 'Active', Customer_Price_List_ID__c = '45426');
        insert cpl;
        
        Map<String, String> maptoSerialize = new Map<String, String>();
        maptoSerialize.put('CustomerId' , '3467367');
        maptoSerialize.put('PriceListId' , [SELECT Customer_Price_List_ID__c from Customer_Price_List__c LIMIT 1].Customer_Price_List_ID__c);
        maptoSerialize.put('AccountId' , [SELECT Account__c from Customer_Price_List__c LIMIT 1].Account__c);
        maptoSerialize.put('TMNumber' , '67674');
		maptoSerialize.put('CountryCode' , 'AU');

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new SM_RESTCalloutMock('{"example":"test"}', 200, false));

        SM_CustomerPriceList.invokeCustomerPriceListServiceDeletion(new Map<Id, Map<String, String>>{cpl.id=>maptoSerialize}, true);

        Test.stopTest();
    }
    
     @isTest
    private static void test_invokeCustomerPriceListServiceDeletion1(){
        List<Account> accounts = TestDataFactory.createAccounts(1);
        insert accounts;
        Price_List_Definition__c pld = new Price_List_Definition__c();
        insert pld;
        Price_List__c pb = new Price_List__c(Status__c = 'Active', Price_List_Definition__c = pld.Id, Price_List_Header_ID__c = String.valueOf(Math.random()));
        insert pb;
        Customer_Price_List__c cpl = new Customer_Price_List__c(Price_List__c = pb.Id, Account__c = [SELECT Id from Account LIMIT 1].Id,
                                                               Status__c = 'Active', Customer_Price_List_ID__c = '45426');
        insert cpl;
        
        Map<String, String> maptoSerialize = new Map<String, String>();
        maptoSerialize.put('CustomerId' , '3467367');
        maptoSerialize.put('PriceListId' , [SELECT Customer_Price_List_ID__c from Customer_Price_List__c LIMIT 1].Customer_Price_List_ID__c);
        maptoSerialize.put('AccountId' , [SELECT Account__c from Customer_Price_List__c LIMIT 1].Account__c);
        maptoSerialize.put('TMNumber' , '67674');
		maptoSerialize.put('CountryCode' , 'AU');

        Test.startTest();
        
        Test.setMock(HttpCalloutMock.class, new SecondCallBadMock());
		SM_CustomerPriceList.invokeCustomerPriceListServiceDeletion(new Map<Id, Map<String, String>>{cpl.id=>maptoSerialize}, true);      
        
        Test.stopTest();
    }    
    
    @isTest
    private static void test_invokeCustomerPriceListServiceDeletion2(){
        List<Account> accounts = TestDataFactory.createAccounts(1);
        insert accounts;
        Price_List_Definition__c pld = new Price_List_Definition__c();
        insert pld;
        Price_List__c pb = new Price_List__c(Status__c = 'Active', Price_List_Definition__c = pld.Id, Price_List_Header_ID__c = String.valueOf(Math.random()));
        insert pb;
        Customer_Price_List__c cpl = new Customer_Price_List__c(Price_List__c = pb.Id, Account__c = [SELECT Id from Account LIMIT 1].Id,
                                                               Status__c = 'Active', Customer_Price_List_ID__c = '45426');
        insert cpl;
        
        Map<String, String> maptoSerialize = new Map<String, String>();
        maptoSerialize.put('CustomerId' , '3467367');
        maptoSerialize.put('PriceListId' , [SELECT Customer_Price_List_ID__c from Customer_Price_List__c LIMIT 1].Customer_Price_List_ID__c);
        maptoSerialize.put('AccountId' , [SELECT Account__c from Customer_Price_List__c LIMIT 1].Account__c);
        maptoSerialize.put('TMNumber' , '67674');
		maptoSerialize.put('CountryCode' , 'AU');

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new SM_RESTCalloutMock('{"example":"test"}', 202, false));
        SM_CustomerPriceList.invokeCustomerPriceListServiceDeletion(new Map<Id, Map<String, String>>{cpl.id=>maptoSerialize}, true);
        
        Test.setMock(HttpCalloutMock.class, new SM_RESTCalloutMock('{"example":"test"', 202, false));
		SM_CustomerPriceList.invokeCustomerPriceListServiceDeletion(new Map<Id, Map<String, String>>{cpl.id=>maptoSerialize}, true);

        Test.stopTest();
    }          
}