unpackaged/main/default/objects/Planned_Leave__c/Planned_Leave__c.object-meta.xml
<CustomObject>
    <label>Planned Leave</label>
    <nameField>
        <displayFormat>PL-{0000}</displayFormat>
        <label>Planned Leave Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Planned Leave</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Planned_Leave__c/fields/Approver__c.field-meta.xml
<CustomField>
    <fullName>Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Planned_Leave</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Planned_Leave__c/fields/Approver_Comment__c.field-meta.xml
<CustomField>
    <fullName>Approver_Comment__c</fullName>
    <label>Approver Comment</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Planned_Leave__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approval In Progress</fullName>
            </value>
            <value>
                <fullName>Leave Cancelled</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>Represents all frame and truss plants, small format stores, trade distribution centres and warehouses.</description>
    <label>Store</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Store__c/fields/Location_Code__c.field-meta.xml
<CustomField>
    <fullName>Location_Code__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Location Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Store__c/fields/Operations_Region_Code__c.field-meta.xml
<CustomField>
    <fullName>Operations_Region_Code__c</fullName>
    <description>The store&#39;s operations region code</description>
    <label>Operations Region Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Store_Member__c/Store_Member__c.object-meta.xml
<CustomObject>
    <description>Junction between user (team members) and store.</description>
    <label>Store Member</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>Store Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Store_Member__c/fields/Default_Trade_Specialist__c.field-meta.xml
<CustomField>
    <fullName>Default_Trade_Specialist__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the trade specialist is default or not</description>
    <label>Default Trade Specialist</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Store_Member__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End date of association with the store</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Store_Member__c/fields/Location_Code__c.field-meta.xml
<CustomField>
    <fullName>Location_Code__c</fullName>
    <formula>Store__r.Location_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Location Code</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Store_Member__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start date of association with the store</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Store_Member__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Store_Member__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipName>User_Stores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Store_Member__c/fields/Team_Member_Call__c.field-meta.xml
<CustomField>
    <fullName>Team_Member_Call__c</fullName>
    <label>Team Member Call %</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0%</fullName>
            </value>
            <value>
                <fullName>10%</fullName>
            </value>
            <value>
                <fullName>20%</fullName>
            </value>
            <value>
                <fullName>30%</fullName>
            </value>
            <value>
                <fullName>40%</fullName>
            </value>
            <value>
                <fullName>50%</fullName>
            </value>
            <value>
                <fullName>60%</fullName>
            </value>
            <value>
                <fullName>70%</fullName>
            </value>
            <value>
                <fullName>80%</fullName>
            </value>
            <value>
                <fullName>90%</fullName>
            </value>
            <value>
                <fullName>100%</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/User/fields/Location_Code__c.field-meta.xml
<CustomField>
    <fullName>Location_Code__c</fullName>
    <description>Location code that maps to the external ID on the store object</description>
    <label>Location Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/DefaultTSPlannedLeaveBatch_Test.cls
/*******************************************************************************************************
* Class Name      	: DefaultTSPlannedLeaveBatch_Test
* Description		: Test class for DefaultTSPlannedLeaveBatch
* Author          	: Simplus - MS
* Created On      	: 02/12/2021
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer			    Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Simplus MS            02/12/2021		1000				Initial version
******************************************************************************************************/
@isTest
public with sharing class DefaultTSPlannedLeaveBatch_Test {
    
    @TestSetup
    static void TestSetupMethod() {
        
        // create store
        List<Store__c> stores = TestDataFactory.createStores(2);
        stores[0].Operations_Region_Code__c = 'NSW';
        stores[0].Location_Code__c = '2000';
        stores[1].Operations_Region_Code__c = 'NSW';
        stores[1].Location_Code__c = '2001';
        insert stores;
        
        Profile profileTS = [SELECT Id FROM Profile WHERE Name = :Constants.AU_TRADE_SPECIALIST_PROFILEENAME LIMIT 1];
        Profile profileRCM = [SELECT Id FROM Profile WHERE Name = :Constants.AU_LIGHT_COMMERCIAL_MANAGER_PROFILEENAME LIMIT 1];
        List<User> users = TestDataFactory.createUsers(4, null);
        // user 0 & 1 for 1st store
        users[0].ProfileId = profileTS.Id;
        users[0].Location_Code__c = stores[0].Location_Code__c;
        users[1].ProfileId = profileTS.Id;
        users[1].Location_Code__c = stores[0].Location_Code__c;
        // user 2 for 2nd store
        users[2].ProfileId = profileTS.Id;
        users[2].Location_Code__c = stores[1].Location_Code__c;
        // user 3 for 2nd store (RCM role)
        users[3].ProfileId = profileRCM.Id;
        users[3].Location_Code__c = stores[1].Location_Code__c;
        insert users;
        
        // create store members
        List<Store_Member__c> members = new List<Store_Member__c>();
        members.add(TestDataFactory.createStoreMember(stores[0].Id, users[0].Id, Constants.STOREMEMBER_TS_ROLENAME));
        members.add(TestDataFactory.createStoreMember(stores[0].Id, users[1].Id, Constants.STOREMEMBER_TS_ROLENAME));
        members.add(TestDataFactory.createStoreMember(stores[0].Id, users[3].Id, Constants.STOREMEMBER_RCM_ROLENAME));
        members.add(TestDataFactory.createStoreMember(stores[1].Id, users[2].Id, Constants.STOREMEMBER_TS_ROLENAME));
        members.add(TestDataFactory.createStoreMember(stores[1].Id, users[3].Id, Constants.STOREMEMBER_RCM_ROLENAME));
        members.add(TestDataFactory.createStoreMember(stores[1].Id, users[1].Id, Constants.STOREMEMBER_TS_ROLENAME));
        members[0].Default_Trade_Specialist__c = true;
        members[2].Default_Trade_Specialist__c = true;
        members[0].Team_Member_Call__c = '10%';
        members[1].Team_Member_Call__c = '20%';
        members[2].Team_Member_Call__c = '30%';
        members[3].Team_Member_Call__c = '40%';
        members[4].Team_Member_Call__c = '50%';
        members[5].Team_Member_Call__c = '60%';
        insert members;
        
        // create Planned Leaves for store members
        List<Planned_Leave__c> plannedLeaves = new List<Planned_Leave__c>();
        plannedLeaves.add(new Planned_Leave__c(End_Date__c=System.today(), Start_Date__c=System.today(), Approver_Comment__c='Approved',
                                               Status__c='Approved', OwnerId=users[0].Id, Approver__c=UserInfo.getUserId()));
        plannedLeaves.add(new Planned_Leave__c(End_Date__c=System.today(), Start_Date__c=System.today(), Approver_Comment__c='Approved',
                                               Status__c='Approved', OwnerId=users[2].Id, Approver__c=UserInfo.getUserId()));
        insert plannedLeaves;
        
    }
    
    @isTest 
    private static void testUpdateDefaultTSOfStore() {
        
        Test.startTest();
        Database.executeBatch(new DefaultTSPlannedLeaveBatch());
        Test.stopTest();
        
    }
}