unpackaged/main/default/objects/Planned_Leave__c/Planned_Leave__c.object-meta.xml
<CustomObject>
    <label>Planned Leave</label>
    <nameField>
        <displayFormat>PL-{0000}</displayFormat>
        <label>Planned Leave Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Planned Leave</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Planned_Leave__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approval In Progress</fullName>
            </value>
            <value>
                <fullName>Leave Cancelled</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>Represents all frame and truss plants, small format stores, trade distribution centres and warehouses.</description>
    <label>Store</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Store__c/fields/Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_1__c</fullName>
    <description>The store&#39;s address line 1</description>
    <label>Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Store__c/fields/Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_2__c</fullName>
    <description>The store&#39;s address line 2</description>
    <label>Address Line 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Store__c/fields/Address_Line_3__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_3__c</fullName>
    <description>The store&#39;s address line 3</description>
    <label>Address Line 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Store__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>The store&#39;s city</description>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Store__c/fields/Engagement_Model__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Model__c</fullName>
    <description>Determines the method used for assigning Powerpass Account Ownership. 
Old Model - the Stores Default Trade Specialist will become the owner. 
New - Ownership is determined by Assignment Rule Metadata records</description>
    <label>Engagement Model</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Old</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Store__c/fields/Location_Code__c.field-meta.xml
<CustomField>
    <fullName>Location_Code__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Location Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Store__c/fields/Location_Type__c.field-meta.xml
<CustomField>
    <fullName>Location_Type__c</fullName>
    <description>Unrestricted list of location types</description>
    <label>Location Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Area</fullName>
            </value>
            <value>
                <fullName>Department</fullName>
            </value>
            <value>
                <fullName>Distribution Centre</fullName>
            </value>
            <value>
                <fullName>Frame and Truss Plant</fullName>
            </value>
            <value>
                <fullName>Function</fullName>
            </value>
            <value>
                <fullName>Logical</fullName>
            </value>
            <value>
                <fullName>Region</fullName>
            </value>
            <value>
                <fullName>Section</fullName>
            </value>
            <value>
                <fullName>Small Format Store</fullName>
            </value>
            <value>
                <fullName>Trade Distribution Centre</fullName>
            </value>
            <value>
                <fullName>Warehouse</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Store__c/fields/Operations_Region_Code__c.field-meta.xml
<CustomField>
    <fullName>Operations_Region_Code__c</fullName>
    <description>The store&#39;s operations region code</description>
    <label>Operations Region Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Store__c/fields/Postcode__c.field-meta.xml
<CustomField>
    <fullName>Postcode__c</fullName>
    <description>The store&#39;s postcode</description>
    <label>Postcode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Store__c/fields/Sales_Rep_ID__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep_ID__c</fullName>
    <description>Sales rep ID that is used to define the role of the trade specialist.</description>
    <label>Sales Rep ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Store__c/fields/Store_Call__c.field-meta.xml
<CustomField>
    <fullName>Store_Call__c</fullName>
    <label>Store Call %</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0%</fullName>
            </value>
            <value>
                <fullName>10%</fullName>
            </value>
            <value>
                <fullName>20%</fullName>
            </value>
            <value>
                <fullName>30%</fullName>
            </value>
            <value>
                <fullName>40%</fullName>
            </value>
            <value>
                <fullName>50%</fullName>
            </value>
            <value>
                <fullName>60%</fullName>
            </value>
            <value>
                <fullName>70%</fullName>
            </value>
            <value>
                <fullName>80%</fullName>
            </value>
            <value>
                <fullName>90%</fullName>
            </value>
            <value>
                <fullName>100%</fullName>
                <default>true</default>
                <label>100%</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Store__c/fields/Trade_Specialist_Email__c.field-meta.xml
<CustomField>
    <fullName>Trade_Specialist_Email__c</fullName>
    <label>Trade Specialist Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Store_Member__c/Store_Member__c.object-meta.xml
<CustomObject>
    <description>Junction between user (team members) and store.</description>
    <label>Store Member</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>Store Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Store_Member__c/fields/Call_Volume__c.field-meta.xml
<CustomField>
    <fullName>Call_Volume__c</fullName>
    <label>Call Volume</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Store_Member__c/fields/Default_Trade_Specialist__c.field-meta.xml
<CustomField>
    <fullName>Default_Trade_Specialist__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the trade specialist is default or not</description>
    <label>Default Trade Specialist</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Store_Member__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End date of association with the store</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Store_Member__c/fields/Location_Code__c.field-meta.xml
<CustomField>
    <fullName>Location_Code__c</fullName>
    <formula>Store__r.Location_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Location Code</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Store_Member__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ASM</fullName>
            </value>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Area BDM</fullName>
            </value>
            <value>
                <fullName>CCS Manager</fullName>
            </value>
            <value>
                <fullName>RCM</fullName>
            </value>
            <value>
                <fullName>Trade Specialist</fullName>
            </value>
            <value>
                <fullName>SSM</fullName>
            </value>
            <value>
                <fullName>CCS</fullName>
                <isActive>false</isActive>
                <label>CCS</label>
            </value>
            <value>
                <fullName>Team Member</fullName>
                <isActive>false</isActive>
                <label>Team Member</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Store_Member__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start date of association with the store</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Store_Member__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Store_Member__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipName>User_Stores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Store_Member__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Stores</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/User/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>&quot;None&quot;</defaultValue>
    <description>This field is used in sharing rules to define a AU User&#39;s and NZ User&#39;s</description>
    <inlineHelpText>This field is used in sharing rules to define a AU User&#39;s and NZ User&#39;s</inlineHelpText>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/User/fields/Location_Code__c.field-meta.xml
<CustomField>
    <fullName>Location_Code__c</fullName>
    <description>Location code that maps to the external ID on the store object</description>
    <label>Location Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/Sales_Rep_ID__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep_ID__c</fullName>
    <description>Unique sales rep number assigned to the user either from legacy system sequence or newly generated in Salesforce</description>
    <label>Sales Rep ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/DM_Store.cls
/*******************************************************************************************************
* Class Name        : DM_Store
* Description       : Data Layer - Selector for Sobject Store__c
* Author            : Simplus - Philip Clark
* Created On        : 23/06/2020
* Modification Log  :
* -----------------------------------------------------------------------------------------------------
* Developer             Date            Modification ID     Description
* -----------------------------------------------------------------------------------------------------
* Philip Clark          23/06/2020      1000                Initial version
* Simplus MS            17/06/2021		3000				CCRM-13881 - Default Trade Specialist Editable by Trade Specialists
* Simplus MS            19/10/2021      4000                Added logic for CCRM15-79: Return a map of store records
* Simplus MS            02/12/2021      5000                Added logic for CCRM15-417: Planned Leave - Account Assignment and Transfers
* Simplus MS 			18/01/2022		6000				Added field getStoresWithAddressByLocationCode for CCRM15-566
******************************************************************************************************/
public with sharing class DM_Store {
    
    /**
    * @description  
    * @author       Philip Clark | 23/06/2020 
    * @param        set<String> 
    * @param        String 
    * @param        set<String> 
    * @return       list<Store__c> 
    **/
    public static list<Store__c> getStoreByLocCode(set<String> locSet, String activeStatus, set<String> roleSet) {
        List<Store__c> retList = new List<Store__c>();
        if (roleSet!=null) {
            retList = [
                SELECT Id, Location_Code__c, Operations_Region_Code__c, Sales_Rep_ID__c,
                    (SELECT Id, Team_Member__c, Default_Trade_Specialist__c, Role__c FROM User_Stores__r 
                    WHERE Status__c =: activeStatus AND Role__c IN: roleSet 
                    ORDER BY CREATEDDATE ASC) 
                FROM Store__c WHERE Location_Code__c IN: locSet];
        } else
        {
            retList = [
                SELECT Id, Location_Code__c, Operations_Region_Code__c, Sales_Rep_ID__c,
                    (SELECT Id, Team_Member__c, Default_Trade_Specialist__c, Role__c FROM User_Stores__r 
                    WHERE Status__c =: activeStatus 
                    ORDER BY CREATEDDATE ASC) 
                FROM Store__c WHERE Location_Code__c IN: locSet];
        }
        return retList;
    }
    
    /**
    * @description  
    * @author       Philip Clark | 23/06/2020 
    * @param        set<String> 
    * @param        String 
    * @param        set<String> 
    * @return       list<Store__c> 
    **/
    public static list<Store__c> getStoreByOpRegCode(set<String> regCodeSet, String activeStatus, set<String> roleSet) {
        List<Store__c> retList = new List<Store__c>();
        if (roleSet!=null) {
            retList = [
                SELECT Id, Location_Code__c, Operations_Region_Code__c, Sales_Rep_ID__c,
                    (SELECT Id, Team_Member__c, Default_Trade_Specialist__c, Role__c FROM User_Stores__r 
                    WHERE Status__c =: activeStatus AND Role__c IN: roleSet 
                    ORDER BY CREATEDDATE ASC) 
                FROM Store__c WHERE Operations_Region_Code__c IN: regCodeSet];
        } else
        {
            retList = [
                SELECT Id, Location_Code__c, Operations_Region_Code__c, Sales_Rep_ID__c,
                    (SELECT Id, Team_Member__c, Default_Trade_Specialist__c, Role__c FROM User_Stores__r 
                    WHERE Status__c =: activeStatus 
                    ORDER BY CREATEDDATE ASC) 
                FROM Store__c WHERE Operations_Region_Code__c IN: regCodeSet];
        }
        return retList;
    }

    /**
    * @description 
    * @author Yi Zhang | 19/08/2020 
    * @param opRegCodes 
    * @return List<Store__c> 
    **/
    public static List<Store__c> getStoreByOpRegCodes(Set<String> opRegCodes) {
        return new List<Store__c>([
            SELECT Id, Operations_Region_Code__c
            FROM Store__c
            WHERE Operations_Region_Code__c IN :opRegCodes
            AND Status__c = :Constants.STATUS_ACTIVE
        ]);
    }

    /**
    * @description 
    * @author Yi Zhang | 20/08/2020 
    * @param storeIds 
    * @return List<Store__c> 
    **/
    public static List<Store__c> getStoresWithActiveTSs(List<Id> storeIds) {
        return new List<Store__c>([
            SELECT Id, Operations_Region_Code__c,
            (
                SELECT Id, Default_Trade_Specialist__c 
                FROM User_Stores__r 
                WHERE Default_Trade_Specialist__c = false
                AND Status__c = :Constants.STOREMEMBER_ACTIVE_STATUS
                AND Role__c = :Constants.STOREMEMBER_TS_ROLENAME 
            )
            FROM Store__c
            WHERE Id IN :storeIds
        ]);
    }

    /**
    * @description Added for CCRM-13881 
    * @author MS Simplus | 17/06/2021
    * @param storeIds 
    * @param storeMemberIds
    **/
    public static List<Store__c> getStoresWithActiveTSList(List<Id> storeIds, Set<Id> storeMemberIds) {
        return new List<Store__c>([
            SELECT Id, Operations_Region_Code__c,
            (
                SELECT Id, Default_Trade_Specialist__c 
                FROM User_Stores__r 
                WHERE Default_Trade_Specialist__c = false
                AND Id NOT IN : storeMemberIds 
                AND Status__c = :Constants.STOREMEMBER_ACTIVE_STATUS
                AND Role__c = :Constants.STOREMEMBER_TS_ROLENAME
                AND Team_Member__c NOT IN (SELECT OwnerId FROM Planned_Leave__c WHERE Status__c = 'Approved' 
                AND (Start_Date__c = TODAY OR End_Date__c = TODAY))
                ORDER BY Call_Volume__c DESC, CreatedDate ASC
            )
            FROM Store__c
            WHERE Id IN :storeIds
        ]);
    }

    /**
    * @description Added for CCRM15-394
    * @author MS Simplus | 31/01/2022
    * @param storeIds 
    * @param storeMemberIds
    **/
    /*public static List<Store__c> getStoresWithAllTSList(List<Id> storeIds, Set<Id> storeMemberIds) {
        return new List<Store__c>([
            SELECT Id, Operations_Region_Code__c,
            (
                SELECT Id, Default_Trade_Specialist__c 
                FROM User_Stores__r 
                WHERE Default_Trade_Specialist__c = true
                //AND Id NOT IN : storeMemberIds 
                //AND Status__c = :Constants.STOREMEMBER_ACTIVE_STATUS
                AND Role__c = :Constants.STOREMEMBER_TS_ROLENAME
                AND Team_Member__c NOT IN (SELECT OwnerId FROM Planned_Leave__c WHERE Status__c = 'Approved' 
                AND (Start_Date__c = TODAY OR End_Date__c = TODAY))
                //ORDER BY Call_Volume__c DESC, CreatedDate ASC
            )
            FROM Store__c
            WHERE Id IN :storeIds
        ]);
    }*/

    /**
    * @description Added for CCRM15-394
    * @author MS Simplus | 20/12/2021
    * @param storeIds
    **/
    public static List<Store__c> getStoresWithActiveDTSList(List<Id> storeIds) {
        return new List<Store__c>([
            SELECT Id, Operations_Region_Code__c,
            (
                SELECT Id, Default_Trade_Specialist__c 
                FROM User_Stores__r 
                WHERE Default_Trade_Specialist__c = true
                AND Status__c = :Constants.STOREMEMBER_ACTIVE_STATUS
                AND Role__c = :Constants.STOREMEMBER_TS_ROLENAME
                AND Team_Member__c NOT IN (SELECT OwnerId FROM Planned_Leave__c WHERE Status__c = 'Approved' 
                AND (Start_Date__c = TODAY OR End_Date__c = TODAY))
                ORDER BY Call_Volume__c DESC, CreatedDate ASC
            )
            FROM Store__c
            WHERE Id IN :storeIds
        ]);
    }

    /**
    * @description Added for CCRM-13881 
    * @author MS Simplus | 14/06/2021 
    * @param storeIds 
    * @return List<Store__c> 
    **/
    public static List<Store__c> getStoresWithDefaultActiveTSs(List<Id> storeIds) {
        return new List<Store__c>([
            SELECT Id, Operations_Region_Code__c,
            (
                SELECT Id, Default_Trade_Specialist__c, Team_Member__c  
                FROM User_Stores__r 
                WHERE Status__c = :Constants.STOREMEMBER_ACTIVE_STATUS
                AND Role__c = :Constants.STOREMEMBER_TS_ROLENAME 
            )
            FROM Store__c
            WHERE Id IN :storeIds
        ]);
    }

    /**
    * @description 
    * @author Yi Zhang | 20/08/2020 
    * @param storeIds 
    * @return List<Store__c> 
    **/
    public static List<Store__c> getStoresWithOneActiveRCM(List<Id> storeIds) {
        return new List<Store__c>([
            SELECT Id, Name, Operations_Region_Code__c,
            (
                SELECT Id, Team_Member__c 
                FROM User_Stores__r 
                WHERE Status__c = :Constants.STOREMEMBER_ACTIVE_STATUS
                AND Role__c = :Constants.STOREMEMBER_RCM_ROLENAME 
                LIMIT 1
            )
            FROM Store__c
            WHERE Id IN :storeIds
        ]);
    }

    /**
    * @description 
    * @author Yi Zhang | 28/10/2020 
    * @param storeIds 
    * @return List<Store__c> 
    **/
    public static List<Store__c> getStoresWithActiveSMs(List<Id> storeIds) {
        return new List<Store__c>([
            SELECT Id, Engagement_Model__c,
            (
                SELECT Id, Team_Member__c, Team_Member__r.Name, Role__c, Default_Trade_Specialist__c 
                FROM User_Stores__r 
                WHERE Status__c = :Constants.STATUS_ACTIVE
            )
            FROM Store__c
            WHERE Id In :storeIds
        ]);
    }

    
    /**
    * @description 
    * @author Yi Zhang | 24/08/2020 
    * @param storeIds 
    * @return List<Store__c> 
    **/
    public static List<Store__c> getStores(List<Id> storeIds) {
        return new List<Store__c>([
            SELECT Id, Name, Operations_Region_Code__c, Location_Code__c, Sales_Rep_ID__c
            FROM Store__c
            WHERE Id IN :storeIds
        ]);
    }

    /**
    * @description 
    * @author Yi Zhang | 03/09/2020 
    * @param locationCodes 
    * @return List<Store__c> 
    **/
    public static List<Store__c> getStoresWithValidOpRegCodeByLocationCode(List<String> locationCodes) {
        return new List<Store__c>([
            SELECT Id, Location_Code__c, Operations_Region_Code__c 
            FROM Store__c 
            WHERE  Location_Code__c IN : locationCodes 
            AND Operations_Region_Code__c != null
        ]);
    }

    /**
    * @description 
    * @author Yi Zhang | 21/10/2020 
    * @param locationCodes 
    * @return List<Store__c> 
    **/
    public static List<Store__c> getStoresWithAddressByLocationCode(List<String> locationCodes) {
        return new List<Store__c>([
            SELECT Id, Location_Code__c, Location_Type__c, 
            Address_Line_1__c, Address_Line_2__c, Address_Line_3__c,
            City__c, State__c, Postcode__c, Country__c, Trade_Specialist_Email__c
            FROM Store__c 
            WHERE  Location_Code__c IN : locationCodes 
        ]);
    }
    
    /**
    * @description 
    * @author Simplus MS | 20/10/2021 
    * @param storeMembers 
    * @return Map<Id, Store__c> 
    **/
    public static Map<Id, Store__c> getStoreMap(List<Store_Member__c> storeMembers) {
        Set<Id> storeIdSet = new Set<Id>();
        for(Store_Member__c sm : storeMembers) {
            storeIdSet.add(sm.Store__c);
        }
        return new Map<Id, Store__c>([
            SELECT Id, Engagement_Model__c, Location_Type__c, Country__c, Store_Call__c
            FROM Store__c WHERE Id IN: storeIdSet
        ]);
    }
}