unpackaged/main/default/objects/Contract_Review_Field__mdt/Contract_Review_Field__mdt.object-meta.xml
<CustomObject>
    <description>Stores definitions of special buy line item columns and contract line item columns on contract review page.</description>
    <label>Contract Review Field</label>
    <pluralLabel>Contract Review Field</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Contract_Review_Field__mdt/fields/Additional_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Name__c</fullName>
    <description>For renewal contract, some editable inputs require an additional field need to be displayed on the top</description>
    <label>Additional Field Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contract_Review_Field__mdt/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Amendment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contract_Review_Field__mdt/fields/Cost_Zone__c.field-meta.xml
<CustomField>
    <fullName>Cost_Zone__c</fullName>
    <label>Cost Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ALL</fullName>
                <default>true</default>
                <label>ALL</label>
            </value>
            <value>
                <fullName>CZ 1</fullName>
            </value>
            <value>
                <fullName>CZ 2</fullName>
            </value>
            <value>
                <fullName>CZ 3</fullName>
            </value>
            <value>
                <fullName>CZ 4</fullName>
            </value>
            <value>
                <fullName>CZ 5</fullName>
            </value>
            <value>
                <fullName>CZ 6</fullName>
            </value>
            <value>
                <fullName>CZ 7</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contract_Review_Field__mdt/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>&quot;Australia&quot;</defaultValue>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Australia</fullName>
                <default>true</default>
                <label>Australia</label>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contract_Review_Field__mdt/fields/Field_Order__c.field-meta.xml
<CustomField>
    <fullName>Field_Order__c</fullName>
    <label>Field Order</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contract_Review_Field__mdt/fields/Field_Type__c.field-meta.xml
<CustomField>
    <fullName>Field_Type__c</fullName>
    <label>Field Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>string</fullName>
                <default>true</default>
                <label>string</label>
            </value>
            <value>
                <fullName>date</fullName>
            </value>
            <value>
                <fullName>currency</fullName>
            </value>
            <value>
                <fullName>percent</fullName>
            </value>
            <value>
                <fullName>number</fullName>
            </value>
            <value>
                <fullName>boolean</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contract_Review_Field__mdt/fields/Is_Retail__c.field-meta.xml
<CustomField>
    <fullName>Is_Retail__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checked, the &quot;Show Retail&quot; checkbox on Search / Filter will show/hide this field</inlineHelpText>
    <label>Is Retail</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contract_Review_Field__mdt/fields/Price_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Price_Field_Name__c</fullName>
    <description>The field referenced in Proposed CZx Special Buy Margin % calculation, special buy field only</description>
    <inlineHelpText>The field referenced in Proposed CZx Special Buy Margin % calculation, special buy field only</inlineHelpText>
    <label>Price Field Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contract_Review_Field__mdt/fields/Table_Type__c.field-meta.xml
<CustomField>
    <fullName>Table_Type__c</fullName>
    <defaultValue>&quot;Contract Line&quot;</defaultValue>
    <label>Table Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Special Buy Line</fullName>
                <default>true</default>
                <label>Special Buy Line</label>
            </value>
            <value>
                <fullName>Contract Line</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/DM_ContractReviewField.cls
/*******************************************************************************************************
* Class Name      	: DM_ContractReviewField
* Description		: Data Layer - Selector for custom metadata Contract_Review_Field__mdt
* Author          	: Simplus - Yi Zhang
* Created On      	: 2020-05-25
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Yi Zhang              2020-05-25		1000				Initial version
******************************************************************************************************/
public with sharing class DM_ContractReviewField {
    /**
    * @description 
    * @author Yi Zhang | 25/05/2020 
    * @param costZones 
    * @return List<Contract_Review_Field__mdt> 
    **/
    public static List<Contract_Review_Field__mdt> getSpecialBuyFields(List<String> costZones) {
        costZones.add('ALL');
        return [
            SELECT Id, Field_Name__c, Label__c, Field_Type__c, Price_Field_Name__c, Field_Order__c 
            FROM Contract_Review_Field__mdt
            WHERE Cost_Zone__c IN :costZones
            AND Table_Type__c = 'Special Buy Line'
            ORDER BY Field_Order__c ASC
        ];
    }

    
    /**
    * @description 
    * @author Yi Zhang | 26/05/2020 
    * @param costZones 
    * @param country 
    * @param contractType 
    * @return List<Contract_Review_Field__mdt> 
    **/
    public static List<Contract_Review_Field__mdt> getContractLineFields(List<String> costZones, String country, String contractType) {
        costZones.add('ALL');
        return [
            SELECT Id, Field_Name__c, Label__c, Field_Type__c, Field_Order__c, Editable__c, Is_Retail__c, Additional_Field_Name__c 
            FROM Contract_Review_Field__mdt
            WHERE Cost_Zone__c IN :costZones
            AND Table_Type__c = 'Contract Line'
            AND Country__c = :country
            AND Contract_Type__c = :contractType
            ORDER BY Field_Order__c ASC
        ];
    }
}