unpackaged/main/default/objects/Spend_Band_Review__c/Spend_Band_Review__c.object-meta.xml
<CustomObject>
    <description>This Object represents the Spend Band Review table mastered in the Commercial Pricing System (CPS). CPS is the master of the Spend Band review data, Salesforce owns the Spend Band Review approval process.</description>
    <label>Spend Band Review</label>
    <nameField>
        <displayFormat>SBR-{0000000}</displayFormat>
        <label>Review Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Spend Band Reviews</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Spend_Band_Review__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Spend Band Reviews</relationshipLabel>
    <relationshipName>Spend_Band_Reviews</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Spend_Band_Review__c/fields/Level_1_Action__c.field-meta.xml
<CustomField>
    <fullName>Level_1_Action__c</fullName>
    <inlineHelpText>A is for Accepted. R is for Rejected</inlineHelpText>
    <label>Level 1 Action</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>Approved</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Spend_Band_Review__c/fields/Level_1_Approver__c.field-meta.xml
<CustomField>
    <fullName>Level_1_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Level 1 Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Spend_Band_Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/DM_SpendBandReview.cls
/*******************************************************************************************************
* Class Name      	: DM_SpendBandReview
* Description		: Data Layer - Selector for Sobject Spend_Band_Review__c
* Author          	: Simplus - Yi Zhang
* Created On      	: 18/05/2020
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Yi Zhang              18/05/2020		1000				Initial version
******************************************************************************************************/
public with sharing class DM_SpendBandReview {

    /**
    * @description Level 1 Approver is the same as owner for this object
    * @author Yi Zhang | 18/05/2020 
    * @param accountIds 
    * @param approverIds 
    * @return Map<Id, Spend_Band_Review__c> 
    **/
    public static Map<Id, Spend_Band_Review__c> getSpendBandReviewsForApprover1(Set<Id> accountIds, Set<Id> approverIds) {
        
        return new Map<Id, Spend_Band_Review__c>([
            SELECT Id, Account__c, Level_1_Approver__c
            FROM Spend_Band_Review__c
            WHERE Account__c IN :accountIds
            AND Level_1_Approver__c IN :approverIds
            AND Level_1_Action__c = null
        ]);
    }
}