unpackaged/main/default/objects/Special_Buy__c/Special_Buy__c.object-meta.xml
<CustomObject>
    <description>This Object is a header representation of an external pricing table, used to group a number of Special Buy Lines (Products purchased for a non-standard Cost Price) purchased from a single supplier</description>
    <label>Special Buy</label>
    <nameField>
        <label>Special Buy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Special Buys</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Special_Buy__c/fields/Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiry_Date__c</fullName>
    <description>The date the Special Buy expires.</description>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Special_Buy__c/fields/Location_Type__c.field-meta.xml
<CustomField>
    <fullName>Location_Type__c</fullName>
    <description>Country the special buy belongs</description>
    <label>Location Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All Stores</fullName>
            </value>
            <value>
                <fullName>All Retail Stores</fullName>
            </value>
            <value>
                <fullName>All Trade Sites</fullName>
            </value>
            <value>
                <fullName>Store Specific</fullName>
            </value>
            <value>
                <fullName>All Trade Stores</fullName>
                <isActive>false</isActive>
                <label>All Trade Stores</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Special_Buy__c/fields/Requested_Date__c.field-meta.xml
<CustomField>
    <fullName>Requested_Date__c</fullName>
    <description>The date the Special Buy starts</description>
    <label>Requested Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Special_Buy__c/fields/States__c.field-meta.xml
<CustomField>
    <fullName>States__c</fullName>
    <description>States associated to the special buy.</description>
    <label>State(s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACT</fullName>
            </value>
            <value>
                <fullName>NSW</fullName>
            </value>
            <value>
                <fullName>NT</fullName>
            </value>
            <value>
                <fullName>QLD</fullName>
            </value>
            <value>
                <fullName>SA</fullName>
            </value>
            <value>
                <fullName>TAS</fullName>
            </value>
            <value>
                <fullName>VIC</fullName>
            </value>
            <value>
                <fullName>WA</fullName>
            </value>
            <value>
                <fullName>NQ</fullName>
            </value>
            <value>
                <fullName>NI</fullName>
            </value>
            <value>
                <fullName>SI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Special_Buy_Line_Item__c/Special_Buy_Line_Item__c.object-meta.xml
<CustomObject>
    <description>This Object is a representation of an external pricing table, where a product has been purchased for a non-standard Cost Price.</description>
    <label>Special Buy Line Item</label>
    <nameField>
        <label>Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Special Buy Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Special_Buy_Line_Item__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <description>Cost excluding GST</description>
    <label>Special Buy Cost (Ex-GST)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Special_Buy_Line_Item__c/fields/Special_Buy__c.field-meta.xml
<CustomField>
    <fullName>Special_Buy__c</fullName>
    <description>A lookup to the related Special Buy.</description>
    <label>Special Buy</label>
    <referenceTo>Special_Buy__c</referenceTo>
    <relationshipLabel>Special Buy Line Items</relationshipLabel>
    <relationshipName>Special_Buy_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/DM_SpecialBuyLineItem.cls
/*******************************************************************************************************
* Class Name      	: DM_SpecialBuyLineItem
* Description		: Data Layer - Selector for Sobject Special_Buy_Line_Item__c
* Author          	: Simplus - Yi Zhang
* Created On      	: 29/05/2020
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Yi Zhang              29/05/2020		1000				Initial version
******************************************************************************************************/
public with sharing class DM_SpecialBuyLineItem {
    
    /**
    * @description 
    * @author Yi Zhang | 29/05/2020 
    * @param specialBuyIds 
    * @return List<Special_Buy_Line_Item__c> 
    **/
    public static List<Special_Buy_Line_Item__c> getNotExpiredSpecialBuyLineItems(List<Id> specialBuyIds) {
        return new List<Special_Buy_Line_Item__c>([
            SELECT Id, Name, Cost__c,            // Special Buy Cost (Ex-GST) ($)
            // special buy fields
            Special_Buy__c,
            Special_Buy__r.Id,
            Special_Buy__r.Name,                // supplier quote number
            Special_Buy__r.Requested_Date__c,   // start date
            Special_Buy__r.Expiry_Date__c,      // end date
            Special_Buy__r.Location_Type__c,    // location type
            Special_Buy__r.States__c            // states
            FROM Special_Buy_Line_Item__c
            WHERE Special_Buy__r.Expiry_Date__c >= TODAY
            AND Special_Buy__c IN :specialBuyIds
        ]);
    }
}