unpackaged/main/default/objects/Initialisation__mdt/Initialisation__mdt.object-meta.xml
<CustomObject>
    <description>CCRM initialisation items</description>
    <label>Initialisation</label>
    <pluralLabel>Initialisations</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Initialisation__mdt/fields/Default_TS_Auto_Selection_Exemption__c.field-meta.xml
<CustomField>
    <fullName>Default_TS_Auto_Selection_Exemption__c</fullName>
    <description>List of profiles that can able to manually select the next available Default Trade specialist. CCRM15-417</description>
    <inlineHelpText>List of profiles that can able to manually select the next available Default Trade specialist. CCRM15-417</inlineHelpText>
    <label>Default TS Auto Selection Exemption</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Initialisation__mdt/fields/RCM_Profiles__c.field-meta.xml
<CustomField>
    <fullName>RCM_Profiles__c</fullName>
    <description>Allowed Team Member Profiles when Role is RCM (In Store Member and Operations Region objects)</description>
    <inlineHelpText>Allowed Team Member Profiles when Role is RCM (In Store Member and Operations Region objects)</inlineHelpText>
    <label>RCM Profiles</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Initialisation__mdt/fields/Trade_Specialist_Profiles__c.field-meta.xml
<CustomField>
    <fullName>Trade_Specialist_Profiles__c</fullName>
    <description>Allowed Team Member Profiles when Role is Trade Specialist (In Store Member and Operations Region objects)</description>
    <inlineHelpText>Allowed Team Member Profiles when Role is Trade Specialist (In Store Member and Operations Region objects)</inlineHelpText>
    <label>Trade Specialist Profiles</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Planned_Leave__c/Planned_Leave__c.object-meta.xml
<CustomObject>
    <label>Planned Leave</label>
    <nameField>
        <displayFormat>PL-{0000}</displayFormat>
        <label>Planned Leave Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Planned Leave</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Planned_Leave__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approval In Progress</fullName>
            </value>
            <value>
                <fullName>Leave Cancelled</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>Represents all frame and truss plants, small format stores, trade distribution centres and warehouses.</description>
    <label>Store</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Store_Member__c/Store_Member__c.object-meta.xml
<CustomObject>
    <description>Junction between user (team members) and store.</description>
    <label>Store Member</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>Store Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Store_Member__c/fields/Default_Trade_Specialist__c.field-meta.xml
<CustomField>
    <fullName>Default_Trade_Specialist__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the trade specialist is default or not</description>
    <label>Default Trade Specialist</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Store_Member__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End date of association with the store</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Store_Member__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start date of association with the store</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Store_Member__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Store_Member__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipName>User_Stores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Store_Member__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Stores</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/DefaultTSPlannedLeaveBatch.cls
/*******************************************************************************************************
* Class Name      	: DefaultTSPlannedLeaveBatch
* Description		: Batch class to Update Default Trade Specialist of Store as per Planned Leave for CCRM15-417
* Author          	: Simplus MS
* Created On      	: 29/11/2021
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer			  		Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Simplus.MS                29/11/2021		1000				Initial version
******************************************************************************************************/
global class DefaultTSPlannedLeaveBatch implements Database.Batchable<sObject> {
    
    String query;
    
    public DefaultTSPlannedLeaveBatch() {
        query = 'SELECT Start_Date__c, End_Date__c, OwnerId ' +
            'FROM Planned_Leave__c ' +
            'WHERE Status__c = \'Approved\' AND (Start_Date__c = TODAY OR End_Date__c = TODAY)';
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext BC, List<Planned_Leave__c> scope) {
        try {
            updateDefaultTSOfStore(scope);  
        } catch(Exception e) {
            ApplicationLogger.log('DefaultTSPlannedLeaveBatch', 'Planned_Leave__c', 'Batch', e);
        }
    }
    
    
    public void finish(Database.BatchableContext BC) {
        // Actions to be carried out on finish of batch job
    }
    
    /**
* @description : Update Default Trade Specialist of Store as per Planned Leave for CCRM15-417
* @author Simplus MS | 29/11/2021
* @param Scope 
**/
    public void updateDefaultTSOfStore(List<Planned_Leave__c> lstPlannedLeave) {

            Set<Id> OwnerIds = new Set<Id>();
            if(lstPlannedLeave.size() > 0) {
                for(Planned_Leave__c plObj:lstPlannedLeave){
                    OwnerIds.add(plObj.OwnerId);
                }
            }
            
            List<Initialisation__mdt> filterRCMProfileList = [SELECT Id, Default_TS_Auto_Selection_Exemption__c FROM Initialisation__mdt];
            
            //String strProfilesOFTSAndRCM = filterRCMProfileList[0].RCM_Profiles__c + ',' + filterRCMProfileList[0].Trade_Specialist_Profiles__c;
            List<String> profilesOFRCMList = new List<String> {filterRCMProfileList[0].Default_TS_Auto_Selection_Exemption__c.replaceAll(',(\\s+)', ',')};
                
                List<Store_Member__c> storeMemList = [SELECT Id, Default_Trade_Specialist__c, Team_Member__r.Name, Store__c, LastModifiedBy.Profile.Name 
                                                      FROM Store_Member__c 
                                                      WHERE Team_Member__c IN  :OwnerIds
                                                      AND Default_Trade_Specialist__c = TRUE
                                                      AND LastModifiedBy.Profile.Name NOT IN :profilesOFRCMList];
            Set<Id> storeIds = new Set<Id>();
            if(storeMemList.size() > 0) {
                for(Store_Member__c storeMem:storeMemList){
                    storeIds.add(storeMem.Store__c);
                }
            }
            
            Map<Id, Integer> storePLTSCount = new Map<Id, Integer>();
            for(Store__c store : DM_Store.getStoresWithActiveTSList(new List<Id>(storeIds), null)) {
                storePLTSCount.put(store.Id, store.User_Stores__r.size());
            }
            
            List<Store_Member__c> lstOfStoreMembersToUpdate = new List<Store_Member__c>();
            if(storeMemList.size() > 0) {
                for(Store_Member__c smObj : storeMemList) {
                    if(storePLTSCount.get(smObj.Store__c) > 0 
                        && !filterRCMProfileList[0].Default_TS_Auto_Selection_Exemption__c.contains(smObj.LastModifiedBy.Profile.Name)){
                        lstOfStoreMembersToUpdate.add(new Store_Member__c(Id = smObj.Id, Default_Trade_Specialist__c = FALSE));
                    }
                }
            }
            
            if(lstOfStoreMembersToUpdate.size() > 0) {
                try {
                    Update lstOfStoreMembersToUpdate;
                } catch(Exception e) {
                    ApplicationLogger.log('DefaultTSPlannedLeaveBatch', 'Planned_Leave__c', 'Batch', e);
                }
            }    
    }
}