unpackaged/main/default/objects/Initialisation__mdt/Initialisation__mdt.object-meta.xml
<CustomObject>
    <description>CCRM initialisation items</description>
    <label>Initialisation</label>
    <pluralLabel>Initialisations</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Initialisation__mdt/fields/Staging_Object_Exemption_Profile__c.field-meta.xml
<CustomField>
    <fullName>Staging_Object_Exemption_Profile__c</fullName>
    <label>Staging Object Exemption Profile</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Loss_Reason__c.field-meta.xml
<CustomField>
    <fullName>Loss_Reason__c</fullName>
    <label>Loss Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>CLOSED_LOST_BUNN_DELV_AVAIL</fullName>
                <label>Closed Lost - Bunnings Delivery Availability</label>
            </value>
            <value>
                <fullName>CLOSED_LOST_PRICING</fullName>
                <label>Closed Lost - Pricing</label>
            </value>
            <value>
                <fullName>CLOSED_LOST_PRIC_TENDER</fullName>
                <label>Closed Lost - Pricing for Tender</label>
            </value>
            <value>
                <fullName>CLOSED_LOST_PUR_NETWORK</fullName>
                <label>Closed Lost - Purchased in Network</label>
            </value>
            <value>
                <fullName>CLOSED_LOST_QUOTE_TURNAROUND</fullName>
                <label>Closed Lost - Quote Turnaround Time</label>
            </value>
            <value>
                <fullName>CLOSED_LOST_STOCK_AVAIL</fullName>
                <label>Closed Lost - Stock Availability</label>
            </value>
            <value>
                <fullName>CLOSED_LOST_SUPP_ETA</fullName>
                <label>Closed Lost - Supplier ETA</label>
            </value>
            <value>
                <fullName>CLOSED_LOST_BETR_SUPP_DIR_AVAL</fullName>
                <label>Closed Lost - Better Pricing Direct from Supplier</label>
            </value>
            <value>
                <fullName>CLOSED_LOST_SUPP_INSR_DIR_AVAL</fullName>
                <label>Closed Lost - In Store Delivery Availability</label>
            </value>
            <value>
                <fullName>CLOSED_EXPIRED_OVER_30_DAYS</fullName>
                <label>Closed Lost-Quote Expired Over 30 Days</label>
            </value>
            <value>
                <fullName>ORDER_ENTRY_ERROR</fullName>
                <label>Order Entry Error</label>
            </value>
            <value>
                <fullName>LOSS_PREVENTION_REQUESTED</fullName>
                <label>Loss Prevention Requested</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Loss_Reason_Comments__c.field-meta.xml
<CustomField>
    <fullName>Loss_Reason_Comments__c</fullName>
    <label>Loss Reason Comments</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Primary_Quote_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Primary_Quote_Expiry_Date__c</fullName>
    <description>Field that replaces Close date as in #275</description>
    <label>Synced Quote Expiry Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Total_Value_excl_GST__c.field-meta.xml
<CustomField>
    <fullName>Total_Value_excl_GST__c</fullName>
    <formula>SyncedQuote.Total_Value_excl_GST__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Value (excl. GST)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/AU_Standard_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>AU_Standard_Opportunity</fullName>
    <active>true</active>
    <businessProcess>Standard AU Sales Process</businessProcess>
    <description>Standard Opportunities</description>
    <label>Standard Opportunity</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/recordTypes/AU_Store_Initiated_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>AU_Store_Initiated_Opportunity</fullName>
    <active>true</active>
    <businessProcess>Standard AU Sales Process</businessProcess>
    <description>Store / COS initiated opportunities in Australia</description>
    <label>AU Store Initiated Opportunity</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/recordTypes/NZ_Estimate_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>NZ_Estimate_Opportunity</fullName>
    <active>true</active>
    <businessProcess>NZ Sales Process</businessProcess>
    <description>Estimate Opportunities</description>
    <label>Estimate Opportunity</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/recordTypes/NZ_Farm_Shed_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>NZ_Farm_Shed_Opportunity</fullName>
    <active>true</active>
    <businessProcess>NZ Sales Process</businessProcess>
    <description>Farm Shed Opportunities</description>
    <label>Farm Shed Opportunity</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/recordTypes/NZ_Schedule_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>NZ_Schedule_Opportunity</fullName>
    <active>true</active>
    <businessProcess>NZ Sales Process</businessProcess>
    <description>Schedule Opportunities</description>
    <label>Schedule Opportunity</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/recordTypes/NZ_Standard_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>NZ_Standard_Opportunity</fullName>
    <active>true</active>
    <businessProcess>NZ Standard Process</businessProcess>
    <description>Standard Opportunities</description>
    <label>NZ Standard Opportunity</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/recordTypes/NZ_Store_Initiated_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>NZ_Store_Initiated_Opportunity</fullName>
    <active>true</active>
    <businessProcess>NZ Standard Process</businessProcess>
    <description>Store / COS initiated opportunities in New Zealand</description>
    <label>NZ Store Initiated Opportunity</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/recordTypes/Organisation_Tender_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Organisation_Tender_Opportunity</fullName>
    <active>true</active>
    <businessProcess>Organisation Tender Process</businessProcess>
    <description>Organisation Tender Opportunities</description>
    <label>Organisation Tender Opportunity</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/recordTypes/Supply_Install_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Supply_Install_Opportunity</fullName>
    <active>true</active>
    <businessProcess>Supply %26 Install Sales Process</businessProcess>
    <description>Supply &amp; Install Opportunity</description>
    <label>Supply &amp; Install Opportunity</label>
</RecordType>

unpackaged/main/default/objects/Order/fields/Cancellation_Comments__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Comments__c</fullName>
    <label>Cancellation Comments</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reason__c</fullName>
    <label>Cancellation Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>COMPETITOR_OFFER</fullName>
                <label>Competitor offer</label>
            </value>
            <value>
                <fullName>CREDIT_REJECTED</fullName>
                <label>Credit Rejected</label>
            </value>
            <value>
                <fullName>CUSTOMER_CANCELLED</fullName>
                <label>Customer Cancelled</label>
            </value>
            <value>
                <fullName>ITEM_NOT_AVAILABLE</fullName>
                <label>Item not available</label>
            </value>
            <value>
                <fullName>KITCHEN_REFUND</fullName>
                <label>Kitchen In-Home Refund</label>
            </value>
            <value>
                <fullName>LEAD_TIME</fullName>
                <label>Lead time</label>
            </value>
            <value>
                <fullName>NO_LONGER_REQUIRED</fullName>
                <label>No longer required</label>
            </value>
            <value>
                <fullName>ORDER_ENTRY_ERROR</fullName>
                <label>Order Entry Error</label>
            </value>
            <value>
                <fullName>ORDER_ERROR</fullName>
                <label>Order error</label>
            </value>
            <value>
                <fullName>OTHER</fullName>
                <label>Other</label>
            </value>
            <value>
                <fullName>OUT_OF_STOCK</fullName>
                <label>Out of stock</label>
            </value>
            <value>
                <fullName>PRICING</fullName>
                <label>Pricing</label>
            </value>
            <value>
                <fullName>PROCESSING_ERROR</fullName>
                <label>Processing Error</label>
            </value>
            <value>
                <fullName>RANGE</fullName>
                <label>Range</label>
            </value>
            <value>
                <fullName>SUBMITTED_TOO_LATE</fullName>
                <label>Order Submitted too late</label>
            </value>
            <value>
                <fullName>SYSTEM_CANCELLATION</fullName>
                <label>System Cancellation</label>
            </value>
            <value>
                <fullName>WITHDRAWN_BY_CUSTOMER</fullName>
                <label>Credit Request withdrawn by Customer</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order/fields/COS_ID__c.field-meta.xml
<CustomField>
    <fullName>COS_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>COS ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Order/fields/Total_GP__c.field-meta.xml
<CustomField>
    <fullName>Total_GP__c</fullName>
    <description>This field calculates the Total GP for an order</description>
    <formula>(Total_Value_excl_GST__c -  Total_Cost_excl_GST__c)/ Total_Value_excl_GST__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total GP</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Total_Value_excl_GST__c.field-meta.xml
<CustomField>
    <fullName>Total_Value_excl_GST__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The total value of the Order excluding GST</description>
    <label>Total Value (excl GST)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Cancellation_Comments__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Comments__c</fullName>
    <label>Cancellation Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reason__c</fullName>
    <label>Cancellation Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CUSTOMER_CANCELLED</fullName>
                <label>Customer Cancelled</label>
            </value>
            <value>
                <fullName>ORDER_ENTRY_ERROR</fullName>
                <label>Order Entry Error</label>
            </value>
            <value>
                <fullName>PRICING</fullName>
                <label>Pricing</label>
            </value>
            <value>
                <fullName>Pricing Only Quote</fullName>
            </value>
            <value>
                <fullName>OTHER</fullName>
                <label>Other</label>
            </value>
            <value>
                <fullName>COMPETITOR_OFFER</fullName>
                <label>Competitor offer</label>
            </value>
            <value>
                <fullName>CREDIT_REJECTED</fullName>
                <label>Credit Rejected</label>
            </value>
            <value>
                <fullName>ITEM_NOT_AVAILABLE</fullName>
                <label>Item not available</label>
            </value>
            <value>
                <fullName>KITCHEN_REFUND</fullName>
                <label>Kitchen In-Home Refund</label>
            </value>
            <value>
                <fullName>LEAD_TIME</fullName>
                <label>Lead time</label>
            </value>
            <value>
                <fullName>NO_LONGER_REQUIRED</fullName>
                <label>No longer required</label>
            </value>
            <value>
                <fullName>ORDER_ERROR</fullName>
                <label>Order error</label>
            </value>
            <value>
                <fullName>OUT_OF_STOCK</fullName>
                <label>Out of stock</label>
            </value>
            <value>
                <fullName>PROCESSING_ERROR</fullName>
                <label>Processing Error</label>
            </value>
            <value>
                <fullName>RANGE</fullName>
                <label>Range</label>
            </value>
            <value>
                <fullName>SYSTEM_CANCELLATION</fullName>
                <label>System Cancellation</label>
            </value>
            <value>
                <fullName>WITHDRAWN_BY_CUSTOMER</fullName>
                <label>Credit Request withdrawn by Customer</label>
            </value>
            <value>
                <fullName>SUBMITTED_TOO_LATE</fullName>
                <label>Order Submitted Too Late</label>
            </value>
            <value>
                <fullName>FRAUD_ORDER</fullName>
                <label>Processing Failure</label>
            </value>
            <value>
                <fullName>INVENTORY_INACCURACY</fullName>
                <label>Inventory Inaccuracy</label>
            </value>
            <value>
                <fullName>LOSS_PREVENTION_REQUESTED</fullName>
                <label>Loss Prevention Requested</label>
            </value>
            <value>
                <fullName>CLOSED_LOST_SUPP_INSR_DIR_AVAL</fullName>
                <label>Closed Lost - Supplier Direct/In Store Delivery Availability</label>
            </value>
            <value>
                <fullName>CLOSED_LOST_STOCK_AVAIL</fullName>
                <label>Closed Lost - Stock Availability/ Supplier ETA</label>
            </value>
            <value>
                <fullName>CLOSED_LOST_PRIC_TENDER</fullName>
                <label>Closed Lost - Pricing for Tender</label>
            </value>
            <value>
                <fullName>CLOSED_LOST_PRICING</fullName>
                <label>Closed Lost - Pricing</label>
            </value>
            <value>
                <fullName>CLOSED_LOST_QUOTE_TURNAROUND</fullName>
                <label>Closed Lost - Quote Turnaround Time</label>
            </value>
            <value>
                <fullName>CLOSED_LOST_PUR_NETWORK</fullName>
                <label>Closed Lost - Purchased in Network</label>
            </value>
            <value>
                <fullName>CLOSED_LOST_BUNN_DELV_AVAIL</fullName>
                <label>Closed Lost - Bunnings Delivery Availability</label>
            </value>
            <value>
                <fullName>CLOSED_EXPIRED_OVER_30_DAYS</fullName>
                <label>Closed-Quote Expired Over 30 Days</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Quote/fields/COS_ID__c.field-meta.xml
<CustomField>
    <fullName>COS_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>COS ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Total_GP__c.field-meta.xml
<CustomField>
    <fullName>Total_GP__c</fullName>
    <description>Total Gross Profit of this quote</description>
    <formula>(Total_Value_excl_GST__c - Total_Cost_excl_GST__c) / Total_Value_excl_GST__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total GP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Total_Value_excl_GST__c.field-meta.xml
<CustomField>
    <fullName>Total_Value_excl_GST__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total Amount minus the Goods and Services Tax</description>
    <label>Total Value (excl. GST)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Quote/recordTypes/COS_Quote.recordType-meta.xml
<RecordType>
    <fullName>COS_Quote</fullName>
    <active>true</active>
    <description>Quotes created in COS</description>
    <label>COS Quote</label>
</RecordType>

unpackaged/main/default/classes/QuoteTriggerHandler.cls
/*******************************************************************************************************
* Class Name      	: QuoteTriggerHandler
* Description		: Trigger Handler for Quote Object
* Author          	: Bunnings Dev
* Created On      	: 22/02/2022
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Bunnings Dev          22/02/2022		1000				SFSUP-51 - Conversion of Process Builder (Quote Create/Update Actions)
*															and Flow (COS Quote Initialisations, COS Quote and Opportunity Sync, 
*															COS Quote and Opportunity Sync, COS Quote to Opportunity Totals Sync)
* Simplus MS            30/05/2022		2000				SFSUP-738 - Opportunity has not updated the syncing quote, 
*                                                            therefore the opp value is incorrect
* Jasper R. Galapon     17/08/2023      3000                BUNDIG-24085 - Fix future call error when loading COS data
* Jasper R. Galapon     19/03/2025      3001                CRMS-470 - AU Store Initiated Opportunities created in Salesforce without any Quotes
* Jasper R. Galapon     07/05/2025      3002                BUNDIG-44073 - Update logic to include COS order token with Status = 'PricingOnlyQuote'
******************************************************************************************************/
public class QuoteTriggerHandler {
    
    public static final Id qtRtId = Schema.SObjectType.Quote.getRecordTypeInfosByDeveloperName().get('COS_Quote').getRecordTypeId();
    
    public static void beforeInsert(List<Quote> lstNewQuote) {
        System.debug('beforeInsert: '+lstNewQuote);
    }

    public static void afterInsert(List<Quote> lstNewQuote) {
        // Quote Create Action: COS Quote Initialisations Flow
        newCOSQuoteInitialisations(lstNewQuote);
    }
    
    public static void afterUpdate(Map<Id, Quote> oldMap, Map<Id, Quote> newMap) {
        // Quote Update Action: COS Quote and Opportunity Sync
        System.debug('***updateCOSQuoteAndOppSync');
        updateCOSQuoteAndOppSync(oldMap, newMap.values());
    }

    /**
    * @description SFSUP-738: Quote Create Action: COS Quote Initialisations Flow
    * @author Simplus MS | 31/05/2022
    * @param lstNewQuote
    **/
    @testVisible 
    private static void newCOSQuoteInitialisations(List<Quote> lstNewQuote) {

        Set<Id> oppIds = new Set<Id>();		                    // use to get all oppty information
        Set<Id> opptyIds = new Set<Id>();	                    // use to filter oppty related to quotes
        Map<Id, ID> opptyToUpdateMap = new Map<Id, ID>();       // used for cos Quote And Opportunity Sync

        for (Quote qt : lstNewQuote) {            
            if (qt.OpportunityId != null)
                oppIds.add(qt.OpportunityId);                        
        }
        
        if (!oppIds.isEmpty()) {
            // Get all opportunity information associated to the quote
            Map<Id, Opportunity> mapOppty = new Map<Id, Opportunity>([SELECT Id, StageName, RecordType.DeveloperName FROM Opportunity WHERE Id IN :oppIds]);
            
            for (Quote qt : lstNewQuote) {
                if (qt.COS_ID__c != null && mapOppty.get(qt.OpportunityId).RecordType.DeveloperName != 'Organisation_Tender_Opportunity' && mapOppty.get(qt.OpportunityId).StageName != 'Closed Won') {                
                    //qt.RecordTypeId = qtRtId;
                    opptyIds.add(qt.OpportunityId);
                    opptyToUpdateMap.put(qt.Id, qt.OpportunityId);
                }
                System.debug(LoggingLevel.FINEST, '***AFTER INSERT opptyIds: ' + opptyIds);
                //SFSUP-792 - Sync S&I Opportunities
              /*  if (qt.Name != null && mapOppty.get(qt.OpportunityId).RecordType.DeveloperName == 'Supply_Install_Opportunity' && mapOppty.get(qt.OpportunityId).StageName != 'Closed Won') {
                    //qt.RecordTypeId = qtRtId;
                     opptyIds.add(qt.OpportunityId);
                     opptyToUpdateMap.put(qt.Id, qt.OpportunityId);
               }   */         
            }
           

            // Quote Create Action: COS Quote Initialisations Flow
            // BUNDIG-24085 - Commented out to fix future method issue
            // cosQuoteAndOppSync(opptyToUpdateMap);

            System.debug('***opptyToUpdateMap: ' + opptyToUpdateMap);

            Initialisation__mdt init = DM_Initialisation.getCCRMInitialisation();
            List<String> exemptionProfile = init.Staging_Object_Exemption_Profile__c.split(', ');
            System.debug(LoggingLevel.FINEST, '***exemptionProfile: ' + exemptionProfile);
    
            // Get Running User Details
            User runningUser = DM_User.getUser(UserInfo.getUserId());
            System.debug(LoggingLevel.FINEST, '***runningsUser: ' + runningUser);
    
            if (runningUser != null && !exemptionProfile.contains(runningUser.Profile.Name)) {
                System.debug(LoggingLevel.FINEST, '***Non-admin user');
                cosQuoteAndOppSync(opptyToUpdateMap);
            
                // Quote Create Action: COS Quote and Opportunity Sync Flow
                cosQuoteAndOppSync(cosQuoteAndOpportunitySync(opptyIds, lstNewQuote, null));
            } else {
                System.debug(LoggingLevel.FINEST, '***Admin user');
                System.enqueueJob(new SM_CosQuoteAndOppSyncQueueable(opptyToUpdateMap));
            }
        }
    }
    
    /**
    * @description SFSUP-738: Based on received map this method sync quote with oppoortunity
    * @author Simplus MS | 31/05/2022
    * @param map of oppToUpdateMap
    **/
    @future
    public static void cosQuoteAndOppSync(Map<Id, Id> oppToUpdateMap) {
        List<Opportunity> oppUpdateList = new List<Opportunity>();
        if (!oppToUpdateMap.isEmpty()) {
            for (Id key : oppToUpdateMap.keySet()) {
                oppUpdateList.add(new Opportunity(Id = oppToUpdateMap.get(key), SyncedQuoteId = key));
            }
        }
        if (!oppUpdateList.isEmpty()) {
            try {
                UPDATE oppUpdateList;
            } catch (Exception e) {
                ApplicationLogger.log('QuoteTriggerHandler.cosQuoteAndOppSync', 'Quote', 'Trigger', e);
            }            
        }
    }
    
    /**
    * @description SFSUP-738: Quote Update Action: COS Quote and Opportunity Sync
    * @author Simplus MS | 31/05/2022
    * @param lstNewQuote
    **/
    @testVisible
    private static Map<Id, Opportunity> updateCOSQuoteAndOppSync(Map<Id, Quote> mapOldQuote, List<Quote> lstNewQuote) {
                
        Set<Id> opptyIds = new Set<Id>();	// use to filter oppty related to quotes
        Map<Id, Opportunity> opptyUpdate = new Map<Id, Opportunity>();
                        
        for (Quote qt : lstNewQuote) {                
            if (qt.COS_ID__c != null && qt.Opportunity.RecordType.DeveloperName != 'Organisation_Tender_Opportunity' && qt.Opportunity.StageName != 'Closed Won') {
                opptyIds.add(qt.OpportunityId);
            }            
        }
        System.debug(LoggingLevel.FINEST, '***opptyIds: ' + opptyIds);
        if (!opptyIds.isEmpty()) {
            for (Quote qt : lstNewQuote) {               

                Quote oldQuote = mapOldQuote?.get(qt.Id);

                // BUNDIG-44073 - Start
                String lossReason = '';
                //String lossReason = qt.Status == 'Pricing Only Quote' ? 'Pricing Only Quote' : qt.Cancellation_Reason__c;
                System.debug(LoggingLevel.FINEST, '***qt.Cancellation_Reason: ' + qt.Cancellation_Reason__c);

                if (qt.Cancellation_Reason__c != null) {
                    lossReason = qt.Cancellation_Reason__c;
                } else if (qt.Status == 'Pricing Only Quote' || qt.Status == 'PricingOnlyQuote') {
                    lossReason = 'Closed Lost - Pricing';
                }
                System.debug(LoggingLevel.FINEST, '***lossReason : ' + lossReason);
                // BUNDIG-44073 - End

                Date qtCancelDt = qt.ExpirationDate != null ? qt.ExpirationDate : null;			
    
                if (qt.COS_ID__c != null && qt.Opportunity.RecordType.DeveloperName != 'Organisation_Tender_Opportunity' &&
                    (qt.Opportunity.StageName != 'Closed Won' || (qt.Opportunity.StageName == 'Closed Won' && qt.IsSyncing)) &&
                    (qt.Total_GP__c != oldQuote?.Total_GP__c || qt.Cancellation_Reason__c != oldQuote?.Cancellation_Reason__c || 
                    qt.Total_Value_excl_GST__c != oldQuote?.Total_Value_excl_GST__c || qt.Cancellation_Comments__c != oldQuote?.Cancellation_Comments__c ||
                    qt.ExpirationDate != oldQuote?.ExpirationDate)) {
                        //if(opptyUpdate.containsKey(qt.OpportunityId)) {
                            opptyUpdate.put(qt.OpportunityId, new Opportunity(Id = qt.OpportunityId, 
                                                                                Amount = qt.Total_Value_excl_GST__c,
                                                                                //StageName = opptyUpdate.get(qt.OpportunityId).StageName,
                                                                                Loss_Reason__c = lossReason, 
                                                                                Loss_Reason_Comments__c = qt.Cancellation_Comments__c,
                                                                                SyncedQuoteId = qt.Id,
                                                                                Primary_Quote_Expiry_Date__c = qtCancelDt));
                        //}
                }
                                
            }
            
            System.debug('***opptyUpdate: '+opptyUpdate.values());

            // Quote Update Action: COS Quote and Opportunity Sync Flow
            // Future method cannot be called from a future or batch method
            if(System.IsBatch() == false && System.isFuture() == false){ 
                // make your future call here
                cosQuoteAndOppSync(cosQuoteAndOpportunitySync(opptyIds, lstNewQuote, mapOldQuote));

                //COS Quote To Opportunity TotalsSync action
                if (!opptyUpdate.isEmpty()) {
                    //Using JSON.Serialize method we can convert the Opportunity list to Json
                    // Pass the JSON String to the Future method
                    cosQuoteToOpportunityTotalsSync(json.serialize(opptyUpdate.values()));
                }
            }
            
            
            /*if (!opptyUpdate.isEmpty()) {
                try {
                    UPDATE opptyUpdate.values();
                } catch (Exception e) {
                    ApplicationLogger.log('QuoteTriggerHandler.updateCOSQuoteAndOppSync', 'Quote', 'Trigger', e);
                }            
            }*/
            
            return opptyUpdate;
        } else {
            return null;
        }
    }

    /**
    * @description SFSUP-738: Based on received JSON this method sync quote with 
    * oppoortunity for: COS Quote To Opportunity TotalsSync flow
    * @author Simplus MS | 15/06/2022
    * @param map of oppToUpdateMap
    **/
    @future
    public static void cosQuoteToOpportunityTotalsSync(String jsonString) {
        //deserialize the JSON to the Account List
        List<Opportunity> oppUpdateList = (List<Opportunity>)Json.deserialize(jsonString, List<Opportunity>.class);
        if (!oppUpdateList.isEmpty()) {
            try {
                UPDATE oppUpdateList;
            } catch (Exception e) {
                ApplicationLogger.log('QuoteTriggerHandler.cosQuoteToOpportunityTotalsSync', 'Quote', 'Trigger', e);
            }            
        }
    }
    
    /**
    * @description SFSUP-738: Quote Create/Update Action: COS Quote and Opportunity Sync
    * @author Simplus MS | 31/05/2022
    * @param Set<Id> oppIds, List<Quote> newQuote, Map<Id, Quote> oldQuot
    **/
    private static Map<Id, Id> cosQuoteAndOpportunitySync(Set<Id> oppIds, List<Quote> newQuote, Map<Id, Quote> oldQuote) {
        
        Map<Id, Opportunity> mapOpp = new Map<Id, Opportunity>();
        Map<Id, Id> cosQuoteAndOppSync = new Map<Id, Id>();
                        
        Map<Id, Opportunity> mapOppty = new Map<Id, Opportunity>([SELECT Id, StageName, RecordType.DeveloperName, Loss_Reason__c,
			Loss_Reason_Comments__c, Primary_Quote_Expiry_Date__c
			FROM Opportunity WHERE Id IN :oppIds]);

        Map<Id, Opportunity> mapOpenQtsWithOpp = new Map<Id, Opportunity>([SELECT Id, (SELECT Id, Status 
        FROM Quotes WHERE Status NOT IN ('Cancelled','Pricing_Only_Quote', 'PricingOnlyQuote') ORDER BY LastModifiedDate DESC LIMIT 1) // BUNDIG-44073
        FROM Opportunity WHERE Id IN :oppIds]);       
        for (Quote qt : newQuote) {
            Quote oldQt = oldQuote != null ? oldQuote?.get(qt.Id) : null;
			
            String opptyRt = mapOppty.get(qt.OpportunityId) != null ? mapOppty.get(qt.OpportunityId).RecordType.DeveloperName : null;
            String opptyStage = mapOppty.get(qt.OpportunityId) != null ? mapOppty.get(qt.OpportunityId).StageName : null;

            // BUNDIG-44073 - Start
            String lossReason = '';
            //String lossReason = qt.Status == 'Pricing_Only_Quote' ? 'Pricing_Only_Quote' : qt.Cancellation_Reason__c;
            System.debug(LoggingLevel.FINEST, '***qt.Cancellation_Reason: ' + qt.Cancellation_Reason__c);

            if (qt.Cancellation_Reason__c != null) {
                lossReason = qt.Cancellation_Reason__c;
            } else if (qt.Status == 'Pricing Only Quote' || qt.Status == 'PricingOnlyQuote') {
                lossReason = 'Closed Lost - Pricing';
            }
            System.debug(LoggingLevel.FINEST, '***lossReason: ' + lossReason);
            // BUNDIG-44073 - End

            Date qtCancelDt = qt.ExpirationDate != null ? qt.ExpirationDate : null;                        
            System.debug('qt.Status: '+qt.Status+' oldQt: '+oldQt+' opptyRt: '+opptyRt+' opptyStage: '+opptyStage);

            if(oldQuote == null){
                // When Insert: Sync Opportunity - COS Quote and Opportunity Sync
                // CRMS-347 - Added Oppty BDM Contract Record Type
                if (opptyRt != 'Organisation_Tender_Opportunity' && opptyStage != 'Closed Won') {
                                                                                    
                    if (qt.Status == 'Cancelled' || qt.Status == 'Pricing_Only_Quote' || qt.Status == 'PricingOnlyQuote') { // BUNDIG-44073
                        
                        // CRMS-470 - Added null checking
                        if (mapOpenQtsWithOpp.get(qt.OpportunityId) == null || mapOpenQtsWithOpp.get(qt.OpportunityId).Quotes.size() == 0) {
                            if (qt.Status == 'Cancelled') {
                                mapOpp.put(qt.OpportunityId, new Opportunity(Id = qt.OpportunityId, 
                                    StageName = 'Closed Lost', 
                                    Loss_Reason__c = lossReason, 
                                    Loss_Reason_Comments__c = qt.Cancellation_Comments__c, 
                                    Amount = qt.Total_Value_excl_GST__c,
                                    Primary_Quote_Expiry_Date__c = qtCancelDt));
                            }
                            if (qt.Status == 'Pricing_Only_Quote' || qt.Status == 'PricingOnlyQuote') { // BUNDIG-44073
                                mapOpp.put(qt.OpportunityId, new Opportunity(Id = qt.OpportunityId, StageName = 'Closed Lost', Loss_Reason__c = 'Closed Lost - Pricing'));
                            }
                        } else {
                            mapOpp.put(qt.OpportunityId, new Opportunity(Id = qt.OpportunityId, Loss_Reason__c = null, Loss_Reason_Comments__c = qt.Cancellation_Comments__c));
                            cosQuoteAndOppSync.put(mapOpenQtsWithOpp.get(qt.OpportunityId).Quotes[0].Id, qt.OpportunityId);
                        }
                    }
                    if (qt.Status == 'Submitted') {
                        mapOpp.put(qt.OpportunityId, new Opportunity(Id = qt.OpportunityId, 
                            StageName = 'Closed Won', 
                            Loss_Reason__c = lossReason, 
                            Loss_Reason_Comments__c = qt.Cancellation_Comments__c,
                            Amount = qt.Total_Value_excl_GST__c,
                            Primary_Quote_Expiry_Date__c = qtCancelDt));                    
                    }
                    if (qt.Status == 'Enquiry' || qt.Status == 'Quote') {
                        if (opptyRt == 'NZ_Standard_Opportunity' || opptyRt == 'NZ_Store_Initiated_Opportunity') {
                            mapOpp.put(qt.OpportunityId, new Opportunity(Id = qt.OpportunityId, 
                                StageName = 'Pending', 
                                Amount = qt.Total_Value_excl_GST__c,
                                Loss_Reason__c = lossReason,
                                Loss_Reason_Comments__c = qt.Cancellation_Comments__c, 
                                Primary_Quote_Expiry_Date__c = qtCancelDt));                        
                        }
                        if (opptyRt == 'NZ_Schedule_Opportunity' || opptyRt == 'NZ_Farm_Shed_Opportunity' || opptyRt == 'NZ_Estimate_Opportunity') {
                            mapOpp.put(qt.OpportunityId, new Opportunity(Id = qt.OpportunityId, 
                                StageName = 'Proposal', 
                                Amount = qt.Total_Value_excl_GST__c,
                                Loss_Reason__c = lossReason,
                                Loss_Reason_Comments__c = qt.Cancellation_Comments__c, 
                                Primary_Quote_Expiry_Date__c = qtCancelDt));                        
                        }
                        if (opptyRt == 'AU_Standard_Opportunity' || opptyRt == 'AU_Store_Initiated_Opportunity') {
                            mapOpp.put(qt.OpportunityId, new Opportunity(Id = qt.OpportunityId, 
                                StageName = 'Proposal', 
                                Amount = qt.Total_Value_excl_GST__c,
                                Loss_Reason__c = lossReason,
                                Loss_Reason_Comments__c = qt.Cancellation_Comments__c, 
                                Primary_Quote_Expiry_Date__c = qtCancelDt));
                        }
                        if (opptyRt == 'Supply_Install_Opportunity') {
                            // SFSUP-792 - Sync S&I Opportunities 
                            mapOpp.put(qt.OpportunityId, new Opportunity(Id = qt.OpportunityId, 
                                StageName = 'Proposal in Progress', 
                                Amount = qt.Total_Value_excl_GST__c,
                                Loss_Reason__c = lossReason,
                                Loss_Reason_Comments__c = qt.Cancellation_Comments__c, 
                                Primary_Quote_Expiry_Date__c = qtCancelDt));
                        }
                        
                    }                
                }
            }else{
                // When Update: Sync Opportunity - COS Quote and Opportunity Sync
                if ((qt.Status != oldQt?.Status && oldQuote != null) && qt.RecordTypeId == qtRtId && opptyRt != 'Organisation_Tender_Opportunity' && opptyStage != 'Closed Won') {                                                                       
                    if (qt.Status == 'Cancelled' || qt.Status == 'Pricing_Only_Quote' || qt.Status == 'PricingOnlyQuote') {  // BUNDIG-44073  
                        
                        // CRMS-470 - Added null checking
                        if (mapOpenQtsWithOpp.get(qt.OpportunityId) == null || mapOpenQtsWithOpp.get(qt.OpportunityId).Quotes.size() == 0) {
                            if (qt.Status == 'Cancelled') {
                                mapOpp.put(qt.OpportunityId, new Opportunity(Id = qt.OpportunityId, 
                                    StageName = 'Closed Lost', 
                                    Loss_Reason__c = lossReason, 
                                    Loss_Reason_Comments__c = qt.Cancellation_Comments__c, 
                                    Amount = qt.Total_Value_excl_GST__c,
                                    Primary_Quote_Expiry_Date__c = qtCancelDt));                            
                            }
                        
                            if (qt.Status == 'Pricing_Only_Quote' || qt.Status == 'PricingOnlyQuote') {  // BUNDIG-44073                        
                                mapOpp.put(qt.OpportunityId, new Opportunity(Id = qt.OpportunityId, StageName = 'Closed Lost', Loss_Reason__c = 'Closed Lost - Pricing'));
                            }
                        } else {
                            mapOpp.put(qt.OpportunityId, new Opportunity(Id = qt.OpportunityId, Loss_Reason__c = null, Loss_Reason_Comments__c = qt.Cancellation_Comments__c));
                            cosQuoteAndOppSync.put(mapOpenQtsWithOpp.get(qt.OpportunityId).Quotes[0].Id, qt.OpportunityId);
                        }
                    }
                    if (qt.Status == 'Submitted') {
                        mapOpp.put(qt.OpportunityId, new Opportunity(Id = qt.OpportunityId, 
                            StageName = 'Closed Won', 
                            Loss_Reason__c = lossReason, 
                            Loss_Reason_Comments__c = qt.Cancellation_Comments__c,
                            Amount = qt.Total_Value_excl_GST__c,
                            Primary_Quote_Expiry_Date__c = qtCancelDt));                    
                    }
                    if (qt.Status == 'Enquiry' || qt.Status == 'Quote') {
                        if (opptyRt == 'NZ_Standard_Opportunity' || opptyRt == 'NZ_Store_Initiated_Opportunity') {
                            mapOpp.put(qt.OpportunityId, new Opportunity(Id = qt.OpportunityId, 
                                StageName = 'Pending', 
                                Amount = qt.Total_Value_excl_GST__c,
                                Loss_Reason__c = lossReason,
                                Loss_Reason_Comments__c = qt.Cancellation_Comments__c, 
                                Primary_Quote_Expiry_Date__c = qtCancelDt));                        
                        }
                        if (opptyRt == 'NZ_Schedule_Opportunity' || opptyRt == 'NZ_Farm_Shed_Opportunity' || opptyRt == 'NZ_Estimate_Opportunity') {
                            mapOpp.put(qt.OpportunityId, new Opportunity(Id = qt.OpportunityId, 
                                StageName = 'Proposal', 
                                Amount = qt.Total_Value_excl_GST__c,
                                Loss_Reason__c = lossReason,
                                Loss_Reason_Comments__c = qt.Cancellation_Comments__c, 
                                Primary_Quote_Expiry_Date__c = qtCancelDt));                        
                        }
                        if (opptyRt == 'AU_Standard_Opportunity' || opptyRt == 'AU_Store_Initiated_Opportunity') {
                            mapOpp.put(qt.OpportunityId, new Opportunity(Id = qt.OpportunityId, 
                                StageName = 'Proposal', 
                                Amount = qt.Total_Value_excl_GST__c,
                                Loss_Reason__c = lossReason,
                                Loss_Reason_Comments__c = qt.Cancellation_Comments__c, 
                                Primary_Quote_Expiry_Date__c = qtCancelDt));
                        }
                        if (opptyRt == 'Supply_Install_Opportunity') {
                            // SFSUP-792 - Sync S&I Opportunities 
                            mapOpp.put(qt.OpportunityId, new Opportunity(Id = qt.OpportunityId, 
                                StageName = 'Proposal in Progress ', 
                                Amount = qt.Total_Value_excl_GST__c,
                                Loss_Reason__c = lossReason,
                                Loss_Reason_Comments__c = qt.Cancellation_Comments__c, 
                                Primary_Quote_Expiry_Date__c = qtCancelDt));
                        }
                    }
                }
            }
        }
            
        if (!mapOpp.isEmpty()) {
            try {
                UPDATE mapOpp.values();
            } catch (Exception e) {
                ApplicationLogger.log('QuoteTriggerHandler.cosQuoteAndOpportunitySync', 'Quote', 'Trigger', e);
            }            
        }
        return cosQuoteAndOppSync;
    }
}