unpackaged/main/default/objects/Initialisation__mdt/Initialisation__mdt.object-meta.xml
<CustomObject>
    <description>CCRM initialisation items</description>
    <label>Initialisation</label>
    <pluralLabel>Initialisations</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Opportunity/fields/Additional_Notes__c.field-meta.xml
<CustomField>
    <fullName>Additional_Notes__c</fullName>
    <label>Additional Notes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Builder_Type__c.field-meta.xml
<CustomField>
    <fullName>Builder_Type__c</fullName>
    <label>Builder Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Large</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Small</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Current_Supplier__c.field-meta.xml
<CustomField>
    <fullName>Current_Supplier__c</fullName>
    <label>Current Supplier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Dwelling_Type__c.field-meta.xml
<CustomField>
    <fullName>Dwelling_Type__c</fullName>
    <label>Dwelling Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unit</fullName>
            </value>
            <value>
                <fullName>House</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Estimated_Amount__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Amount__c</fullName>
    <label>Estimated Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Associated project for this Opportunity</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Quality__c.field-meta.xml
<CustomField>
    <fullName>Quality__c</fullName>
    <label>Quality</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Good</fullName>
            </value>
            <value>
                <fullName>Better</fullName>
            </value>
            <value>
                <fullName>Best</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Site_Address__c.field-meta.xml
<CustomField>
    <fullName>Site_Address__c</fullName>
    <description>Address of the Site or office</description>
    <externalId>true</externalId>
    <label>Site Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>This object is used for grouping Opportunities related to a single construction project.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Project__c/fields/Main_Account__c.field-meta.xml
<CustomField>
    <fullName>Main_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Main Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects (Main Account)</relationshipLabel>
    <relationshipName>Projects2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Selected_Contact__c.field-meta.xml
<CustomField>
    <fullName>Selected_Contact__c</fullName>
    <label>Selected Contact</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WoB_Opp_Offer_Visibility_Mapping__mdt/WoB_Opp_Offer_Visibility_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>WoB Opp Offer Visibility Mapping</label>
    <pluralLabel>WoB Opp Offer Visibility Mappings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/WoB_S_I_Opp_Offer_Estimate_Amount__mdt/WoB_S_I_Opp_Offer_Estimate_Amount__mdt.object-meta.xml
<CustomObject>
    <label>WoB S&amp;I Opp Offer Estimate Amount</label>
    <pluralLabel>WoB S&amp;I Opp Offer Estimate Amount</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/WoB_S_I_Opp_Offer_Estimate_Amount__mdt/fields/Estimated_Amount__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Amount__c</fullName>
    <label>Estimated Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/WOBFormOpportunityLWCController_Test.cls
/**
 * @File Name          : WoOBFormOpportunityLWCController_Test.cls
 * @Description        : Covers test coverage for WoOBFormOpportunityLWCController apex class
 * @Author             : Sidney Garcia
 * @Group              : MS-AU
 * @Last Modified By   : Sidney Garcia
 * @Last Modified On   : 29/11/2021
 * @Modification Log   : 
 * Ver		Date			Author      		    Modification
 * 1.0		29/11/2021		Sidney Garcia    		Initial Version
**/
@isTest
public class WOBFormOpportunityLWCController_Test {
	@testSetup static void setupmethod() {
        // create user
        Profile p = [SELECT Id FROM Profile WHERE Name = 'Account Manager' LIMIT 1];
        User u = TestDataFactory.createUsers(1, p.Id)[0];
        
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        System.runAs(thisUser) {        
        	insert u;
        }
        
		List<Account> accountList = TestDataFactory.createAccounts(1);
        insert accountList;
        
        List<Contact> contactList = TestDataFactory.createContacts(accountList[0].Id, u.Id, 1);
        insert contactList;
        
        List<Project__c> projectList = TestDataFactory.createProject(1);
        for(Project__c pro : projectList){
            pro.Main_Account__c = accountList[0].Id;
            pro.Selected_Contact__c = contactList[0].Id;
        }
        insert projectList;
        
        
        List<Opportunity> oppList = TestDataFactory.createOpenOpportunities(accountList[0].Id, u.Id, 1);
        for(Integer i = 0; i < oppList.size(); i++){
            oppList[i].Project__c = projectList[i].Id;
            oppList[i].Current_Supplier__c = 'Test Supplier';
            oppList[i].Builder_Type__c = 'Medium';
            oppList[i].Dwelling_Type__c = 'House';
            oppList[i].Quality__c = 'Best';
            oppList[i].Site_Address__c = 'Test Site Address';
            oppList[i].Other__c = 'Test';
            oppList[i].Additional_Notes__c = 'Test';
        }
        insert oppList;
        

        OpportunityContactRole ocrRecord = new OpportunityContactRole();
        ocrRecord.ContactId = contactList[0].Id;
        ocrRecord.OpportunityId = oppList[0].Id;
        
        insert ocrRecord;            

    }
    @istest 
    public static void testGetRelatedOpportunities(){
        Project__c projectRecord = [SELECT Id FROM Project__c LIMIT 1];
        Account accountRecord = [SELECT Id FROM Account LIMIT 1];
        List<Opportunity> relatedOppList = new List<Opportunity>();
        Test.startTest();
        try{
            relatedOppList = WOBFormOpportunityLWCController.getRelatedOpportunities(projectRecord.Id, accountRecord.Id);
        }catch(Exception e){
            System.debug(e.getMessage());
        }
        Test.stopTest();
        
        System.assertEquals(1, relatedOppList.size());
    }
    
    @istest 
    public static void testGetRelatedOpportunitiesCatch(){
        Project__c projectRecord = [SELECT Id FROM Project__c LIMIT 1];
        Account accountRecord = [SELECT Id FROM Account LIMIT 1];
        List<Opportunity> oppListToDelete = [SELECT ID FROM Opportunity LIMIT 100];
        delete oppListToDelete;
        List<Opportunity> relatedOppList = new List<Opportunity>();
        Test.startTest();
        try{
            relatedOppList = WOBFormOpportunityLWCController.getRelatedOpportunities(projectRecord.Id, accountRecord.Id);
        }catch(Exception e){
            System.debug(e.getMessage());
        }
        
        Test.stopTest();
        
        System.assertEquals(0, relatedOppList.size());
    }
    
    @istest 
    public static void testCheckExistingOpportunityContactRole(){
        Contact contactRecord = [SELECT Id FROM Contact LIMIT 1];
        Opportunity oppRecord = [SELECT Id FROM Opportunity LIMIT 1];
        Boolean hasExistingOCR = false;
        Test.startTest();
        try{
            hasExistingOCR = WOBFormOpportunityLWCController.checkExistingOpportunityContactRole(oppRecord.Id, contactRecord.Id);
        }catch(Exception e){
            System.debug(e.getMessage());
        }
        
        Test.stopTest();
        
        System.assertEquals(true, hasExistingOCR);
    }
    
    @istest 
    public static void testCheckExistingOpportunityContactRoleCatch(){
        Account accRecord = [SELECT Id FROM Account LIMIT 1];
        User userRecord = [SELECT Id FROM User LIMIT 1];
        List<Contact> contactToDelete = [SELECT Id FROM Contact LIMIT 10];
        delete contactToDelete;
        Boolean hasExistingOCR = false;
        List<Contact> contactList = TestDataFactory.createContacts(accRecord.Id, userRecord.Id, 1);
        insert contactList;
        
        Contact contactRecord = [SELECT Id FROM Contact LIMIT 1];
        Opportunity oppRecord = [SELECT Id FROM Opportunity LIMIT 1];
        
        Test.startTest();
        try{
            hasExistingOCR = WOBFormOpportunityLWCController.checkExistingOpportunityContactRole(oppRecord.Id, contactRecord.Id);
        }catch(Exception e){
            System.debug(e.getMessage());
        }
        
        Test.stopTest();
        
        System.assertNotEquals(true, hasExistingOCR);
    }
    
    @istest 
    public static void testGetLoggedInUserProfileName(){
        Profile userProfile = [SELECT Id,Name FROM Profile WHERE Id = :userinfo.getProfileId() LIMIT 1];
        String profileNameToCompare;
        String loggedInUserProfileName;
        Test.startTest();
        try{
            profileNameToCompare = userProfile.Name;
            loggedInUserProfileName = WOBFormOpportunityLWCController.getLoggedInUserProfileName();
            
        }catch(Exception e){
            System.debug(e.getMessage());
        }
        
        Test.stopTest();
        
        System.assertEquals(profileNameToCompare, loggedInUserProfileName);
    }
    
    @istest 
    public static void testGetEstimatedAmountOppOffer(){
        String oppOffer = 'Flooring';
        WoB_S_I_Opp_Offer_Estimate_Amount__mdt oppOfferEstimateAmount = new WoB_S_I_Opp_Offer_Estimate_Amount__mdt();
        Test.startTest();
        try{
            oppOfferEstimateAmount = WOBFormOpportunityLWCController.getEstimatedAmountOppOffer(oppOffer);
            
        }catch(Exception e){
            System.debug(e.getMessage());
        }
        
        Test.stopTest();
        
        System.assert(oppOfferEstimateAmount.Estimated_Amount__c == 4000);
    }
    
    @istest 
    public static void testGetTactileOppOfferUrl(){
        String projectState = 'NSW';
        Initialisation__mdt wobOppOfferTactile = new Initialisation__mdt();
        Test.startTest();
        try{
            wobOppOfferTactile = WOBFormOpportunityLWCController.getTactileOppOfferUrl();
            
        }catch(Exception e){
            System.debug(e.getMessage());
        }
        
        Test.stopTest();
        
        System.assert(wobOppOfferTactile != null);
    }
    
    @istest 
    public static void testGetGarageDoorOfferUrls(){
        Profile userProfile = [SELECT Id,Name FROM Profile WHERE Id = :userinfo.getProfileId() LIMIT 1];
        String projectState = 'NSW';
        Initialisation__mdt garageDoorUrls = new Initialisation__mdt();
        Test.startTest();
        try{
            garageDoorUrls = WOBFormOpportunityLWCController.getGarageDoorOfferUrls();
            
        }catch(Exception e){
            System.debug(e.getMessage());
        }
        
        Test.stopTest();
        
        System.assert(garageDoorUrls != null);
    }
    
    @istest 
    public static void testGetOpportunityOfferVisibilityByProjectState(){
        Profile userProfile = [SELECT Id,Name FROM Profile WHERE Id = :userinfo.getProfileId() LIMIT 1];
        String projectState = 'NSW';
        WoB_Opp_Offer_Visibility_Mapping__mdt oppOfferVisibility = new WoB_Opp_Offer_Visibility_Mapping__mdt();
        Test.startTest();
        try{
            oppOfferVisibility = WOBFormOpportunityLWCController.getOpportunityOfferVisibilityByProjectState(projectState,userProfile.Name);
            
        }catch(Exception e){
            System.debug(e.getMessage());
        }
        
        Test.stopTest();
        
        System.assert(oppOfferVisibility != null);
    }
}