unpackaged/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>This object is used for grouping Opportunities related to a single construction project.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Project__c/fields/Build_Stage__c.field-meta.xml
<CustomField>
    <fullName>Build_Stage__c</fullName>
    <description>The Stage of the Project eg. Council Approval</description>
    <label>Build Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Construction</fullName>
            </value>
            <value>
                <fullName>Slab</fullName>
            </value>
            <value>
                <fullName>Frame/Brickwork</fullName>
            </value>
            <value>
                <fullName>Lock Up</fullName>
            </value>
            <value>
                <fullName>Fix</fullName>
            </value>
            <value>
                <fullName>Fit Out</fullName>
            </value>
            <value>
                <fullName>Council Approval</fullName>
            </value>
            <value>
                <fullName>Builder appointed</fullName>
            </value>
            <value>
                <fullName>Tender</fullName>
            </value>
            <value>
                <fullName>Post tender</fullName>
            </value>
            <value>
                <fullName>Greenfield</fullName>
            </value>
            <value>
                <fullName>Foundation</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Floor</fullName>
            </value>
            <value>
                <fullName>Frame &amp; Truss</fullName>
            </value>
            <value>
                <fullName>Exterior</fullName>
            </value>
            <value>
                <fullName>Interior Fitout</fullName>
            </value>
            <value>
                <fullName>Landscaping</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
            <value>
                <fullName>Construction</fullName>
                <isActive>false</isActive>
                <label>Construction</label>
            </value>
            <value>
                <fullName>Frame</fullName>
                <isActive>false</isActive>
                <label>Frame</label>
            </value>
            <value>
                <fullName>Landscape</fullName>
                <isActive>false</isActive>
                <label>Landscape</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Concatenated_Address__c.field-meta.xml
<CustomField>
    <fullName>Concatenated_Address__c</fullName>
    <description>Field used for project address matching rule and project address duplicate rule</description>
    <label>Concatenated Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Project_Address__c.field-meta.xml
<CustomField>
    <fullName>Project_Address__c</fullName>
    <description>The Address where the Project is taking place.</description>
    <externalId>true</externalId>
    <label>Project Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The Status of the Project eg. Quotation</description>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Documentation</fullName>
            </value>
            <value>
                <fullName>Tender</fullName>
            </value>
            <value>
                <fullName>Post Tender</fullName>
            </value>
            <value>
                <fullName>Builder Appointed</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Closed - Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/WOBSearchController.cls
public with sharing class WOBSearchController {
    @AuraEnabled
    public static List<sObject> search(String objectName, List<String> searchFields, List<String> queryFields, String searchTerm, String whereClauseFilter, String whereClauseValue){   
        try{
            String searchKeyword ='*'+ searchTerm + '*';
            String returningQuery = '';
            System.debug('whereClauseFilter ' + whereClauseFilter);
            System.debug('whereClauseValue ' + whereClauseValue);
            String query = '';

            

            if(whereClauseFilter == null){
                query = 'SELECT ID, ' + String.join(queryFields, ', ') + ' FROM ' + objectName;
            }else{
                query = 'SELECT ID, ' + String.join(queryFields, ', ') + ' FROM ' + objectName + ' WHERE ' + whereClauseFilter;
            }

            if(whereClauseValue != null){
                query += ' =\'' + whereClauseValue + '\'';
            }
            
            if(searchTerm.length() >= 3){
                String andClause = '(';
                Integer index = 1;
                for(String field : searchFields){
                    andClause += field + ' LIKE \'' + searchTerm + '%\' ';
                    if(index < searchFields.size()){
                        andClause += 'OR ';
                    }
                    index++;
                }
                andClause += ')';
                if(whereClauseFilter != null){
                    query += ' AND ';
                }else{
                    query += ' WHERE ';
                }
                query += andClause;
            }

            query += ' LIMIT 5';
            List<sObject> sobjList = Database.query(query);
            return sobjList;
        }catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static List<Project__c> findProjectDuplicate(String nameField, String projectId){
        try {
            List<Project__c> projectList = new List<Project__c>();
            Project__c projectRec = new Project__c();
            projectRec.Name = nameField;
            projectList.add(projectRec);

            List<Project__c> duplicateProjectListToDisplay = new List<Project__c>();

            List<Project__c> duplicateProjectRecordList = new List<Project__c>();

            Datacloud.FindDuplicatesResult[] results = Datacloud.FindDuplicates.findDuplicates(projectList);
            for (Datacloud.FindDuplicatesResult findDupeResult : results) {
                system.debug('WOBSearchController.findProjectDuplicate->Datacloud.FindDuplicatesResult: result found' );
                for (Datacloud.DuplicateResult dupeResult : findDupeResult.getDuplicateResults()) {
                    system.debug('WOBSearchController.findProjectDuplicate->Datacloud.DuplicateResult: duplicate found' );
                    for (Datacloud.MatchResult matchResult : dupeResult.getMatchResults()) {
                        system.debug('WOBSearchController.findProjectDuplicate->Datacloud.MatchResult: match found' );
                        for (Datacloud.MatchRecord matchRecord : matchResult.getMatchRecords()) {
                            System.debug('Duplicate Record: ' + matchRecord.getRecord());
                            if(matchRecord.getRecord().Id != projectId){
                                system.debug('WOBSearchController.findProjectDuplicate->different id: ' + projectId );
                                duplicateProjectRecordList.add((Project__c) matchRecord.getRecord());
                            }
                        }
                    }
                }
            }

            
            Set<Id> projectIdSet = new Set<Id>();
            if(duplicateProjectRecordList.size() > 0){
                for(Project__c p : duplicateProjectRecordList){
                    projectIdSet.add(p.Id);
                }

                duplicateProjectListToDisplay = [SELECT Id, Name, Status__c, Project_Address__c, Build_Stage__c FROM Project__c WHERE Id IN :projectIdSet];
            }
            System.debug('duplicateProjectListToDisplay ' + duplicateProjectListToDisplay);
            return duplicateProjectListToDisplay;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        
    }

    @AuraEnabled
    public static  Map<String, List<Project__c>> findProjectAddressDuplicate(String concatenatedAddress, String projectId){
        try {
            Map<Double, List<Project__c>> matchConfidenceProjectListMap = new Map<Double,List<Project__c>>();
            Map<String, List<Project__c>> matchAlgoProjectListMap = new Map<String,List<Project__c>>();
            List<Project__c> projectList = new List<Project__c>();
            List<Project__c> duplicateProjectListToDisplay = new List<Project__c>();
            Project__c projectRec = new Project__c();
            projectRec.Concatenated_Address__c = concatenatedAddress;
            projectList.add(projectRec);

            List<Project__c> duplicateProjectRecordList = new List<Project__c>();

            Datacloud.FindDuplicatesResult[] results = Datacloud.FindDuplicates.findDuplicates(projectList);
            for (Datacloud.FindDuplicatesResult findDupeResult : results) {
                system.debug('WOBSearchController.findProjectAddressDuplicate->Datacloud.FindDuplicatesResult: result found' );
                for (Datacloud.DuplicateResult dupeResult : findDupeResult.getDuplicateResults()) {
                    system.debug('WOBSearchController.findProjectAddressDuplicate->Datacloud.DuplicateResult: duplicate found' );
                    for (Datacloud.MatchResult matchResult : dupeResult.getMatchResults()) {
                        system.debug('WOBSearchController.findProjectAddressDuplicate->Datacloud.MatchResult: match found' );
                        if(matchResult.getSize() > 0){
                            for (Datacloud.MatchRecord matchRecord : matchResult.getMatchRecords()) {
                                System.debug('Duplicate Record: ' + matchRecord.getRecord());
                                if(matchRecord.getRecord().Id != projectId){
                                    system.debug('WOBSearchController.findProjectDuplicate->different id: ' + projectId );
                                    duplicateProjectRecordList.add((Project__c) matchRecord.getRecord());
                                    matchConfidenceProjectListMap.put(matchRecord.getMatchConfidence(), duplicateProjectRecordList);
                                }
                            }
                        }
                    }
                }
            }

            Set<Id> projectIdSet = new Set<Id>();
            Double exactMatchConfidence = 100.0;
            if(matchConfidenceProjectListMap.size() > 0){
                system.debug('WOBSearchController.findProjectAddressDuplicate: matchConfidenceProjectListMap.size()>0' );
                if(matchConfidenceProjectListMap.containsKey(exactMatchConfidence)){
                    system.debug('WOBSearchController.findProjectAddressDuplicate: containsKey ' + exactMatchConfidence );
                    if(matchConfidenceProjectListMap.get(exactMatchConfidence).size() > 0){
                        system.debug('WOBSearchController.findProjectAddressDuplicate: matchConfidenceProjectListMap size > 0' );
                        List<Project__c> exactMatchProjectList = matchConfidenceProjectListMap.get(exactMatchConfidence);
                        for(Project__c p : exactMatchProjectList){
                            projectIdSet.add(p.Id);
                        }
        
                        duplicateProjectListToDisplay = [SELECT Id, Name, Status__c, Project_Address__c, Build_Stage__c, Concatenated_Address__c FROM Project__c WHERE Id IN :projectIdSet];
        
                        matchAlgoProjectListMap.put('ExactMatch', duplicateProjectListToDisplay);
        
                    }
                }
                else{
                    system.debug('WOBSearchController.findProjectAddressDuplicate: does not contain key ' + exactMatchConfidence );
                    system.debug('WOBSearchController.findProjectAddressDuplicate: matchConfidenceProjectListMap ' + JSON.serialize(matchConfidenceProjectListMap.keySet()) );
                    Set<Double> fuzzyMatchConfidenceSet = new Set<Double>();
                    for(Double matchConfidence : matchConfidenceProjectListMap.keySet()){
                        if(matchConfidence != exactMatchConfidence){
                            fuzzyMatchConfidenceSet.add(matchConfidence);
                        }
                    }
    
                    List<Project__c> fuzzyMatchProjectListTemp = new List<Project__c>();
                    
                    system.debug('WOBSearchController.findProjectAddressDuplicate: fuzzyMatchConfidenceSet ' + JSON.serialize(fuzzyMatchConfidenceSet) );
                    for(Double fuzzyMatchConfidence : fuzzyMatchConfidenceSet){
                        if(matchConfidenceProjectListMap.get(fuzzyMatchConfidence).size() > 0){
                            fuzzyMatchProjectListTemp.addAll(matchConfidenceProjectListMap.get(fuzzyMatchConfidence));
                        }
                    }
    
                    List<Project__c> fuzzyMatchProjectList = new List<Project__c>(new Set<Project__c>(fuzzyMatchProjectListTemp));

                    system.debug('WOBSearchController.findProjectAddressDuplicate: fuzzyMatchProjectList ' + JSON.serialize(fuzzyMatchProjectList) );
                    for(Project__c p : fuzzyMatchProjectList){
                        projectIdSet.add(p.Id);
                    }
                    
                    duplicateProjectListToDisplay = [SELECT Id, Name, Status__c, Project_Address__c, Build_Stage__c, Concatenated_Address__c FROM Project__c WHERE Id IN :projectIdSet];
                    system.debug('WOBSearchController.findProjectAddressDuplicate: duplicateProjectListToDisplay ' + JSON.serialize(duplicateProjectListToDisplay) );
                    if(duplicateProjectListToDisplay.size() > 0){
                        matchAlgoProjectListMap.put('FuzzyMatch', duplicateProjectListToDisplay);
                    }
                }
            }else{
                system.debug('WOBSearchController.findProjectAddressDuplicate: no duplicate' );
                matchAlgoProjectListMap.put('NoDups', duplicateProjectListToDisplay);
            }
            
            return matchAlgoProjectListMap;
        } catch (Exception e) {
            System.debug('sid error ' + e);
            throw new AuraHandledException(e.getMessage());
        }
    }
}