unpackaged/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>This object is used for grouping Opportunities related to a single construction project.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Project__c/fields/Build_Stage__c.field-meta.xml
<CustomField>
    <fullName>Build_Stage__c</fullName>
    <description>The Stage of the Project eg. Council Approval</description>
    <label>Build Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Construction</fullName>
            </value>
            <value>
                <fullName>Slab</fullName>
            </value>
            <value>
                <fullName>Frame/Brickwork</fullName>
            </value>
            <value>
                <fullName>Lock Up</fullName>
            </value>
            <value>
                <fullName>Fix</fullName>
            </value>
            <value>
                <fullName>Fit Out</fullName>
            </value>
            <value>
                <fullName>Council Approval</fullName>
            </value>
            <value>
                <fullName>Builder appointed</fullName>
            </value>
            <value>
                <fullName>Tender</fullName>
            </value>
            <value>
                <fullName>Post tender</fullName>
            </value>
            <value>
                <fullName>Greenfield</fullName>
            </value>
            <value>
                <fullName>Foundation</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Floor</fullName>
            </value>
            <value>
                <fullName>Frame &amp; Truss</fullName>
            </value>
            <value>
                <fullName>Exterior</fullName>
            </value>
            <value>
                <fullName>Interior Fitout</fullName>
            </value>
            <value>
                <fullName>Landscaping</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
            <value>
                <fullName>Construction</fullName>
                <isActive>false</isActive>
                <label>Construction</label>
            </value>
            <value>
                <fullName>Frame</fullName>
                <isActive>false</isActive>
                <label>Frame</label>
            </value>
            <value>
                <fullName>Landscape</fullName>
                <isActive>false</isActive>
                <label>Landscape</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Concatenated_Address__c.field-meta.xml
<CustomField>
    <fullName>Concatenated_Address__c</fullName>
    <description>Field used for project address matching rule and project address duplicate rule</description>
    <label>Concatenated Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Construction_End__c.field-meta.xml
<CustomField>
    <fullName>Construction_End__c</fullName>
    <label>Construction End</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Construction_Start__c.field-meta.xml
<CustomField>
    <fullName>Construction_Start__c</fullName>
    <label>Construction Start</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Development_Type__c.field-meta.xml
<CustomField>
    <fullName>Development_Type__c</fullName>
    <label>Development Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Build</fullName>
            </value>
            <value>
                <fullName>Alteration &amp; Addition</fullName>
            </value>
            <value>
                <fullName>Extension</fullName>
            </value>
            <value>
                <fullName>Refurbishment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Document_Library_URL__c.field-meta.xml
<CustomField>
    <fullName>Document_Library_URL__c</fullName>
    <label>Document Library URL</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Floors__c.field-meta.xml
<CustomField>
    <fullName>Floors__c</fullName>
    <label>Floors</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/House_Type__c.field-meta.xml
<CustomField>
    <fullName>House_Type__c</fullName>
    <label>House Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Detached</fullName>
            </value>
            <value>
                <fullName>Semi Detached Townhouse</fullName>
            </value>
            <value>
                <fullName>Low Rise Build</fullName>
            </value>
            <value>
                <fullName>Single Dwelling site</fullName>
            </value>
            <value>
                <fullName>Multi Dwelling site</fullName>
            </value>
            <value>
                <fullName>Multi Level residential</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Number_of_Units_Buildings__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Units_Buildings__c</fullName>
    <label>Number of Units/Buildings</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Postcode__c.field-meta.xml
<CustomField>
    <fullName>Postcode__c</fullName>
    <label>Postcode</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Project_Address__c.field-meta.xml
<CustomField>
    <fullName>Project_Address__c</fullName>
    <description>The Address where the Project is taking place.</description>
    <externalId>true</externalId>
    <label>Project Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Project_Type__c.field-meta.xml
<CustomField>
    <fullName>Project_Type__c</fullName>
    <label>Project Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Townhouse</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Project_Value__c.field-meta.xml
<CustomField>
    <fullName>Project_Value__c</fullName>
    <label>Project Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Selected_Account__c.field-meta.xml
<CustomField>
    <fullName>Selected_Account__c</fullName>
    <label>Selected Account</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Selected_Contact__c.field-meta.xml
<CustomField>
    <fullName>Selected_Contact__c</fullName>
    <label>Selected Contact</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Shared_Document_Password__c.field-meta.xml
<CustomField>
    <fullName>Shared_Document_Password__c</fullName>
    <label>Shared Document Password</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The Status of the Project eg. Quotation</description>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Documentation</fullName>
            </value>
            <value>
                <fullName>Tender</fullName>
            </value>
            <value>
                <fullName>Post Tender</fullName>
            </value>
            <value>
                <fullName>Builder Appointed</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Closed - Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/TECH_WOB_Construction_End_Formatted__c.field-meta.xml
<CustomField>
    <fullName>TECH_WOB_Construction_End_Formatted__c</fullName>
    <formula>TEXT(DAY(Construction_End__c ))+&quot;-&quot; +TEXT(MONTH(Construction_End__c ))+&quot;-&quot; +TEXT(YEAR(Construction_End__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TECH WOB Construction End Formatted</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/TECH_WOB_Construction_Start_Formatted__c.field-meta.xml
<CustomField>
    <fullName>TECH_WOB_Construction_Start_Formatted__c</fullName>
    <formula>TEXT(DAY(Construction_Start__c ))+&quot;-&quot; +TEXT(MONTH(Construction_Start__c ))+&quot;-&quot; +TEXT(YEAR(Construction_Start__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TECH WOB Construction Start Formatted</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/TECH_WOB_Lot_No__c.field-meta.xml
<CustomField>
    <fullName>TECH_WOB_Lot_No__c</fullName>
    <label>TECH WOB Lot No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/TECH_WOB_Street_Name__c.field-meta.xml
<CustomField>
    <fullName>TECH_WOB_Street_Name__c</fullName>
    <label>TECH WOB Street Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/TECH_WOB_Street_No__c.field-meta.xml
<CustomField>
    <fullName>TECH_WOB_Street_No__c</fullName>
    <label>TECH WOB Street No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/TECH_WOB_Street_Type__c.field-meta.xml
<CustomField>
    <fullName>TECH_WOB_Street_Type__c</fullName>
    <label>TECH WOB Street Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Tender_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Tender_Due_Date__c</fullName>
    <label>Tender Due Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Town__c.field-meta.xml
<CustomField>
    <fullName>Town__c</fullName>
    <label>Town</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Project_Participant__c/Project_Participant__c.object-meta.xml
<CustomObject>
    <description>This junction object captures the relationship between an Account and a construction Project. This object also captures the relationship between a &quot;Project Specific Contract&quot;, and the Accounts with Access to the Project Specific Pricing.</description>
    <label>Project Participant</label>
    <nameField>
        <displayFormat>PP-{00000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Project_Participant__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Project Participants</relationshipLabel>
    <relationshipName>Project_Groups</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Project_Participant__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>A lookup to the related Project.</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Project_Groups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Project_Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active - Not on Contract</fullName>
                <default>true</default>
                <label>Active - Not on Contract</label>
            </value>
            <value>
                <fullName>Active - On Contract</fullName>
            </value>
            <value>
                <fullName>Request for Contract Addition</fullName>
            </value>
            <value>
                <fullName>Request for Contract Change</fullName>
            </value>
            <value>
                <fullName>Request for Contract Removal</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>.</fullName>
                <isActive>false</isActive>
                <label>.</label>
            </value>
            <value>
                <fullName>Active</fullName>
                <isActive>false</isActive>
                <label>Active</label>
            </value>
            <value>
                <fullName>On Contract</fullName>
                <isActive>false</isActive>
                <label>On Contract</label>
            </value>
            <value>
                <fullName>Request tor Contract</fullName>
                <isActive>false</isActive>
                <label>Request tor Contract</label>
            </value>
            <value>
                <fullName>Request tor Contract Addition</fullName>
                <isActive>false</isActive>
                <label>Request tor Contract Addition</label>
            </value>
            <value>
                <fullName>Request tor Contract Change</fullName>
                <isActive>false</isActive>
                <label>Request tor Contract Change</label>
            </value>
            <value>
                <fullName>Request tor Contract Removal</fullName>
                <isActive>false</isActive>
                <label>Request tor Contract Removal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/WOBFormProjectLWCController.cls
public with sharing class WOBFormProjectLWCController {
    
    @AuraEnabled(cacheable=true)
    public static Project__c getProjectRecordDetails(String projectId){
        
        try {
            Project__c projectRecord = [SELECT Id, Name, TECH_WOB_Lot_No__c, TECH_WOB_Street_No__c,
            TECH_WOB_Street_Name__c,TECH_WOB_Street_Type__c, Project_Address__c, Build_Stage__c, Development_Type__c, Status__c,
                                    Project_Type__c, Project_Value__c,Floors__c, Number_of_Units_Buildings__c, 
                                    Tender_Due_Date__c, Town__c, State__c, Postcode__c,
                                    Concatenated_Address__c, House_Type__c, Shared_Document_Password__c,
                                    Construction_Start__c, Construction_End__c , Selected_Contact__c, Document_Library_URL__c, Selected_Account__c,
                                    TECH_WOB_Construction_End_Formatted__c,TECH_WOB_Construction_Start_Formatted__c, Main_Account__c, OwnerId
                                    FROM Project__c WHERE Id = :projectId];
        
            return projectRecord;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    //to refactor
    @AuraEnabled
    public static Boolean checkExistingProjectParticipant(String projectId, String accountId){
        try {
            Boolean existingSameProjectAndAccount;
            Project_Participant__c projectParticipant = [SELECT Id, Project__c, Account__c FROM Project_Participant__c 
                                                         WHERE Project__c = :projectId 
                                                         AND Account__c = :accountId];
            System.debug('Sid ' + projectParticipant);
            if(projectParticipant.Id != null){
                existingSameProjectAndAccount = true;
            }else{
                existingSameProjectAndAccount = false;
            }

            return existingSameProjectAndAccount;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}