unpackaged/main/default/objects/Supplier_Quote__c/Supplier_Quote__c.object-meta.xml
<CustomObject>
    <label>Supplier Quote</label>
    <nameField>
        <displayFormat>SQ-{000000}</displayFormat>
        <label>Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Supplier_Quote__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>category selected based on supplier</description>
    <label>Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Supplier_Quote__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>NZ Standard Opportunity, Estimate Opportunity, Schedule Opportunity, Farm Shed Opportunity, Standard Opportunity</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Supplier Quotes</relationshipLabel>
    <relationshipName>Supplier_Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Supplier_Quote__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Repriced</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Supplier_Quote__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>NZ Supplier, AU Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supplier Quotes</relationshipLabel>
    <relationshipName>Supplier_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/DM_SupplierQuote.cls
/*******************************************************************************************************
* Class Name      	: DM_SupplierQuote
* Description		: Data Layer - Selector for Sobject Supplier_Quote__c
* Author          	: Simplus - Philip Clark
* Created On      	: 13/07/2020
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Philip Clark          13/07/2020		1000				Initial version
* Bunnings Dev          21/11/2024		2000				
* Bunnings Dev          2024-11-21      1011                CRMS204 - Update Supplier Quote for Closed Won
******************************************************************************************************/
public with sharing class DM_SupplierQuote {
    
    /**
    * @description  
    * @author       Philip Clark | 13/07/2020 
    * @param        Id
    * @return       list<Supplier_Quote__c> 
    **/
    public static list<Supplier_Quote__c> getSupplierQuotesbyOpportunity(Id oppId) {
        return new List<Supplier_Quote__c> ([
            SELECT Id, Name, Category__c, Opportunity__c, Supplier__c, Supplier__r.Name, Status__c   
			FROM Supplier_Quote__c 
            WHERE Opportunity__c =: oppId
        ]);
	}


       /**
    * @description  
    * @author       Bunnings Dev | 21/11/2024
    * @param        Set<Id>
    * @return       list<Supplier_Quote__c> 
    **/
    public static list<Supplier_Quote__c> getSupplierQuotesbyOpportunities(Set<Id> opptyId) {
        return new List<Supplier_Quote__c> ([
            SELECT Id, Name, Category__c, Opportunity__c, Supplier__c, Supplier__r.Name, Status__c   
			FROM Supplier_Quote__c 
            WHERE Opportunity__c IN : opptyId
        ]);
	}
}