unpackaged/main/default/objects/Category_Assist__c/Category_Assist__c.object-meta.xml
<CustomObject>
    <description>Category Assist object as child of Assisted Sales and Product Sub Department</description>
    <label>Category Assist</label>
    <nameField>
        <displayFormat>CA-{0000}</displayFormat>
        <label>Category Assist Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Category Assists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Category_Assist__c/fields/Assisted_Sale__c.field-meta.xml
<CustomField>
    <fullName>Assisted_Sale__c</fullName>
    <description>Assisted sale the category is being associated to.</description>
    <label>Assisted Sale</label>
    <referenceTo>Assisted_Sales__c</referenceTo>
    <relationshipLabel>Category Assists</relationshipLabel>
    <relationshipName>Category_Assists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Category_Assist__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Sub department category selected for association.</description>
    <label>Category</label>
    <referenceTo>Product_Sub_Department__c</referenceTo>
    <relationshipLabel>Category Assists</relationshipLabel>
    <relationshipName>Category_Assists</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Category_Assist__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End date of association.</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Category_Assist__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start date of association.</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Product_Sub_Department__c/Product_Sub_Department__c.object-meta.xml
<CustomObject>
    <description>Master Detail of Category Assist Object and related to Assisted Sales</description>
    <label>Product Sub Department</label>
    <nameField>
        <label>Sub Department</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Sub Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>Represents all frame and truss plants, small format stores, trade distribution centres and warehouses.</description>
    <label>Store</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Store_Assist__c/Store_Assist__c.object-meta.xml
<CustomObject>
    <description>A M:M Junction relationship between Assisted Sales and Store Locations. Object is only used for &quot;Location Specific&quot; Store Assists</description>
    <label>Store Assist</label>
    <nameField>
        <displayFormat>StoreAssist-{000000}</displayFormat>
        <label>Store Assist Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Assists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Store_Assist__c/fields/Assisted_Sale__c.field-meta.xml
<CustomField>
    <fullName>Assisted_Sale__c</fullName>
    <label>Assisted Sale</label>
    <referenceTo>Assisted_Sales__c</referenceTo>
    <relationshipLabel>Store Assists</relationshipLabel>
    <relationshipName>Store_Assists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Store_Assist__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>The Store Assist&#39;s End Date</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Store_Assist__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>The Store Assist&#39;s Start Date</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Store_Assist__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Store Assists</relationshipLabel>
    <relationshipName>Store_Assists</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/AssistedSalesTemplateController.cls
/*******************************************************************************************************
* Class Name      	: AssistedSalesTemplateController
* Description		: Controller to query child record of Assisted Sales in an email template
* Author          	: Simplus - Francis Benzon
* Created On      	: 15/05/2020
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Francis Benzon        15/05/2020		1000				Initial version
******************************************************************************************************/
global without sharing class AssistedSalesTemplateController{
    
    String cpsApproved = System.Label.CPSApproved;

    
    global String assistedSaleId{get;set;}
    
    global  AssistedSalesTemplateController() {
        //constructor
    }
        
    global List<Store_Assist__c> storeAssistList {
        get {
            storeAssistList = new List<Store_Assist__c>();
                    
            for(Store_Assist__c sa : [SELECT ID, Start_Date__c, End_Date__c, Store__c, Store__r.Name 
                                        FROM Store_Assist__c                            
                                        WHERE Assisted_Sale__c = :assistedSaleId]) {
                storeAssistList.add(sa);
            }  
                      
            return storeAssistList;          
        }
        set;
    }
    
    global List<Category_Assist__c> categoryAssistList {
        get {
            categoryAssistList = new List<Category_Assist__c>();
                       
                    
            for(Category_Assist__c ca : [SELECT ID, Start_Date__c, End_Date__c, Category__c, Category__r.Name 
                                            FROM Category_Assist__c                             
                                            WHERE Assisted_Sale__c = :assistedSaleId]) {
                categoryAssistList.add(ca);
            }  
                      
            return categoryAssistList;        
        }
        set;
    }       
}