unpackaged/main/default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml
<CustomObject>
    <description>SFSUP - 306</description>
    <label>Account Plan</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Account Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Account_Plan__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SFSUP-306</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Plans</relationshipLabel>
    <relationshipName>Account_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account_Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/DM_AccountPlan.cls
/*******************************************************************************************************
* Class Name        : DM_AccountPlan
* Description       : Data Layer - Selector for Sobject Account Plan
* Author            : Bunnings Dev - Jasper R Galapon
* Created On        : 04/08/2022
* Modification Log  :
* -----------------------------------------------------------------------------------------------------
* Developer             Date            Modification ID     Description
* -----------------------------------------------------------------------------------------------------
* Jasper R Galapon      04/08/2022      1000                SFSUP-898 - Initial version
******************************************************************************************************/

public with sharing class DM_AccountPlan {

    public static List<Account_Plan__c> getAccountPlans(Set<Id> accountIds, Set<Id> ownerIds, Id recTypeId) {
        return [
            SELECT Id, Status__c, Account__c, OwnerId 
            FROM Account_Plan__c 
            WHERE Account__c IN :accountIds
            AND OwnerId IN : ownerIds
            AND RecordTypeId = :recTypeId
        ];
    }
    
}