unpackaged/main/default/objects/ApplicationLog__c/ApplicationLog__c.object-meta.xml
<CustomObject>
    <description>Object that contains unhandled exception errors &amp; outbound message</description>
    <label>Application Log</label>
    <nameField>
        <displayFormat>Log-{000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ApplicationLog__c/fields/Retry_Count__c.field-meta.xml
<CustomField>
    <fullName>Retry_Count__c</fullName>
    <description>This field is part of callout exception retry mechanism.</description>
    <label>Retry Count</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ApplicationLog__c/fields/Retry_Params__c.field-meta.xml
<CustomField>
    <fullName>Retry_Params__c</fullName>
    <description>Serialised retry parameters</description>
    <label>Retry Params</label>
    <length>10240</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/ApplicationLog__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <inlineHelpText>Source of outbound message</inlineHelpText>
    <label>Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ApplicationLog__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Outbound message</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
            <value>
                <fullName>Inbound message</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Customer_Price_List__c/Customer_Price_List__c.object-meta.xml
<CustomObject>
    <description>Junction between Price List and Customers</description>
    <label>Customer Price List</label>
    <nameField>
        <displayFormat>CPL-{0000000000}</displayFormat>
        <label>Customer Price List Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Price Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Price_List__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>The customer</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Price Lists</relationshipLabel>
    <relationshipName>Customer_Price_Lists</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Customer_Price_List__c/fields/Customer_Price_List_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_Price_List_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Definition Id of the price list assoicated to a customer</description>
    <externalId>true</externalId>
    <label>Customer Price List ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Customer_Price_List__c/fields/Price_List__c.field-meta.xml
<CustomField>
    <fullName>Price_List__c</fullName>
    <description>The price list</description>
    <label>Price List</label>
    <referenceTo>Price_List__c</referenceTo>
    <relationshipLabel>Customer Price Lists</relationshipLabel>
    <relationshipName>Customer_Price_Lists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Customer_Price_List__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This field determines whether a Price List is active (checked) or In active (unchecked) for the related Customer.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Price_List__c/Price_List__c.object-meta.xml
<CustomObject>
    <description>This Object represents the header level of an externally mastered pricing table, which applies item level discounts for a pre-defined list of products within specific Cost Zones.</description>
    <label>Price List</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Price List Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Price_List__c/fields/Price_List_Definition__c.field-meta.xml
<CustomField>
    <fullName>Price_List_Definition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Price List Definition</description>
    <label>Price List Definition</label>
    <referenceTo>Price_List_Definition__c</referenceTo>
    <relationshipLabel>Price Lists</relationshipLabel>
    <relationshipName>Price_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Price_List__c/fields/Price_List_Header_ID__c.field-meta.xml
<CustomField>
    <fullName>Price_List_Header_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>External ID Reference for Price List</description>
    <externalId>true</externalId>
    <label>Price List Header ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Price_List__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Price List</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Price_List_Definition__c/Price_List_Definition__c.object-meta.xml
<CustomObject>
    <label>Price List Definition</label>
    <nameField>
        <displayFormat>PLD-{000000}</displayFormat>
        <label>Price List Definition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price List Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Quote/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of Quote</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Enquiry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/SM_RESTCalloutRetryBatch_Test.cls
/*******************************************************************************************************
* Class Name      	: SM_RESTCalloutRetryBatch_Test
* Description		: Test class for SM_RESTCalloutRetryBatch
* Author          	: Simplus - Yi Zhang
* Created On      	: 17/08/2020
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Yi Zhang              17/08/2020		1000				Initial version
* Simplus MS            18/12/2020      1001                New code to cover CCRM-6890,6892 changes
* Simplus MS            22/12/2020      1002                CCRM-297 code coverage addition
* Simplus MS           14/05/2021		2000				modifications CCRM-13728
******************************************************************************************************/
@isTest
private class SM_RESTCalloutRetryBatch_Test {

    @testSetup static void setup() {

        List<Account> accounts = TestDataFactory.createAccounts(1);
        insert accounts;
        List<Opportunity> oppties = TestDataFactory.createOpenOpportunities(accounts[0].Id, UserInfo.getUserId(), 1);
        insert oppties;
		List<Quote> quotes = TestDataFactory.createQuotes(oppties[0].Id,'Enquiry',1);
        insert quotes;
    }


    @isTest
    private static void testRESTCalloutRetryBatch_ClosedLost() {
        ApplicationLog__c log = new ApplicationLog__c(
            Source__c           = 'SM_Opportunity.sendClosedLostOpptyToCOS',
            Type__c             = 'Outbound message',
            Retry_Count__c      = 1,
            Retry_Params__c     = JSON.serialize(new Map<String, String>{'opptyId'=>[SELECT Id FROM Opportunity LIMIT 1].Id, 'previousStageName'=>'Qualifying', 'userId'=>UserInfo.getUserId(),
                	'lossComments'=>'Error','lossReason'=>'Customer Cancelled','orderToken'=>'6345656','username'=>'335205'})
        );
        insert log;

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new SM_RESTCalloutMock('{"returnCode":"Success"}', 200, false));

        // batchable
        Database.executebatch(new SM_RESTCalloutRetryBatch(), 50);

        Test.stopTest();

        ApplicationLog__c updatedLog = [SELECT Id, Retry_Count__c FROM ApplicationLog__c LIMIT 1];
        System.assert(updatedLog.Retry_Count__c == null || updatedLog.Retry_Count__c < log.Retry_Count__c, 'Batch not run');

    }
    
    @isTest
    private static void testRESTCalloutRetryBatch_ClosedLost_RetryCntZero() {
        ApplicationLog__c log = new ApplicationLog__c(
            Source__c           = 'SM_Opportunity.sendClosedLostOpptyToCOS',
            Type__c             = 'Outbound message',
            Retry_Count__c      = 1,
            Retry_Params__c     = JSON.serialize(new Map<String, String>{'opptyId'=>[SELECT Id FROM Opportunity LIMIT 1].Id, 'previousStageName'=>'Qualifying', 'userId'=>UserInfo.getUserId(),
                	'lossComments'=>'Error','lossReason'=>'Customer Cancelled','orderToken'=>'6345656','username'=>'335205'})
        );
        insert log;

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new SM_RESTCalloutMock('{calloutSuccess=false, opportunityToRevertStage=Opportunity:{Id=0061m000003VFmrAAG, StageName=Qualifying}}', 400, false));
        // batchable
        Database.executebatch(new SM_RESTCalloutRetryBatch(), 50);

        Test.stopTest();
		
        ApplicationLog__c updatedLog = [SELECT Id, Retry_Count__c FROM ApplicationLog__c LIMIT 1];
        System.assert(updatedLog.Retry_Count__c == null || updatedLog.Retry_Count__c < log.Retry_Count__c, 'Batch not run');

    }
   
    
    @isTest
    private static void testRESTCalloutRetryBatch_ClosedWon() {
        ApplicationLog__c log = new ApplicationLog__c(
            Source__c           = 'SM_Opportunity.sendClosedWonOpptyToCOS',
            Type__c             = 'Outbound message',
            Retry_Count__c      = 1,
            Retry_Params__c     = JSON.serialize(new Map<String, String>{'opptyId'=>[SELECT Id FROM Opportunity LIMIT 1].Id, 'previousStageName'=>'Qualifying',
                					'username'=>[SELECT Owner.Team_Member_ID__c FROM Opportunity LIMIT 1].Owner.Team_Member_ID__c,
                					'orderToken'=>'B58B6D636C40328AE053051B17AC519B','userId'=>UserInfo.getUserId()})
        );
        insert log;

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new SM_RESTCalloutMock('{"returnCode":"Success"}', 200, false));

        // schedulable (not immediate)
        Id jobId = System.schedule('Callout Retry Batch Test', '0 0 * * * ?', new SM_RESTCalloutRetryBatch());
        
        // batchable
        Database.executebatch(new SM_RESTCalloutRetryBatch(), 50);

        Test.stopTest();

        ApplicationLog__c updatedLog = [SELECT Id, Retry_Count__c FROM ApplicationLog__c LIMIT 1];
        System.assert(updatedLog.Retry_Count__c == null || updatedLog.Retry_Count__c < log.Retry_Count__c, 'Batch not run');

    }
    
    @isTest
    private static void testRESTCalloutRetryBatch_ClosedWon_RetryCntZero() {
        ApplicationLog__c log = new ApplicationLog__c(
            Source__c           = 'SM_Opportunity.sendClosedWonOpptyToCOS',
            Type__c             = 'Outbound message',
            Retry_Count__c      = 1,
            Retry_Params__c     = JSON.serialize(new Map<String, String>{'opptyId'=>[SELECT Id FROM Opportunity LIMIT 1].Id, 'previousStageName'=>'Qualifying',
                					'username'=>[SELECT Owner.Team_Member_ID__c FROM Opportunity LIMIT 1].Owner.Team_Member_ID__c,
                					'orderToken'=>'B58B6D636C40328AE053051B17AC519B','userId'=>UserInfo.getUserId()})
        );
        insert log;

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new SM_RESTCalloutMock('{calloutSuccess=false, opportunityToRevertStage=Opportunity:{Id=0061m000003VFmrAAG, StageName=Qualifying}}', 400, false));

        // schedulable (not immediate)
        Id jobId = System.schedule('Callout Retry Batch Test', '0 0 * * * ?', new SM_RESTCalloutRetryBatch());
        
        // batchable
        Database.executebatch(new SM_RESTCalloutRetryBatch(), 50);

        Test.stopTest();

        ApplicationLog__c updatedLog = [SELECT Id, Retry_Count__c FROM ApplicationLog__c LIMIT 1];
        System.assert(updatedLog.Retry_Count__c == null || updatedLog.Retry_Count__c < log.Retry_Count__c, 'Batch not run');

    }
    
    @isTest
    private static void testRESTCalloutRetryBatch_CPLAssignment() {
        
        Price_List_Definition__c pld = new Price_List_Definition__c();
        insert pld;
        Price_List__c pb = new Price_List__c(Status__c = 'Active', Price_List_Definition__c = pld.Id, Price_List_Header_ID__c = String.valueOf(Math.random()));
        insert pb;
        Customer_Price_List__c cpl = new Customer_Price_List__c(Price_List__c = pb.Id, Account__c = [SELECT Id from Account LIMIT 1].Id,
                                                               Status__c = 'Active', Customer_Price_List_ID__c = '45426');
        insert cpl;
        
        Map<Id, Map<String, String>> maptoSerialize = new Map<Id, Map<String, String>>();
        maptoSerialize.put([SELECT Price_List__c from Customer_Price_List__c LIMIT 1].Price_List__c, new Map<String, String>{'CustomerId' => '3467367', 'PriceListId' => [SELECT Customer_Price_List_ID__c from Customer_Price_List__c LIMIT 1].Customer_Price_List_ID__c,
                                                                            'AccountId' => [SELECT Account__c from Customer_Price_List__c LIMIT 1].Account__c, 'TMNumber' => '67674',
                                                                            'CountryCode' => 'AU'});
        
        ApplicationLog__c log = new ApplicationLog__c(
            Source__c           = 'SM_CustomerPriceList.invokeCustomerPriceListServiceAssignment',
            Type__c             = 'Outbound message',
            Retry_Count__c      = 1,
            Retry_Params__c     = JSON.serialize(maptoSerialize));
        insert log;

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new SM_RESTCalloutMock('{calloutSuccess=false, opportunityToRevertStage=Opportunity:{Id=0061m000003VFmrAAG, StageName=Qualifying}}', 400, false));

        // schedulable (not immediate)
        Id jobId = System.schedule('Callout Retry Batch Test', '0 0 * * * ?', new SM_RESTCalloutRetryBatch());
        
        // batchable
        Database.executebatch(new SM_RESTCalloutRetryBatch(), 50);

        Test.stopTest();

        ApplicationLog__c updatedLog = [SELECT Id, Retry_Count__c FROM ApplicationLog__c LIMIT 1];
        System.assert(updatedLog.Retry_Count__c == null || updatedLog.Retry_Count__c < log.Retry_Count__c, 'Batch not run');

    }
    
    @isTest
    private static void testRESTCalloutRetryBatch_CPLDeletion() {
        
        Price_List_Definition__c pld = new Price_List_Definition__c();
        insert pld;
        Price_List__c pb = new Price_List__c(Status__c = 'Active', Price_List_Definition__c = pld.Id, Price_List_Header_ID__c = String.valueOf(Math.random()));
        insert pb;
        Customer_Price_List__c cpl = new Customer_Price_List__c(Price_List__c = pb.Id, Account__c = [SELECT Id from Account LIMIT 1].Id,
                                                               Status__c = 'Active', Customer_Price_List_ID__c = '45426');
        insert cpl;
        
        Map<String,String> params = new Map<String, String>{'CustomerId' => '3467367', 'PriceListId' => [SELECT Customer_Price_List_ID__c from Customer_Price_List__c LIMIT 1].Customer_Price_List_ID__c,
                                                                            'AccountId' => [SELECT Account__c from Customer_Price_List__c LIMIT 1].Account__c, 
                                                                            'CountryCode' => 'AU'};
        
        ApplicationLog__c log = new ApplicationLog__c(
            Source__c           = 'SM_CustomerPriceList.invokeCustomerPriceListServiceDeletion',
            Type__c             = 'Outbound message',
            Retry_Count__c      = 1,
            Retry_Params__c     = JSON.serialize(new Map<Id, Map<String, String>>{cpl.id=> params}));
        insert log;

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new SM_RESTCalloutMock('{calloutSuccess=false, opportunityToRevertStage=Opportunity:{Id=0061m000003VFmrAAG, StageName=Qualifying}}', 400, false));

        // schedulable (not immediate)
        Id jobId = System.schedule('Callout Retry Batch Test', '0 0 * * * ?', new SM_RESTCalloutRetryBatch());
        
        // batchable
        Database.executebatch(new SM_RESTCalloutRetryBatch(), 50);

        Test.stopTest();

        ApplicationLog__c updatedLog = [SELECT Id, Retry_Count__c FROM ApplicationLog__c LIMIT 1];
        System.assert(updatedLog.Retry_Count__c == null || updatedLog.Retry_Count__c < log.Retry_Count__c, 'Batch not run');

    }

    @isTest
    private static void test_schedule(){
        Test.startTest();
        SM_RESTCalloutRetryBatch.schedule(); 
        Test.stopTest(); 
    }
}