unpackaged/main/default/objects/Sales_Rep__c/Sales_Rep__c.object-meta.xml
<CustomObject>
    <description>Bunnings&#39; Sales Rep ID assigned to team members and stores for attribution. This is based from a legacy definition of sales rep hierrachy and ids.</description>
    <label>Sales Rep</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Sales Rep ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Rep</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Sales_Rep__c/fields/Assigned_to_Store__c.field-meta.xml
<CustomField>
    <fullName>Assigned_to_Store__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Store the sales rep id is assigned to</description>
    <label>Assigned to Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Sales Rep</relationshipLabel>
    <relationshipName>Sales_Rep</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Sales_Rep__c/fields/Assigned_to_Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Assigned_to_Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Team member the sales rep is assigned to</description>
    <label>Assigned to Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales_Rep</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Sales_Rep__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>This field is used in conjunction with custom metadata type (Sales Rep Category Mapping) and user&#39;s Bunnings Job Role, Location Code field to determine the Sales Rep Id for the store member TS.</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Default</fullName>
                <default>true</default>
                <label>Default</label>
            </value>
            <value>
                <fullName>Landscape</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Sales_Rep__c/fields/Current_Sales_Rep_ID__c.field-meta.xml
<CustomField>
    <fullName>Current_Sales_Rep_ID__c</fullName>
    <description>If the leagcy sales rep id is assigned then it is considered as sales rep number else newly generated auto number sales rep id from Salesforce is used</description>
    <formula>IF(ISBLANK(Sales_Rep_Legacy_ID__c),  Name , Sales_Rep_Legacy_ID__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Current Sales Rep ID</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>Represents all frame and truss plants, small format stores, trade distribution centres and warehouses.</description>
    <label>Store</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Store__c/fields/Location_Code__c.field-meta.xml
<CustomField>
    <fullName>Location_Code__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Location Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Store__c/fields/Sales_Rep_ID__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep_ID__c</fullName>
    <description>Sales rep ID that is used to define the role of the trade specialist.</description>
    <label>Sales Rep ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/DM_SalesRep.cls
/*******************************************************************************************************
* Class Name      	: DM_SalesRep
* Description		: Data Layer - Selector for Sobject Sales_Rep__c
* Author          	: Simplus - Yi Zhang
* Created On      	: 24/08/2020
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Yi Zhang              24/08/2020		1000				Initial version
******************************************************************************************************/
public with sharing class DM_SalesRep {
    /**
    * @description 
    * @author Yi Zhang | 24/08/2020 
    * @param storeUserIds 
    * @param excludedSalesRepIds 
    * @return List<Sales_Rep__c> 
    **/
    public static List<Sales_Rep__c> getActiveSalesReps(List<Id> storeUserIds, List<Id> excludedSalesRepIds) {
        return new List<Sales_Rep__c>([
            SELECT Id, Assigned_to_Store__c, Assigned_to_Team_Member__c, Category__c
            FROM Sales_Rep__c
            WHERE Status__c = :Constants.STATUS_ACTIVE
            AND (Assigned_to_Store__c IN :storeUserIds OR Assigned_to_Team_Member__c IN :storeUserIds)
            AND Id NOT IN :excludedSalesRepIds
        ]);
    }

    /**
    * @description 
    * @author Yi Zhang | 24/08/2020 
    * @param storeLocationCodes 
    * @return List<Sales_Rep__c> 
    **/
    public static List<Sales_Rep__c> getActiveSalesRepsWith(List<String> storeLocationCodes) {
        // System.debug('In getActiveSalesRepsWith');
        return new List<Sales_Rep__c>([
            SELECT Id, Assigned_to_Store__c, Current_Sales_Rep_ID__c, Category__c, 
            Assigned_to_Store__r.Location_Code__c
            FROM Sales_Rep__c
            WHERE Assigned_to_Store__r.Location_Code__c IN :storeLocationCodes
            AND Status__c = :Constants.STATUS_ACTIVE
        ]);
    }

    /**
    * @description 
    * @author Yi Zhang | 27/08/2020 
    * @param storeIds 
    * @return List<Sales_Rep__c> 
    **/
    public static List<Sales_Rep__c> getActiveSalesRepsWithStoreIds(List<Id> storeIds) {
        return new List<Sales_Rep__c>([
            SELECt Id, Assigned_to_Store__c, Current_Sales_Rep_ID__c, Category__c, 
            Assigned_to_Store__r.Id, Assigned_to_Store__r.Sales_Rep_ID__c, Assigned_to_Store__r.Location_Code__c
            FROM Sales_Rep__c
            WHERE Assigned_to_Store__c IN :storeIds
            AND Status__c = :Constants.STATUS_ACTIVE
        ]);
    }
}